= 将来の破壊的変更について(Upcoming breaking changes)

Git プロジェクトは、 可能な限り下位互換性を確保することを狙っています。 マイナー・リリースでは、 セキュリティ上の脆弱性など、 非常に強い理由がない限り、下位互換性が失われることはありません。

それでも、 Git プロジェクトはとにかく古くからあるあるため、 変化する世界に合わせてプロジェクトを維持するために最終的に必要となる、 下位互換性のない変更のバックログが蓄積するのは当然のことです。 こういう変更はいくつかのカテゴリに分類されます:

* デフォルトを長年に渡り確立されてきたものに変更する。
* 概念をより優れたデザインで置き換える。
* 大きく機能が足りない点があり、 かつ、 修正できないため、 置き換えできずに削除する、 概念やコマンドや構成やオプション。

ユーザーから見える振る舞いの変更を引き起こす可能性があっても、 軽微なバグの修正は、 このリストには入れません。

Git プロジェクトは、 古いバージョンとの下位互換性を意図的に破壊する破壊的なバージョンを不定期にリリースします。 これは、 Git が今後とも有意義であり続け、 安全性や保守性を維持できるようにするために行われます。 通常、 破壊的最新バージョンのリリース頻度は数年ごとに見られます。 過去には以下の主要な破壊的リリースがありました:

* 2008年8月リリースの Git 1.6.0
* 2014年5月リリースの Git 2.0

最近では、 Git 2.0 から初めた <メジャー>.<マイナー> 形式のリリース番号を使用しています。 将来のリリースについては、 次の最新リリースを作成するときにリリース番号の <メジャー> をインクリメントする予定です。 Git 2.0 より前は、 リリース番号形式は 1.<major>.<minor> でしたが、これは「通常の」互換性を損なうリリースのために <major> をインクリメントすることを目的としており、 非常に大きな下位互換性破壊を伴う重大な変更のために Git 2.0 への飛躍を予約しておいたものです。

このドキュメントの目的は、 将来の最新リリースで予定されている非推奨(deprecations)を追跡することです。 さらに、 このドキュメントでは、 非推奨にならないものについても追跡します。 これは、 議論が非推奨を支持する場合と、 非推奨を拒否する場合の両方を議論の結果の文書に文書化するために行われます。

項目には、 メーリング・リストでの議論を読まなくても簡単に理解できるような、 記載の変更を、行う理由・行わない理由の明確な概要が含まれている必要があります。 変更する機能の代替手段がある場合は、 それをユーザーに提示すべきです。

すべての項目には、 非推奨が議論された、 関連するメーリング・リストのスレッドへの参照を添付する必要があります。 これらの参照はメッセージ ID を使用しており以下によりアクセスできます

  https://lore.kernel.org/git/$message_id/

これにより、 メッセージとそれにまつわる議論を確認します。 このような参照は、 当時、 そのプロジェクトがどのようにして説明された項目に関して合意に達したかを見つけやすくするためにあります。

プロジェクトを取り巻く環境は時間の経過とともに変化するため、 これは随時更新される文書です。 状況が変化した場合、 何かを廃止または変更するという、 以前決定したことをしばしば再検討する必要がある場合があります。 したがって、 このリストにある項目を「解決済みなので、 これを再度取り上げて時間を無駄にする必要はありません」という意味に受け取らないでください。

== 手順

Discussing the desire to make breaking changes, declaring that breaking changes are made at a certain version boundary, and recording these decisions in this document, are necessary but not sufficient. Because such changes are expected to be numerous, and the design and implementation of them are expected to span over time, they have to be deployable trivially at such a version boundary, prepared over long time.

The breaking changes MUST be guarded with the a compile-time switch, WITH_BREAKING_CHANGES, to help this process. When built with it, the resulting Git binary together with its documentation would behave as if these breaking changes slated for the next big version boundary are already in effect. We also have a CI job to exercise the work-in-progress version of Git with these breaking changes.


== Git 3.0

The following subsections document upcoming breaking changes for Git 3.0. There is no planned release date for this breaking version yet.

提案されている変更および削除には、 行う「準備ができている(ready)」項目のみが含まれています。 言い換えれば、 これは、 代替機能がすでに実装されている場合に備えて、 変更または置き換えるべき機能の欲しい物リスト(wishlist)であることを想定していません。

=== 変更されるもの

* 新しいリポジトリのデフォルトのハッシュ関数は、「sha1」から「sha256」に変更されます。 SHA-1 は 2011 年に NIST によって非推奨になり、 現在では FIPS 140-2 および同様の認証で使用しないことが推奨されています。 さらに、 以下のような SHA-1 の暗号特性を弱める実用的な攻撃がありました:
+
  ** SHAppening (2015): 2^57 演算による SHA-1 に対する実用的な攻撃の最初のデモンストレーション。
  ** SHAttered (2017): 2^63 演算による 2 つの有効(valid)な PDF ファイルの生成。
  ** Birthday-Near-Collision (2019): この攻撃では、2^68 演算による選択プレフィックス攻撃(chosen prefix attacks)が可能になります。
  ** Shambles (2020): この攻撃では、2^63 演算による選択プレフィックス攻撃(chosen prefix attacks)が可能になります。
+
既知の攻撃に対しては防御策が講じられていますが、 今後の研究により SHA-1 に対するさらに多くの攻撃が発見されることが予想されます。 ハードウェアの機能が成長し続けることと相まって、 SHA-1 を完全に破れるとみなされるのも時間の問題です。 我々はこれに備えたいので、 新しく初期化されるリポジトリのデフォルトのハッシュ・アルゴリズムを「sha256」に変更します。
+
この変更の重要な要件は、 エコシステムが「sha256」オブジェクト形式をサポートする準備ができていることです。 これには、 一般的な Git ライブラリやアプリケーションやフォージ(forges)が含まれます。
+
「sha1」オブジェクト形式を廃止する予定は、 現時点では何もありません(no plan)。
+
参照: <2f5de416-04ba-c23d-1e0b-83bb655829a7@zombino.com>, <20170223155046.e7nxivfwqqoprsqj@LykOS.localdomain>, <CA+EOSBncr=4a4d8n9xS4FNehyebpmX8JiUwCsXD47EQDE+DiUQ@mail.gmail.com>.

* The default storage format for references in newly created repositories will be changed from "files" to "reftable". The "reftable" format provides multiple advantages over the "files" format:
+
  ** It is impossible to store two references that only differ in casing on case-insensitive filesystems with the "files" format. This issue is common on Windows and macOS platforms. As the "reftable" backend does not use filesystem paths to encode reference names this problem goes away.
  ** Similarly, macOS normalizes path names that contain unicode characters, which has the consequence that you cannot store two names with unicode characters that are encoded differently with the "files" backend. Again, this is not an issue with the "reftable" backend.
  ** Deleting references with the "files" backend requires Git to rewrite the complete "packed-refs" file. In large repositories with many references this file can easily be dozens of megabytes in size, in extreme cases it may be gigabytes. The "reftable" backend uses tombstone markers for deleted references and thus does not have to rewrite all of its data.
  ** Repository housekeeping with the "files" backend typically performs all-into-one repacks of references. This can be quite expensive, and consequently housekeeping is a tradeoff between the number of loose references that accumulate and slow down operations that read references, and compressing those loose references into the "packed-refs" file. The "reftable" backend uses geometric compaction after every write, which amortizes costs and ensures that the backend is always in a well-maintained state.
  ** Operations that write multiple references at once are not atomic with the "files" backend. Consequently, Git may see in-between states when it reads references while a reference transaction is in the process of being committed to disk.
  ** Writing many references at once is slow with the "files" backend because every reference is created as a separate file. The "reftable" backend significantly outperforms the "files" backend by multiple orders of magnitude.
  ** The reftable backend uses a binary format with prefix compression for reference names. As a result, the format uses less space compared to the "packed-refs" file.
+
Users that get immediate benefit from the "reftable" backend could continue to opt-in to the "reftable" format manually by setting the "init.defaultRefFormat" config. But defaults matter, and we think that overall users will have a better experience with less platform-specific quirks when they use the new backend by default.
+
A prerequisite for this change is that the ecosystem is ready to support the "reftable" format. Most importantly, alternative implementations of Git like JGit, libgit2 and Gitoxide need to support it.

* In new repositories, the default branch name will be `main`. We have been warning that the default name will change since 675704c74dd (init: provide useful advice about init.defaultBranch, 2020-12-11). The new name matches the default branch name used in new repositories by many of the big Git forges.

* Git will require Rust as a mandatory part of the build process. While Git already started to adopt Rust in Git 2.49, all parts written in Rust are optional for the time being. This includes:
+
  ** The Rust wrapper around libgit.a that is part of "contrib/" and which has been introduced in Git 2.49.
  ** Subsystems that have an alternative implementation in Rust to test interoperability between our C and Rust codebase.
  ** Newly written features that are not mission critical for a fully functional Git client.
+
These changes are meant as test balloons to allow distributors of Git to prepare for Rust becoming a mandatory part of the build process. There will be multiple milestones for the introduction of Rust:
+
--
1. Initially, with Git 2.52, support for Rust will be auto-detected by Meson and disabled in our Makefile so that the project can sort out the initial infrastructure.
2. In Git 2.53, both build systems will default-enable support for Rust. Consequently, builds will break by default if Rust is not available on the build host. The use of Rust can still be explicitly disabled via build flags.
3. In Git 3.0, the build options will be removed and support for Rust is mandatory.
--
+
You can explicitly ask both Meson and our Makefile-based system to enable Rust by saying `meson configure -Drust=enabled` and `make WITH_RUST=YesPlease`, respectively.
+
The Git project will declare the last version before Git 3.0 to be a long-term support release. This long-term release will receive important bug fixes for at least four release cycles and security fixes for six release cycles. The Git project will hand over maintainership of the long-term release to distributors in case they need to extend the life of that long-term release even further. Details of how this long-term release will be handed over to the community will be discussed once the Git project decides to stop officially supporting it.
+
We will evaluate the impact on downstream distributions before making Rust mandatory in Git 3.0. If we see that the impact on downstream distributions would be significant, we may decide to defer this change to a subsequent minor release. This evaluation will also take into account our own experience with how painful it is to keep Rust an optional component.

=== 削除されるもの

* grafts コミットのサポートは、 git-replace(1) に置き換えられて久しいです。 grafts は 置換 refs (replacement refs)よりも劣っています:
+
  ** grafts はローカルのみのメカニズムであり、 リポジトリ間にまたがって共有することができません。
  ** grafts は、リポジトリ間でオブジェクトを転送するときに診断が難しい問題を引き起こす可能性があります。
+
e650d0643b (文書: mark info/grafts as outdated, 2014-03-05)以降、 grafts メカニズムは時代遅れのモノとしてマークされています。 削除されます。
+
参照: <20140304174806.GA11561@sigill.intra.peff.net>.

* git-pack-redundant(1) コマンドを使用して、 重複したパック・ファイルを削除できます。 このサブ・コマンドは耐え難いほど遅いのですが、 これをパフォーマンスのバグとして誰も報告しない理由は、 このコマンドの利用者が存在しないことが原因であると考えられます。 私達はこのコマンドを削除対象に指定し、 コマンドが実行されるたびに利用者に表示される警告を発する事にしました(c3b58472be (pack-redundant: gauge the usage before proposing its removal, 2020-08-25))。
+
これまでのところ、 誰かがまだこのコマンドを使用しているという苦情が 1 件ありましたが、 その苦情によって方針を変更することはありませんでした。 それどころか、 非推奨についてはさらに強化しており、 4406522b76 (pack-redundant: escalate deprecation warning to an error, 2023-03-23) 以降は、 利用者が `--i-still-use-this` オプションを渡さない限り、 コマンドは終了(die)します。
+
その後苦情は寄せられていないため、 このコマンドは最終的には削除される予定です。
+
参照: <xmqq1rjuz6n3.fsf_-_@gitster.c.googlers.com>,
      <CAKvOHKAFXQwt4D8yUCCkf_TQL79mYaJ=KAKhtpDNTvHJFuX1NA@mail.gmail.com>,
      <20230323204047.GA9290@coredump.intra.peff.net>,

* Support for storing shorthands for remote URLs in "$GIT_COMMON_DIR/branches/" and "$GIT_COMMON_DIR/remotes/" has been long superseded by storing remotes in the repository configuration.
+
The mechanism has originally been introduced in f170e4b39d ([PATCH] fetch/pull: short-hand notation for remote repositories., 2005-07-16) and was superseded by 6687f8fea2 ([PATCH] Use .git/remote/origin, not .git/branches/origin., 2005-08-20), where we switched from ".git/branches/" to ".git/remotes/". That commit already mentions an upcoming deprecation of the ".git/branches/" directory, and starting with a1d4aa7424 (Add repository-layout document., 2005-09-01) we have also marked this layout as deprecated. Eventually we also started to migrate away from ".git/remotes/" in favor of config-based remotes, and we have marked the directory as legacy in 3d3d282146 (Documentation: Grammar correction, wording fixes and cleanup, 2011-08-23)
+
As our documentation mentions, these directories are unlikely to be used in modern repositories and most users aren't even aware of these mechanisms. They have been deprecated for almost 20 years and 14 years respectively, and we are not aware of any active users that have complained about this deprecation. Furthermore, the ".git/branches/" directory is nowadays misleadingly named and may cause confusion as "branches" are almost exclusively used in the context of references.
+
These features will be removed.

* Support for "--stdin" option in the "name-rev" command was deprecated (and hidden from the documentation) in the Git 2.40 timeframe, in preference to its synonym "--annotate-stdin". Git 3.0 removes the support for "--stdin" altogether.

* The git-whatchanged(1) command has outlived its usefulness more than 10 years ago, and takes more keystrokes to type than its rough equivalent `git log --raw`. We have nominated the command for removal, have changed the command to refuse to work unless the `--i-still-use-this` option is given, and asked the users to report when they do so.
+
The command will be removed.

* Support for `core.commentString=auto` has been deprecated and will be removed in Git 3.0.
+
cf. <xmqqa59i45wc.fsf@gitster.g>

* Support for `core.preferSymlinkRefs=true` has been deprecated and will be removed in Git 3.0. Writing symbolic refs as symbolic links will be phased out in favor of using plain files using the textual representation of symbolic refs.
+
Symbolic references were initially always stored as a symbolic link. This was changed in 9b143c6e15 (Teach update-ref about a symbolic ref stored in a textfile., 2005-09-25), where a new textual symref format was introduced to store those symbolic refs in a plain file. In 9f0bb90d16 (core.prefersymlinkrefs: use symlinks for .git/HEAD, 2006-05-02), the Git project switched the default to use the textual symrefs in favor of symbolic links.
+
The migration away from symbolic links has happened almost 20 years ago by now, and there is no known reason why one should prefer them nowadays. Furthermore, symbolic links are not supported on some platforms.
+
Note that only the writing side for such symbolic links is deprecated. Reading such symbolic links is still supported for now.

== 廃止されずに新機能に取って代わられたもの

一部の機能は、 特定の方法で設計を改善することを目的として、 新しい代替品を取得しました。 代替品があるからといって古いやり方が自動的に削除されることを意味するものではありません。 このセクションでは、 より新しい代替品を持つこれらの機能を追跡していきます。

* git-checkout(1) が提供する機能は、 コマンド git-restore(1) と git-switch(1) のペアでカバーされています。 git-checkout(1) の使用は依然として広く普及しており、 この状態がすぐに変化するとは予想できないため、 3 つのコマンドはすべてそのまま残ります。
+
この決定は、 当該コマンドのユーザーがほとんどいないことが判明したときは、 再検討されるかもしれません。
+
参照: <xmqqttjazwwa.fsf@gitster.g>, <xmqqleeubork.fsf@gitster.g>, <112b6568912a6de6672bf5592c3a718e@manjaro.org>.
