[[generate_patch_text_with_p]]
Generating patch text with -p
-----------------------------

linkgit:git-diff[1] 、 linkgit:git-log[1] 、 linkgit:git-show[1] 、 linkgit:git-diff-index[1] 、 linkgit:git-diff-tree[1] 、 linkgit:git-diff-files[1] に `-p` オプションを付けて実行するとパッチテキストを生成します。パッチテキストの作成は、 `GIT_EXTERNAL_DIFF` と `GIT_DIFF_OPTS` 環境変数( linkgit:git[1] 参照)、および `diff` 属性( linkgit:gitattributes[5] 参照)を介してカスタマイズできます。

`-p` オプションが生成するものは、 従来のdiff形式とは少々異なります:

1.   先行して、以下のような `git diff` ヘッダーがあります:

       diff --git a/file1 b/file2
+
名前の変更/コピーが含まれない限り、 `a/` と `b/` のファイル名は同じです。 特に、作成または削除の場合でも、 `a/` または `b/` ファイル名の代わりに `/dev/null` が使用されることはありません。
+
名前変更/コピー が含まれる場合、 `file1` と `file2` は、それぞれ 名前変更/コピー のソース・ファイルの名前と、 名前変更/コピー が生成するファイルの名前を示します。

2.   その後に、1つ以上の拡張ヘッダー行達が続きます:
+
------------
old mode <mode>
new mode <mode>
deleted file mode <mode>
new file mode <mode>
copy from <path>
copy to <path>
rename from <path>
rename to <path>
similarity index <number>
dissimilarity index <number>
index <hash>..<hash> <mode>
------------
+
ファイルモード(<mode>)は、 ファイル・タイプとファイル許可ビットを含む6桁の8進数として出力されます。
+
拡張ヘッダーのパス名には、 `a/` および `b/` プレフィックスは含まれません。
+
類似インデックス(similarity index)は変更されていない行のパーセンテージであり、非類似インデックス(dissimilarity index)は変更された行のパーセンテージです。これは切り捨てられた整数であり、その後にパーセント記号が続きます。したがって、100％の類似インデックス値は2つの等しいファイルを表し、100％の非類似性は古いファイルから新しいファイルに移行された行がないことを意味します。
+
インデックス行には、変更前後のブロブオブジェクト名が含まれます。 <mode> は、ファイルモードが変更されない場合に含まれます。それ以外の場合、別々の行は古いモードと新しいモードを示します。

3.  通常の文字でないキャラクタ("unusual" characters)を含むパス名は、構成変数 `core.quotePath` で説明されているようにクォートされています( linkgit:git-config[1]参照)。

4.  出力内のすべての `file1` ファイルはコミット前のファイルを参照し、すべての `file2` ファイルはコミット後のファイルを参照します。各変更を各ファイルに順番に適用するのは誤りです。たとえば、以下のパッチはaとbを交換します:

      diff --git a/a b/b
      rename from a
      rename to b
      diff --git a/b b/a
      rename from b
      rename to a

5.  ハンク・ヘッダーには、 ハンクが適用される関数の名前が記載されています。 これを特定のプログラミング言語に合わせて調整する方法の詳細については、 linkgit:gitattributes[5] の「Defining a custom hunk-header」(カスタム・ハンク・ヘッダーの定義)を参照してください。

Combined diff format
--------------------

diffを生成するコマンドは、マージを表示するときに `-c` または `--cc` オプションを使用して「合成diff」(combined diff)を生成できます。これは linkgit:git-diff[1] または linkgit:git-show[1] でのマージを表示するときのデフォルトの形式です。 注意: これらのコマンドのいずれかに適切な `--diff-merges` オプションを指定して、特定の形式で差分を強制的に生成できることにも注意してください。

合成diff形式は以下のようになります:

------------
diff --combined describe.c
index fabadb8,cc95eb0..4866510
--- a/describe.c
+++ b/describe.c
@@@ -98,20 -98,12 +98,20 @@@
	return (a_date > b_date) ? -1 : (a_date == b_date) ? 0 : 1;
  }

- static void describe(char *arg)
 -static void describe(struct commit *cmit, int last_one)
++static void describe(char *arg, int last_one)
  {
 +	unsigned char sha1[20];
 +	struct commit *cmit;
	struct commit_list *list;
	static int initialized = 0;
	struct commit_name *n;

 +	if (get_sha1(arg, sha1) < 0)
 +		usage(describe_usage);
 +	cmit = lookup_commit_reference(sha1);
 +	if (!cmit)
 +		usage(describe_usage);
 +
	if (!initialized) {
		initialized = 1;
		for_each_ref(get_name);
------------

1.   `git diff` ヘッダーがその前にあり、 以下のようになっています(`-c` オプションが使用されている場合):

       diff --combined file
+
または、以下のようになります( `--cc` オプションが使用されている場合):

       diff --cc file

2.   その後に1つ以上の拡張ヘッダー行が続きます(以下の例は、2つの親とのマージを示しています):
+
------------
index <hash>,<hash>..<hash>
mode <mode>,<mode>..<mode>
new file mode <mode>
deleted file mode <mode>,<mode>
------------
+
`mode <mode>,<mode>..<mode>` 行は、 <mode> の少なくとも1つが他の <mode> と異なる場合にのみ表示されます。 検出されたコンテンツの移動(名前の変更とコピーの検出)に関する情報を含む拡張ヘッダーは、 2つの <tree-ish> の diff で機能するように設計されており、 合成 diff 形式では使用されません。

3.   その後に2行の from-file/to-file ヘッダーが続きます:

       --- a/file
       +++ b/file
+
従来の統一 diff 形式の2行ヘッダーと同様に、 `/dev/null` は、 作成または削除されたファイルを通知するために使用されます。
+
ただし、 `--combined-all-paths` オプションが指定されている場合、 2行の from-file/to-file の代わりに、 N+1 行の from-file/to-file ヘッダーが取得されます。ここで、 N はマージコミットの親の数です:

       --- a/file
       --- a/file
       --- a/file
       +++ b/file
+
この拡張形式は、名前変更またはコピー検出がアクティブな場合に役立ち、別の親のファイルの元の名前を確認できます。

4.   チャンクヘッダーの形式が変更され、誤って `patch-p1` にフィードされるのを防ぎます。合成差分形式は、マージコミットの変更を確認するために作成されたものであり、適用されることを意図したものではありません。この変更は、拡張された「インデックス」ヘッダーの変更に似ています:

       @@@ <from-file-range> <from-file-range> <to-file-range> @@@
+
合成diff形式のチャンクヘッダーには親の数+1の `@` 文字があります。

従来の統一diff形式とは異なり、2つのファイルAとBが、 `-` (マイナス:Aに表示されますが、Bでは削除されます) または `+` (プラス:Aにはありませんが、Bには追加されます)、または " " (スペース:変更なし)なプレフィックスを持つ単一の列で表示される場合、この形式は2つ以上のファイル file1, file2,... を1つのファイルXと比較し、Xが各 fileN とどのように異なるかを示します。ファイルNごとに1つの列が出力行の前に追加され、Xの行が出力行とどのように異なるかを示します。

列Nの `-` 文字は、その行が fileN に表示されているが、結果には表示されていないことを意味します。 列Nの `+` 文字は、結果に行が表示され、 fileN にその行がないことを意味します(つまり、その親の観点から見て行が追加されたことを示す)。

上記の出力例では、関数のシグネチャが両方のファイルから見て変更されています(したがって、 file1 と file2 の両方から2つの `-` が削除され、さらに `++` が追加されたため、 file1 と file2 のどちらにも表示されません)。また、他の8行は file1 と同じですが、 file2 には表示されません(したがって、接頭辞として `+` が付けられます)。

`git diff-tree -c` で表示される場合、マージコミットの親をマージ結果と比較します(つまり、 file1..fileN が親です)。 `git diff-files -c` で表示される場合、2つの未解決のマージ親を作業ツリーファイルと比較します(つまり、 file1 はステージ2、別名「私たちのバージョン」、 file2 はステージ3、別名「彼らのバージョン」です)。
