'\" t
.\"     Title: git-http-fetch
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-HTTP\-FETCH" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-http-fetch \- HTTPでリモートGitリポジトリからダウンロード
.SH "SYNOPSIS"
.sp
.nf
\fIgit http\-fetch\fR [\-c] [\-t] [\-a] [\-d] [\-v] [\-w <filename>] [\-\-recover] [\-\-stdin | \-\-packfile=<hash> | <commit>] <URL>
.fi
.sp
.SH "DESCRIPTION"
.sp
HTTPでリモートGitリポジトリからダウンロード
.sp
このコマンドは常にすべてのオブジェクトを取得します。歴史的に、ダウンロードするオブジェクトを選択するには、 \fB\-a\fR と \fB\-c\fR と \fB\-t\fR の3つのオプションがありました。それらは現在、何も警告を出さずに無視されます。
.SH "OPTIONS"
.PP
commit\-id
.RS 4
プルするハッシュ、または [URL]/refs/ 下のファイル名 のいずれか。
.RE
.PP
\fB\-a, \-c, \-t\fR
.RS 4
これらのオプションは、歴史的な理由により無視されます。
.RE
.PP
\fB\-v\fR
.RS 4
ダウンロードしたものを報告します。
.RE
.PP
\fB\-w <filename>\fR
.RS 4
転送が完了した後、ローカル側ドの $GIT_DIR/refs/<filename> の下のファイル名にcommit\-idを書き込みます。
.RE
.PP
\fB\-\-stdin\fR
.RS 4
(この場合は期待されていない)コマンドラインのコミットIDの代わりに、
\fBgithttp\-fetch\fR
は標準入力からの行を以下の形式であると期待します
.sp
.if n \{\
.RS 4
.\}
.nf
<commit\-id>[\*(Aq\et\*(Aq<filename\-as\-in\-\-w>]
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB\-\-packfile=<hash>\fR
.RS 4
内部使用のみ。 (この場合は期待されていない)コマンドラインのコミットIDの代わりに、
\fBgit http\-fetch\fR
は指定されたURLで直接パックファイルをフェッチし、 index\-pack を使用して対応する \&.idx ファイルと \&.keep ファイルを生成します。ハッシュは一時ファイルの名前を決定するために使用され、任意です。 index\-pack の出力は stdout に出力されます。
\fB\-\-index\-pack\-args\fR
が必要です。
.RE
.PP
\fB\-\-index\-pack\-args=<args>\fR
.RS 4
内部使用のみ。 ダウンロードしたパックの内容に対して実行するコマンド。引数はスペースで区切られURLエンコードされます。
.RE
.PP
\fB\-\-recover\fR
.RS 4
ターゲットから到達可能なすべてのものがフェッチされていることを確認します。以前のフェッチが中断された後に使用されます。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
