'\" t
.\"     Title: git-diagnose
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-DIAGNOSE" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-diagnose \- 診断情報の zip アーカイブを生成する
.SH "SYNOPSIS"
.sp
.nf
\fIgit diagnose\fR [(\-o | \-\-output\-directory) <path>] [(\-s | \-\-suffix) <format>]
               [\-\-mode=<mode>]
.fi
.sp
.SH "DESCRIPTION"
.sp
ユーザーのマシンや、 Git クライアントや、 リポジトリの状態に関する詳細情報を収集し、 その情報を zip アーカイブにパッケージ化します。 生成されたアーカイブは、 たとえば、Git メーリング・リストと共有して、 問題のデバッグを支援したり、 独立したデバッグの参照として使用したりできます。
.sp
デフォルトでは以下の情報がアーカイブに収められます:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBgit version \-\-build\-options\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
リポジトリ・ルートへのパス(path)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ファイルシステムで利用可能なディスク容量
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
代替オブジェクト・ストア(alternate object stores)内のものを含む、 各パック・ファイルの名前とサイズ
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
緩い(loose)オブジェクトの総数と、
\fB\&.git/objects\fR
のサブディレクトリごとに分類されたカウント
.RE
.sp
\fB\-\-mode\fR オプションを使用して別の診断モードを選択すると、 追加情報を収集できます。
.sp
このツールは、 \fBgit-bugreport\fR(1) とは異なり、 リポジトリ・コンテンツのサイズとデータ形状のレポートに重点を置いて、 より詳細な情報を収集します。
.SH "OPTIONS"
.PP
\fB\-o <path>\fR, \fB\-\-output\-directory <path>\fR
.RS 4
結果の診断アーカイブを、 現在のディレクトリではなく
\fB<path>\fR
に配置します。
.RE
.PP
\fB\-s <format>\fR, \fB\-\-suffix <format>\fR
.RS 4
診断アーカイブ名の代替サフィックスを指定して、
\fBgit\-diagnostics\-<formatted suffix>\fR
という名前のファイルを作成します。 これは、 strftime(3) 書式文字列の形式を取る必要があり、 現地の現在時間(current local time)が使用されます。
.RE
.PP
\fB\-\-mode=(stats|all)\fR
.RS 4
収集する必要がある診断のタイプを指定します。
\fBgit diagnostic\fR
のデフォルトの動作は
\fB\-\-mode=stats\fR
と同等です。
.sp
\fB\-\-mode=all\fR
オプションは、
\fB\-\-mode=stats\fR
に含まれるすべてのものと、
\fB\&.git\fR
と
\fB\&.git/hooks\fR
と
\fB\&.git/info\fR
と
\fB\&.git/logs\fR
と
\fB\&.git/objects/info\fR
ディレクトリのコピーを収集します。 この追加情報は、 診断されたリポジトリの完全なコンテンツを再構築するために使用できるため、 機密情報である可能性があります。
\fB\-\-mode=all\fR
で生成されたアーカイブを共有する場合、ユーザーは注意を払う必要があります。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
