'\" t
.\"     Title: git-mailinfo
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-MAILINFO" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-mailinfo \- 単一の電子メールメッセージからパッチと作成者を抽出します
.SH "SYNOPSIS"
.sp
.nf
\fIgit mailinfo\fR [\-k|\-b] [\-u | \-\-encoding=<encoding> | \-n]
               [\-\-[no\-]scissors] [\-\-quoted\-cr=<action>]
               <msg> <patch>
.fi
.sp
.SH "DESCRIPTION"
.sp
標準入力から単一の電子メールメッセージを読み取り、コミットログメッセージを <msg> ファイルに書き込み、パッチを <patch> ファイルに書き込みます。作者名と電子メールアドレスと電子メールの件名は、コミットを作成する \fBgit am\fR で使用するために標準出力に書き出されます。通常、このコマンドをユーザーが直接使用する必要はありません。代わりに \fBgit-am\fR(1) を参照してください。
.SH "OPTIONS"
.PP
\fB\-k\fR
.RS 4
通常、プログラムは、
\fBSubject:\fR
ヘッダー行から電子メール特有の断片文字列を取り除き、コミットログメッセージのタイトル行を取り出します。このオプションは、この変更をある程度防ぎ、
\fBgit format\-patch \-k\fR
出力を読み返すために使用する場合に最も役立つようにします。
.sp
具体的には、以下のものがなくなるまでは削除を行います:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
先頭と末尾の空白(whitespace)を削除。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
先頭の
\fBRe:\fR
や
\fBre:\fR
や
\fB:\fR
を削除。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
先頭のブラケットで囲まれた文字列(
\fB[\fR
〜
\fB]\fR
、 通常は
\fB[PATCH]\fR
) 。
.RE
.sp
最後に、空白類(whitespace)は単一のASCIIスペース文字(\ex20)に正規化されます。
.RE
.PP
\fB\-b\fR
.RS 4
\fB\-k\fR
が有効でない場合、 先頭のブラケット
\fB[\fR
と
\fB]\fR
のペアで囲まれたすべての文字列が削除されます。このオプションは、括弧で囲まれた文字列に
\fBPATCH\fR
という単語が含まれているペアのみに削除を制限します。
.RE
.PP
\fB\-u\fR
.RS 4
コミットログメッセージ、作者名、作者の電子メールアドレスは電子メールから取得され、MIME転送エンコーディングを最小限にデコードした後、それらを変換することにより、
\fBi18n\&.commitEncoding\fR
(デフォルトはUTF\-8) で指定された文字セットに再コーディングされます。これは以前はオプションでしたが、現在はデフォルトです。
.sp
注意: このフラグがあっても、パッチは常に文字セット変換なしでそのまま使用されることに注意してください。
.RE
.PP
\fB\-\-encoding=<encoding>\fR
.RS 4
\fB\-u\fR
に似ています。 ただし、再コーディング時には、
\fBi18n\&.commitEncoding\fR
で指定された文字セットまたはUTF\-8の代わりに、ここで指定した文字セットが使用されます。
.RE
.PP
\fB\-n\fR
.RS 4
メタデータのすべての文字セットの再コーディングを無効にします。
.RE
.PP
\fB\-m\fR, \fB\-\-message\-id\fR
.RS 4
コミットメッセージの最後にあるMessage\-IDヘッダーをコピーします。これは、コミットをメーリングリストのディスカッションに関連付けるのに役立ちます。
.RE
.PP
\fB\-\-scissors\fR
.RS 4
本文で切り取り線(例えば
\fB\-\- >8 \-\-\fR
)の前にあるすべてを取り除きます。 この線は、はさみ(scissors)とミシン目マークを表しており、その行でメッセージをカットするように読者に要求するために使用されます。パッチの前のメッセージの本文にその行が表示されている場合、このオプションを使用すると、その行の前のすべて(切り取り線の行自体を含む)が無視されます(訳注:
\fB>8\fR
や
\fB8<\fR
は「ハサミ」を示す絵文字)。
.sp
これは、返信するメッセージに関するコメントと提案を含むディスカッションスレッドでメッセージを開始し、パッチの送信でメッセージを終了し、ディスカッションと提案されたコミットログメッセージの開始を切り取り線で区切る場合に役立ちます。
.sp
これは、構成オプション mailinfo\&.scissors を使用してデフォルトで有効にできます。
.RE
.PP
\fB\-\-no\-scissors\fR
.RS 4
切り取り線を無視します。 mailinfo\&.scissors 設定を上書きするのに便利です。
.RE
.PP
\fB\-\-quoted\-cr=<action>\fR
.RS 4
base64またはquoted\-printableエンコーディングで送信された電子メールメッセージを処理し、デコードされた行が単純なLFではなくCRLFで終了する場合の操作(action)を指定。
.sp
有効な操作(action)は:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBnowarn\fR: そのようなCRLFが見つかった場合、Gitは何もしません。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBwarn\fR: そのようなCRLFが見つかった場合、 Gitはメッセージごとに警告を発行します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBstrip\fR: GitはそれらのCRLFをLFに変換します。
.RE
.sp
デフォルトの操作(action)は、構成オプション
\fBmailinfo\&.quotedCR\fR
で設定できます。そのような構成オプションが設定されていない場合、
\fBwarn\fR
が使用されます。
.RE
.PP
<msg>
.RS 4
電子メールから抽出されたコミットログメッセージ。通常、電子メールの件名から抽出したタイトル行は除きます。
.RE
.PP
<patch>
.RS 4
電子メールから抽出されたパッチ。
.RE
.SH "CONFIGURATION"
.sp
このセクションの以下のすべては、 \fBgit-config\fR(1) ドキュメントの抜粋です。 内容は \fBgit-config\fR(1) ドキュメント にあるものと同一です:
.PP
mailinfo\&.scissors
.RS 4
trueの場合、
\fBgit-mailinfo\fR(1)
(それゆえ
\fBgit-am\fR(1)
も)は、コマンドラインで
\fB\-\-scissors\fR
オプションが指定されているかのようにデフォルトで動作します。この機能がアクティブな場合、メッセージ本文から切り取り線(つまり、主に ">8" や "8<" や "\-" で構成される)行とそれより前のすべてを削除します。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
