'\" t
.\"     Title: git-count-objects
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-COUNT\-OBJECTS" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-count-objects \- パックされていない(unpack)オブジェクトの数とそのディスク消費量を計量します
.SH "SYNOPSIS"
.sp
.nf
\fIgit count\-objects\fR [\-v] [\-H | \-\-human\-readable]
.fi
.sp
.SH "DESCRIPTION"
.sp
これは、パックされていないオブジェクトファイルの数とそれらによって消費されたディスク領域を計量し、再パックするのに適した時期を判断するのに役立ちます。
.SH "OPTIONS"
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
より詳細な報告:
.sp
count: 緩いオブジェクト(loose objects;ファイルごとに１つのオブジェクトな形式)の数
.sp
size: 緩いオブジェクトによって消費される、KiB単位のディスク容量(\-H が指定されていない場合)
.sp
in\-pack: パック内にあるオブジェクトの数
.sp
size\-pack: パック群によって消費される、KiB単位のディスク容量(\-Hが指定されていない場合)
.sp
prune\-packable: パック内にも同じものが存在する緩いオブジェクトの数。これらの緩いオブジェクトは、\fBgit prune\-packed\fR
を使用して剪定する(prune)事ができます。
.sp
garbage: オブジェクトデータベース内の、有効な緩いオブジェクトでも有効なパックでもないファイルの数
.sp
size\-garbage: garbageファイルによって消費されるKiB単位のディスク容量(\-Hが指定されていない場合)
.sp
alternate: 代替オブジェクトデータベース群の絶対パス。パスごとに1行ずつ、複数回表示される場合があります。パスに印刷不可能な文字が含まれている場合は、二重引用符で囲まれ、C言語スタイルのバックスラッシュエスケープシーケンスが含まれている可能性があることに注意してください。
.RE
.PP
\fB\-H\fR, \fB\-\-human\-readable\fR
.RS 4
人間に分かりやすい形式でサイズを出力する
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
