'\" t
.\"     Title: git-column
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-COLUMN" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-column \- データを複数列表示する
.SH "SYNOPSIS"
.sp
.nf
\fIgit column\fR [\-\-command=<name>] [\-\-[raw\-]mode=<mode>] [\-\-width=<width>]
             [\-\-indent=<string>] [\-\-nl=<string>] [\-\-padding=<n>]
.fi
.sp
.SH "DESCRIPTION"
.sp
このコマンドは、標準入力の行を複数の列を持つテーブル(表)にフォーマットします。各入力行は、テーブルの1つのセルを占有します。これは、出力を複数列にフォーマットするために他のgitコマンドによって内部的に使用されます。
.SH "OPTIONS"
.PP
\fB\-\-command=<name>\fR
.RS 4
構成変数 column\&.<name> とcolumn\&.ui を使用してレイアウトモードを探します。
.RE
.PP
\fB\-\-mode=<mode>\fR
.RS 4
レイアウトモードを指定します。
\fBgit-config\fR(1)
のオプション構文については、構成変数 column\&.ui を参照してください。
.RE
.PP
\fB\-\-raw\-mode=<n>\fR
.RS 4
\fB\-\-mode\fR
と同じですが、数値としてエンコードされたモードを使用します。これは主に、レイアウトモードをすでにパースしている他のコマンドによって使用されます。
.RE
.PP
\fB\-\-width=<width>\fR
.RS 4
端末幅を指定します。デフォルトでは、「git column」は端末の幅を検出するか、検出できない場合は80にフォールバックします。
.RE
.PP
\fB\-\-indent=<string>\fR
.RS 4
各行の先頭に印刷される文字列。
.RE
.PP
\fB\-\-nl=<string>\fR
.RS 4
改行文字を含む、各行の終わりに印刷される文字列。
.RE
.PP
\fB\-\-padding=<N>\fR
.RS 4
列間のスペースの数。 デフォルトでは1つの空白。
.RE
.SH "EXAMPLES"
.sp
データを複数列(columns)でフォーマット:
.sp
.if n \{\
.RS 4
.\}
.nf
$ seq 1 24 | git column \-\-mode=column \-\-padding=5
1      4      7      10     13     16     19     22
2      5      8      11     14     17     20     23
3      6      9      12     15     18     21     24
.fi
.if n \{\
.RE
.\}
.sp
.sp
データを複数行(rows)でフォーマット:
.sp
.if n \{\
.RS 4
.\}
.nf
$ seq 1 21 | git column \-\-mode=row \-\-padding=5
1      2      3      4      5      6      7
8      9      10     11     12     13     14
15     16     17     18     19     20     21
.fi
.if n \{\
.RE
.\}
.sp
.sp
列幅が等しくないテーブルにいくつかのタグをリストします:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git tag \-\-list \*(Aqv2\&.4\&.*\*(Aq \-\-column=row,dense
v2\&.4\&.0  v2\&.4\&.0\-rc0  v2\&.4\&.0\-rc1  v2\&.4\&.0\-rc2  v2\&.4\&.0\-rc3
v2\&.4\&.1  v2\&.4\&.10     v2\&.4\&.11     v2\&.4\&.12     v2\&.4\&.2
v2\&.4\&.3  v2\&.4\&.4      v2\&.4\&.5      v2\&.4\&.6      v2\&.4\&.7
v2\&.4\&.8  v2\&.4\&.9
.fi
.if n \{\
.RE
.\}
.sp
.SH "CONFIGURATION"
.sp
このセクションの以下のすべては、 \fBgit-config\fR(1) ドキュメントの抜粋です。 内容は \fBgit-config\fR(1) ドキュメント にあるものと同一です:
.PP
column\&.ui
.RS 4
サポートされているコマンドを列(column)で出力するかどうかを指定します。 この変数は、スペースまたはコンマで区切られたトークンのリストで構成されます:
.sp
以下のオプションは、機能を有効にするタイミングを制御します(デフォルトは
\fBnever\fR):
.PP
\fBalways\fR
.RS 4
常に列表示
.RE
.PP
\fBnever\fR
.RS 4
決して列表示しない
.RE
.PP
\fBauto\fR
.RS 4
端末へ出力の場合は列表示
.RE
.sp
以下のオプションはレイアウトを制御します(デフォルトは
\fBcolumn\fR)。
\fBalways\fR
や
\fBnever\fR
や
\fBauto\fR
のいずれも指定されていない場合に、以下のいずれかを設定すると、
\fBalways\fR
の指定を含みます。
.PP
\fBcolumn\fR
.RS 4
行の前に列を埋める
.RE
.PP
\fBrow\fR
.RS 4
列の前に行を埋める
.RE
.PP
\fBplain\fR
.RS 4
1つの列に表示
.RE
.sp
最後に、以下のオプションはレイアウトオプションと組み合わせることができます(デフォルトは
\fBnodense\fR):
.PP
\fBdense\fR
.RS 4
より多くのスペースを利用するために不等サイズの列を作成する
.RE
.PP
\fBnodense\fR
.RS 4
同じサイズの列を作成する
.RE
.RE
.PP
column\&.branch
.RS 4
\fBgit branch\fR
でブランチリストを列出力するかどうかを指定します。 詳細については、
\fBcolumn\&.ui\fR
を参照してください。
.RE
.PP
column\&.clean
.RS 4
\fBgit clean \-i\fR
でアイテムを一覧表示するときのレイアウトを指定します。これにより、常にファイルとディレクトリが列表示されます。 詳細については、
\fBcolumn\&.ui\fR
を参照してください。
.RE
.PP
column\&.status
.RS 4
\fBgit status\fR
で追跡されていないファイルを列表示するかどうかを指定します。 詳細については、
\fBcolumn\&.ui\fR
を参照してください。
.RE
.PP
column\&.tag
.RS 4
\fBgit tag\fR
でタグリストを列出力するかどうかを指定します。 詳細については、
\fBcolumn\&.ui\fR
を参照してください。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
