'\" t
.\"     Title: git-mergetool--lib
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-MERGETOOL\-\-LI" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-mergetool--lib \- 共通 Gitマージツール シェル スクリプレット群
.SH "SYNOPSIS"
.sp
.nf
\fITOOL_MODE=(diff|merge) \&. "$(git \-\-exec\-path)/git\-mergetool\-\-lib"\fR
.fi
.sp
.SH "DESCRIPTION"
.sp
これは、全くもってエンドユーザー向けコマンドではありません。この文書は、磁器風のスクリプトを研究している、および/または 新しいスクリプトを書いている人々を対象としています。
.sp
\fIgit\-mergetool\-\-lib\fR スクリプトレットは、Gitマージツールを操作するための関数を設定するために、他のシェルスクリプトから( `\&.`を使用して)呼び出される(source)されるように設計されています。
.sp
\fIgit\-mergetool\-\-lib\fR を(sourceで)実行する前に、スクリプトで \fBTOOL_MODE\fR を設定して、以下にリストされている関数の操作モードを定義する必要があります。 \fIdiff\fR と \fImerge\fR は有効な値です。
.SH "FUNCTIONS"
.PP
get_merge_tool
.RS 4
マージツールを返します。推測されたマージツールを返した場合、戻りコードは1です。それ以外の場合は0です。適切なGUIツールを検索するために、
\fI$GIT_MERGETOOL_GUI\fR
を
\fItrue\fR
に設定できます。
.RE
.PP
get_merge_tool_cmd
.RS 4
マージツールのカスタムコマンドを返します。
.RE
.PP
get_merge_tool_path
.RS 4
マージツールのカスタムパスを返します。
.RE
.PP
initialize_merge_tool
.RS 4
マージツール固有の関数をスコープに入れて、使用またはオーバーライドできるようにします。
.RE
.PP
run_merge_tool
.RS 4
ツール名と true/false フラグを指定してマージツールを起動し、マージベースが存在するかどうかを示します。
\fI$MERGED\fR
・
\fI$LOCAL\fR
・
\fI$REMOTE\fR
・
\fI$BASE\fR
は、マージツールで使用するために定義する必要があります。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
