'\" t
.\"     Title: git-for-each-repo
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-FOR\-EACH\-REPO" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-for-each-repo \- リポジトリのリストでGitコマンドを実行します
.SH "SYNOPSIS"
.sp
.nf
\fIgit for\-each\-repo\fR \-\-config=<config> [\-\-] <arguments>
.fi
.sp
.SH "DESCRIPTION"
.sp
リポジトリのリストでGitコマンドを実行します。既知のオプションや \fB\-\-\fR の、後ろの引数は、Gitサブプロセスの引数として使用されます。
.sp
！！このコマンドは実験的なものです！！動作が変わる可能性があります！！
.sp
たとえば、以下を使用して、 \fBmaintenance\&.repo\fR 構成変数に格納されているリポジトリのリストのそれぞれに対して maintenance を実行できます。
.sp
.if n \{\
.RS 4
.\}
.nf
git for\-each\-repo \-\-config=maintenance\&.repo maintenance run
.fi
.if n \{\
.RE
.\}
.sp
.sp
これにより、複数値の構成変数である \fBmaintenance\&.repo\fR の各値である \fB<repo>\fR ごとに \fBgit \-C <repo> maintenance run\fR が実行されます。
.SH "OPTIONS"
.PP
\fB\-\-config=<config>\fR
.RS 4
指定された構成変数を、絶対パス名を格納する複数値リストとして使用します。そのパスのリストを繰り返して(iterate)、指定された引数を実行します。
.sp
これらの構成値は、利用可能な場合、システム、グローバル、およびローカルのGit構成からロードされます。
\fBgit for\-each\-repo\fR
がGitリポジトリではないディレクトリで実行される場合、システムとグローバル設定のみが使用されます。
.RE
.SH "SUBPROCESS BEHAVIOR"
.sp
\fBgit \-C <repo> <arguments>\fR サブプロセスがゼロ以外の終了コードを返す場合、 \fBgit for\-each\-repo\fR プロセスはそれ以上のサブプロセスを実行せずにその終了コードを返します。
.sp
各 \fBgit \-C <repo> <arguments>\fR サブプロセスは、標準のファイルデスクリプタ \fBstdin\fR と \fBstdout\fR と \fBstderr\fR を継承します。
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
