'\" t
.\"     Title: git-whatchanged
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-WHATCHANGED" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-whatchanged \- 各コミットでの差分のログを表示
.SH "SYNOPSIS"
.sp
.nf
\fIgit whatchanged\fR <option>\&...
.fi
.sp
.SH "DESCRIPTION"
.sp
各コミットのコミットログとdiff出力を表示します。
.sp
新規ユーザーは、これの代わりに \fBgit-log\fR(1) を使用することをお勧めします。 \fBwhatchanged\fR コマンドは基本的に \fBgit-log\fR(1) と同じですが、デフォルトでは生の形式の差分出力を表示し、マージをスキップします。
.sp
このコマンドは主に歴史的な理由で保持されています。\fBgit log\fR が発明されるずっと前に Linux kernel mailing list を読んで Gitを学んだ多くの人々の指は、このコマンドをタイプするよう訓練されています。
.SH "EXAMPLES"
.PP
\fBgit whatchanged \-p v2\&.6\&.12\&.\&. include/scsi drivers/scsi\fR
.RS 4
include/scsi または drivers/scsi サブディレクトリ内のファイルを変更したバージョン
\fIv2\&.6\&.12\fR
以降のコミットをパッチとして表示する
.RE
.PP
\fBgit whatchanged \-\-since="2 weeks ago" \-\- gitk\fR
.RS 4
過去2週間の変更をファイル
\fIgitk\fR
に表示します。 "\-\-" は、「ブランチ名
\fIgitk\fR
」との混同を避けるために必要です。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
