'\" t
.\"     Title: git-ls-remote
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-LS\-REMOTE" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-ls-remote \- リモートリポジトリの参照を一覧表示する
.SH "SYNOPSIS"
.sp
.nf
\fIgit ls\-remote\fR [\-\-heads] [\-\-tags] [\-\-refs] [\-\-upload\-pack=<exec>]
              [\-q | \-\-quiet] [\-\-exit\-code] [\-\-get\-url] [\-\-sort=<key>]
              [\-\-symref] [<repository> [<refs>\&...]]
.fi
.sp
.SH "DESCRIPTION"
.sp
リモートリポジトリで有効な参照を、関連するコミットIDとともに表示します。
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-heads\fR, \fB\-t\fR, \fB\-\-tags\fR
.RS 4
それぞれ、refs/heads と refs/tags のみに制限します。これらのオプションは相互に排他的ではありません。両方を指定すると、 refs/heads と refs/tags に保存されている参照が表示されます。コマンドラインで他に何も指定せずに使用された
\fBgit ls\-remote \-h\fR
は、他のgitサブコマンドと同じようにヘルプを提供することに注意してください。
.RE
.PP
\fB\-\-refs\fR
.RS 4
ピーリングされたタグ(peeled tag)や
\fBHEAD\fR
のような疑似参照(pseudoref)を出力に表示しないでください。
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
stderrにリモートURLを出力しないでください。
.RE
.PP
\fB\-\-upload\-pack=<exec>\fR
.RS 4
リモートホストの「git\-upload\-pack」のフルパスを指定します。これにより、SSH経由でアクセスされ、SSHデーモンがユーザーによって構成されたPATHを使用しないリポジトリからの参照を一覧表示できます。
.RE
.PP
\fB\-\-exit\-code\fR
.RS 4
リモートリポジトリに一致する参照が見つからない場合は、ステータス「2」で終了します。通常、コマンドはステータス「0」で終了し、一致する参照が見つかったかどうかに関係なく、リモートリポジトリと正常に通信したことを示します。
.RE
.PP
\fB\-\-get\-url\fR
.RS 4
\fBurl\&.<base>\&.insteadOf\fR
構成設定(\fBgit-config\fR(1)を参照)を考慮して、指定されたリモートリポジトリのURLを展開し、リモートと通信せずに終了します。
.RE
.PP
\fB\-\-symref\fR
.RS 4
それが指すオブジェクトに加えて、シンボリックrefを表示するときに、それが指す基になるrefを表示します。 現在、upload\-packはsymref HEADのみを表示するため、ls\-remoteによって表示されるのはこれだけです。
.RE
.PP
\fB\-\-sort=<key>\fR
.RS 4
指定されたキーに基づいて並べ替えます。接頭辞
\fB\-\fR
を使用して、値の降順で並べ替えます。
\fBversion:refname\fR
または
\fBv:refname\fR
をサポートします(タグ名はバージョンとして扱われます)。
\fBversion:refname\fR
のソート順は、
\fBversionsort\&.suffix\fR
構成変数の影響も受ける可能性があります。 その他の並べ替えオプションについては
\fBgit-for-each-ref\fR(1)
を参照してください。ただし、オブジェクト自体へのアクセスを必要とする
\fBcommitterdate\fR
のようなキーは、オブジェクトがまだリモートからフェッチされていないrefに対しては機能せず、
\fBmissing object\fR
エラーが発生することに注意してください。
.RE
.PP
\fB\-o <option>\fR, \fB\-\-server\-option=<option>\fR
.RS 4
プロトコルバージョン2を使用して通信する場合は、指定された文字列をサーバーに送信します。指定された文字列には、NULまたはLF文字を含めることはできません。 複数の
\fB\-\-server\-option=<option>\fR
が指定されている場合、それらはコマンドラインにリストされている順序で送信されます。
.RE
.PP
<repository>
.RS 4
クエリする「リモート」リポジトリ。 このパラメーターは、URLまたはリモートの名前のいずれかです(\fBgit-fetch\fR(1)
の「GIT URLS」と「REMOTES」セクションを参照してください)。
.RE
.PP
<refs>\&...
.RS 4
指定しない場合、
\fB\-\-heads\fR
と
\fB\-\-tags\fR
でフィルタリングを行った後のすべての参照が表示されます。 <refs>\&... を指定すると、指定したパターンに一致する参照のみが表示されます。
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
$ git ls\-remote \-\-tags \&./\&.
d6602ec5194c87b0fc87103ca4d67251c76f233a        refs/tags/v0\&.99
f25a265a342aed6041ab0cc484224d9ca54b6f41        refs/tags/v0\&.99\&.1
7ceca275d047c90c0c7d5afb13ab97efdf51bd6e        refs/tags/v0\&.99\&.3
c5db5456ae3b0873fc659c19fafdde22313cc441        refs/tags/v0\&.99\&.2
0918385dbd9656cab0d1d81ba7453d49bbc16250        refs/tags/junio\-gpg\-pub
$ git ls\-remote http://www\&.kernel\&.org/pub/scm/git/git\&.git master seen rc
5fe978a5381f1fbad26a80e682ddd2a401966740        refs/heads/master
c781a84b5204fb294c9ccc79f8b3baceeb32c061        refs/heads/seen
$ git remote add korg http://www\&.kernel\&.org/pub/scm/git/git\&.git
$ git ls\-remote \-\-tags korg v\e*
d6602ec5194c87b0fc87103ca4d67251c76f233a        refs/tags/v0\&.99
f25a265a342aed6041ab0cc484224d9ca54b6f41        refs/tags/v0\&.99\&.1
c5db5456ae3b0873fc659c19fafdde22313cc441        refs/tags/v0\&.99\&.2
7ceca275d047c90c0c7d5afb13ab97efdf51bd6e        refs/tags/v0\&.99\&.3
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.sp
\fBgit-check-ref-format\fR(1)\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
