'\" t
.\"     Title: git-show-index
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-SHOW\-INDEX" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-show-index \- パックされたアーカイブインデックスを表示する
.SH "SYNOPSIS"
.sp
.nf
\fIgit show\-index\fR [\-\-object\-format=<hash\-algorithm>]
.fi
.sp
.SH "DESCRIPTION"
.sp
標準入力から、(\fBgit-pack-objects\fR(1) または \fBgit-index-pack\fR(1) で作成の)Gitパックファイルの、 \fB\&.idx\fR ファイルを読み取り、その内容をダンプします。 出力は、行ごとに1つのオブジェクトで構成され、各行には2つまたは3つのスペースで区切られた複数列が含まれます:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
最初の列は、対応するパックファイル内のオブジェクトのバイト単位のオフセットです。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
2番目の列はオブジェクトのオブジェクトIDです
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
インデックスバージョンが2以上の場合、3番目の列にはオブジェクトデータのCRC32が含まれます
.RE
.sp
オブジェクトは、インデックスファイルで見つかった順序で出力されます。(正しく作成されたファイルであれば、)インデックスファイルはオブジェクトIDソートされていなければなりません。
.sp
注意: あなたは \fBgit-verify-pack\fR(1) を呼び出すと、パックファイルに関する情報をよりたくさん取得できます。けれども、このコマンド(show\-index)はインデックスファイル自体のみを考慮するため、より高速で柔軟性があります。
.SH "OPTIONS"
.PP
\fB\-\-object\-format=<hash\-algorithm>\fR
.RS 4
インデックスファイルのためのオブジェクト形式(ハッシュアルゴリズム)を指定します。有効な値は
\fIsha1\fR
および (有効な場合)
\fIsha256\fR
です。 デフォルトは、現在のリポジトリのアルゴリズム(\fBextensions\&.objectFormat\fR
で設定)、または値が設定されていないかリポジトリの外部にある場合は
\fIsha1\fR
です。
.sp
このオプションは実験的なものです！ SHA\-256のサポートは実験的なものであり、まだ初期段階です。 SHA\-256リポジトリは、通常、「通常の」SHA\-1リポジトリと作業を共有できません。 たとえば、SHA\-256リポジトリに関連するGit内部ファイル形式は、下位互換性のない方法で変更される可能性があると想定する必要があります。テスト目的でのみ
\fB\-\-object\-format=sha256\fR
を使用してください。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
