'\" t
.\"     Title: git-help
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-HELP" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-help \- Gitに関するヘルプ情報を表示します
.SH "SYNOPSIS"
.sp
.nf
\fIgit help\fR [\-a|\-\-all] [\-\-[no\-]verbose] [\-\-[no\-]external\-commands] [\-\-[no\-]aliases]
\fIgit help\fR [[\-i|\-\-info] [\-m|\-\-man] [\-w|\-\-web]] [<command>|<doc>]
\fIgit help\fR [\-g|\-\-guides]
\fIgit help\fR [\-c|\-\-config]
\fIgit help\fR [\-\-user\-interfaces]
\fIgit help\fR [\-\-developer\-interfaces]
.fi
.sp
.SH "DESCRIPTION"
.sp
オプションがなく、 \fB<command>\fR または \fB<doc>\fR が指定されていない場合、 gitコマンドの概要と最も一般的に使用されるGitコマンドのリストが標準出力に出力されます。
.sp
オプション \fB\-\-all\fR または \fB\-a\fR を指定すると、使用可能なすべてのコマンドが標準出力に出力されます。
.sp
オプション \fB\-\-guides\fR または \fB\-g\fR を指定すると、Gitコンセプトガイドのリストも標準出力に出力されます。
.sp
コマンドまたはその他のドキュメントを指定すると、 関連するマニュアル・ページが表示されます。 \fBman\fR プログラムは、この目的のためにデフォルトで使用されますが、これは他のオプションまたは構成変数によってオーバーライドできます。
.sp
エイリアスが指定されている場合、gitは標準出力にエイリアスの定義を表示します。 エイリアスコマンドのマニュアルページを取得するには、 \fBgit <command> \-\-help\fR を使用します。
.sp
注意: \fBgit \-\-help\&.\&.\&.\fR は \fBgit help \&.\&.\&.\fR と同じであることに注意してください。これは、前者が内部で後者に変換されるためです。
.sp
\fBgit\fR(1) のマニュアルページを表示するには、 \fBgit help git\fR を使用します。
.sp
このページは、 \fBgit help help\fR または \fBgit help \-\-help\fR で表示できます。
.SH "OPTIONS"
.PP
\fB\-a\fR, \fB\-\-all\fR
.RS 4
使用可能なすべてのコマンドを標準出力に出力します。
.RE
.PP
\fB\-\-no\-external\-commands\fR
.RS 4
\fB\-\-all\fR
とともに使用すると、
\fB$PATH\fR
上にある外部の
\fBgit\-*\fR
コマンドのリストが除外されます。
.RE
.PP
\fB\-\-no\-aliases\fR
.RS 4
\fB\-\-all\fR
とともに使用すると、構成されたエイリアス(configured aliases)のリストが除外されます。
.RE
.PP
\fB\-\-verbose\fR
.RS 4
\fB\-\-all\fR
と一緒に使用すると、認識されたすべてのコマンドの説明が出力されます。 これがデフォルトです。
.RE
.PP
\fB\-c\fR, \fB\-\-config\fR
.RS 4
使用可能なすべての構成変数をリストします。 これは、
\fBgit-config\fR(1)
のリストの簡単な要約です。
.RE
.PP
\fB\-g\fR, \fB\-\-guides\fR
.RS 4
Gitコンセプトガイドのリストを標準出力に出力します。
.RE
.PP
\fB\-\-user\-interfaces\fR
.RS 4
リポジトリや、コマンドや、ファイル・インターフェイス・ドキュメントのリストを標準出力に出力します。
.sp
\fB\&.git/info/exclude\fR
などのリポジトリ内ファイル・インターフェース(\fBgitrepository-layout\fR(5)
参照)は、\fB\&.mailmap\fR
などのツリー内設定(\fBgitmailmap\fR(5)
参照)と同様に、ここに文書化されています。
.sp
ドキュメントのこのセクションでは、一般的または広範なユーザー・インターフェイス規則(例:
\fBgitcli\fR(7))や、
\fBgithooks\fR(5)
で説明されているファイル・ベースの
\fB\&.git/hooks/*\fR
インターフェイスなどの疑似構成についても説明します。
.RE
.PP
\fB\-\-developer\-interfaces\fR
.RS 4
ファイル形式や、プロトコルや、その他の開発者インターフェース・キュメントのリストを標準出力に出力します。
.RE
.PP
\fB\-i\fR, \fB\-\-info\fR
.RS 4
コマンドのマニュアルページをinfo形式で表示します。
\fBinfo\fR
プログラムがその目的で使用されます。
.RE
.PP
\fB\-m\fR, \fB\-\-man\fR
.RS 4
コマンドのマニュアルページをman形式で表示します。 このオプションは、
\fBhelp\&.format\fR
構成変数に設定された値をオーバーライドするために使用できます。
.sp
デフォルトでは、
\fBman\fR
プログラムを使用してマニュアルページを表示しますが、
\fBman\&.viewer\fR
構成変数を使用して他の表示プログラムを選択することもできます(後述)。
.RE
.PP
\fB\-w\fR, \fB\-\-web\fR
.RS 4
コマンドのマニュアルページを
\fBweb\fR
(HTML)形式で表示します。その目的のためにウェブブラウザが使用されます。
.sp
Webブラウザーは、構成変数
\fBhelp\&.browser\fR
または
\fBweb\&.browser\fR
を使用して指定できます。前者が設定されていない場合は、
\fBweb\&.browser\fR
を使用します。 これらの構成変数のいずれも設定されていない場合、 (\fBgit help\fR
によって呼び出される、)
\fBgit web{litdd}browse\fR
ヘルパースクリプトが適切なデフォルトを選択します。 詳細については、
\fBgit-web--browse\fR(1)
を参照してください。
.RE
.SH "CONFIGURATION VARIABLES"
.SS "help\&.format"
.sp
コマンドラインオプションが渡されない場合、 \fBhelp\&.format\fR 構成変数がチェックされます。 この変数では、以下の値がサポートされています。 これらは \fBgit help\fR の対応するコマンドラインオプションとして動作します:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBman\fR
は
\fB\-m|\-\-man\fR
に対応します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBinfo\fR
は
\fB\-i|\-\-info\fR
に対応します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBweb\fR
または
\fBhtml\fR
は
\fB\-w|\-\-web\fR
に対応します。
.RE
.SS "help\&.browser と web\&.browser と browser\&.<tool>\&.path"
.sp
\fBhelp\&.browser\fR と \fBweb\&.browser\fR と \fBbrowser\&.<tool>\&.path\fR は、 (コマンドラインオプションまたは構成変数のいずれかによって、) \fBweb\fR 形式が選択されているかどうかもチェックされます。上記「OPTIONS」セクションの \fB\-w|\-\-web\fR と および \fBgit-web--browse\fR(1) を参照してください。
.SS "man\&.viewer"
.sp
\fBman\fR 形式が選択されている場合、 \fBman\&.viewer\fR 構成変数がチェックされます。 現在、以下の値がサポートされています:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBman\fR
: 通常どおり
\fBman\fR
プログラムを使用します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBwoman\fR
:
\fBemacsclient\fR
を使用してemacsで
\fBwoman\fR
モードを起動します(これはemacsclientバージョン22以降でのみ機能します)。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBkonqueror\fR
:
\fBkfmclient\fR
を使用して、新しいkonquerorタブでマニュアルページを開きます(以下の「Note about konqueror」を参照)。
.RE
.sp
対応する \fBman\&.<tool>\&.cmd\fR 構成エントリがある場合は、他のツールの値を使用できます(後述)。
.sp
\fBman\&.viewer\fR 構成変数に複数値を指定できます。対応するプログラムは、構成ファイルにリストされている順序で試されます。
.sp
たとえば、以下の構成:
.sp
.if n \{\
.RS 4
.\}
.nf
        [man]
                viewer = konqueror
                viewer = woman
.fi
.if n \{\
.RE
.\}
.sp
.sp
最初にkonquerorを使用しようと試みます。 ただし、これは失敗する可能性があり(たとえば、DISPLAYが設定されていない場合)、その場合、emacsのwomanモードが試されます。
.sp
すべてが失敗した場合、またはビューアが設定されていない場合は、 \fBGIT_MAN_VIEWER\fR 環境変数で指定されたビューアが試されます。それも失敗した場合は、とにかく \fBman\fR プログラムが試されます。
.SS "man\&.<tool>\&.path"
.sp
構成変数 \fBman\&.<tool>\&.path\fR を設定することにより、優先するmanビューアへのフルパスを明示的に指定できます。 たとえば、 \fBman\&.konqueror\&.path\fR を設定することで、konquerorへの絶対パスを設定できます。 それ以外の場合、 \fBgit help\fR はツールがPATH上にあると想定します。
.SS "man\&.<tool>\&.cmd"
.sp
\fBman\&.viewer\fR 構成変数で指定されたmanビューアがサポートされているものに含まれていない場合、対応する \fBman\&.<tool>\&.cmd\fR 構成変数が検索されます。 この変数が存在する場合、指定されたツールはカスタムコマンドとして扱われ、シェルのevalを使用して、引数として渡されたマニュアルページを使用してコマンドを実行します。
.SS "Note about konqueror"
.sp
\fBman\&.viewer\fR 構成変数で \fBkonqueror\fR が指定されている場合、可能であれば、 \fBkfmclient\fR を起動して、既に開いているkonquerorのmanページを新しいタブで開こうとします。
.sp
一貫性を保つために、 \fBman\&.konqueror\&.path\fR が \fBA_PATH_TO/konqueror\fR のようなものに設定されている場合にも、このようなトリックを試します。 つまり、代わりに \fBA_PATH_TO/kfmclient\fR を起動しようとします。
.sp
あなたが本当に \fBkonqueror\fR を使用したい場合は、以下のようなものを使用できます:
.sp
.if n \{\
.RS 4
.\}
.nf
        [man]
                viewer = konq

        [man "konq"]
                cmd = A_PATH_TO/konqueror
.fi
.if n \{\
.RE
.\}
.sp
.SS "Note about \fBgit config \-\-global\fR"
.sp
注意: これらの構成変数はすべて、たとえば以下のように、 \fB\-\-global\fR フラグを使用して設定する必要があることに注意してください:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git config \-\-global help\&.format web
$ git config \-\-global web\&.browser firefox
.fi
.if n \{\
.RE
.\}
.sp
.sp
それらは、おそらくリポジトリ固有というよりはユーザー固有であるためです。 詳細については、 \fBgit-config\fR(1) を参照してください。
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
