'\" t
.\"     Title: git-sh-i18n--envsubst
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-SH\-I18N\-\-ENV" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-sh-i18n--envsubst \- i18nフォールバック用のGit独自のenvsubst(1)
.SH "SYNOPSIS"
.sp
.nf
eval_gettext () {
        printf "%s" "$1" | (
                export PATH $(\fIgit sh\-i18n\-\-envsubst\fR \-\-variables "$1");
                \fIgit sh\-i18n\-\-envsubst\fR "$1"
        )
}
.fi
.sp
.SH "DESCRIPTION"
.sp
これは、全くもってエンドユーザーが実行するコマンドではありません。この文書は、配管スクリプトを研究している、および/または新しいスクリプトを作成している人々を対象としています。
.sp
\fIgit sh\-i18n\-\-envsubst\fR は、GNU gettextパッケージに付属するGNU \fBenvsubst(1)\fR プログラムのGit用簡略版です。これは、 \fBgit-sh-i18n\fR(1) によって内部的に使用され、 \fBeval_gettext\fR 関数に渡された変数を差し込みます。
.sp
インターフェイスについては何も約束されていません。また、このプログラムが次のバージョンのGitで警告なしに消えることはありません。使用しないでください。(No promises are made about the interface, or that this program won\(cqt disappear without warning in the next version of Git\&. Don\(cqt use it\&.)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
