git-checkout(1)
===============

NAME
----
git-checkout - ブランチの切り替え、または作業ツリーファイルの復元を行います。

SYNOPSIS
--------
[synopsis]
	git checkout [-q] [-f] [-m] [<branch>]
	git checkout [-q] [-f] [-m] --detach [<branch>]
	git checkout [-q] [-f] [-m] [--detach] <commit>
	git checkout [-q] [-f] [-m] [[-b|-B|--orphan] <new-branch>] [<start-point>]
	git checkout <tree-ish> [--] <pathspec>...
	git checkout <tree-ish> --pathspec-from-file=<file> [--pathspec-file-nul]
	git checkout [-f|--ours|--theirs|-m|--conflict=<style>] [--] <pathspec>...
	git checkout [-f|--ours|--theirs|-m|--conflict=<style>] --pathspec-from-file=<file> [--pathspec-file-nul]
	git checkout (-p|--patch) [<tree-ish>] [--] [<pathspec>...]

DESCRIPTION
-----------

`git checkout` has two main modes:

1. **Switch branches**, with `git checkout <branch>`
2. **Restore a different version of a file**, for example with
   `git checkout <commit> <filename>` or `git checkout <filename>`

See ARGUMENT DISAMBIGUATION below for how Git decides which one to do.

`git checkout [<branch>]`::
	Switch to _<branch>_. This sets the current branch to _<branch>_ and updates the files in your working directory. The checkout will fail if there are uncommitted changes to any files where _<branch>_ and your current commit have different content. Uncommitted changes will otherwise be kept.
+
If _<branch>_ is not found but there does exist a tracking branch in exactly one remote (call it _<remote>_) with a matching name and `--no-guess` is not specified, treat as equivalent to
+
------------
$ git checkout -b <branch> --track <remote>/<branch>
------------
+
Running `git checkout` without specifying a branch has no effect except to print out the tracking information for the current branch.

`git checkout -b <new-branch> [<start-point>]`::

	Create a new branch named _<new-branch>_, start it at _<start-point>_ (defaults to the current commit), and check out the new branch. You can use the `--track` or `--no-track` options to set the branch's upstream tracking information.
+
This will fail if there's an error checking out _<new-branch>_, for example if checking out the `<start-point>` commit would overwrite your uncommitted changes.

`git checkout -B <branch> [<start-point>]`::

	The same as `-b`, except that if the branch already exists it resets _<branch>_ to the start point instead of failing.

`git checkout --detach [<branch>]`::
`git checkout [--detach] <commit>`::

	The same as `git checkout <branch>`, except that instead of pointing `HEAD` at the branch, it points `HEAD` at the commit ID. See the "DETACHED HEAD" section below for more.
+
Omitting _<branch>_ detaches `HEAD` at the tip of the current branch.

`git checkout <tree-ish> [--] <pathspec>...`::
`git checkout <tree-ish> --pathspec-from-file=<file> [--pathspec-file-nul]`::

	Replace the specified files and/or directories with the version from the given commit or tree and add them to the index (also known as "staging area").
+
For example, `git checkout main file.txt` will replace `file.txt` with the version from `main`.

`git checkout [-f|--ours|--theirs|-m|--conflict=<style>] [--] <pathspec>...`::
`git checkout [-f|--ours|--theirs|-m|--conflict=<style>] --pathspec-from-file=<file> [--pathspec-file-nul]`::

	Replace the specified files and/or directories with the version from the index.
+
For example, if you check out a commit, edit `file.txt`, and then decide those changes were a mistake, `git checkout file.txt` will discard any unstaged changes to `file.txt`.
+
This will fail if the file has a merge conflict and you haven't yet run `git add file.txt` (or something equivalent) to mark it as resolved. You can use `-f` to ignore the unmerged files instead of failing, use `--ours` or `--theirs` to replace them with the version from a specific side of the merge, or use `-m` to replace them with the original conflicted merge result.

`git checkout (-p|--patch) [<tree-ish>] [--] [<pathspec>...]`::
	This is similar to the previous two modes, but lets you use the interactive interface to show the "diff" output and choose which hunks to use in the result. See below for the description of `--patch` option.

OPTIONS
-------
`-q`::
`--quiet`::
	静かにします。フィードバックメッセージを抑制します。

`--progress`::
`--no-progress`::
	`--quiet` が指定されていない限り、進行状況は、端末に接続されている場合、デフォルトで標準エラーストリームに報告されます。 このフラグは、 `--quiet` に関係なく、端末に接続されていない場合でも進行状況のレポートを有効にします。

`-f`::
`--force`::
	ブランチを切り替えるとき、インデックスや作業ツリーが `HEAD` と異なっていても、また、邪魔な未追跡のファイルがあっても進行します。 これは、ローカルの変更や、邪魔な未追跡のファイルやディレクトリを捨てるために使用します。
+
インデックスからパスをチェックアウトするときは、マージされていないエントリ(unmerged entries)はエラーにせず、代わりに無視します。

`--ours`::
`--theirs`::
	When checking out paths from the index, check out stage #2 (`ours`) or #3 (`theirs`) for unmerged paths.
+
Note that during `git rebase` and `git pull --rebase`, `ours` and `theirs` may appear swapped; `--ours` gives the version from the branch the changes are rebased onto, while `--theirs` gives the version from the branch that holds your work that is being rebased.
+
これは、リモートでの履歴を共有の正規の履歴として扱うワークフローで `rebase` が使用されているためです。リベースするブランチで行われた作業を、統合されるサードパーティの作業として扱います。そして、あなたは一時的にリベース中に正規の歴史の管理者の役割を引き受けています。正規の履歴の管理者として、リモートからの履歴を「私たち」(ours; つまり、「私達の共有された正規の履歴」)として表示する必要があり、サイドブランチで行ったことは「彼ら」(theirs;つまり「その上での貢献者の作品」)として表示する必要があります。

`-b <new-branch>`::
	Create a new branch named _<new-branch>_, start it at _<start-point>_, and check the resulting branch out; see linkgit:git-branch[1] for details.

`-B <new-branch>`::
	The same as `-b`, except that if the branch already exists it resets _<branch>_ to the start point instead of failing.

`-t`::
`--track[=(direct|inherit)]`::
	When creating a new branch, set up "upstream" configuration. See `--track` in linkgit:git-branch[1] for details. As a convenience, --track without -b implies branch creation.
+
`-b` オプションが指定されていない場合、新しいブランチの名前は、対応するリモート用に構成されたrefspecのローカル部分を調べ、最初の部分を `*` まで削除することにより、リモート追跡ブランチから派生させます。これにより、 `origin/hack` (または `remotes/origin/hack`、 あるいは `refs/remotes/origin/hack`) から分岐するときに、ローカルブランチとして `hack` を使用するように指示されます。指定された名前にスラッシュ(`/`)がない場合、または上記の推測の結果が空の名前になる場合、推測は中止されます。このような場合は、 `-b` を使用して明示的に名前を付けることができます。

`--no-track`::
	`branch.autoSetupMerge` 構成変数がtrueであっても、「上流構成」を設定しないでください。

`--guess`::
`--no-guess`::
	If _<branch>_ is not found but there does exist a tracking branch in exactly one remote (call it _<remote>_) with a matching name, treat as equivalent to
+
------------
$ git checkout -b <branch> --track <remote>/<branch>
------------
+
If the branch exists in multiple remotes and one of them is named by the `checkout.defaultRemote` configuration variable, we'll use that one for the purposes of disambiguation, even if the _<branch>_ isn't unique across all remotes. Set it to e.g. `checkout.defaultRemote=origin` to always checkout remote branches from there if _<branch>_ is ambiguous but exists on the 'origin' remote. See also `checkout.defaultRemote` in linkgit:git-config[1].
+
`--guess` がデフォルトの振る舞いです。無効にするには、 `--no-guess` を使用します。
+
デフォルトの振る舞いは、`checkout.guess` 構成変数を介して設定できます。

`-l`::
	新しいブランチのreflogを作成します。詳細については、 linkgit:git-branch[1] を参照してください。

`-d`::
`--detach`::
	Rather than checking out a branch to work on it, check out a commit for inspection and discardable experiments. This is the default behavior of `git checkout <commit>` when _<commit>_ is not a branch name. See the "DETACHED HEAD" section below for details.

`--orphan <new-branch>`::
	Create a new unborn branch, named _<new-branch>_, started from _<start-point>_ and switch to it. The first commit made on this new branch will have no parents and it will be the root of a new history totally disconnected from all the other branches and commits.
+
The index and the working tree are adjusted as if you had previously run `git checkout <start-point>`. This allows you to start a new history that records a set of paths similar to _<start-point>_ by easily running `git commit -a` to make the root commit.
+
これは、ツリーの完全な履歴を公開せずにコミットからツリーを公開する場合に便利です。これは、現在のツリーが「クリーン」であるが、完全な履歴にはプロプライエタリなコードやその他の邪魔なコードが含まれているプロジェクトの、オープンソースブランチを公開するためにこれを行うことができます。
+
If you want to start a disconnected history that records a set of paths that is totally different from the one of _<start-point>_, then you should clear the index and the working tree right after creating the orphan branch by running `git rm -rf .` from the top level of the working tree. Afterwards you will be ready to prepare your new files, repopulating the working tree, by copying them from elsewhere, extracting a tarball, etc.

`--ignore-skip-worktree-bits`::
	In sparse checkout mode, `git checkout -- <path>...` would update only entries matched by _<paths>_ and sparse patterns in `$GIT_DIR/info/sparse-checkout`. This option ignores the sparse patterns and adds back any files in `<path>...`.

`-m`::
`--merge`::
	ブランチを切り替えるときに、現在のブランチと切り替え先のブランチの間で異なる1つ以上のファイルにローカルの変更がある場合、コマンドは、コンテキストでの変更を保持するためにブランチの切り替えを拒否します。ただし、このオプションを使用すると、現在のブランチ、作業ツリーの内容、および新しいブランチの間の3方向のマージを実行してから新しいブランチに移動します。
+
マージの競合が発生すると、競合するパスのインデックスエントリはマージされないままになります。競合を解決し、解決されたパスを `git add`（またはマージによってパスが削除される場合は `git rm`)でマークする必要があります。
+
インデックスからパスをチェックアウトする場合、このオプションを使用すると、指定したパスで競合するマージを再作成できます。 このオプションは、 ツリーっぽい何か(tree-ish)からパスをチェックアウトする場合には使用できません。
+
`--merge` でブランチを切り替えると、ステージされた変更が失われる可能性があります。

`--conflict=<style>`::
	The same as `--merge` option above, but changes the way the conflicting hunks are presented, overriding the `merge.conflictStyle` configuration variable. Possible values are `merge` (default), `diff3`, and `zdiff3`.

`-p`::
`--patch`::
	Interactively select hunks in the difference between the _<tree-ish>_ (or the index, if unspecified) and the working tree. The chosen hunks are then applied in reverse to the working tree (and if a _<tree-ish>_ was specified, the index).
+
This means that you can use `git checkout -p` to selectively discard edits from your current working tree. See the "Interactive Mode" section of linkgit:git-add[1] to learn how to operate the `--patch` mode.
+
注意: このオプションはデフォルトでオーバーレイなしモードを使用します(`--overlay` も参照)。現在はオーバーレイモードをサポートしていないことに注意してください。

include::diff-context-options.adoc[]

`--ignore-other-worktrees`::
	`git checkout` は、 必要なブランチが既にチェックアウト済か、 別のワークツリーによって使用されている場合には拒否されます。 このオプションを使用すると、 とにかくブランチをチェックアウトします。 つまり、 このブランチは1つ以上のワークツリーで使用される可能性があります。

`--overwrite-ignore`::
`--no-overwrite-ignore`::
	ブランチを切り替えるときに、無視したファイルを黙って上書きします。これがデフォルトの動作です。新しいブランチに無視したファイルが含まれている場合に操作を中止するには、 `--no-overwrite-ignore` を使用します。

`--recurse-submodules`::
`--no-recurse-submodules`::
	`--recurse-submodules` を使用すると、スーパープロジェクトに記録されたコミットに従って、すべてのアクティブなサブモジュールのコンテンツが更新されます。サブモジュールのローカル変更が上書きされる場合、 `-f` が使用されない限り、チェックアウトは失敗します。何も使用されていない場合(または `--no-recurse-submodules`)、サブモジュールの作業ツリーは更新されません。 linkgit:git-submodule[1] と同様に、これはサブモジュールの `HEAD` を切り離します(detach)。

`--overlay`::
`--no-overlay`::
	In the default overlay mode, `git checkout` never removes files from the index or the working tree. When specifying `--no-overlay`, files that appear in the index and working tree, but not in _<tree-ish>_ are removed, to make them match _<tree-ish>_ exactly.

`--pathspec-from-file=<file>`::
	Pathspec is passed in _<file>_ instead of commandline args. If _<file>_ is exactly `-` then standard input is used. Pathspec elements are separated by _LF_ or _CR_/_LF_. Pathspec elements can be quoted as explained for the configuration variable `core.quotePath` (see linkgit:git-config[1]). See also `--pathspec-file-nul` and global `--literal-pathspecs`.

`--pathspec-file-nul`::
	Only meaningful with `--pathspec-from-file`. Pathspec elements are separated with _NUL_ character and all other characters are taken literally (including newlines and quotes).

`<branch>`::
	チェックアウトするブランチ。もしそれがブランチ(つまり、 `refs/heads/` を前につけたとき、有効なrefである名前)を参照しているなら、そのブランチはチェックアウトされます。そうでない場合、もしそれが有効なコミットを参照していれば、あなたの `HEAD` は "detached" となり、あなたはもはやどのブランチにもいません(詳しくは以下を参照してください)。
+
`@{-N}` 構文を使用して、 `git checkout` を使って、チェックアウトされた最後からN番目 ブランチ/コミット を参照できます。 `@{-1}` と同義の `-` を指定することもできます。
+
As a special case, you may use `<rev-a>...<rev-b>` as a shortcut for the merge base of _<rev-a>_ and _<rev-b>_ if there is exactly one merge base. You can leave out at most one of _<rev-a>_ and _<rev-b>_, in which case it defaults to `HEAD`.

_<new-branch>_::
	新しいブランチの名前。

_<start-point>_::
	新しいブランチを開始するコミットの名前。詳細については、 linkgit:git-branch[1] を参照してください。デフォルトは `HEAD` です。
+
As a special case, you may use `<rev-a>...<rev-b>` as a shortcut for the merge base of _<rev-a>_ and _<rev-b>_ if there is exactly one merge base. You can leave out at most one of _<rev-a>_ and _<rev-b>_, in which case it defaults to `HEAD`.

_<tree-ish>_::
	チェックアウト元のツリー(パスが指定されている場合)。指定しない場合はインデックスが使用されます。
+
As a special case, you may use `<rev-a>...<rev-b>` as a shortcut for the merge base of _<rev-a>_ and _<rev-b>_ if there is exactly one merge base. You can leave out at most one of _<rev-a>_ and _<rev-b>_, in which case it defaults to `HEAD`.

`--`::
	これ以降の引数をオプションとして解釈しないでください。

`<pathspec>...`::
	操作の影響を受けるパスを制限します。
+
詳細については、 linkgit:gitglossary[7] の「pathspec」エントリを参照してください。

DETACHED HEAD
-------------
`HEAD` は通常、名前付きブランチ(`master` など)を指します。一方、各ブランチは特定のコミットを参照します。3つのコミットがあり、そのうちの1つがタグ付けされており、ブランチ `master` がチェックアウトされているリポジトリを見てみましょう:

------------
           HEAD (refers to branch 'master')
            |
            v
a---b---c  branch 'master' (refers to commit 'c')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

When a commit is created in this state, the branch is updated to refer to the new commit. Specifically, `git commit` creates a new commit `d`, whose parent is commit `c`, and then updates branch `master` to refer to new commit `d`. `HEAD` still refers to branch `master` and so indirectly now refers to commit `d`:

------------
$ edit; git add; git commit

               HEAD (refers to branch 'master')
                |
                v
a---b---c---d  branch 'master' (refers to commit 'd')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

名前付きブランチの先端にないコミットをチェックアウトしたり、名前付きブランチによって参照されていない新しいコミットを作成したりできると便利な場合があります。 コミット `b` をチェックアウトするとどうなるか見てみましょう(ここでは、これを行う2つの方法を示します):

------------
$ git checkout v2.0  # or
$ git checkout master^^

   HEAD (refers to commit 'b')
    |
    v
a---b---c---d  branch 'master' (refers to commit 'd')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

どのチェックアウト・コマンドを使用しても、 今や `HEAD` が直接コミット `b` を参照することに注目してください。 これは、切り離された `HEAD` (detached HEAD)状態として知られています。 単に `HEAD` が名前付きブランチではなく、 特定のコミットを参照することを意味します。 この状態でコミットを作成するとどうなるか見てみましょう:

------------
$ edit; git add; git commit

     HEAD (refers to commit 'e')
      |
      v
      e
     /
a---b---c---d  branch 'master' (refers to commit 'd')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

新しいコミット `e` がありますが、これは `HEAD` によってのみ参照されます。 もちろん、この状態でさらに別のコミットを追加できます:

------------
$ edit; git add; git commit

	 HEAD (refers to commit 'f')
	  |
	  v
      e---f
     /
a---b---c---d  branch 'master' (refers to commit 'd')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

実際、私達は通常のGit操作はすべて実行できます。 しかし、ここで私達が `master` をチェックアウトするとどうなるか見てみましょう:

------------
$ git checkout master

               HEAD (refers to branch 'master')
      e---f     |
     /          v
a---b---c---d  branch 'master' (refers to commit 'd')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

この時点で、コミット `f` を指しているものは何もないことを理解することが重要です。最終的に、コミット `f` (および拡張によりコミット `e` )は、あなたがルーチンのGitガベージコレクションプロセス前に参照を作成しない限り、ルーチンのGitガベージコレクションプロセスによって削除されます。あなたが、まだコミット`f`から離れていない場合、以下のいずれかがそれへの参照を作成します:

------------
$ git checkout -b foo  # or "git switch -c foo"  <1>
$ git branch foo                                 <2>
$ git tag foo                                    <3>
------------
<1> コミット `f` を参照する新しいブランチ `foo` を作成し、次にブランチ `foo` を参照するように`HEAD`を更新します。つまり、このコマンドを実行すると、もはや切り離された`HEAD` (detached HEAD)状態では無くなります。
<2> 同様に、コミット `f` を参照する新しいブランチ `foo` を作成しますが、 `HEAD` は切り離されたままにします。
<3> 新しいタグ `foo` を作成します。これは、`HEAD` を切り離したままコミット `f` を参照します。

私達がうっかり `f` から離れてしまった場合は、最初にそのオブジェクト名を回復する必要があり(通常は `git reflog` を使用)、次にそれへの参照を作成できます。 たとえば、 `HEAD` が参照した最後の2つのコミットを確認するには、以下のいずれかのコマンドを使用できます:

------------
$ git reflog -2 HEAD # or
$ git log -g -2 HEAD
------------

ARGUMENT DISAMBIGUATION(引数の曖昧性解消)
---------------------------------

When you run `git checkout <something>`, Git tries to guess whether `<something>` is intended to be a branch, a commit, or a set of file(s), and then either switches to that branch or commit, or restores the specified files.

If there's any ambiguity, Git will treat `<something>` as a branch or commit, but you can use the double dash `--` to force Git to treat the parameter as a list of files and/or directories, like this:

----------
git checkout -- file.txt
----------

EXAMPLES
--------

=== 1. Paths

以下のシーケンスは、 `master` ブランチをチェックアウトし、 `Makefile` のリビジョンを2つ戻し、誤って `hello.c` を削除したので、 `hello.c` をインデックスから取得します。

------------
$ git checkout master             <1>
$ git checkout master~2 Makefile  <2>
$ rm -f hello.c
$ git checkout hello.c            <3>
------------
<1> ブランチを切り替えます
<2> 別のコミットからファイルを取り出します
<3> インデックスから `hello.c` を復元します

あなたがインデックスから「すべての」Cソースファイルをチェックアウトしたい場合は、以下のように言うことができます

------------
$ git checkout -- '*.c'
------------

`*.c` を囲む引用符に注意してください。 ファイル `hello.c` も、作業ツリーに存在していなくてもチェックアウトされます。これは、(引用符で囲む事で作業ツリーに対してシェル展開するのではなくて)ファイルグロブがインデックスのエントリを照合するために使用されるためです。

`hello.c` という名前の不幸なブランチがある場合、このステップはそのブランチに切り替えるための指示として混乱を産みます。あなたは代わりに以下のように書く必要があります。

------------
$ git checkout -- hello.c
------------

=== 2. Merge

間違ったブランチで作業した後、正しいブランチへの切り替えは以下を使用して行います:

------------
$ git checkout mytopic
------------

ただし、あなたの「間違った」ブランチと正しい `mytopic` ブランチは、ローカルで変更したファイルで異なる場合があります。その場合、上記のチェックアウトは以下のように失敗します:

------------
$ git checkout mytopic
error: You have local changes to 'frotz'; not switching branches.
------------

コマンドに `-m` フラグを指定すると、3方向のマージを試みます:

------------
$ git checkout -m mytopic
Auto-merging frotz
------------

この3方向マージの後、ローカルの変更はインデックスファイルに登録されないため、 `git diff` は、新しいブランチの先端以降に行った変更を表示します。

=== 3. Merge conflict

`-m` オプションを使用してブランチを切り替えるときにマージの競合が発生すると、以下のように表示されます:

------------
$ git checkout -m mytopic
Auto-merging frotz
ERROR: Merge conflict in frotz
fatal: merge program failed
------------

この時点で、 `git diff` は、前の例のようにきれいにマージされた変更と、競合するファイルの変更を示しています。 競合を編集して解決し、通常どおり `git add` で解決済みのマークを付けます。

------------
$ edit frotz
$ git add frotz
------------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/checkout.adoc[]

SEE ALSO
--------
linkgit:git-switch[1], linkgit:git-restore[1]

GIT
---
Part of the linkgit:git[1] suite
