git-repo(1)
===========

NAME
----
git-repo - リポジトリーに関する情報を取得

SYNOPSIS
--------
[synopsis]
	git repo info [--format=(keyvalue|nul)] [-z] [<key>...]
	git repo structure [--format=(table|keyvalue|nul)]

DESCRIPTION
-----------
リポジトリーに関する情報を取得します。

※このコマンドは実験的(EXPERIMENTAL)なものです。 振る舞いは変更される可能性があります。

COMMANDS
--------
`info [--format=(keyvalue|nul)] [-z] [<key>...]`::
	現在のリポジトリに関するメタデータ関連の情報を取得します。要求されたデータのみが、そのキーに基づいて返されます(後述の "INFO KEYS" セクションを参照)。
+
値は、それぞれのキーが要求されたのと同じ順序で返されます。
+
出力形式は `--format` フラグで選択できます。2 つの形式をサポートします:
+
`keyvalue`:::
	キーと値の区切り文字として `=` を使用し、キーと値のペアを 1 行に 1 つずつ出力します。「通常ではない」文字を含む値は、設定変数 `core.quotePath` の説明に従ってクオートされます(linkgit:git-config[1] 参照)。これがデフォルトです。

`nul`:::
	`keyvalue` に似ていますが、キーと値の区切り文字に改行文字を使用し、各値の後に NUL 文字を使用します。この形式は `keyvalue` よりも他のアプリケーションで解析するのに適しています。`keyvalue` 形式とは異なり、値は決してクオートされません。
+
`-z` は `--format=nul` の別名です。

`structure [--format=(table|keyvalue|nul)]`::
	現在のリポジトリ構造に関する統計情報を取得します。以下の種類の情報が報告されます:
+
* 種類別の参照数
* 種類別の到達可能オブジェクト数

+
出力形式は `--format` フラグで選択できます。3 つの形式をサポートします:
+
`table`:::
	リポジトリの統計情報を、人間に読みやすい表形式で出力します。この形式は変更される可能性があり、機械による解析を意図していません。これがデフォルト形式です。

`keyvalue`:::
	出力の各行には、リポジトリ統計のキーと値のペアが含まれます。キーと値の区切りには '=' 文字を使用します。「通常ではない」文字を含む値は、設定変数 `core.quotePath` の説明に従ってクオートされます(linkgit:git-config[1] 参照)。

`nul`:::
	`keyvalue` に似ていますが、キーと値のペアの区切りに改行ではなく NUL 文字を使用します。また、キーと値の区切りには '=' の代わりに改行文字を使用します。`keyvalue` 形式とは異なり、「通常ではない」文字を含む値も決してクオートされません。

INFO KEYS
---------
`git repo info` から値の集合を得るには、それらを識別するキーを指定する必要があります。利用可能なキーと、それらが返す値の一覧は次のとおりです:

`layout.bare`::
	ベアリポジトリであれば `true`、そうでなければ `false` です。

`layout.shallow`::
	shallow リポジトリであれば `true`、そうでなければ `false` です。

`object.format`::
	リポジトリで使用されているオブジェクト形式(ハッシュアルゴリズム)です。

`references.format`::
	参照ストレージ形式です。有効な値は次のとおりです:
+
include::ref-storage-format.adoc[]

EXAMPLES
--------

* 現在のリポジトリの参照形式を取得します:
+
------------
git repo info references.format
------------
+

* `nul` 形式を使って、現在のリポジトリがベアかどうか、および shallow かどうかを取得します:
+
------------
git repo info --format=nul layout.bare layout.shallow
------------

SEE ALSO
--------
linkgit:git-rev-parse[1]

GIT
---
Part of the linkgit:git[1] suite
