'\" t
.\"     Title: git-grep
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-GREP" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-grep \- パターンにマッチする行を出力します
.SH "SYNOPSIS"
.sp
.nf
\fIgit grep\fR [\-a | \-\-text] [\-I] [\-\-textconv] [\-i | \-\-ignore\-case] [\-w | \-\-word\-regexp]
           [\-v | \-\-invert\-match] [\-h|\-H] [\-\-full\-name]
           [\-E | \-\-extended\-regexp] [\-G | \-\-basic\-regexp]
           [\-P | \-\-perl\-regexp]
           [\-F | \-\-fixed\-strings] [\-n | \-\-line\-number] [\-\-column]
           [\-l | \-\-files\-with\-matches] [\-L | \-\-files\-without\-match]
           [(\-O | \-\-open\-files\-in\-pager) [<pager>]]
           [\-z | \-\-null]
           [ \-o | \-\-only\-matching ] [\-c | \-\-count] [\-\-all\-match] [\-q | \-\-quiet]
           [\-\-max\-depth <depth>] [\-\-[no\-]recursive]
           [\-\-color[=<when>] | \-\-no\-color]
           [\-\-break] [\-\-heading] [\-p | \-\-show\-function]
           [\-A <post\-context>] [\-B <pre\-context>] [\-C <context>]
           [\-W | \-\-function\-context]
           [(\-m | \-\-max\-count) <num>]
           [\-\-threads <num>]
           [\-f <file>] [\-e] <pattern>
           [\-\-and|\-\-or|\-\-not|(|)|\-e <pattern>\&...]
           [\-\-recurse\-submodules] [\-\-parent\-basename <basename>]
           [ [\-\-[no\-]exclude\-standard] [\-\-cached | \-\-no\-index | \-\-untracked] | <tree>\&...]
           [\-\-] [<pathspec>\&...]
.fi
.sp
.SH "DESCRIPTION"
.sp
作業ツリーの追跡ファイル(tracked files)内または、インデックスファイルに登録されているブロブまたは、指定のツリーオブジェクトのブロブ、で指定のパターンを探します。 パターンは、改行文字(newline characters)で区切られた1つ以上の検索式のリストです。 検索式としての空文字列は、すべての行にマッチします。
.SH "OPTIONS"
.PP
\fB\-\-cached\fR
.RS 4
作業ツリーで追跡中のファイル(tracked files)を検索する代わりに、インデックスファイルに登録されているブロブを検索します。
.RE
.PP
\fB\-\-no\-index\fR
.RS 4
Git管理管理下に無い、現在のディレクトリ内のファイルを検索します。
.RE
.PP
\fB\-\-untracked\fR
.RS 4
作業ツリーで、追跡中のファイル(tracked files)を検索するだけでなく、追跡されていないファイル(untracked files)も検索します。
.RE
.PP
\fB\-\-no\-exclude\-standard\fR
.RS 4
また、
\fB\&.gitignore\fR
メカニズムを尊重せずに、無視されたファイル(ignored files)を検索します。
\fB\-\-untracked\fR
でのみ役立ちます。
.RE
.PP
\fB\-\-exclude\-standard\fR
.RS 4
\fB\&.gitignore\fR
メカニズムを介して指定されている、無視されたファイル(ignored files)に注意を払わないでください。
\fB\-\-no\-index\fR
を使用して現在のディレクトリ内のファイルを検索する場合にのみ役立ちます。
.RE
.PP
\fB\-\-recurse\-submodules\fR
.RS 4
リポジトリ内で、アクティブかつチェックアウトされている各サブモジュールを再帰的に検索します。 <tree> オプションと組み合わせて使用すると、すべてのサブモジュール出力のプレフィックスは、親プロジェクトの <tree> オブジェクトの名前になります。
\fB\-\-no\-index\fR
が指定されている場合、このオプションは効果がありません。
.RE
.PP
\fB\-a\fR, \fB\-\-text\fR
.RS 4
バイナリファイルをテキストであるかのように処理します。
.RE
.PP
\fB\-\-textconv\fR
.RS 4
textconvフィルター設定を尊重します。
.RE
.PP
\fB\-\-no\-textconv\fR
.RS 4
textconvフィルター設定を尊重しません。 これがデフォルトです。
.RE
.PP
\fB\-i\fR, \fB\-\-ignore\-case\fR
.RS 4
パターンとファイルの間で英大文字小文字の違いは無視(ignore case)してください。
.RE
.PP
\fB\-I\fR
.RS 4
バイナリファイルでパターンのマッチをしないでください。
.RE
.PP
\fB\-\-max\-depth <depth>\fR
.RS 4
コマンドラインで指定された<pathspec>ごとに、最大 <depth> レベルまでディレクトリを降りていくかを指定します。 \-1 は、制限がないことを意味します。 <pathspec> にアクティブなワイルドカード(active wildcards)が含まれている場合、このオプションは無視されます。言い換えると、
\fBa*\fR
が
\fBa*\fR
という名前のディレクトリと一致する場合、
\fB*\fR
は文字通り一致するため、
\fB\-\-max\-depth\fR
は引き続き有効です。
.RE
.PP
\fB\-r\fR, \fB\-\-recursive\fR
.RS 4
\fB\-\-max\-depth=\-1\fR
と同一です。これがデフォルトです。
.RE
.PP
\fB\-\-no\-recursive\fR
.RS 4
\fB\-\-max\-depth=0\fR
と同一です。
.RE
.PP
\fB\-w\fR, \fB\-\-word\-regexp\fR
.RS 4
パターンは単語(word)単位でのみ一致します(行頭で開始するかまたは単語以外の文字が先行するかのいずれか。行末で終わるか、単語以外の文字が続きます)。
.RE
.PP
\fB\-v\fR, \fB\-\-invert\-match\fR
.RS 4
一致しない行を選択します。
.RE
.PP
\fB\-h\fR, \fB\-H\fR
.RS 4
デフォルトでは、コマンドは各々マッチしたファイル名を表示します。
\fB\-h\fR
オプションは、この出力を抑制するために使用されます。\fB\-H\fR
はオプション機能として完全を期すためにあり、コマンドラインで
\fB\-H\fR
以前に指定した
\fB\-h\fR
を打ち消す以外は何もしません。
.RE
.PP
\fB\-\-full\-name\fR
.RS 4
サブディレクトリから実行する場合、コマンドは通常、現在のディレクトリからの相対パスを出力します。 このオプションは、プロジェクトの最上位ディレクトリを基準にしたパスを出力します。
.RE
.PP
\fB\-E\fR, \fB\-\-extended\-regexp\fR, \fB\-G\fR, \fB\-\-basic\-regexp\fR
.RS 4
パターンにはPOSIX 拡張/基本 正規表現を使用します。 デフォルトでは基本正規表現を使用します。
.RE
.PP
\fB\-P\fR, \fB\-\-perl\-regexp\fR
.RS 4
パターンにはPerl互換の正規表現を使用してください。
.sp
これらのタイプの正規表現のサポートは、コンパイル時オプションに依存します。 Gitがこれらのサポート付きでコンパイルされていない場合、このオプションを指定するとGitが停止(die)します。
.RE
.PP
\fB\-F\fR, \fB\-\-fixed\-strings\fR
.RS 4
パターンには固定文字列を使用します(パターンを正規表現として解釈しないでください)。
.RE
.PP
\fB\-n\fR, \fB\-\-line\-number\fR
.RS 4
マッチした行の前に行番号を付けます。
.RE
.PP
\fB\-\-column\fR
.RS 4
マッチがあった行の中で(複数マッチするかもしれないので)、最初にマッチしたぶんの行頭(行頭を0じゃなくて1とする)からのオフセットバイト(1\-indexed byte\-offset)を行頭に置きます。
.RE
.PP
\fB\-l\fR, \fB\-\-files\-with\-matches\fR, \fB\-\-name\-only\fR, \fB\-L\fR, \fB\-\-files\-without\-match\fR
.RS 4
一致したすべての行を表示する代わりに、一致を含む(または含まない;\fB\-\-files\-without\-match\fR)ファイル名のみを表示します。
\fBgit diff\fR
との互換性を高めるために、\fB\-\-name\-only\fR
が
\fB\-\-files\-with\-matches\fR
の同義語となっています。
.RE
.PP
\fB\-O[<pager>]\fR, \fB\-\-open\-files\-in\-pager[=<pager>]\fR
.RS 4
一致するファイルをページャーで開きます(ただし、
\fBgrep\fR
の出力ではありません)。 ページャーがたまたま「less」または「vi」であり、ユーザーが1つのパターンのみを指定した場合、 最初に開かれるファイルは自動的に最初のマッチになります。
\fBpager\fR
引数はオプションです。 指定する場合は、 スペースなしでオプションに固定する必要があります。
\fBpager\fR
が指定されていない場合、 デフォルトのページャーが使用されます(\fBgit-config\fR(1)
の`core\&.pager` を参照)。(訳注:lessで次のファイルに移動するには :n とタイプする。詳しくはmanページ参照)
.RE
.PP
\fB\-z\fR, \fB\-\-null\fR
.RS 4
出力のパス名の区切り文字として
\fB\e0\fR
を使用し、そのまま(verbatim)出力します。 このオプションがないと、構成変数 core\&.quotePath で説明されているように、「異常な」文字を含むパス名がクォートされます(\fBgit-config\fR(1)
参照)。
.RE
.PP
\fB\-o\fR, \fB\-\-only\-matching\fR
.RS 4
マッチがある行のマッチする(空でない)部分のみを出力し、行内で複数マッチした場合、そのような各部分を別々の行に出力します。(訳注: 例えば
\fBgit grep \-n \-\-break \-\-column \-\-only\-matching hoge\fR)
.RE
.PP
\fB\-c\fR, \fB\-\-count\fR
.RS 4
マッチした行を全て表示する代わりに、ファイル毎にマッチした行の行数を表示します。
.RE
.PP
\fB\-\-color[=<when>]\fR
.RS 4
色付きのマッチ表示します。 値は always (デフォルト) または never または auto である必要があります。
.RE
.PP
\fB\-\-no\-color\fR
.RS 4
構成ファイルがデフォルトでカラー出力を提供している場合でも、マッチのハイライト表示をオフにします。
\fB\-\-color=never\fR
と同じです。
.RE
.PP
\fB\-\-break\fR
.RS 4
一致の出力で、異なるファイルの間に(区切りとして)1行の空行を出力します。(訳注:例
\fBgit grep \-\-break \-\-heading hoge\fR)
.RE
.PP
\fB\-\-heading\fR
.RS 4
マッチしたのを表示する各行の初めファイル名を表示するのではなく、表示するファイル毎に、その直前にファイル名だけの行を出力します。 (訳注:例
\fBgit grep \-\-break \-\-heading hoge\fR)
.RE
.PP
\fB\-p\fR, \fB\-\-show\-function\fR
.RS 4
マッチした行が関数名そのものでない限り、 マッチした関数名を含む先行の行を表示します。 名前は、
\fBgit diff\fR
がパッチハンクヘッダーを処理するのと同じ方法で決定されます (\fBgitattributes\fR(5)
の「Defining a custom hunk\-header」参照)。
.RE
.PP
\fB\-<num>\fR, \fB\-C <num>\fR, \fB\-\-context <num>\fR
.RS 4
各マッチ行ごとに <num>行の先行する行と後続する行も表示し、 マッチしたグループ毎に
\fB\-\-\fR
行を挿入します。
.RE
.PP
\fB\-A <num>\fR, \fB\-\-after\-context <num>\fR
.RS 4
各マッチ行ごとに <num> 行の後続行も表示し、マッチしたグループ毎に
\fB\-\-\fR
行を挿入します。
.RE
.PP
\fB\-B <num>\fR, \fB\-\-before\-context <num>\fR
.RS 4
各マッチした行ごとに <num> 行の先行する行も表示し、 マッチしたグループ毎に
\fB\-\-\fR
行を挿入します。
.RE
.PP
\fB\-W\fR, \fB\-\-function\-context\fR
.RS 4
関数名を含む前の行から次の関数名の前の行までの周囲のテキストを表示し、マッチした関数全体を効果的に示します。 関数名は、
\fBgit diff\fR
がパッチハンクヘッダーを処理するのと同じ方法で決定されます(\fBgitattributes\fR(5)
の「Defining a custom hunk\-header」参照)。
.RE
.PP
\fB\-m <num>\fR, \fB\-\-max\-count <num>\fR
.RS 4
ファイルごとのマッチ数を制限します。
\fB\-v\fR
または
\fB\-\-invert\-match\fR
オプションを使用すると、指定された数の不一致の後に検索(search)が停止(stop)します。 \-1 の値は無制限の結果を返します (デフォルト)。 0 の値は、ゼロ以外のステータスですぐに終了します。
.RE
.PP
\fB\-\-threads <num>\fR
.RS 4
使用するgrepワーカースレッドの数。 詳細については、「CONFIGURATION」の「grep\&.threads」を参照してください。
.RE
.PP
\fB\-f <file>\fR
.RS 4
<file>から1行に1つずつパターンを読み取ります。
.sp
<file>を介してパターンを渡すと、
\fB\e0\fR
を含む検索パターンを指定できます。
.sp
すべてのパターンタイプが
\fB\e0\fR
を含むパターンをサポートしているわけではありません。 特定のパターンタイプがそのようなパターンをサポートできない場合、Gitはエラーになります。 PCRE v2 バックエンドに対してコンパイルされた場合の
\fB\-\-perl\-regexp\fR
パターンタイプは、これらのタイプのパターンを最も広くサポートしています。
.sp
Git の 2\&.23\&.0 より前のバージョンでは、
\fB\e0\fR
を含むパターンは黙って修正されます。 これは全く文書化されておらず、また、例えば
\fB\e0\fR
を含む非ASCIIパターンと
\fB\-\-ignore\-case\fR
との間の文書化されていない奇妙な相互作用がありました。
.sp
将来のバージョンでは、より多くの検索バックエンドが
\fB\e0\fR
を含むパターンをサポートする可能性がありますが、それまでは、問題のパターンタイプがそれらをサポートしない場合は終了(die)します。
.RE
.PP
\fB\-e\fR
.RS 4
これに続く次のパラメータはパターンであることを示します。 このオプションは、
\fB\-\fR
で始まるパターンに使用する必要があり、ユーザー入力をgrepに渡すスクリプトで使用する必要があります。複数のパターンは or 結合されます。
.RE
.PP
\fB\-\-and\fR, \fB\-\-or\fR, \fB\-\-not\fR, \fB( \&.\&.\&. )\fR
.RS 4
ブール式を使用して、複数のパターンを組み合わせる方法を指定します。
\fB\-\-or\fR
はデフォルトの演算子です。
\fB\-\-and\fR
は
\fB\-\-or\fR
よりも優先されます。
\fB\-e\fR
はすべてのパターンに使用する必要があります。
.RE
.PP
\fB\-\-all\-match\fR
.RS 4
\fB\-\-or\fR
と組み合わせて複数のパターン式を指定する場合、このフラグを指定して、すべてにマッチする行を持つファイルにマッチを制限します。
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
マッチした行を出力しないでください。 代わりに、マッチした場合は終了ステータス0で終了し、マッチしない場合は終了ステータスがゼロ以外で終了します。
.RE
.PP
\fB<tree>\&.\&.\&.\fR
.RS 4
作業ツリーで追跡中のファイル(tracked files)を検索する代わりに、指定のツリーでブロブを検索します。
.RE
.PP
\fB\-\-\fR
.RS 4
コマンドにオプション指定の終了を教えます。 残りのパラメーターは <pathspec> リミッターです。
.RE
.PP
\fB<pathspec>\&.\&.\&.\fR
.RS 4
指定されている場合は、検索を少なくとも1つのパターンに一致するパスに制限します。 パスの先行一致 と glob(7)パターン の両方がサポートされます。
.sp
<pathspec> 構文の詳細については、
\fBgitglossary\fR(7)
の「pathspec」エントリを参照してください。
.RE
.SH "EXAMPLES"
.PP
\fBgit grep \*(Aqtime_t\*(Aq \-\- \*(Aq*\&.[ch]\*(Aq\fR
.RS 4
作業ディレクトリとそのサブディレクトリで、追跡中(tracked)のすべての \&.c ファイルと \&.h ファイルで
\fBtime_t\fR
を探します。
.RE
.PP
\fBgit grep \-e \*(Aq#define\*(Aq \-\-and \e( \-e MAX_PATH \-e PATH_MAX \e)\fR
.RS 4
\fB#define\fR
かつ、
\fBMAX_PATH\fR
または
\fBPATH_MAX\fR
のいずれか、を持つ行を探します。
.RE
.PP
\fBgit grep \-\-all\-match \-e NODE \-e Unexpected\fR
.RS 4
各ファイル内で
\fBNODE\fR
または
\fBUnexpected\fR
を探し、かつ、
\fBNODE\fR
と
\fBUnexpected\fR
の両方を持つ行があるファイルだけを表示します。
.RE
.PP
\fBgit grep solution \-\- :^Documentation\fR
.RS 4
\fBDocumentation\fR
ファイルを除くファイル達から
\fBsolution\fR
を探します。
.RE
.SH "NOTES ON THREADS"
.sp
\fB\-\-open\-files\-in\-pager\fR が使用されている場合、 \fB\-\-threads\fR オプション(および grep\&.threads 構成)は無視され、シングルスレッド実行が強制されます。
.sp
オブジェクトストアを(\fB\-\-cached\fR を使用して、またはツリーオブジェクトを指定して)grepする場合、 \fB\-\-textconv\fR が指定され、テキスト変換が多すぎると、複数のスレッドで実行するとシングルスレッドよりもパフォーマンスが低下する可能性があります。 したがって、このような場合でパフォーマンスが低下する時は、 \fB\-\-threads=1\fR を使用することが望ましい場合があります。
.SH "CONFIGURATION"
.sp
このセクションの以下のすべては、 \fBgit-config\fR(1) ドキュメントの抜粋です。 内容は \fBgit-config\fR(1) ドキュメント にあるものと同一です:
.PP
grep\&.lineNumber
.RS 4
trueに設定すると、デフォルトで
\fB\-n\fR
オプションが有効になります。
.RE
.PP
grep\&.column
.RS 4
trueに設定されている場合、デフォルトで
\fB\-\-column\fR
オプションを有効にします。
.RE
.PP
grep\&.patternType
.RS 4
デフォルトのマッチング動作を設定します。
\fBbasic\fR
または
\fBextended\fR
または
\fBfixed\fR
または
\fBperl\fR
の値を使用すると、それぞれに応じて
\fB\-\-basic\-regexp\fR
または ` \-\-extended\-regexp` または
\fB\-\-fixed\-strings\fR
または
\fB\-\-perl\-regexp\fR
オプションが有効になります。 値
\fBdefault\fR
は
\fBgrep\&.extendedRegexp\fR
オプションを使用して
\fBbasic\fR
と
\fBextended\fR
のどちらかを選択します。
.RE
.PP
grep\&.extendedRegexp
.RS 4
trueに設定されている場合、デフォルトで
\fB\-\-extended\-regexp\fR
オプションを有効にします。
\fBgrep\&.patternType\fR
オプションが
\fBdefault\fR
以外の値に設定されている場合、このオプションは無視されます。
.RE
.PP
grep\&.threads
.RS 4
使用する grep ワーカー・スレッドの数。 設定しない場合(または 0 に設定した場合)、 Git は使用可能な論理コアの数と同じ数のスレッドを使用します。
.RE
.PP
grep\&.fullName
.RS 4
trueに設定すると、デフォルトで
\fB\-\-full\-name\fR
オプションが有効になります。
.RE
.PP
grep\&.fallbackToNoIndex
.RS 4
trueに設定すると、
\fBgit grep\fR
がgitリポジトリの外部で実行される場合は、
\fBgit grep \-\-no\-index\fR
にフォールバックします。 デフォルトはfalseです。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
