git-multi-pack-index(1)
=======================

NAME
----
git-multi-pack-index - マルチ・パック・インデックスの書き出し・検証


SYNOPSIS
--------
[synopsis]
	'git multi-pack-index' [--object-dir=<dir>] [--[no-]bitmap] <sub-command>

DESCRIPTION
-----------
マルチ・パック・インデックス(MIDX;multi-pack-index)ファイルの書き出し・検証を行う。

OPTIONS
-------

`--object-dir=<dir>`::
	Gitオブジェクトの場所として、指定されたディレクトリを使用します。 現在のMIDXファイルについては `<dir>/packs/multi-pack-index` をチェックし、インデックスを作成するパックファイルについては `<dir>/packs` をチェックします。
+
`<dir>` は、現在のリポジトリの代替(alternate)である必要があります。

`--progress`::
`--no-progress`::
	進行状況を明示的にオン/オフにします。どちらも指定されていない場合、標準エラーが端末に接続されていれば進行状況が表示されます。 サブコマンド `write` と `verify` と `expire` と `repack` がサポートされています。

以下のサブコマンドを使用できます:

write::
	新しいMIDXファイルを書き込みます。 `write` サブコマンドでは、以下のオプションを使用できます:
+
--
	`--preferred-pack=<pack>`::
	指定すると、他のパックにもそのオブジェクトの追加コピーがある場合に、このパックを優先して雌雄を決めます。 優先パックに見つからないオブジェクトについての雌雄は、 常に mtime が最も新しいパックにあるコピーが優先されます。 指定しない場合、 既定では mtime が最も古いパックが使用されます。 優先パックには少なくとも 1 つのオブジェクトが含まれている必要があります。

	`--[no-]bitmap`::
		マルチパックビットマップ(multi-pack bitmap)を書き込むかどうかを制御します。

	`--stdin-packs`::
		stdin 経由で提供される行区切りのパック・インデックスのベース名のセットのみを含む
		マルチパック・インデックスを作成します。

	`--refs-snapshot=<path>`::
		`--bitmap` を使用して、必要に応じて、再パックの前に作成された
		「refs スナップショット」を含むファイルを指定します。
+
参照スナップショットは、参照先端(reference tips)に対応する行区切りの OID で構成され、通常は新しいパックを生成する前に +git repack+ によって取得されます。 オプションで `+` 文字で始まる行は、 その OID に対応する参照が「優先」(preferred)であることを示すことができます(linkgit:git-config[1] の `pack.preferBitmapTips` を参照してください)。
+
`<path>` で指定されたファイルは読み取り可能であることが期待されており、重複を含んでいる可能性があります。 (特定の OID が複数回指定されている場合、少なくとも 1 つのインスタンスが特別な `+` マーカーで始まる場合、優先としてマークされます)。

	`--incremental`::
		既存のMIDXレイヤーに存在しないオブジェクトとパックのみを含む増分MIDXファイル(incremental MIDX file)を書き込みます。
		必要に応じて、
		非増分のMIDX達を増分のMIDXに移行します。
		`--bitmap` とは互換性がありません。
--

verify::
	MIDXファイルの内容を検証(verify)します。

expire::
	MIDXファイルによって追跡されているが、MIDXによって参照されているオブジェクトがないパックファイルを削除します(`.keep` パックと cruft パックを除く)。その後、MIDXファイルを書き直して、これらのパックファイルへのすべての参照を削除します。
+
NOTE: このモードは、増分MIDXファイル(incremental MIDX files)と互換性がありません。

repack::
	マルチパックインデックス(multi-pack-index)によって参照される小さなパックファイル(pack-files)にオブジェクトを含む新しいパックファイルを作成します。 `--batch-size=<size>` 引数で指定されたサイズがゼロの場合、マルチパックインデックスによって参照されるすべてのオブジェクトを含むパックを作成します。ゼロ以外のバッチサイズの場合は、パックを古いものから新しいものへと調べてパックファイルを選択します。マルチパックインデックスによって参照されるパック内のオブジェクトの数をカウントすることにより、「予想サイズ」を計算します。次に、予想サイズをパック内のオブジェクトの総数で割り、パックサイズを掛けます。パックのセットが少なくともバッチサイズの合計予想サイズになるまで、またはすべてのパックファイルが考慮されるまで、予想サイズがバッチサイズよりも小さいパックを選択します。パックファイルが1つだけ選択されている場合は、何もしません。 新しいパックファイルが作成された場合は、マルチパックインデックスを書き直して(rewrite)、新しいパックファイルを参照します。後で `git multi-pack-index expire` を実行すると、このバッチの一部であったパックファイルが削除されます。
+
`repack.packKeptObjects` が `false` の場合、 `.keep` ファイルが関連付けられているパックファイルはバッチで再パックするために選択されません。
+
NOTE: このモードは、増分MIDXファイル(incremental MIDX files)と互換性がありません。

EXAMPLES
--------

* 現在の `.git` ディレクトリにパックファイル達のMIDXファイルを書き込みます。
+
-----------------------------------------------
$ git multi-pack-index write
-----------------------------------------------


* 対応するビットマップを使用して、現在の `.git` ディレクトリ内のパックファイル達のMIDXファイルを書き込みます。
+
-------------------------------------------------------------
$ git multi-pack-index write --preferred-pack=<pack> --bitmap
-------------------------------------------------------------

* 代替オブジェクトストア(alternate object store)にパックファイルのMIDXファイルを書き込みます。
+
-----------------------------------------------
$ git multi-pack-index --object-dir <alt> write
-----------------------------------------------

* 現在の `.git` ディレクトリ内のパックファイル達のMIDXファイルを検証(verify)します。
+
-----------------------------------------------
$ git multi-pack-index verify
-----------------------------------------------


SEE ALSO
--------
マルチパックインデックス機能の詳細については、 link:technical/multi-pack-index.html[The Multi-Pack-Index Design Document] と linkgit:gitformat-pack[5] を参照してください。


GIT
---
Part of the linkgit:git[1] suite
