'\" t
.\"     Title: git-bugreport
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-BUGREPORT" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-bugreport \- ユーザーがバグ報告を提出するための情報を収集する
.SH "SYNOPSIS"
.sp
.nf
\fIgit bugreport\fR [(\-o | \-\-output\-directory) <path>] [(\-s | \-\-suffix) <format>]
                [\-\-diagnose[=<mode>]]
.fi
.sp
.SH "DESCRIPTION"
.sp
ユーザーのマシン、Gitクライアント、リポジトリの状態に関する情報、およびユーザーが観察した動作に関する情報の入力書式を(例えば、Gitメーリングリストに観察されたバグを報告するために)、ユーザーが共有できる単一のテキストファイルとして獲得します。
.sp
以下の情報がユーザーに要求されます:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
再現手順
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
期待する動作
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
実際の動作
.RE
.sp
以下の情報が自動的に収集されます:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIgit version \-\-build\-options\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
uname sysname と release と version と machine strings
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
コンパイラ指定情報文字列
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
有効なフックのリスト
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
$SHELL
.RE
.sp
追加情報は、 \fB\-\-diagnose\fR オプションを使用して別の zip アーカイブに収集することができ、読者に追加のコンテキストを提供するためにバグレポート・ドキュメントと一緒に添付できます。
.sp
このツールは、通常のGitセットアッププロセスを介して呼び出されます。つまり、関連する構成ファイルが読み取れない場合など、起動できない場合があります。 この種のシナリオでは、手動で助けを求めるときに、上記の種類の情報を手動で収集すると役立つ場合があります。
.SH "OPTIONS"
.PP
\fB\-o <path>\fR, \fB\-\-output\-directory <path>\fR
.RS 4
結果のバグレポートファイルを現在のディレクトリではなく
\fB<path>\fR
に配置します。
.RE
.PP
\fB\-s <format>\fR, \fB\-\-suffix <format>\fR
.RS 4
バグレポート名の代替サフィックスを指定して、
\fBgit\-bugreport\-<formatted suffix>\fR
という名前のファイルを作成します。 これは、 strftime(3) 形式の文字列の形式をとる必要があります。現在の現地時間が使用されます。
.RE
.PP
\fB\-\-no\-diagnose\fR, \fB\-\-diagnose[=<mode>]\fR
.RS 4
ユーザーの、マシンとGitクライアントとリポジトリの状態に関する補足情報の zip アーカイブを作成します。 アーカイブはバグ・レポートと同じ出力ディレクトリに書き込まれ、
\fBgit\-diagnostics\-<formatted suffix>\fR
という名前が付けられます。
.sp
\fBmode\fR
が指定されていない場合、診断アーカイブには
\fBgit diagnostic\fR
によって報告されるデフォルトの統計セットが含まれます。 オプションの
\fBmode\fR
値を指定して、アーカイブに含める情報を変更できます。
\fBmode\fR
の有効な値のリストとその使用方法の詳細については、\fBgit-diagnose\fR(1)
を参照してください。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
