'\" t
.\"     Title: git-var
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-VAR" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-var \- Git論理変数を表示します
.SH "SYNOPSIS"
.sp
.nf
\fIgit var\fR ( \-l | <variable> )
.fi
.sp
.SH "DESCRIPTION"
.sp
Git論理変数を出力します。
.SH "OPTIONS"
.PP
\fB\-l\fR
.RS 4
論理変数をリストします。さらに、Git構成ファイル \&.git/config のすべての変数も一覧表示されます。 (ただし、構成変数を一覧表示する機能は非推奨になり、
\fBgit config \-l\fR
が採用されました。)
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
$ git var GIT_AUTHOR_IDENT
Eric W\&. Biederman <ebiederm@lnxi\&.com> 1121223278 \-0600
.fi
.if n \{\
.RE
.\}
.SH "VARIABLES"
.PP
GIT_AUTHOR_IDENT
.RS 4
コードの作者。
.RE
.PP
GIT_COMMITTER_IDENT
.RS 4
コードの一部をGitに入れた人。
.RE
.PP
GIT_EDITOR
.RS 4
Gitコマンドで使用するためのテキストエディタ。 この値は、 使用時にシェルによって解釈されることを意図しています。 例:
\fB~/bin/vi\fR
、
\fB$SOME_ENVIRONMENT_VARIABLE\fR
、
\fB"C:\eProgram Files\eVim\egvim\&.exe" \-\-nofork\fR
。 優先順位は、
\fB$GIT_EDITOR\fR
環境変数 、\fBcore\&.editor\fR
構成、
\fB$VISUAL\fR
、\fB$EDITOR\fR
、そしてコンパイル時に選択されるデフォルト(通常は
\fBvi\fR)です。
.RE
.PP
GIT_PAGER
.RS 4
Gitコマンドで使用するためのテキストビューア(例: less)。値はシェルによって解釈されることを意図しています。 優先順位は、
\fB$GIT_PAGER\fR
環境変数、
\fBcore\&.pager\fR
構成、
\fB$PAGER\fR
、そしてコンパイル時に選択されるデフォルト(通常は
\fBless\fR)です。
.RE
.PP
GIT_DEFAULT_BRANCH
.RS 4
新しく初期化されたリポジトリで作成された最初のブランチの名前。
.RE
.SH "SEE ALSO"
.sp
\fBgit-commit-tree\fR(1) \fBgit-tag\fR(1) \fBgit-config\fR(1)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
