'\" t
.\"     Title: git-http-push
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-HTTP\-PUSH" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-http-push \- HTTP/DAV を介してオブジェクトを別のリポジトリにプッシュする
.SH "SYNOPSIS"
.sp
.nf
\fIgit http\-push\fR [\-\-all] [\-\-dry\-run] [\-\-force] [\-\-verbose] <URL> <ref> [<ref>\&...]
.fi
.sp
.SH "DESCRIPTION"
.sp
リモートに不足しているオブジェクトをリモートリポジトリに送信し、リモートブランチを更新します。
.sp
\fB注\fR : libcurlが7\&.16より古い場合、このコマンドは一時的に無効になります。 これは、組み合わせが機能しないことが報告されており、 リポジトリが破損する場合があるためです。
.SH "OPTIONS"
.PP
\fB\-\-all\fR
.RS 4
リモートリポジトリが現在の状態で完全であると想定しません。また、ローカルrefの履歴全体のすべてのオブジェクトがリモートリポジトリに存在することを確認します。
.RE
.PP
\fB\-\-force\fR
.RS 4
通常、コマンドは、上書きに使用されたローカルrefの祖先ではないリモートrefの更新を拒否します。このフラグはこのチェックを無効にします。これが意味するのは、リモートリポジトリがコミットを失う可能性があるということです。注意して使用してください。
.RE
.PP
\fB\-\-dry\-run\fR
.RS 4
実際に更新を送信する以外はすべて行います。
.RE
.PP
\fB\-\-verbose\fR
.RS 4
ローカルでウォークされているオブジェクトのリストと、リモートリポジトリに正常に送信されたオブジェクトのリストを報告します。
.RE
.PP
\fB\-d\fR, \fB\-D\fR
.RS 4
リモートリポジトリから <ref> を削除します。指定のブランチをリモートHEADにすることはできません。
\fB\-d\fR
を指定する場合は、以下の他の条件も満たす必要があります:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
リモートHEADは、ローカルに存在するオブジェクトに名前解決(resolve)できなければなりません。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
指定のブランチは、ローカルに存在するオブジェクトに名前解決(resolve)します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
指定のブランチは、リモートHEADの祖先です。
.RE
.RE
.PP
<ref>\&...
.RS 4
更新したいリモートrefs
.RE
.SH "SPECIFYING THE REFS"
.sp
\fB<ref>\fR 指定は、単一のパターン、またはコロン \fB:\fR で区切られた、そのようなパターンのペアのいずれかです(これは、ref名にコロンを含めることができないことを意味します)。 単一のパターン \fB<name>\fR は、 \fB<name>:<name>\fR の短縮形です。
.sp
各パターン ペア \fB<src>:<dst>\fR は、ソース側 (コロンの前) と宛先側 (コロンの後) で構成されます。 プッシュされるrefは、ソース側に一致する一致を見つけることによって決定され、プッシュされる場所は、宛先側を使用して決定されます。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB<src>\fR
がローカルrefの1つと正確に一致しない場合は、エラーになります。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB<dst>\fR
がどのリモートrefとも一致しない場合、以下のどちらかです
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
"refs/" で始まる必要があります。この場合、文字通り <dst> が宛先として使用されます。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
<src> == <dst> かつ <src> に一致するrefは、リモートrefのセットに存在してはなりません。ローカルで一致するref <src> は、宛先の名前として使用されます。
.RE
.RE
.sp
\fB\-\-force\fR の指定が無く、<dst> が存在しない場合または <dst> が <src> の適切なサブセット(つまり、祖先)である場合のみリモートに保存されます。 "fast\-forward check" (早送りチェック)と呼ばれるこのチェックは、リモートrefを誤って上書きして、そこから他の人のコミットを失うことを回避するために実行されます。
.sp
\fB\-\-force\fR を使用すると、すべてのrefに対して fast\-forward check が無効になります。
.sp
オプションで、<ref> パラメーターの前に「+」記号を付けて、そのrefでのみ fast\-forward check を無効にすることができます。
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
