'\" t
.\"     Title: git-mailsplit
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-MAILSPLIT" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-mailsplit \- 簡易 UNIX mbox 分割プログラム
.SH "SYNOPSIS"
.sp
.nf
\fIgit mailsplit\fR [\-b] [\-f<nn>] [\-d<prec>] [\-\-keep\-cr] [\-\-mboxrd]
                \-o<directory> [\-\-] [(<mbox>|<Maildir>)\&...]
.fi
.sp
.SH "DESCRIPTION"
.sp
mboxファイルまたはMaildirを指定のディレクトリ内でファイルのリストに分割し("0001" "0002" \&.\&.)、そこからさらに処理できるようにします。
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBImportant\fR
.ps -1
.br
.sp
Maildirの分割は、ファイル名が正しい順序でパッチを出力するためにソートされていることに依存しています。
.sp .5v
.RE
.SH "OPTIONS"
.PP
<mbox>
.RS 4
分割するmboxファイル。指定しない場合、mboxは標準入力から読み取られます。
.RE
.PP
<Maildir>
.RS 4
分割するMaildirのルート。このディレクトリには、cur と tmp とnew サブディレクトリが含まれている必要があります。
.RE
.PP
\fB\-o<directory>\fR
.RS 4
個々のメッセージを配置するディレクトリ。
.RE
.PP
\fB\-b\fR
.RS 4
ファイルがFrom行で始まらない場合は、エラーにするのではなく、単一のメールメッセージであると想定してください。
.RE
.PP
\fB\-d<prec>\fR
.RS 4
先行ゼロを含むデフォルトの4桁の代わりに、生成するファイル名に異なる桁数を指定できます。
.RE
.PP
\fB\-f<nn>\fR
.RS 4
出力ファイル名の最初の <nn> 番号までをスキップします。たとえば、 \-f3 が指定されている場合は、番号を0004から始めます。
.RE
.PP
\fB\-\-keep\-cr\fR
.RS 4
\fB\er\en\fR
で終わる行から
\fB\er\fR
を削除しないでください。
.RE
.PP
\fB\-\-mboxrd\fR
.RS 4
入力は「mboxrd」形式であり、 "^>+From " 行のエスケープは逆になります。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
