'\" t
.\"     Title: git-instaweb
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-INSTAWEB" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-instaweb \- gitwebで作業リポジトリをインスタントにブラウズします
.SH "SYNOPSIS"
.sp
.nf
\fIgit instaweb\fR [\-\-local] [\-\-httpd=<httpd>] [\-\-port=<port>]
               [\-\-browser=<browser>]
\fIgit instaweb\fR [\-\-start] [\-\-stop] [\-\-restart]
.fi
.sp
.SH "DESCRIPTION"
.sp
ローカルリポジトリを参照するための \fBgitweb\fR とWebサーバーを設定するための簡単なスクリプト。
.SH "OPTIONS"
.PP
\fB\-l\fR, \fB\-\-local\fR
.RS 4
WebサーバーをローカルIP(127\&.0\&.0\&.1)にのみバインドします。
.RE
.PP
\fB\-d\fR, \fB\-\-httpd\fR
.RS 4
実行されるHTTPデーモンのコマンドライン。コマンドラインオプションはここで指定でき、構成ファイルはコマンドラインの最後に追加されます。現在、apache2、lighttpd、mongoose、plackup、python、webrickがサポートされています。（デフォルト：lighttpd）
.RE
.PP
\fB\-m\fR, \fB\-\-module\-path\fR
.RS 4
モジュールパス(httpdがApacheの場合にのみ必要)。(デフォルト: /usr/lib/apache2/modules )
.RE
.PP
\fB\-p\fR, \fB\-\-port\fR
.RS 4
httpdをバインドするポート番号。(デフォルト: 1234)
.RE
.PP
\fB\-b\fR, \fB\-\-browser\fR
.RS 4
gitwebページを表示するために使用する必要があるWebブラウザー。これは、gitwebインスタンスのURLとともに
\fIgit web\-\-browse\fR
ヘルパースクリプトに渡されます。詳細については、
\fBgit-web--browse\fR(1)
を参照してください。スクリプトが失敗した場合、URLはstdoutに出力されます。
.RE
.PP
start, \fB\-\-start\fR
.RS 4
httpdインスタンスを開始して本コマンドを終了します。新しいインスタンスを生成するために、必要に応じて構成ファイルを再生成します。
.RE
.PP
stop, \fB\-\-stop\fR
.RS 4
httpdインスタンスを停止して本コマンドを終了します。これにより、新しいインスタンスを生成するための構成ファイルが生成されたり、ブラウザーが閉じられたりすることはありません。
.RE
.PP
restart, \fB\-\-restart\fR
.RS 4
httpdインスタンスを再起動して本コマンドを終了します。 新しいインスタンスを生成するために、必要に応じて構成ファイルを再生成します。
.RE
.SH "CONFIGURATION"
.sp
あなたは \&.git/config で構成を指定できます
.sp
.if n \{\
.RS 4
.\}
.nf
[instaweb]
        local = true
        httpd = apache2 \-f
        port = 4321
        browser = konqueror
        modulePath = /usr/lib/apache2/modules
.fi
.if n \{\
.RE
.\}
.sp
.sp
構成変数 \fBinstaweb\&.browser\fR が設定されていない場合に、\fBweb\&.browser\fR が定義されていれば、代わりに \fBweb\&.browser\fR が使用されます。詳細については、 \fBgit-web--browse\fR(1) を参照してください。
.SH "SEE ALSO"
.sp
\fBgitweb\fR(1)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
