'\" t
.\"     Title: git-difftool
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-DIFFTOOL" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-difftool \- 一般的なdiffツールを使用して変更を表示します
.SH "SYNOPSIS"
.sp
.nf
\fIgit difftool\fR [<options>] [<commit> [<commit>]] [\-\-] [<path>\&...]
.fi
.sp
.SH "DESCRIPTION"
.sp
\fBgit difftool\fR は、一般的なdiffツールを使用してリビジョン間でファイルを比較および編集できるようにするGitコマンドです。 \fBgit difftool\fR は \fBgit diff\fR のフロントエンドであり、同じオプションと引数を受け入れます。 \fBgit-diff\fR(1) を参照してください。
.SH "OPTIONS"
.PP
\fB\-d\fR, \fB\-\-dir\-diff\fR
.RS 4
変更したファイルを一時的な場所にコピーし、それらに対してディレクトリdiffを実行します。 このモードは、diffツールを起動する前にプロンプトを表示することはありません。
.RE
.PP
\fB\-y\fR, \fB\-\-no\-prompt\fR
.RS 4
diffツールを起動する前にプロンプトを表示しないでください。
.RE
.PP
\fB\-\-prompt\fR
.RS 4
diffツールを呼び出す前にプロンプトを表示します。 これがデフォルトの振る舞いです。 オプションは、構成設定を上書きするために提供されています。
.RE
.PP
\fB\-\-rotate\-to=<file>\fR
.RS 4
指定のパスのdiffの表示から開始します。これ以前のパスは最後の後ろに回されます(訳注:
\fBgit difftool\fR
で a,b,c,d,e の場合、
\fB\-\-rotate\-to=c\fR
とすると、 c,d,e,a,b,c の順になる)
.RE
.PP
\fB\-\-skip\-to=<file>\fR
.RS 4
その前のすべてのパスをスキップして、指定されたパスのdiffの表示から開始します(訳注: a,b,c,d,e の場合、
\fB\-\-skip\-to=c\fR
は c,d,e)
.RE
.PP
\fB\-t <tool>\fR, \fB\-\-tool=<tool>\fR
.RS 4
<tool> で指定されたdiffツールを使用します。 有効な値には emergeやkompareやmeldやvimdiffも含まれています。有効な<tool>設定のリストについては、
\fBgit difftool \-\-tool\-help\fR
を実行してください。
.sp
diffツールが指定されていない場合、
\fBgit difftool\fR
は構成変数
\fBdiff\&.tool\fR
を使用します。 構成変数
\fBdiff\&.tool\fR
が設定されていない場合、
\fBgit difftool\fR
は適切なデフォルトを選択します。
.sp
あなたは構成変数
\fBdifftool\&.<tool>\&.path\fR
を設定することにより、ツール(<tool>)へのフルパスを明示的に指定できます。 たとえば、
\fBdifftool\&.kdiff3\&.path\fR
を設定することにより、kdiff3への絶対パスを構成できます。 それ以外の場合、
\fBgit difftool\fR
は、ツールがPATH上にあると想定します。
.sp
既知のdiffツールの1つを実行する代わりに、構成変数
\fBdifftool\&.<tool>\&.cmd\fR
で、呼び出すコマンドラインを指定することにより、
\fBgit difftool\fR
をカスタマイズして代替プログラムを実行できます。
.sp
このツールを使用して(\fB\-t\fR
または
\fB\-\-tool\fR
オプションまたは
\fBdiff\&.tool\fR
構成変数を介して、)
\fBgit difftool\fR
を呼び出すと、構成されたコマンドラインが次の変数を使用して呼び出されます。
\fB$LOCAL\fR
は、diff pre\-imageの内容を含む一時ファイルの名前に設定され、
\fB$REMOTE\fR
は、diff post\-imageの内容を含む一時ファイルの名前に設定されます。
\fB$MERGED\fR
は、比較されるファイルの名前です。
\fB$BASE\fR
は、カスタムマージツールコマンドとの互換性のために提供されており、
\fB$MERGED\fR
と同じ値です。
.RE
.PP
\fB\-\-tool\-help\fR
.RS 4
\fB\-\-tool\fR
で使用できるdiffツールのリストを出力します。
.RE
.PP
\fB\-\-[no\-]symlinks\fR
.RS 4
\fBgit difftool\fR
のデフォルトの動作は、
\fB\-\-dir\-diff\fR
モードで実行したときに、作業ツリーへのシンボリックリンクを作成することです。つまり、比較の右側は、作業ツリーのファイルそのものです。
.sp
\fB\-\-no\-symlinks\fR
を指定すると、代わりにコピーを作成するように
\fBgit difftool\fR
に指示します。
\fB\-\-no\-symlinks\fR
はWindowsのデフォルトです。
.RE
.PP
\fB\-x <command>\fR, \fB\-\-extcmd=<command>\fR
.RS 4
diffを表示するためのカスタムコマンドを指定します。
\fBgit\-difftool\fR
は、構成されたデフォルトを無視し、このオプションが指定されている場合は
\fB$command $LOCAL $REMOTE\fR
を実行します。 さらに、`$BASE`が環境に設定されます。
.RE
.PP
\fB\-g\fR, \fB\-\-[no\-]gui\fR
.RS 4
\fBgit\-difftool\fR
が
\fB\-g\fR
または
\fB\-\-gui\fR
オプションで呼び出されると、デフォルトのdiffツールが
\fBdiff\&.tool\fR
ではなく設定された
\fBdiff\&.guitool\fR
変数から読み取られます。
\fB\-\-no\-gui\fR
オプションを使用して、この設定を上書きできます。
\fBdiff\&.guitool\fR
が設定されていない場合、ツールが見つかるまで、
\fBmerge\&.guitool\fR
、
\fBdiff\&.tool\fR
、
\fBmerge\&.tool\fR
の順でフォールバックします。
.RE
.PP
\fB\-\-[no\-]trust\-exit\-code\fR
.RS 4
\fBgit\-difftool\fR
は、各ファイルで個別にdiffツールを呼び出します。diff分ツールによって報告されたエラーは、デフォルトでは無視されます。呼び出されたdiffツールがゼロ以外の終了コードを返したときに
\fB\-\-trust\-exit\-code`を使用して、 `git\-difftool\fR
を終了させます。
.sp
\fBgit\-difftool\fR
は、
\fB\-\-trust\-exit\-code\fR
が使用されている場合、呼び出されたツールの終了コードを転送します。
.RE
.sp
サポートされているオプションの完全なリストについては、 \fBgit-diff\fR(1) を参照してください。
.SH "CONFIGURATION"
.sp
同等のdifftoolが定義されていない場合、 \fBgit difftool\fR は \fBgit mergetool\fR 構成変数にフォールバックします。
.sp
このセクションのこの行より上にあるものはすべて、 \fBgit-config\fR(1) ドキュメントには含まれていません。 以下の内容に関しては、\fBgit-config\fR(1) ドキュメント にあるものと同一です。
.PP
diff\&.tool
.RS 4
\fBgit-difftool\fR(1)
で使用する diff ツールを制御します。 この変数は、
\fBmerge\&.tool\fR
で構成された値をオーバーライドします。 以下のリストは、有効な組み込み値を示しています。 その他の値はカスタム diff ツール(tool)として扱われ、対応する difftool\&.<tool>\&.cmd 変数を定義する必要があります。
.RE
.PP
diff\&.guitool
.RS 4
\fB\-g\fR/\fB\-\-gui\fR
フラグが指定されている場合に、
\fBgit-difftool\fR(1)
によって使用されるdiffツールを制御します。 この変数は、
\fBmerge\&.guitool\fR
で構成された値をオーバーライドします。 以下のリストは、有効な組み込み値を示しています。 その他の値はカスタム diff ツール(tool)として扱われ、対応する difftool\&.<guitool>\&.cmd 変数を定義する必要があります。
.RE
.PP
difftool\&.<tool>\&.cmd
.RS 4
指定のdiffツール(<tool>)を呼び出すコマンドを指定します。指定されたコマンドは、次の変数を使用してシェルで評価されます:
\fBLOCAL\fR
は、diff pre\-imageの内容を含む一時ファイルの名前に設定され、
\fBREMOTE\fR
は、diff post\-imageの内容を含む一時ファイルの名前に設定されます。
.sp
詳細については、
\fBgit-difftool\fR(1)
の
\fB\-\-tool=<tool>\fR
オプションを参照してください。
.RE
.PP
difftool\&.<tool>\&.path
.RS 4
指定のツール(<tool>)のパスを上書きします。これは、あなたのツールがPATHにない場合に役立ちます。
.RE
.PP
difftool\&.trustExitCode
.RS 4
呼び出された difftool がゼロ以外の終了ステータス(exit status)を返す場合は、difftool を終了(exit)します。
.sp
詳細については、
\fBgit-difftool\fR(1)
の
\fB\-\-trust\-exit\-code\fR
オプションを参照してください。
.RE
.PP
difftool\&.prompt
.RS 4
diffツールを呼び出す前にプロンプトを表示します。
.RE
.SH "SEE ALSO"
.PP
\fBgit-diff\fR(1)
.RS 4
コミット、コミット、作業ツリー等の間の変更を表示する
.RE
.PP
\fBgit-mergetool\fR(1)
.RS 4
マージ競合解決ツールを実行して、マージ競合を解決します
.RE
.PP
\fBgit-config\fR(1)
.RS 4
リポジトリまたはグローバルオプションの取得と設定
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
