git-log(1)
==========

NAME
----
git-log - コミットのログを表示


SYNOPSIS
--------
[synopsis]
	git log [<options>] [<revision-range>] [[--] <path>...]

DESCRIPTION
-----------
コミットのログを表示します。

:git-log: 1
include::rev-list-description.adoc[]

このコマンドは、 linkgit:git-rev-list[1] コマンドに適用可能なオプションを使用して、表示内容と方法を制御し、そして linkgit:git-diff[1] コマンドに適用可能なオプションを使用して、各コミットによって導入される変更の表示方法を制御します。


OPTIONS
-------

`--follow`::
	ファイル名が途中でリネームされていてもそこで中断することなく、そのファイルの一覧を続けて表示します(単一のファイルに対してのみ機能します)。

`--no-decorate`::
`--decorate[=(short|full|auto|no)]`::
* 表示されているコミットの参照名を出力します。 可能な値は以下のとおりです:
** `short`: ref名の接頭辞 `refs/heads/` と `refs/tags/` と `refs/remotes/` は出力されません。
** `full`: 完全なref名(接頭辞を含む)が出力されます。
** `auto`: 出力が端末に送られる場合は、ref名は `short` が指定されたかのように表示され、それ以外の場合はref名は表示されません。
* オプション `--decorate` は、`--decorate=short` の短縮形です。 デフォルトは、 設定されている場合は `log.decorate` の設定値に設定され、 それ以外の場合は `auto` になります。

`--decorate-refs=<pattern>`::
`--decorate-refs-exclude=<pattern>`::
	候補refごとに、`--decorate-refs-exclude` に与えられた <pattern> パラメータのいずれかにマッチする場合、または `--decorate-refs` に与えられた <pattern> パラメータのいずれにもマッチしない場合は、装飾に使用しないでください。 `log.excludeDecoration` 構成オプションを使用すると、装飾からrefを除外できますが、明示的な `--decorate-refs` パターンは `log.excludeDecoration` のマッチングをオーバーライドします。
+
これらのオプションまたは構成設定のいずれも指定されていない場合、参照が `HEAD` または `refs/heads/` または `refs/remotes/` または `refs/stash/` または `refs/tags/` にマッチする場合、参照は装飾(decoration)として使用されます。

`--clear-decorations`::
	このオプションを指定すると、以前のすべての `--decorate-refs` または `--decorate-refs-exclude` オプションがクリアされ、すべての参照が含まれるようにデフォルトの装飾(decoration)フィルタが緩和されます。 このオプションは、構成値 `log.initialDecorationSet` が `all` に設定されている場合は前提として適用されています(This option is assumed)。

`--source`::
	各コミットがコマンドラインで指定のコミットのいずれかから到達できる祖先である場合、当該コミット毎にコマンドラインで指定のコミットのref名で表示します。

`--mailmap`::
`--no-mailmap`::
`--use-mailmap`::
`--no-use-mailmap`::
	mailmapファイルを使用して、作者名(author names)とコミッター名(committer names)と電子メールアドレス(email addresses)を、正式な本名と電子メールアドレスにマップします。 linkgit:git-shortlog[1] 参照。

`--full-diff`::
	このフラグがない場合、 `git log -p <path>...` は、指定されたパスに関連(touch)するコミットを示し、その指定されたパスについての差分を取ります。これにより、指定されたパスに関連するコミットの完全な差分が表示されます。これは、 "<path>..." がコミットのみを制限し、それらのコミットの差分を制限しないことを意味します。
+
これは、例えば `--stat` によって生成されたものなど、すべての差分ベースの出力タイプに影響することに注意してください。 

`--log-size`::
	各コミットの出力に "log size <number>" という行を含めます。ここで、 <number> はそのコミットのメッセージの長さ(バイト単位)です。プログラムがスペースをコミットのメッセージ読み込み前に割り当てられるようにして、 `git log` 出力からログメッセージを読み取るツールを高速化することを目的としています。

include::line-range-options.adoc[]

_<revision-range>_::
	指定されたリビジョン範囲のコミットのみを表示します。 <revision-range> が指定されていない場合、デフォルトで `HEAD` (つまり、現在のコミットにつながる履歴全体)になります。 `origin..HEAD` は、現在のコミット(つまり、`HEAD`)から到達可能なすべてのコミットを指定しますが、`origin` からは指定しません。 <revision-range> の綴り方の完全なリストについては、 linkgit:gitrevisions[7] の「Specifying Ranges」節を参照してください。

`[--] <path>...`::
	指定されたパスに一致するファイルがどのようになったかを説明するのに必要十分なコミットのみを表示します。詳細およびその他の簡略化モードについては、以下の「History Simplification」を参照してください。
+
混乱が生じた場合、パスをオプションまたはリビジョン範囲から分離するために、パスの前に `--` を付ける必要がある場合があります。

include::rev-list-options.adoc[]

include::pretty-formats.adoc[]

DIFF FORMATTING
---------------

デフォルトでは、 `git log` はdiff出力を生成しません。以下のオプションを使用して、各コミットによって行われた変更を表示できます。

注意: `--diff-merges` のバリエーション(短い `-m`, `-c`, `--cc`, `--dd` オプションを含む)の1つが明示的に指定されていない限り、マージ・コミットは diff を表示しませんし、 `--patch` のような diff 書式が選択されていても、 `-S` のような検索オプションとも一致しません。 例外は、 `--first-parent` が使用されている場合です。 この場合、 `first-parent` がマージ・コミットのデフォルトの書式です。

:git-log: 1
:diff-merges-default: `off`
include::diff-options.adoc[]

include::diff-generate-patch.adoc[]

EXAMPLES
--------
`git log --no-merges`::

	コミット履歴全体を表示しますが、マージはスキップします

`git log v2.6.12.. include/scsi drivers/scsi`::

	バージョン v2.6.12 以降で include/scsi または drivers/scsi サブディレクトリ内のファイルの変更がある、すべてのコミットを表示します

`git log --since="2 weeks ago" -- gitk`::

	gitk ファイルの変更について過去2週間の範囲で表示します。 `--` は「ブランチ名のgitk」と混同しないようにするために必要です。

`git log --name-status release..test`::

	「test」ブランチにはあるがまだ「release」ブランチにはないコミットを、各コミットが変更するパスのリストとともに表示します。

`git log --follow builtin/rev-list.c`::

	ファイルに現在の名前が付けられる前に発生したコミット(訳注:つまりファイル名が変更される前の当該ファイル)を含め、`builtin/rev-list.c` を変更したコミットを表示します。

`git log --branches --not --remotes=origin`::

	ローカルブランチ origin にあり、 origin のリモート追跡ブランチのいずれにも存在していないコミットを表示します。

`git log master --not --remotes=*/master`::

	ローカルmasterにはあるが、リモートリポジトリmasterブランチにはないすべてのコミットを表示します。

`git log -p -m --first-parent`::

	変更の差分を含む履歴を表示しますが、「主ブランチ」の観点からのみ、マージされたブランチからのコミットをスキップし、マージによって導入された変更の完全な差分を表示します。これは、単一の統合ブランチにとどまり、そのブランチにすべてのトピックブランチをマージするという厳格なポリシーに従う場合にのみ意味があります。

`git log -L '/int main/',/^}/:main.c`::

	ファイル `main.c` の関数 `main()` が時間の経過とともにどのように進化したかを示します。

`git log -3`::

	表示するコミットの数を3個に制限します。

DISCUSSION
----------

include::i18n.adoc[]

CONFIGURATION
-------------

コア変数については linkgit:git-config[1] を、diff生成に関連する設定については linkgit:git-diff[1] を参照してください。

`format.pretty`::
	`--format` オプションのデフォルト。(上記「Pretty Formats」を参照してください。)デフォルトは medium です。

`i18n.logOutputEncoding`::
	ログを表示するときに使用するエンコーディング。(上記「Discussion」を参照してください。)デフォルトでは、設定されている場合は `i18n.commitEncoding` の値になり、そうでない場合は UTF-8 になります。

include::includes/cmd-config-section-rest.adoc[]

include::config/log.adoc[]

include::config/notes.adoc[]

GIT
---
Part of the linkgit:git[1] suite
