'\" t
.\"     Title: git-get-tar-commit-id
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-GET\-TAR\-COMMI" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-get-tar-commit-id \- git\-archiveを使用して作成されたアーカイブからコミットIDを抽出します
.SH "SYNOPSIS"
.sp
.nf
\fIgit get\-tar\-commit\-id\fR
.fi
.sp
.SH "DESCRIPTION"
.sp
\fIgit archive\fR によって作成されたtarアーカイブを標準入力から読み取り、そこに保存されているコミットIDを抽出します。入力の最初の1024バイトのみを読み取るため、実行時間はtarアーカイブのサイズに大きく影響されることはありません。
.sp
コミットIDが見つからない場合、 \fIgit get\-tar\-commit\-id\fR は何も出力せずリターンコード1を返すだけです。これは、アーカイブが \fIgit archive\fR を使用して作成されていない場合、または \fIgit archive\fR の最初のパラメーターが、コミットIDまたはタグではなくツリーIDだった場合に発生する可能性があります。(訳注:入力がtarアーカイブで無い場合はstderrにtarアーカイブで無い旨のエラー出力があり、exit code は 128。入力がtarアーカイブの場合で、コミットIDが見つからない場合は表記どおりstdout/stderr出力一切無しでexit code 1)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
