git-var(1)
==========

NAME
----
git-var - Git論理変数を表示します


SYNOPSIS
--------
[synopsis]
	git var (-l | <variable>)

DESCRIPTION
-----------
Git論理変数を出力します。 変数が値を持たない場合はコード 1 で終了(exit)します。

OPTIONS
-------
`-l`::
	論理変数を表示します。 さらに、 Git 構成ファイル `.git/config` のすべての変数も一覧表示されます。 (ただし、 設定変数の一覧表示機能は、 `git config -l` に置き換えられるため非推奨です。)

EXAMPLES
--------
	$ git var GIT_AUTHOR_IDENT
	Eric W. Biederman <ebiederm@lnxi.com> 1121223278 -0600


VARIABLES
---------
`GIT_AUTHOR_IDENT`::
    コードの作者。

`GIT_COMMITTER_IDENT`::
    コードの一部をGitに入れた人。

`GIT_EDITOR`::
    Text editor for use by Git commands. The value is meant to be interpreted by the shell when it is used. Examples: `~/bin/vi`, `$SOME_ENVIRONMENT_VARIABLE`, `"C:\Program Files\Vim\gvim.exe" --nofork`. The order of preference is `$GIT_EDITOR`, then `core.editor` configuration value, then `$VISUAL`, then `$EDITOR`, and then the default chosen at compile time, which is usually 'vi'.
ifdef::git-default-editor[]
    あなたが使用しているビルドは、デフォルトとして `{git-default-editor}` を選択しました。
endif::git-default-editor[]

`GIT_SEQUENCE_EDITOR`::
    Text editor used to edit the 'todo' file while running `git rebase -i`. Like `GIT_EDITOR`, the value is meant to be interpreted by the shell when it is used. The order of preference is `$GIT_SEQUENCE_EDITOR`, then `sequence.editor` configuration value, and then the value of `git var GIT_EDITOR`.

`GIT_PAGER`::
    Text viewer for use by Git commands (e.g., 'less'). The value is meant to be interpreted by the shell. The order of preference is `$GIT_PAGER`, then the value of `core.pager` configuration, then `$PAGER`, and then the default chosen at compile time (usually `less`).
ifdef::git-default-pager[]
    あなたが使用しているビルドは、デフォルトとして `{git-default-pager}` を選択しました。
endif::git-default-pager[]

`GIT_DEFAULT_BRANCH`::
    新しく初期化されたリポジトリで作成された最初のブランチの名前。

`GIT_SHELL_PATH`::
    シェルを使用するコマンドに POSIX シェルを提供する、 バイナリへのパス。

`GIT_ATTR_SYSTEM`::
    システム linkgit:gitattributes[5] ファイルへのパス (有効な場合)。

`GIT_ATTR_GLOBAL`::
    (ユーザーごとの)グローバル linkgit:gitattributes[5] ファイルへのパス。

`GIT_CONFIG_SYSTEM`::
    システム構成ファイル(system configuration file)へのパス (有効な場合)。

`GIT_CONFIG_GLOBAL`::
    (ユーザーごとの)グローバル構成ファイルへのパス(存在する場合)。

ほとんどのパス値型変数には値が 1 つだけ含まれます。 ただし、一部の変数には複数の値を含めることができ、 それらの値は改行で区切られ、 優先度の高いものから低いものへの順にリストされます。 呼び出し元は、 そのようなパス値型変数には複数の項目が含まれものとして備える必要があります。

注意: パス型変数は値が存在しない場合でも出力が行われますが、 他の環境変数によって無効にされている場合は出力されないことに注意してください。

SEE ALSO
--------
linkgit:git-commit-tree[1] linkgit:git-tag[1] linkgit:git-config[1]

GIT
---
Part of the linkgit:git[1] suite
