git-hash-object(1)
==================

NAME
----
git-hash-object - オブジェクトIDを計算し、 オプションでファイルからオブジェクトを作成する


SYNOPSIS
--------
[synopsis]
	'git hash-object' [-t <type>] [-w] [--path=<file> | --no-filters]
			[--stdin [--literally]] [--] <file>...
	'git hash-object' [-t <type>] [-w] --stdin-paths [--no-filters]

DESCRIPTION
-----------
指定のファイル(作業ツリーの外部にある可能性あり)の内容を使用して、指定されたタイプのオブジェクトのオブジェクトID値を計算し、オブジェクトIDを標準出力に報告します。オプションで結果のオブジェクトをオブジェクトデータベースに書き込みます。 <type> が指定されていない場合、デフォルトで「blob」になります。

OPTIONS
-------

`-t <type>`::
	作成するオブジェクトのタイプを指定します(デフォルト: "blob")。 可能な値は、 `commit`, `tree`, `blob`, `tag` です。

`-w`::
	実際にオブジェクトをオブジェクトデータベースに書き込みます。

`--stdin`::
	ファイルからではなく、標準入力からオブジェクトを読み取ります。

`--stdin-paths`::
	コマンドラインからではなく、標準入力から1行に1つずつファイル名を読み取ります。

`--path`::
	指定のパスに配置されているかのようにオブジェクトをハッシュ化します。 ファイルの実際の場所はハッシュ値に直接影響を与えませんが、 指定のパスは、オブジェクトがデータベースに格納される前に適用される、 Gitフィルターを決定するために使用されます。 フィルターが適用された結果、 オブジェクト・データベースに格納される実際のブロブは、 指定されたファイルと異なる場合があります。 このオプションは主に、 作業ディレクトリ(working directory)外にある一時ファイルや、 標準入力から読み取ったファイルをハッシュ化する際に便利です。

`--no-filters`::
	行末変換など、属性メカニズムによって選択された入力フィルターを無視して、コンテンツをそのままハッシュします。 ファイルが標準入力から読み取られる場合、 `--path` オプションが指定されていない限り、これは常に暗黙に指定されたものとみなします。

`--literally`::
	`--stdin` が、標準のオブジェクトパースやgit-fsckチェックに合格しない可能性のあるガベージをハッシュして緩いオブジェクトにできるようにします。Git自体のストレステストや、野生で遭遇した破損または偽のオブジェクトの特性の再現に役立ちます。

GIT
---
Part of the linkgit:git[1] suite
