'\" t
.\"     Title: git-symbolic-ref
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-SYMBOLIC\-REF" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-symbolic-ref \- シンボリックrefの読み取り、変更、および削除
.SH "SYNOPSIS"
.sp
.nf
\fIgit symbolic\-ref\fR [\-m <reason>] <name> <ref>
\fIgit symbolic\-ref\fR [\-q] [\-\-short] <name>
\fIgit symbolic\-ref\fR \-\-delete [\-q] <name>
.fi
.sp
.SH "DESCRIPTION"
.sp
引数が1つ与えられると、指定されたシンボリックrefが参照するブランチヘッドを読み取り、 \fB\&.git/\fR ディレクトリを基準にしてそのパスを出力します。 通常、作業ツリーがどのブランチにあるかを確認するには、 <name> 引数として \fBHEAD\fR を指定します。
.sp
2つの引数を与えると、指定されたブランチ <ref> を指すようにシンボリックref <name> を作成または更新します。
.sp
\fB\-\-delete\fR と追加の引数を指定すると、指定されたシンボリックrefが削除されます。
.sp
シンボリックrefは、 \fBref: refs/\fR で始まる文字列を格納する通常のファイルです。 たとえば、 \fB\&.git/HEAD\fR は、内容が \fBref: refs/heads/master\fR である通常のファイルです。
.SH "OPTIONS"
.PP
\fB\-d\fR, \fB\-\-delete\fR
.RS 4
シンボリックref <name> を削除します。
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
<name> がシンボリックrefではなく、切り離されたHEAD(detached HEAD)である場合は、エラーメッセージを発行しないでください。 代わりに、ゼロ以外のステータスで何も言わずに終了します。
.RE
.PP
\fB\-\-short\fR
.RS 4
<name> の値をシンボリックrefとして表示する場合は、値を短くする事を試みます。例えば
\fBrefs/heads/master\fR
から
\fBmaster\fR
へ。
.RE
.PP
\fB\-m\fR
.RS 4
<name> のreflogを <reason> で更新します。これは、シンボリックrefを作成または更新する場合にのみ有効です。
.RE
.SH "NOTES"
.sp
以前は、 \fB\&.git/HEAD\fR は \fBrefs/heads/master\fR を指すシンボリックリンクでした。別のブランチに切り替えたい場合は、 \fBln \-sf refs/heads/newbranch \&.git/HEAD\fR を実行し、現在のブランチを確認したい場合は、 \fBreadlink \&.git/HEAD\fR を実行しました。 ただし、シンボリックリンクは完全に移植可能ではないため、非推奨になり、(上記のとおり)シンボリックrefがデフォルトで使用されます。
.sp
\fIgit symbolic\-ref\fR は、シンボリックrefの内容が正しく出力された場合はステータス0で終了し、要求された名前がシンボリックrefでない場合はステータス1で終了し、別のエラーが発生した場合は128で終了します。
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
