'\" t
.\"     Title: git-request-pull
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-REQUEST\-PULL" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-request-pull \- 保留中の変更の概要を生成します
.SH "SYNOPSIS"
.sp
.nf
\fIgit request\-pull\fR [\-p] <start> <URL> [<end>]
.fi
.sp
.SH "DESCRIPTION"
.sp
アップストリームプロジェクトに変更をツリーにプルするように要求するリクエストを生成します。標準出力に出力される要求は、ブランチの説明で始まり、変更を要約し、どこからプルできるかを示します。
.sp
アップストリームプロジェクトには \fB<start>\fR という名前のコミットがあると予想され、出力では、そのコミット以降に行った変更を \fB<URL>`という名前のリポジトリの、\fR<end>` という名前のコミットまで統合するように求められます。
.SH "OPTIONS"
.PP
\fB\-p\fR
.RS 4
出力にパッチテキストを含めます。
.RE
.PP
<start>
.RS 4
開始コミット。これは、すでにアップストリーム履歴に存在するコミットを指定します。
.RE
.PP
<URL>
.RS 4
プル元のリポジトリURL。
.RE
.PP
<end>
.RS 4
終了コミット(省略時デフォルトはHEAD)。プルを要求している履歴の先端にあるコミットを指定します。
.sp
\fB<URL>\fR
で指定されたリポジトリの、ローカルにあるrefとは異なるrefの先端にコミットがある場合、「ローカル名 コロン(:) リモート名」である、
\fB<local>:<remote>\fR
構文を使用することができます。
.RE
.SH "EXAMPLES"
.sp
\fBv1\&.0\fR リリースの上にある \fBmaster\fR ブランチで作業を構築し、それをプロジェクトに統合したいとします。 まず、他の人が見ることができるように、その変更をパブリックリポジトリにプッシュします:
.sp
.if n \{\
.RS 4
.\}
.nf
git push https://git\&.ko\&.xz/project master
.fi
.if n \{\
.RE
.\}
.sp
それから、あなたは以下のコマンドを実行します:
.sp
.if n \{\
.RS 4
.\}
.nf
git request\-pull v1\&.0 https://git\&.ko\&.xz/project master
.fi
.if n \{\
.RE
.\}
.sp
これにより、アップストリームへのリクエストが生成され、 \fBv1\&.0\fR リリースと \fBmaster\fR の間の変更が要約されて、パブリックリポジトリからプルされます。
.sp
ローカルにあるブランチとは名前が異なるブランチに変更をプッシュする場合、例えば、
.sp
.if n \{\
.RS 4
.\}
.nf
git push https://git\&.ko\&.xz/project master:for\-linus
.fi
.if n \{\
.RE
.\}
.sp
それからあなたはそれをプルするように頼むことができます
.sp
.if n \{\
.RS 4
.\}
.nf
git request\-pull v1\&.0 https://git\&.ko\&.xz/project master:for\-linus
.fi
.if n \{\
.RE
.\}
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
