'\" t
.\"     Title: git-verify-pack
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-VERIFY\-PACK" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-verify-pack \- パックされたGitアーカイブファイルを検証する
.SH "SYNOPSIS"
.sp
.nf
\fIgit verify\-pack\fR [\-v|\-\-verbose] [\-s|\-\-stat\-only] [\-\-] <pack>\&.idx \&...
.fi
.sp
.SH "DESCRIPTION"
.sp
\fIgit pack\-objects\fR コマンドで作成されたパックされたGitアーカイブの指定のidxファイルを読み取り、idxファイルと、対応するパックファイルが正しいことを確認します。
.SH "OPTIONS"
.PP
<pack>\&.idx \&...
.RS 4
確認するidxファイル(複数ファイル指定可)
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
パックを確認した後、パックに含まれるオブジェクトのリストとデルタチェーン長のヒストグラムを表示します。
.RE
.PP
\fB\-s\fR, \fB\-\-stat\-only\fR
.RS 4
パックの内容を確認せず、デルタチェーン長のヒストグラムのみを表示します。
\fB\-\-verbose\fR
を使用すると、オブジェクトのリストも表示されます。
.RE
.PP
\-\-
.RS 4
これ以降の引数をオプションとして解釈しないでください。
.RE
.SH "OUTPUT FORMAT"
.sp
オプション \-v を指定する場合、使用される形式は以下のとおりです:
.sp
.if n \{\
.RS 4
.\}
.nf
SHA\-1 type size size\-in\-packfile offset\-in\-packfile
.fi
.if n \{\
.RE
.\}
.sp
は、パックで削除されていないオブジェクトの場合です。そして、
.sp
.if n \{\
.RS 4
.\}
.nf
SHA\-1 type size size\-in\-packfile offset\-in\-packfile depth base\-SHA\-1
.fi
.if n \{\
.RE
.\}
.sp
は、削除されたオブジェクトの場合です。
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
