git-branch(1)
=============

NAME
----
git-branch - ブランチを、一覧表示または作成または削除します

SYNOPSIS
--------
[synopsis]
	git branch [--color[=<when>] | --no-color] [--show-current]
		   [-v [--abbrev=<n> | --no-abbrev]]
		   [--column[=<options>] | --no-column] [--sort=<key>]
		   [--merged [<commit>]] [--no-merged [<commit>]]
		   [--contains [<commit>]] [--no-contains [<commit>]]
		   [--points-at <object>] [--format=<format>]
		   [(-r|--remotes) | (-a|--all)]
		   [--list] [<pattern>...]
	git branch [--track[=(direct|inherit)] | --no-track] [-f]
		   [--recurse-submodules] <branch-name> [<start-point>]
	git branch (--set-upstream-to=<upstream>|-u <upstream>) [<branch-name>]
	git branch --unset-upstream [<branch-name>]
	git branch (-m|-M) [<old-branch>] <new-branch>
	git branch (-c|-C) [<old-branch>] <new-branch>
	git branch (-d|-D) [-r] <branch-name>...
	git branch --edit-description [<branch-name>]

DESCRIPTION
-----------

`--list` が指定されている場合、またはオプション以外の引数がない場合は、既存のブランチが一覧表示されます。 現在のブランチは緑色(green)で強調表示され、アスタリスク(`*`)でマークされます。 リンクされたワークツリーでチェックアウトされたブランチは、シアン(cyan)で強調表示され、プラス記号(`+`)でマークされます。 オプション `-r` を指定すると、リモート追跡ブランチが一覧表示され、オプション `-a` はローカルブランチとリモートブランチの両方を表示します。

`<pattern>` が指定されている場合、出力を、マッチするブランチに制限するためのシェルワイルドカードとして使用されます。 複数のパターンが指定されている場合、いずれかのパターンに一致するとブランチが表示されます。

`<pattern>` を提供するときは、 `--list` を使用する必要があることに注意してください。 そうしないと、コマンドがブランチの作成として解釈される可能性があります。

With `--contains`, shows only the branches that contain the named commit (in other words, the branches whose tip commits are descendants of the named commit), `--no-contains` inverts it. With `--merged`, only branches merged into the named commit (i.e. the branches whose tip commits are reachable from the named commit) will be listed. With `--no-merged` only branches not merged into the named commit will be listed. If the _<commit>_ argument is missing it defaults to `HEAD` (i.e. the tip of the current branch).

The command's second form creates a new branch head named _<branch-name>_ which points to the current `HEAD`, or _<start-point>_ if given. As a special case, for _<start-point>_, you may use `<rev-A>...<rev-B>` as a shortcut for the merge base of _<rev-A>_ and _<rev-B>_ if there is exactly one merge base. You can leave out at most one of _<rev-A>_ and _<rev-B>_, in which case it defaults to `HEAD`.

Note that this will create the new branch, but it will not switch the working tree to it; use `git switch <new-branch>` to switch to the new branch.

When a local branch is started off a remote-tracking branch, Git sets up the branch (specifically the `branch.<name>.remote` and `branch.<name>.merge` configuration entries) so that `git pull` will appropriately merge from the remote-tracking branch. This behavior may be changed via the global `branch.autoSetupMerge` configuration flag. That setting can be overridden by using the `--track` and `--no-track` options, and changed later using `git branch --set-upstream-to`.

With a `-m` or `-M` option, _<old-branch>_ will be renamed to _<new-branch>_. If _<old-branch>_ had a corresponding reflog, it is renamed to match _<new-branch>_, and a reflog entry is created to remember the branch renaming. If _<new-branch>_ exists, `-M` must be used to force the rename to happen.

`-c` および `-C` オプションは、 `-m` および `-M` とまったく同一の意図(semantics)ですが、ブランチの名前が変更される代わりに、configおよびreflogとともに新しい名前にコピーされます。

With a `-d` or `-D` option, _<branch-name>_ will be deleted. You may specify more than one branch for deletion. If the branch currently has a reflog then the reflog will also be deleted.

Use `-r` together with `-d` to delete remote-tracking branches. Note, that it only makes sense to delete remote-tracking branches if they no longer exist in the remote repository or if `git fetch` was configured not to fetch them again. See also the `prune` subcommand of linkgit:git-remote[1] for a way to clean up all obsolete remote-tracking branches.


OPTIONS
-------
`-d`::
`--delete`::
	ブランチを削除します。 ブランチは、上流ブランチで完全にマージする必要があります。上流が `--track` または `--set-upstream-to` で設定されていない場合は、`HEAD` でマージする必要があります。

`-D`::
	`--delete --force` のショートカットです。

`--create-reflog`::
	Create the branch's reflog. This activates recording of all changes made to the branch ref, enabling use of date based sha1 expressions such as `<branch-name>@{yesterday}`. Note that in non-bare repositories, reflogs are usually enabled by default by the `core.logAllRefUpdates` config option. The negated form `--no-create-reflog` only overrides an earlier `--create-reflog`, but currently does not negate the setting of `core.logAllRefUpdates`.

`-f`::
`--force`::
	Reset _<branch-name>_ to _<start-point>_, even if _<branch-name>_ exists already. Without `-f`, `git branch` refuses to change an existing branch. In combination with `-d` (or `--delete`), allow deleting the branch irrespective of its merged status, or whether it even points to a valid commit. In combination with `-m` (or `--move`), allow renaming the branch even if the new branch name already exists, the same applies for `-c` (or `--copy`).
+
Note that `git branch -f <branch-name> [<start-point>]`, even with `-f`, refuses to change an existing branch _<branch-name>_ that is checked out in another worktree linked to the same repository.

`-m`::
`--move`::
	ブランチを、その構成や reflog とともに 移動/名前変更 します。

`-M`::
	`--move --force` のショートカットです。

`-c`::
`--copy`::
	ブランチを、その構成や reflog とともにコピーします。

`-C`::
	`--copy --force` のショートカットです。

`--color[=<when>]`::
	Color branches to highlight current, local, and remote-tracking branches. The value must be `always` (the default), `never`, or `auto`.

`--no-color`::
	構成ファイルでデフォルトのカラー出力が指定されている場合でも、ブランチの色付けをオフにします。 `--color=never` と同じです。

`-i`::
`--ignore-case`::
	ブランチの並べ替えとフィルタリングでは英大文字小文字を区別しません(case insensitive)。

`--omit-empty`::
	書式が空の文字列に展開される、書式化された ref の後ろに改行を出力しないでください。

`--column[=<options>]`::
`--no-column`::
	Display branch listing in columns. See configuration variable `column.branch` for option syntax. `--column` and `--no-column` without options are equivalent to `always` and `never` respectively.
+
このオプションは、非おしゃべりモード(non-verbose mode)でのみ適用できます。

`--sort=<key>`::
	Sort based on _<key>_. Prefix `-` to sort in descending order of the value. You may use the `--sort=<key>` option multiple times, in which case the last key becomes the primary key. The keys supported are the same as those in linkgit:git-for-each-ref[1]. Sort order defaults to the value configured for the `branch.sort` variable if it exists, or to sorting based on the full refname (including `refs/...` prefix). This lists detached `HEAD` (if present) first, then local branches and finally remote-tracking branches. See linkgit:git-config[1].

`-r`::
`--remotes`::
	List or delete (if used with `-d`) the remote-tracking branches. Combine with `--list` to match the optional pattern(s).

`-a`::
`--all`::
	リモートトラッキングブランチとローカルブランチの両方を一覧表示します。 `--list` と組み合わせて、オプションのパターンにマッチさせます。

`-l`::
`--list`::
	ブランチを一覧表示します。 オプションで `<pattern>...` を使用します。 たとえば `git branch --list 'maint-*'` は、指定のパターン `maint-*` にマッチするブランチのみをリストします。

`--show-current`::
	Print the name of the current branch. In detached `HEAD` state, nothing is printed.

`-v`::
`-vv`::
`--verbose`::
	When in list mode, show sha1 and commit subject line for each head, along with relationship to upstream branch (if any). If given twice, print the path of the linked worktree (if any) and the name of the upstream branch, as well (see also `git remote show <remote>`). Note that the current worktree's `HEAD` will not have its path printed (it will always be your current directory).

`-q`::
`--quiet`::
	エラー以外のメッセージを抑制して、ブランチを作成または削除するときはもっと静かにしてください。

`--abbrev=<n>`::
	In the verbose listing that show the commit object name, show the shortest prefix that is at least _<n>_ hexdigits long that uniquely refers the object. The default value is 7 and can be overridden by the `core.abbrev` config option.

`--no-abbrev`::
	省略せずに、出力リストに完全なsha1を表示します。

`-t`::
`--track[=(direct|inherit)]`::
	新しいブランチを作成するときは、 `branch.<name>.remote` および `branch.<name>.merge` 構成エントリをセットアップして、新しいブランチの「上流」追跡構成(upstream tracking configuration)を設定します。 この構成は、 `git status` と `git branch -v` で、2つのブランチの間の関係を表示するようにgitに指示します。 さらに、引数なしで `git pull` に、新しいブランチがチェックアウトされたときに上流(upstream)からプルするように指示します。
+
オプションの引数に応じて、正確な上流(upstream)ブランチが選択されます。 `-t` または `--track` または `--track=direct` は、起点(start-point)ブランチ自体を上流として使用することを意味します。 `--track=inherit` は、起点ブランチの上流構成(upstream configuration)をコピーすることを意味します。
+
The `branch.autoSetupMerge` configuration variable specifies how `git switch`, `git checkout` and `git branch` should behave when neither `--track` nor `--no-track` are specified:
+
The default option, `true`, behaves as though `--track=direct` were given whenever the start-point is a remote-tracking branch. `false` behaves as if `--no-track` were given. `always` behaves as though `--track=direct` were given. `inherit` behaves as though `--track=inherit` were given. `simple` behaves as though `--track=direct` were given only when the _<start-point>_ is a remote-tracking branch and the new branch has the same name as the remote branch.
+
`branch.<name>.remote` および `branch.<name>.merge` オプションの使用方法に関する追加の説明については、 linkgit:git-pull[1] および linkgit:git-config[1] を参照してください。

`--no-track`::
	Do not set up "upstream" configuration, even if the `branch.autoSetupMerge` configuration variable is set.

`--recurse-submodules`::
	THIS OPTION IS EXPERIMENTAL! Cause the current command to recurse into submodules if `submodule.propagateBranches` is enabled. See `submodule.propagateBranches` in linkgit:git-config[1]. Currently, only branch creation is supported.
+
When used in branch creation, a new branch _<branch-name>_ will be created in the superproject and all of the submodules in the superproject's _<start-point>_. In submodules, the branch will point to the submodule commit in the superproject's _<start-point>_ but the branch's tracking information will be set up based on the submodule's branches and remotes e.g. `git branch --recurse-submodules topic origin/main` will create the submodule branch "topic" that points to the submodule commit in the superproject's "origin/main", but tracks the submodule's "origin/main".

`--set-upstream`::
	このオプションは構文がわかりにくいため、サポートされなくなりました。 代わりに `--track` または `--set-upstream-to` を使用してください。

`-u <upstream>`::
`--set-upstream-to=<upstream>`::
	Set up _<branch-name>_'s tracking information so _<upstream>_ is considered _<branch-name>_'s upstream branch. If no _<branch-name>_ is specified, then it defaults to the current branch.

`--unset-upstream`::
	Remove the upstream information for _<branch-name>_. If no branch is specified it defaults to the current branch.

`--edit-description`::
	エディタを開き、テキストを編集して、ブランチの目的を説明し、他のさまざまなコマンド(`format-patch` 、` request-pull` 、 `merge` (有効な場合) など)で使用できるようにします。 複数行の説明を使用できます。

`--contains [<commit>]`::
	Only list branches which contain _<commit>_ (`HEAD` if not specified). Implies `--list`.

`--no-contains [<commit>]`::
	Only list branches which don't contain _<commit>_ (`HEAD` if not specified). Implies `--list`.

`--merged [<commit>]`::
	Only list branches whose tips are reachable from _<commit>_ (`HEAD` if not specified). Implies `--list`.

`--no-merged [<commit>]`::
	Only list branches whose tips are not reachable from _<commit>_ (`HEAD` if not specified). Implies `--list`.

`--points-at <object>`::
	Only list branches of _<object>_.

`--format <format>`::
	A string that interpolates `%(fieldname)` from a branch ref being shown and the object it points at. _<format>_ is the same as that of linkgit:git-for-each-ref[1].

_<branch-name>_::
	作成または削除するブランチの名前。 新しいブランチ名は、 linkgit:git-check-ref-format[1] で定義されているすべてのチェックに合格する必要があります。 これらのチェックの一部は、ブランチ名で使える文字を制限する場合があります。

_<start-point>_::
	The new branch head will point to this commit. It may be given as a branch name, a commit-id, or a tag. If this option is omitted, the current `HEAD` will be used instead.

_<old-branch>_::
	既存のブランチの名前。 このオプションを省略した場合は、 代わりに現在のブランチの名前が使用されます。

_<new-branch>_::
	The new name for an existing branch. The same restrictions as for _<branch-name>_ apply.

CONFIGURATION
-------------
`pager.branch` は、ブランチを一覧表示する場合、 つまり `--list` が使用または暗示されている場合にのみ尊重されます。 デフォルトでは pager を使用します。 linkgit:git-config[1] を参照してください。

include::includes/cmd-config-section-rest.adoc[]

include::config/branch.adoc[]

EXAMPLES
--------

Start development from a known tag::
+
------------
$ git clone git://git.kernel.org/pub/scm/.../linux-2.6 my2.6
$ cd my2.6
$ git branch my2.6.14 v2.6.14   <1>
$ git switch my2.6.14
------------
+
<1> このステップと次のステップは、 `checkout -b my2.6.14 v2.6.14` を使用して1つのステップに組み合わせることができます。

Delete an unneeded branch::
+
------------
$ git clone git://git.kernel.org/.../git.git my.git
$ cd my.git
$ git branch -d -r origin/todo origin/html origin/man   <1>
$ git branch -D test                                    <2>
------------
+
<1> Delete the remote-tracking branches "todo", "html" and "man". The next `git fetch` or `git pull` will create them again unless you configure them not to. See linkgit:git-fetch[1].
<2> 「master」ブランチ(または現在チェックアウトされているブランチ)にtestブランチからのすべてのコミットがない場合でも、「test」ブランチを削除します。

Listing branches from a specific remote::
+
------------
$ git branch -r -l '<remote>/<pattern>'                 <1>
$ git for-each-ref 'refs/remotes/<remote>/<pattern>'    <2>
------------
+
<1> Using `-a` would conflate _<remote>_ with any local branches you happen to have been prefixed with the same _<remote>_ pattern.
<2> `for-each-ref` は幅広いオプションをとることができます。 linkgit:git-for-each-ref[1] を参照してください

通常、パターンにはクォートが必要です。

NOTES
-----

If you are creating a branch that you want to switch to immediately, it is easier to use the `git switch` command with its `-c` option to do the same thing with a single command.

オプション `--contains` と ` --no-contains` と `--merged` と `--no-merged` は、4つの関連しているが異なる目的を果たします:

- `--contains <commit>` is used to find all branches which will need special attention if _<commit>_ were to be rebased or amended, since those branches contain the specified _<commit>_.

- `--no-contains <commit>` is the inverse of that, i.e. branches that don't contain the specified _<commit>_.

- `--merged` is used to find all branches which can be safely deleted, since those branches are fully contained by `HEAD`.

- `--no-merged` is used to find branches which are candidates for merging into `HEAD`, since those branches are not fully contained by `HEAD`.

include::ref-reachability-filters.adoc[]

SEE ALSO
--------
linkgit:git-check-ref-format[1], linkgit:git-fetch[1], linkgit:git-remote[1], link:user-manual.html#what-is-a-branch["Understanding history: What is a branch?"] in the Git User's Manual.

GIT
---
Part of the linkgit:git[1] suite
