'\" t
.\"     Title: git-prune-packed
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-PRUNE\-PACKED" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-prune-packed \- すでにパックファイルにある余分なオブジェクトを削除します
.SH "SYNOPSIS"
.sp
.nf
\fIgit prune\-packed\fR [\-n|\-\-dry\-run] [\-q|\-\-quiet]
.fi
.sp
.SH "DESCRIPTION"
.sp
このプログラムは、 パックファイルに現在存在するすべてのオブジェクトを、 \fB$GIT_OBJECT_DIRECTORY\fR で検索し、独立したオブジェクトディレクトリでも検索します。
.sp
余分なオブジェクトはすべて削除されます。
.sp
パックは、個別に圧縮され、デルタ圧縮が適用され、単一のファイルに格納され、関連付けられたインデックスファイルを持つオブジェクトのコレクションです。
.sp
パックは、ミラーシステム、バックアップエンジン、ディスクストレージなどの負荷を軽減するために使用されます。
.SH "OPTIONS"
.PP
\fB\-n\fR, \fB\-\-dry\-run\fR
.RS 4
実際にオブジェクトを削除するのではなく、削除されるはずのオブジェクトの表示のみを行います。
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
進行状況インジケーターを黙らせます。
.RE
.SH "SEE ALSO"
.sp
\fBgit-pack-objects\fR(1) \fBgit-repack\fR(1)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
