'\" t
.\"     Title: git-web--browse
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-WEB\-\-BROWSE" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-web--browse \- Webブラウザを起動するためのGitヘルパースクリプト
.SH "SYNOPSIS"
.sp
.nf
\fIgit web\-\-browse\fR [<options>] (<URL>|<file>)\&...
.fi
.sp
.SH "DESCRIPTION"
.sp
このスクリプトは、引数として渡されたURLとファイルを、可能な限り、既に開いているWebブラウザーの新しいタブにHTMLページとして表示しようとします。
.sp
現在、以下のブラウザ(またはコマンド)がサポートされています:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
firefox (これは、KDEを使用しない場合のX Windowのデフォルトです)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
iceweasel
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
seamonkey
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
iceape
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
chromium (chromium\-browser としてもサポートされています)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
google\-chrome (chromeとしてもサポートされています)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
konqueror (これはKDEのデフォルトです。以下の「Note about konqueror」を参照してください)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
opera
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
w3m (これはグラフィカル環境以外のデフォルトです)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
elinks
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
links
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
lynx
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
dillo
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
open (これはMac OS X GUIのデフォルトです)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
start (これはMinGWのデフォルトです)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
cygstart (これはCygwinのデフォルトです)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
xdg\-open
.RE
.sp
カスタムコマンドを指定することもできます。
.SH "OPTIONS"
.PP
\fB\-b <browser>\fR, \fB\-\-browser=<browser>\fR
.RS 4
指定のブラウザを使用します。サポートされているブラウザのリストに含まれている必要があります。
.RE
.PP
\fB\-t <browser>\fR, \fB\-\-tool=<browser>\fR
.RS 4
同上。
.RE
.PP
\fB\-c <conf\&.var>\fR, \fB\-\-config=<conf\&.var>\fR
.RS 4
CONF\&.VAR はGit構成ファイルで検索されます。設定されている場合、その値は使用するブラウザを指定します。
.RE
.SH "CONFIGURATION VARIABLES"
.SS "CONF\&.VAR( \fB\-c\fR 由来) と web\&.browser"
.sp
Webブラウザーは、 \fB\-c\fR (または \fB\-\-config\fR)コマンドラインオプションで渡される構成変数、または前者が使用されていない場合は \fBweb\&.browser\fR 構成変数を使用して指定できます。
.SS "browser\&.<tool>\&.path"
.sp
あなたは構成変数 \fBbrowser\&.<tool>\&.path\fR を設定することにより、希望するブラウザーへのフルパスを明示的に指定できます。たとえば、 \fBbrowser\&.firefox\&.path\fR を設定することで、Firefoxへの絶対パスを設定できます。それ以外の場合、 \fBgit web{litdd}browse\fR はツールがPATH上にあると想定します。
.SS "browser\&.<tool>\&.cmd"
.sp
オプションまたは構成変数で指定されたブラウザーがサポートされているブラウザーに含まれていない場合、対応する \fBbrowser\&.<tool>\&.cmd\fR 構成変数が検索されます。 この変数が存在する場合、 \fBgit web{litdd}browse\fR は指定されたツールをカスタムコマンドとして扱い、シェルのevalを使用してURLを引数として渡してコマンドを実行します。
.SH "NOTE ABOUT KONQUEROR"
.sp
\fBkonqueror\fR がコマンドラインオプションまたは構成変数で指定されている場合、可能であれば、 \fBkfmclient\fR を起動して、既に開いているkonquerorのHTMLマニュアルページを新しいタブで開こうとします。
.sp
一貫性を保つために、 \fBbrowser\&.konqueror\&.path\fR が \fBA_PATH_TO/konqueror\fR のように設定されている場合にも、このようなトリックを試します。 つまり、代わりに \fBA_PATH_TO/kfmclient\fR を起動しようと試みます。
.sp
あなたが本当に \fBkonqueror\fR の使用を望むのなら、あなたは以下のようなものを使用できます:
.sp
.if n \{\
.RS 4
.\}
.nf
        [web]
                browser = konq

        [browser "konq"]
                cmd = A_PATH_TO/konqueror
.fi
.if n \{\
.RE
.\}
.sp
.SS "注意: \fBgit\-config \-\-global\fR について"
.sp
注意: これらの構成変数は、おそらく以下のように \fB\-\-global\fR フラグを使用して設定する必要があることに注意してください:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git config \-\-global web\&.browser firefox
.fi
.if n \{\
.RE
.\}
.sp
.sp
なぜなら、おそらくリポジトリ固有よりもユーザー固有であるためです。詳細については、 \fBgit-config\fR(1) を参照してください。
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
