'\" t
.\"     Title: git-remote-fd
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-REMOTE\-FD" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-remote-fd \- スマートトランスポートストリームを呼び出し元に反映します(Reflect smart transport stream back to caller)
.SH "SYNOPSIS"
.sp
"fd::<infd>[,<outfd>][/<anything>]" (as URL)
.SH "DESCRIPTION"
.sp
このヘルパーは、指定のファイルデスクリプタを使用してリモートGitサーバーに接続します。これはエンドユーザー向けではなく、git fetch、pushまたはarchiveを呼び出すプログラムとスクリプトを対象としています。
.sp
<infd> のみが指定されている場合は、リモートGitサーバー(git\-upload\-pack、git\-receive\-pack または git\-upload\-archive)に接続されている双方向ソケットであると見なされます。 <infd> と <outfd> の両方が指定されている場合、それらはリモートGitサーバーに接続されているパイプであると見なされます( <infd> は入力パイプ、 <outfd> は出力パイプです)。
.sp
このヘルパーが開始される前に、ハンドシェイク手順(git:// のサービスリクエストの送信など)がすでに完了していることを前提としています。
.sp
<anything> は任意の文字列にすることができます。それは無視されます。これは、URLが何らかのコンテキストで表示される場合に、URLでユーザーに情報を提供するためのものです。
.SH "ENVIRONMENT VARIABLES"
.PP
GIT_TRANSLOOP_DEBUG
.RS 4
設定されている場合、さまざまな 読み取り/書き込み に関するデバッグ情報を出力します。
.RE
.SH "EXAMPLES"
.PP
\fBgit fetch fd::17 master\fR
.RS 4
ファイルデスクリプタ #17 使用して master を Fetch し、 git\-upload\-pack と通信します。
.RE
.PP
\fBgit fetch fd::17/foo master\fR
.RS 4
同上。
.RE
.PP
\fBgit push fd::7,8 master (as URL)\fR
.RS 4
master を push し、ファイルデスクリプタ #7 を使用して git\-receive\-pack からデータを読み取り、ファイルデスクリプタ #8 を使用して同じサービスにデータを書き込みます。
.RE
.PP
\fBgit push fd::7,8/bar master\fR
.RS 4
同上。
.RE
.SH "SEE ALSO"
.sp
\fBgitremote-helpers\fR(7)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
