'\" t
.\"     Title: git-credential-cache
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-CREDENTIAL\-CAC" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-credential-cache \- パスワードを一時的にメモリに保存するヘルパー
.SH "SYNOPSIS"
.sp
.nf
git config credential\&.helper \*(Aqcache [<options>]\*(Aq
.fi
.sp
.SH "DESCRIPTION"
.sp
このコマンドは、将来のGitプログラムで使用するために認証情報(credential)をメモリにキャッシュします。保存された認証情報はディスクに記録されることはなく、設定可能なタイムアウト後にメモリから削除されます。キャッシュはUnixドメインソケットを介してアクセスでき、ファイルシステムのアクセス許可によって現在のユーザーに制限されます。
.sp
あなたはこのコマンドを直接呼び出すことは無いでしょう。これは、Gitの他の部分で認証情報ヘルパーとして使用されることを目的としています。\fBgitcredentials\fR(7) または 以下の EXAMPLES を参照してください。
.SH "OPTIONS"
.PP
\fB\-\-timeout <seconds>\fR
.RS 4
認証情報をキャッシュする秒数(デフォルト: 900)。
.RE
.PP
\fB\-\-socket <path>\fR
.RS 4
\fB<path>\fR
を使用して、実行中のキャッシュデーモンに接続します(または、新しいキャッシュデーモンが開始されていない場合は開始します)。デフォルトは
\fB$XDG_CACHE_HOME/git/credential/socket\fR
です(\fB~/\&.git\-credential\-cache/\fR
が存在しない限り)。
\fB~/\&.git\-credential\-cache/\fR
が存在する場合は、代わりに
\fB~/\&.git\-credential\-cache/\fR
が使用されます。あなたのホームディレクトリがネットワークにマウントされたファイルシステム上にある場合は、これをローカルファイルシステムに変更する必要がある場合があります。あなたは絶対パスを指定しなければなりません。
.RE
.SH "CONTROLLING THE DAEMON"
.sp
あなたがデーモンを早期に終了させ、タイムアウトする前にキャッシュされたすべての認証情報を忘れ去りたい場合は、「exit」アクションを発行できます:
.sp
.if n \{\
.RS 4
.\}
.nf
git credential\-cache exit
.fi
.if n \{\
.RE
.\}
.sp
.SH "EXAMPLES"
.sp
このヘルパーの肝は、ユーザー名またはパスワードを入力する必要がある回数を減らすことです。例えば:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git config credential\&.helper cache
$ git push http://example\&.com/repo\&.git
Username: <type your username>
Password: <type your password>

[work for 5 more minutes]
$ git push http://example\&.com/repo\&.git
[your credentials are used automatically]
.fi
.if n \{\
.RE
.\}
.sp
.sp
credential\&.helper構成変数を介してオプションを提供できます(この例では、キャッシュ時間が5分に短縮されます):
.sp
.if n \{\
.RS 4
.\}
.nf
$ git config credential\&.helper \*(Aqcache \-\-timeout=300\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
