'\" t
.\"     Title: git-update-server-info
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-UPDATE\-SERVER\" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-update-server-info \- ダムサーバー(dumb servers)を支援するために補助情報ファイル(auxiliary info file)を更新する
.SH "SYNOPSIS"
.sp
.nf
\fIgit update\-server\-info\fR
.fi
.sp
.SH "DESCRIPTION"
.sp
オンザフライパック生成(on\-the\-fly pack generations)を行わないダムサーバー(dumb server)は、クライアントがサーバーの参照とパックを検出できるように、 $GIT_DIR/info と $GIT_OBJECT_DIRECTORY/info ディレクトリにいくつかの補助情報ファイル(auxiliary information files)を持っている必要があります。このコマンドは、そのような補助ファイルを生成します。
.SH "OUTPUT"
.sp
現在、このコマンドは以下のファイルを更新します。それらの目的の説明については、 \fBgitrepository-layout\fR(5) を参照してください:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
objects/info/packs
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
info/refs
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
