git-merge(1)
============

NAME
----
git-merge - 2つまたはそれ以上の開発履歴を結合します


SYNOPSIS
--------
[synopsis]
	git merge [-n] [--stat] [--compact-summary] [--no-commit] [--squash] [--[no-]edit]
	         [--no-verify] [-s <strategy>] [-X <strategy-option>] [-S[<keyid>]]
	         [--[no-]allow-unrelated-histories]
	         [--[no-]rerere-autoupdate] [-m <msg>] [-F <file>]
	         [--into-name <branch>] [<commit>...]
	git merge (--continue | --abort | --quit)

DESCRIPTION
-----------
指定のコミットからの変更(それらの履歴が現在のブランチから分岐した時点以降のもの)を現在のブランチに取り込みます。 このコマンドは、 別のリポジトリからの変更を組み込むために `git pull` によって使用され、 そしてまた、 手動で、 あるブランチから別のブランチへの変更をマージするためにも使用できます。

以下の履歴が存在し、現在のブランチが `master` であるとします:

------------
          A---B---C topic
         /
    D---E---F---G master
------------

Then `git merge topic` will replay the changes made on the `topic` branch since it diverged from `master` (i.e., `E`) until its current commit (`C`) on top of `master`, and record the result in a new commit along with the names of the two parent commits and a log message from the user describing the changes. Before the operation, `ORIG_HEAD` is set to the tip of the current branch (`G`).

------------
          A---B---C topic
         /         \
    D---E---F---G---H master
------------

マージでは、 自動的に解決できない競合が発生した場合や、 マージを開始する際に `--no-commit` が指定された場合に停止(stop)します。 その時点で、 あなたは `git merge --abort` または `git merge --continue` を実行できます。

`git merge --abort` はマージ処理を中止し、 マージ前の状態を再構築しようとします。 ただし、マージの開始時にコミットされていない変更があった場合(特に、マージの開始後にそれらの変更がさらに変更された場合)、 `git merge --abort` は、元の(マージ前の)変更を再構築できない場合があります。 つまり以下の事が言えます:

WARNING: Running `git merge` with non-trivial uncommitted changes is discouraged: while possible, it may leave you in a state that is hard to back out of in the case of a conflict.

OPTIONS
-------
:git-merge: 1

include::merge-options.adoc[]

`-m <msg>`::
	マージコミットに使用するコミットメッセージを設定します(マージコミットが作成された場合)。
+
`--log` が指定されている場合、マージされるコミットのショートログが与えられたメッセージに追加されます。
+
`git fmt-merge-msg` コマンドを使用して、自動化された `git merge` 呼び出しに適切なデフォルトを与えることができます。 自動メッセージには、ブランチの説明を含めることができます。

`--into-name <branch>`::
	Prepare the default merge message as if merging to the branch _<branch>_, instead of the name of the real branch to which the merge is made.

`-F <file>`::
`--file=<file>`::
	(マージ・コミットが作成される場合に備えて)マージ・コミットに使用するコミット・メッセージを読み取ります。
+
`--log` が指定されている場合、マージされるコミットのショートログが与えられたメッセージに追加されます。

include::rerere-options.adoc[]

`--overwrite-ignore`::
`--no-overwrite-ignore`::
	マージ結果から無視されたファイルを黙って上書きします。 これがデフォルトの動作です。 中止(abort)するには、 `--no-overwrite-ignore` を使用します。

`--abort`::
	現在の競合解決プロセスを中止(abort)し、マージ前の状態を再構築してみてください。 自動スタッシュエントリが存在する場合は、それをワークツリーに適用します。
+
マージの開始時にコミットされていないワーク・ツリーの変更が存在した場合、 `git merge --abort` は、これらの変更を再構築できない場合があります。 したがって、 `git merge` を実行する前に、常にあなたの変更をコミット、またはスタッシュしておくことをお勧めします。
+
`git merge --abort` は、 `MERGE_HEAD` がある場合は `git reset --merge` と同じです。ただし `MERGE_AUTOSTASH` もある場合は `git merge --abort` はスタッシュ・エントリをワーク・ツリーに適用しますが、 `git reset --merge` は スタッシュ・リストにスタッシュした変更を保持したままにします。

`--quit`::
	進行中の現在のマージを忘れさせます。 インデックスと作業ツリーはそのままにしておきます。 `MERGE_AUTOSTASH` が存在する場合、スタッシュエントリはスタッシュリストに保存されます。

`--continue`::
	競合が原因で `git merge` が停止(stop)した後で、 `git merge --continue` を実行してマージを終了できます(下記「HOW TO RESOLVE CONFLICTS」セクション参照)。

`<commit>...`::
	通常、 他のブランチのヘッドであるコミットを、 私たちのブランチにマージします。 2つ以上のコミットを指定すると、 3つ以上の親を持つマージが作成されます(Octopusマージという愛称で親しまれています)。
+
コマンドラインからコミットが指定されていない場合は、現在のブランチが上流として使用するように構成されている、リモート追跡ブランチをマージします。 このマニュアルページの CONFIGURATION セクションも参照してください。
+
FETCH_HEAD` が指定された場合(他のコミットは指定しない場合)、直前の `git fetch` によるマージによって `.git/FETCH_HEAD` ファイルに記録されたブランチは、現在のブランチにマージされます。


PRE-MERGE CHECKS
----------------

外部の変更を適用する前に、自分の作業を良好な状態にしてローカルでコミットしとく必要があります。これにより、競合が発生した場合に作業が中断されることはなくなります。 linkgit:git-stash[1] も参照してください。 `git pull`/`git merge` は、ローカルのコミットされていない変更が `git pull`/`git merge` の更新が必要なファイルと重複する場合、何もせずに停止(stop)します。

To avoid recording unrelated changes in the merge commit, `git pull` and `git merge` will also abort if there are any changes registered in the index relative to the `HEAD` commit. (Special narrow exceptions to this rule may exist depending on which merge strategy is in use, but generally, the index must match `HEAD`.)

すべての名前付きコミットがすでに `HEAD` の祖先である場合、`git merge` は "Already up to date." (既に最新です)というメッセージで早期に終了(exit)します。

FAST-FORWARD MERGE
------------------

多くの場合、現在のブランチ・ヘッドは、指定のコミットの祖先です。 これは、特に `git pull` から呼び出された場合に最も一般的なケースです: 例えば、あなたは上流リポジトリーを追跡していて、ローカルの変更をコミットしていないので、新しい上流リビジョンに更新する必要があります。 この場合、結合された履歴を保存するために新しいコミットは必要ありませんが、代わりに、「HEAD」（およびインデックス）は、追加のマージ・コミットを作成せずに、指定のコミットを指すように更新されます。

この振る舞いは、`--no-ff` オプションで抑制できます。

TRUE MERGE
----------

早送りマージ(fast-forward merge)(上記参照)を除いて、マージされるブランチは、両方を親として持つマージコミットによって結合する必要があります。

マージされるすべてのブランチの変更を調整したマージバージョンがコミットされ、`HEAD`、インデックス、作業ツリーがそのコミットに更新されます。 作業ツリーには、この更新と重ならない限りは変更を加えることができます。

変更を調停する方法が明確でない場合、以下のようになります:

1. `HEAD` ポインタは同一のままです。
2. `MERGE_HEAD` ref は、他方のブランチヘッド(the other branch head)を指すように設定されています。
3. 正常にマージされたパスは、インデックスファイルとあなたの作業ツリーの両方で更新されます。
4. For conflicting paths, the index file records up to three versions: stage 1 stores the version from the common ancestor, stage 2 from `HEAD`, and stage 3 from `MERGE_HEAD` (you can inspect the stages with `git ls-files -u`). The working tree files contain the result of the merge operation; i.e. 3-way merge results with familiar conflict markers +<<<+ `===` +>>>+.
5. A ref named `AUTO_MERGE` is written, pointing to a tree corresponding to the current content of the working tree (including conflict markers for textual conflicts). Note that this ref is only written when the `ort` merge strategy is used (the default).
6. その他の変更は行われません。 特に、マージを開始する前に行ったローカルの変更は同じままであり、それらのインデックスエントリはそのまま、つまり「HEAD」と一致します。

試しにマージした結果、複雑な競合が発生してしまったのでやり直したいという場合は、 `git merge --abort` で回復(recover)することができます。

MERGING TAG
-----------

注釈付きの(可能ならば署名された)タグをマージする場合、早送りマージが可能であっても、Gitは常にマージコミットを作成し、コミットメッセージテンプレートはタグメッセージ付きで準備されます。 さらに、タグが署名されている場合、シグネチャチェックはメッセージテンプレートのコメントとして報告されます。 linkgit:git-tag[1] も参照してください。

たまたまタグ付けされたコミットにつながる作業と統合し、例えば、アップストリームのリリースポイントと同期したい場合、あなたは不要なマージコミットを作成したくない場合があります。

このような場合、タグを `git merge` にフィードする前に自分で「包装を解く」(unwrap)か、自分で作業を行わない場合は `--ff-only` を渡すことができます。 例えば以下ようにします

----
git fetch origin
git merge v1.2.3^0
git merge --ff-only v1.2.3
----

HOW CONFLICTS ARE PRESENTED(競合の提示方法)
------------------------------------

マージ中に、作業ツリーのファイルが更新されてマージの結果が反映されます。 共通の祖先のバージョンに加えられた変更の中で、重複しないもの(つまり、ファイルの領域を変更し、反対側がその領域をそのままにしておく、またはその逆)が最終結果にそのまま組み込まれます。 ただし、両方の側が同じ領域に変更を加えた場合、Gitは一方の側をもう一方の側からランダムに選択することはできず、両方の側がその領域に行ったことをファイルに残してあなたに解決するように求めます。

デフォルトでは、GitはRCSスイートの「マージ」プログラムで使用されるものと同じスタイルを使用して、以下のように競合するハンクを表示します:

------------
Here are lines that are either unchanged from the common
ancestor, or cleanly resolved because only one side changed,
or cleanly resolved because both sides changed the same way.
<<<<<<< yours:sample.txt
Conflict resolution is hard;
let's go shopping.
=======
Git makes conflict resolution easy.
>>>>>>> theirs:sample.txt
And here is another line that is cleanly resolved or unmodified.
------------

The area where a pair of conflicting changes happened is marked with markers +<<<<<<<+, `=======`, and +>>>>>>>+. The part before the `=======` is typically your side, and the part afterwards is typically their side.

デフォルトの形式では、競合している部分でオリジナルが何を言っているのかは分かりません。 自分側の何行が削除され、バービー人形の発言に置き換えられているのかは分かりません。 唯一わかるのは、あなた側(your side)は大変だから買い物に行きたいと言いたいのに、相手側(the other size)は簡単だと主張したいということです。

An alternative style can be used by setting the `merge.conflictStyle` configuration variable to either `diff3` or `zdiff3`. In `diff3` style, the above conflict may look like this:

------------
Here are lines that are either unchanged from the common
ancestor, or cleanly resolved because only one side changed,
<<<<<<< yours:sample.txt
or cleanly resolved because both sides changed the same way.
Conflict resolution is hard;
let's go shopping.
||||||| base:sample.txt
or cleanly resolved because both sides changed identically.
Conflict resolution is hard.
=======
or cleanly resolved because both sides changed the same way.
Git makes conflict resolution easy.
>>>>>>> theirs:sample.txt
And here is another line that is cleanly resolved or unmodified.
------------

while in `zdiff3` style, it may look like this:

------------
Here are lines that are either unchanged from the common
ancestor, or cleanly resolved because only one side changed,
or cleanly resolved because both sides changed the same way.
<<<<<<< yours:sample.txt
Conflict resolution is hard;
let's go shopping.
||||||| base:sample.txt
or cleanly resolved because both sides changed identically.
Conflict resolution is hard.
=======
Git makes conflict resolution easy.
>>>>>>> theirs:sample.txt
And here is another line that is cleanly resolved or unmodified.
------------

In addition to the +<<<<<<<+, `=======`, and +>>>>>>>+ markers, it uses another +|||||||+ marker that is followed by the original text. You can tell that the original just stated a fact, and your side simply gave in to that statement and gave up, while the other side tried to have a more positive attitude. You can sometimes come up with a better resolution by viewing the original.


HOW TO RESOLVE CONFLICTS
------------------------

競合を目にした後、あなたは以下の2つのことができます:

 * マージしないことを決定します。 必要なクリーンアップは、インデックスファイルを `HEAD` コミットにリセットして (2) をリバースし、 (2) と (3) によって行われた作業ツリーの変更をクリーンアップすることだけです。 これには `git merge --abort` を使用できます。

 * 競合を解決します。 Gitは、作業ツリーの競合をマークします。 ファイルを編集して形にし、`git add` してインデックスに追加します。 `git commit` または `git merge --continue` を使用して、取引を成立させます。 後者のコマンドは、 `git commit` を呼び出す前に、進行中の(中断(interrupted)された)マージがあるかどうかをチェックします。

あなたはいくつかの道具を使用して、競合を解決できます:

 * mergetool を使用します。 `git mergetool` を実行すると、 グラフィカルなマージ・ツールが起動し、 あなたと一緒にマージ作業を進めてくれます。

 * diffを見てください。 `git diff` は3方向の差分を表示し、 `HEAD` バージョンと `MERGE_HEAD` バージョンの両方からの変更を強調表示します。 `git diff AUTO_MERGE` では、 あなたがテキストの競合を解決するためにこれまでに行った変更が表示されます。

 * 各ブランチからのdiffを見てください。 `git log --merge -p <path>` は、最初に `HEAD` バージョンの差分を表示し、次に `MERGE_HEAD` バージョンを表示します。

 * オリジナルを見てください。 `git show :1:filename` は共通の祖先を示し、 `git show :2:filename` は `HEAD` バージョンを示し、 `git show :3:filename` は `MERGE_HEAD` バージョンを示します。


EXAMPLES
--------

* 現在のブランチにブランチ `fixes` と `enhancements` をマージし、octopusマージします:
+
------------------------------------------------
$ git merge fixes enhancements
------------------------------------------------

* `ours` マージ戦略を使用して、ブランチ `obsolete` を現在のブランチにマージします:
+
------------------------------------------------
$ git merge -s ours obsolete
------------------------------------------------

* ブランチ `maint` を現在のブランチにマージしますが、新しいコミットを自動的に行わないでください:
+
------------------------------------------------
$ git merge --no-commit maint
------------------------------------------------
+
これは、マージにさらに変更を加えたい場合、または独自のマージコミットメッセージを作成したい場合に使用できます。
+
大幅な変更をマージコミットに忍び込ませるために、このオプションを悪用することは控えてください。 bumping release(微修正)/version name(バージョン名変更) のような小さな修正は許容されます。


include::merge-strategies.adoc[]

CONFIGURATION
-------------

`branch.<name>.mergeOptions`::
	Sets default options for merging into branch _<name>_. The syntax and supported options are the same as those of `git merge`, but option values containing whitespace characters are currently not supported.

include::includes/cmd-config-section-rest.adoc[]

include::config/merge.adoc[]

SEE ALSO
--------
linkgit:git-fmt-merge-msg[1], linkgit:git-pull[1], linkgit:gitattributes[5], linkgit:git-reset[1], linkgit:git-diff[1], linkgit:git-ls-files[1], linkgit:git-add[1], linkgit:git-rm[1], linkgit:git-mergetool[1]

GIT
---
Part of the linkgit:git[1] suite
