'\" t
.\"     Title: git-upload-pack
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-UPLOAD\-PACK" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-upload-pack \- パックされたオブジェクトをgit\-fetch\-packに送り返す
.SH "SYNOPSIS"
.sp
.nf
\fIgit\-upload\-pack\fR [\-\-[no\-]strict] [\-\-timeout=<n>] [\-\-stateless\-rpc]
                  [\-\-advertise\-refs] <directory>
.fi
.sp
.SH "DESCRIPTION"
.sp
\fBgit fetch\-pack\fR によって呼び出され、通信の反対側で欠落しているオブジェクトを調べ、パッキング後にそれらを送信します。
.sp
このコマンドは通常、エンドユーザーによって直接呼び出されることはありません。プロトコルのUIは「git fetch\-pack」側にあり、プログラムのペアはリモートリポジトリから更新をプルするために使用されることを目的としています。プッシュ操作については、「git send\-pack」を参照してください。
.SH "OPTIONS"
.PP
\fB\-\-[no\-]strict\fR
.RS 4
<directory> Gitディレクトリでない場合、 <directory>/\&.git/ を試さない
.RE
.PP
\fB\-\-timeout=<n>\fR
.RS 4
非アクティブになった <n> 秒後に転送を中断します。
.RE
.PP
\fB\-\-stateless\-rpc\fR
.RS 4
stdinとstdoutを使用して 読み取り/書き込み サイクルを1回だけ実行します。これは、プログラムが要求を読み取り、応答を書き込み、終了する必要があるHTTP POST要求処理モデルに適合します。
.RE
.PP
\fB\-\-http\-backend\-info\-refs\fR
.RS 4
\fB$GIT_URL/info/refs?service=git\-upload\-pack\fR
リクエストを処理するために
\fBgit-http-backend\fR(1)
によって使用されます。
\fBgitprotocol-http\fR(5)
の「Smart Clients」と
\fBgitprotocol-v2\fR(5)
ドキュメントの「HTTP Transport」を参照してください。
\fBgit-receive-pack\fR(1)
でも理解されます。
.RE
.PP
<directory>
.RS 4
同期元のリポジトリ。
.RE
.SH "ENVIRONMENT"
.PP
\fBGIT_PROTOCOL\fR
.RS 4
ワイヤープロトコルをハンドシェイクするために使用される内部変数。サーバー管理者は、この変数を渡すことができるようにいくつかのトランスポートを構成する必要がある場合があります。
\fBgit\fR(1)
のdiscussionを参照してください。
.RE
.SH "SEE ALSO"
.sp
\fBgitnamespaces\fR(7)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
