'\" t
.\"     Title: git-hook
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-HOOK" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-hook \- gitフックの実行
.SH "SYNOPSIS"
.sp
.nf
\fIgit hook\fR run [\-\-ignore\-missing] <hook\-name> [\-\- <hook\-args>]
.fi
.sp
.SH "DESCRIPTION"
.sp
他のスクリプト化された git コマンドで使用するための、 git フック(\fBgithooks\fR(5) 参照) を実行するためのコマンド・インターフェイス。
.SH "SUBCOMMANDS"
.PP
run
.RS 4
\fB<hook\-name>\fR
フックを実行します。 サポートされているフック名については、
\fBgithooks\fR(5)
を参照してください。
.sp
フックへの位置引数は、 必須の
\fB\-\-\fR
(または
\fB\-\-end\-of\-options\fR
については
\fBgitcli\fR(7)
参照)の後ろで渡す必要があります。 フックが期待する引数(存在する場合)については、
\fBgithooks\fR(5)
を参照してください。
.RE
.SH "OPTIONS"
.PP
\fB\-\-ignore\-missing\fR
.RS 4
見つからないフックを無視し、黙ってゼロを返します。 存在するかどうかわからないフックを一発で実行したいツールに使用します。
.RE
.SH "SEE ALSO"
.sp
\fBgithooks\fR(5)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
