'\" t
.\"     Title: git-credential-store
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-CREDENTIAL\-STO" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-credential-store \- 資格情報をディスクに保存するヘルパー
.SH "SYNOPSIS"
.sp
.nf
git config credential\&.helper \*(Aqstore [<options>]\*(Aq
.fi
.sp
.SH "DESCRIPTION"
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.sp
このヘルパーを使用すると、パスワードは暗号化されずにディスクに保存され、ファイルシステムのアクセス許可によってのみ保護されます。これが許容できるセキュリティのトレードオフではない場合は \fBgit-credential-cache\fR(1) を試すか、オペレーティングシステムが提供する安全なストレージと統合するヘルパーを探してください。
.sp .5v
.RE
.sp
このコマンドは、将来に渡ってGitプログラムで使用できるように、資格情報をディスクに無期限に保存します。
.sp
このコマンドが直接呼び出されることはありません。これは、gitの他の部分で資格情報ヘルパーとして使用されることを目的としています。以下のEXAMPLESまたは \fBgitcredentials\fR(7) を参照してください。
.SH "OPTIONS"
.PP
\fB\-\-file=<path>\fR
.RS 4
\fB<path>\fR
を使用して、資格情報を探してして保存します。ファイルには、システム上の他のユーザーがファイルを読み取れないようにファイルシステムのアクセス許可が設定されますが、暗号化またはその他の方法で保護されることはありません。\fB<path>\fR
指定がない場合、資格情報は
\fB~/\&.git\-credentials\fR
と
\fB$XDG_CONFIG_HOME/git/credentials\fR
から検索されます。そして、書き込みは、存在すれば
\fB~/\&.git\-credentials\fR
に書き込みますが、\fB~/\&.git\-credentials\fR
に書き込まなかった場合、存在すれば
\fB$XDG_CONFIG_HOME/git/credentials\fR
に書き込みます。
the section called \(lqFILES\(rq
も参照してください。
.RE
.SH "FILES"
.sp
\fB\-\-file\fR で明示的に設定されていない場合、git\-credential\-store が優先順位に従って資格情報を検索する2つのファイルがあります:
.PP
~/\&.git\-credentials
.RS 4
ユーザー毎の資格情報ファイル。
.RE
.PP
$XDG_CONFIG_HOME/git/credentials
.RS 4
2番目のユーザー毎の資格情報ファイル。
\fI$XDG_CONFIG_HOME\fR
が設定されていないか空の場合、
\fB$HOME/\&.config/git/credentials\fR
が使用されます。
\fB~/\&.git\-credentials\fR
に一致する資格情報がある場合、このファイルに保存されている資格情報は使用されません。このファイルがサポートされていない、古いバージョンのGitを使用することがある場合は、このファイルを作成しないことをお勧めします。
.RE
.sp
資格情報探索の場合、ファイルは上記の順序で読み取られ、最初に一致した資格情報が、リストのさらに下のファイルで見つかった資格情報よりも優先されます。
.sp
資格情報ストレージは、デフォルトでこのリストの順で最初に見つかった既存のファイルに書き込みます。これらのファイルが存在しない場合は、 \fB~/\&.git\-credentials\fR を作成して書き込みます。
.sp
資格情報の消去を行うと、一致するすべての資格情報がすべてのファイルから消去されます。
.SH "EXAMPLES"
.sp
このヘルパーの要点は、ユーザー名またはパスワードを入力する必要がある回数を減らすことです。 例えば:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git config credential\&.helper store
$ git push http://example\&.com/repo\&.git
Username: <type your username>
Password: <type your password>

[several days later]
$ git push http://example\&.com/repo\&.git
[your credentials are used automatically]
.fi
.if n \{\
.RE
.\}
.sp
.SH "STORAGE FORMAT"
.sp
\fB\&.git\-credentials\fR ファイルはプレーンテキストで保存されます。各資格情報は、以下のようなURLとしてそれぞれ独自の行に保存されます:
.sp
.if n \{\
.RS 4
.\}
.nf
https://user:pass@example\&.com
.fi
.if n \{\
.RE
.\}
.sp
.sp
他の種類の行(空の行やコメント行など)は、一部が黙って無視される場合でも、ファイル内では許可されません。エディタでファイルを表示または編集しないでください。
.sp
Gitが特定のURLコンテキストの認証を必要とする場合、credential\-store はそのコンテキストを、資格情報ファイルの各エントリと照合するパターンと見なします。 protocolとhostnameと(すでに持っている場合)usernameが一致する場合、パスワードはGitに返されます。詳細については、 \fBgitcredentials\fR(7) の 「the discussion of configuration」を参照してください。
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
