'\" t
.\"     Title: git-sh-i18n
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-SH\-I18N" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-sh-i18n \- シェルスクリプトのためのGit用i18nセットアップコード
.SH "SYNOPSIS"
.sp
.nf
\fI\&. "$(git \-\-exec\-path)/git\-sh\-i18n"\fR
.fi
.sp
.SH "DESCRIPTION"
.sp
これは、全くもってエンドユーザーが実行するコマンドではありません。この文書は、磁器風のスクリプトを研究している、および/または新しいスクリプトを書いている人々を対象としています。
.sp
\*(Aqgit sh\-i18n スクリプトレットは、シェルスクリプト内に実装されたGitの磁器プログラムによって、(\fB\&.`を使用してsourceコマンドで)実行されるように設計されています。 これは、 `gettext\&.sh\fR スクリプトを介してアクセス可能なGNU \fBgettext\fR および \fBeval_gettext\fR 関数のラッパーを提供し、GNU gettextのないシステムではこれらが自動的に使われます(pass\-through fallbacks)。
.SH "FUNCTIONS"
.PP
gettext
.RS 4
現在、
\fBprintf(1)\fR
のラッパーとして実装されているダミーのフォールスルー関数。今後のバージョンでは、実際のgettext実装に置き換えられる事でしょう。
.RE
.PP
eval_gettext
.RS 4
現在、
\fBprintf(1)\fR
のラッパーとして実装されているダミーのフォールスルー関数で、その変数達は
\fBgit-sh-i18n--envsubst\fR(1)
ヘルパーによって展開されます。今後のバージョンでは、実際のgettext実装に置き換えられる事でしょう。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
