'\" t
.\"     Title: git-check-mailmap
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-CHECK\-MAILMAP" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-check-mailmap \- 連絡先(contacts)の、正式な名前と電子メールアドレスを表示
.SH "SYNOPSIS"
.sp
.nf
\fIgit check\-mailmap\fR [<options>] <contact>\&...
.fi
.sp
.SH "DESCRIPTION"
.sp
コマンドライン指定または、(\fB\-\-stdin\fR を使用する場合)標準入力からの各 \(lqName <user@host>\(rq または \(lq<user@host>\(rq について、その人の正規名と電子メールアドレス(以下 "Mapping Authors" 参照)を検索します。見つかった場合は、それらを印刷します。それ以外の場合は、入力をそのまま出力します。
.SH "OPTIONS"
.PP
\fB\-\-stdin\fR
.RS 4
コマンドラインで指定された連絡先(contacts)を消費後、標準入力から連絡先(contacts)を1行に1つずつ読み取ります。
.RE
.SH "OUTPUT"
.sp
各連絡先(contact)ごとに、改行で終了する1行が出力されます。 名前が \fImailmap\fR に提供または認識されている場合、 \(lqName <user@host>\(rq が出力されます。それ以外の場合は、 \(lq<user@host>\(rq のみが出力されます。
.SH "CONFIGURATION"
.sp
カスタムの \fB\&.mailmap\fR ターゲットファイルまたはオブジェクトを指定する方法については、 \fBgit-config\fR(1) の \fBmailmap\&.file\fR と \fBmailmap\&.blob\fR を参照してください。
.SH "MAPPING AUTHORS"
.sp
\fBgitmailmap\fR(5) 参照。
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
