'\" t
.\"     Title: git-pack-redundant
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-PACK\-REDUNDANT" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-pack-redundant \- 無駄なパックファイルを探す
.SH "SYNOPSIS"
.sp
.nf
\fIgit pack\-redundant\fR [ \-\-verbose ] [ \-\-alt\-odb ] ( \-\-all | <pack\-filename>\&... )
.fi
.sp
.SH "DESCRIPTION"
.sp
このプログラムは、リポジトリ内のどのパックが無駄であるかを計算します。あなたがリポジトリのルートにいる場合、出力は \fBxargsrm\fR へのパイプに適しています。
.sp
\fBgit pack\-redundant\fR は、標準入力のオブジェクトのリストを受け入れます。無駄でない必要なパックを確認するとき、指定した任意のオブジェクトはすべて無視されます。これにより、到達不能なオブジェクトを含むパックを削除する場合に、以下のコマンドが役立ちます。
.sp
git fsck \-\-full \-\-unreachable | cut \-d \*(Aq \*(Aq \-f3 | \e git pack\-redundant \-\-all | xargs rm
.SH "OPTIONS"
.PP
\fB\-\-all\fR
.RS 4
すべてのパックを処理します。コマンドラインのファイル名はすべて無視されます。
.RE
.PP
\fB\-\-alt\-odb\fR
.RS 4
代替オブジェクトディレクトリのパックに存在するオブジェクトがローカルパックに存在する必要なしとします。
.RE
.PP
\fB\-\-verbose\fR
.RS 4
いくつかの統計をstderrに出力します。 パフォーマンスの低下はわずかです。
.RE
.SH "SEE ALSO"
.sp
\fBgit-pack-objects\fR(1) \fBgit-repack\fR(1) \fBgit-prune-packed\fR(1)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
