git-pull(1)
===========

NAME
----
git-pull - 別のリポジトリまたはローカルブランチから取得して統合する


SYNOPSIS
--------
[synopsis]
	'git pull' [<options>] [<repository> [<refspec>...]]


DESCRIPTION
-----------

リモートリポジトリからの変更を現在のブランチに統合します。

まず、`git pull` はマージオプションを除く同じ引数で `git fetch` を実行し、リモートブランチを取得します。次に、どのリモートブランチを統合するかを決定します。引数を指定せずに `git pull` を実行した場合、これは現在のブランチの <<UPSTREAM-BRANCHES,upstream>> がデフォルトになります。そして、そのブランチを現在のブランチに統合します。

リモートブランチを統合するための主なオプションは4つあります:

1. `git pull --ff-only` は「fast-forward」更新のみを行います。ローカルブランチがリモートブランチから分岐している場合は失敗します。これがデフォルトです。
2. `git pull --rebase` とすると `git rebase` を実行します。
3. `git pull --no-rebase` とすると `git merge` を実行します。
4. `git pull --squash` とすると `git merge --squash` を実行します。

設定オプション `pull.rebase`, `pull.squash`, `pull.ff` に希望する振る舞いを設定することもできます。

マージまたはリベース中に処理したくないマージコンフリクトが発生した場合は、`git merge --abort` または `git --rebase abort` で安全に中止できます。

OPTIONS
-------

<repository>::
	取得元となる「remote」リポジトリです。これは、URL(下記の <<URLS,GIT URLS>> セクションを参照)またはリモートの名前(下記の <<REMOTES,REMOTES>> セクションを参照)のいずれかです。
+
デフォルトは、現在のブランチに設定された上流(upstream)、または `origin` です。 upstream の設定方法の詳細は、下記の <<UPSTREAM-BRANCHES,UPSTREAM BRANCHES>> を参照してください。

<refspec>::
	現在のブランチに取得・統合するブランチまたはその他の参照で、例えば `git pull origin main` における `main` です。デフォルトは、現在のブランチに設定された upstream です。
+
これは、ブランチ、タグ、またはその他の参照の集合を指定できます。完全な構文については、下記の「Options related to fetching」の <<fetch-refspec,<refspec>>> を、`git pull` がこの引数を使ってどのリモートブランチを統合するかを決定する方法については、下記の <<DEFAULT-BEHAVIOUR,DEFAULT BEHAVIOUR>> を参照してください。

`-q`::
`--quiet`::
	このオプションは git-fetch では転送中のレポートを黙らせる為に、 そして git-merge ではマージ中の出力を黙らせるために、 git-fetch と git-merge の両方に渡されます。

`-v`::
`--verbose`::
	`--verbose` を git-fetch と git-merge に渡します。

`--recurse-submodules[=(yes|on-demand|no)]`::
`--no-recurse-submodules`::
	このオプションは、入力されたサブモジュールの新しいコミットを取得する必要があるかどうか、およびアクティブなサブモジュールの作業ツリーも更新する必要があるかどうかを制御します(linkgit:git-fetch[1] 、linkgit:git-config[1] 、linkgit:gitmodules[5] を参照)。
+
チェックアウトがリベースを介して行われる場合、ローカルサブモジュールのコミットもリベースされます。
+
更新がマージを介して行われる場合、サブモジュールの競合(conflicts)は解決され、チェックアウトされます。

Options related to merging
~~~~~~~~~~~~~~~~~~~~~~~~~~

:git-pull: 1

include::merge-options.adoc[]

`-r`::
`--rebase[=(false|true|merges|interactive)]`::
	trueの場合、 取得後に現在のブランチを上流ブランチの上にリベースします。 上流ブランチに対応するリモート追跡ブランチがあり、上流ブランチが最後に取得されてからリベースされた場合、リベースはその情報を使用して、非ローカル変更のリベースを回避します。
+
`merges` に設定すると、 `git rebase --rebase-merges` を使用してリベースし、ローカルマージコミットがリベースに含まれるようにします(詳細については、 linkgit:git-rebase[1] を参照してください)。
+
falseの場合、上流ブランチを現在のブランチにマージします。
+
`interactive` の場合、リベースの対話モードを有効にします。
+
`git pull` がマージする代わりに、常に `--rebase` を使用するようにしたいなら、 linkgit:git-config[1] の `pull.rebase` と `branch.<name>.rebase` と `branch.autoSetupRebase` を参照してください。
+
[NOTE]
これは潜在的に「危険」な操作モードです。 それは履歴を塗り替えてしまいます。その履歴はすでに公開されているのですから、良くない兆候です。 linkgit:git-rebase[1] を注意深く読んでいない限り、このオプションを使用しないでください。

`--no-rebase`::
	これは `--rebase=false` の省略形です。

Options related to fetching
~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::fetch-options.adoc[]

include::pull-fetch-param.adoc[]

include::urls-remotes.adoc[]

include::merge-strategies.adoc[]

[[DEFAULT-BEHAVIOUR]]
DEFAULT BEHAVIOUR
-----------------

`git pull` は多くの場合パラメータを指定せずに使われます。伝統的にこれは `git pull origin` と言うのと同じです。 ただし、ブランチ `<name>` に設定 `branch.<name>.remote` が存在する場合は、 `origin` の代わりにその値が使用されます。

取得に使用するURLを決定するために、構成 `remote.<origin>.url` の値が参照され、そのような変数がない場合は、 `$GIT_DIR/remotes/<origin>` の `URL:` 行の値が使用されます。

コマンドラインにrefspecパラメーターを指定せずにコマンドを実行したときに取得する(およびオプションでリモート追跡ブランチに格納する)リモートブランチを決定するには、構成変数 `remote.<origin>.fetch` の値を参照します。 構成変数 `remote.<origin>.fetch` が存在しない場合は、 `$GIT_DIR/remotes/<origin>` が参照され、その `Pull:` 行が使用されます。 「OPTIONS」セクションで説明されているrefspec形式に加えて、以下のようなrefspecグロブを作成できます:

------------
refs/heads/*:refs/remotes/origin/*
------------

グロブの refspec には空でないRHSが必要であり(つまり、リモート追跡ブランチで取得されたものを格納する必要があります)、そのLHSとRHSは `/*` で終わる必要があります。 上記では、すべてのリモート・ブランチが、同じ名前の `refs/remotes/origin/` 階層のリモート追跡ブランチを使用して追跡されることを指定しています。

下位互換性を損なわないために、 取得後にマージするリモート・ブランチを決定するルールは少し複雑です。

`git pull` のコマンドラインで明示的なrefspecが指定されている場合、それらはすべてマージされます。

コマンドラインでrefspecが指定されていない場合、 `git pull` は 構成 または `$GIT_DIR/remotes/<origin>` からのrefspecを使用します。このような場合、以下のルールが適用されます:

. 現在のブランチ `<name>` の `branch.<name>.merge` 構成が存在する場合、それはマージされるリモートサイトのブランチの名前です。

. refspecがグロブのものである場合、何もマージされません。

. それ以外の場合は、最初のrefspecのリモートブランチがマージされます。


EXAMPLES
--------

* クローンを作成したリポジトリのリモート追跡ブランチを更新し、そのうちの1つを現在のブランチにマージします:
+
------------------------------------------------
$ git pull
$ git pull origin
------------------------------------------------
+
通常、マージされるブランチはリモートリポジトリのHEADですが、選択は branch.<name>.remote および branch.<name>.merge オプションによって決定されます。 詳細については、 linkgit:git-config[1] を参照してください。

* 現在のブランチにリモートブランチ `next` をマージします:
+
------------------------------------------------
$ git pull origin next
------------------------------------------------
+
これにより、 `next` のコピーが一時的に FETCH_HEAD に残され、 リモート追跡ブランチの `origin/next` が更新されます。 fetch と merge を呼び出すことで同じことができます:
+
------------------------------------------------
$ git fetch origin
$ git merge origin/next
------------------------------------------------


あなたがプルを試みた結果、複雑な競合が発生し、最初からやり直したい場合は、 `git reset` で回復できます。


include::transfer-data-leaks.adoc[]

BUGS
----
現在は `--recurse-submodules` を使用すると、 既にチェックアウトされているサブモジュールでの新しいコミットのみを取得できます。 たとえば、 上流がスーパー・プロジェクトの直前に取得したコミットで新しいサブモジュールを追加した場合、 そのサブモジュール自体を取得できないため、 後でそのサブモジュールをチェックアウトするには再度取得する必要があります。 この問題は、 将来の Git バージョンで修正される予定です。

SEE ALSO
--------
linkgit:git-fetch[1], linkgit:git-merge[1], linkgit:git-config[1]

GIT
---
Part of the linkgit:git[1] suite
