git-refs(1)
===========

NAME
----
git-refs - ref への低レベル・アクセス


SYNOPSIS
--------
[synopsis]
	git refs migrate --ref-format=<format> [--no-reflog] [--dry-run]
	git refs verify [--strict] [--verbose]
	git refs list [--count=<count>] [--shell|--perl|--python|--tcl]
			   [(--sort=<key>)...] [--format=<format>]
			   [--include-root-refs] [--points-at=<object>]
			   [--merged[=<object>]] [--no-merged[=<object>]]
			   [--contains[=<object>]] [--no-contains[=<object>]]
			   [(--exclude=<pattern>)...] [--start-after=<marker>]
			   [ --stdin | (<pattern>...)]
	git refs exists <ref>
	git refs optimize [--all] [--no-prune] [--auto] [--include <pattern>] [--exclude <pattern>]

DESCRIPTION
-----------

このコマンドは参照への低レベル・アクセスを提供します。

COMMANDS
--------

`migrate`::
	異なる形式間で参照ストアを移行します。

`verify`::
	参照データーベースの一貫性を検証する。

list::
	フィルタリング、書式設定、ソートをサポートして、リポジトリ内の参照を一覧表示します。このサブコマンドは linkgit:git-for-each-ref[1] の別名で、同一の機能を提供します。

exists::
	指定した参照が存在するかどうかを確認します。存在する場合は終了コード 0、存在しない場合は 2 を返し、参照が存在しないこと以外のエラーにより参照の検索に失敗した場合は 1 を返します。これは、参照が実際のオブジェクトに解決されるかどうかは検証しません。

optimize::
	リポジトリの性能を改善しディスク使用量を減らすために、参照を最適化します。このサブコマンドは linkgit:git-pack-refs[1] の別名で、同一の機能を提供します。

OPTIONS
-------

以下のオプション達は `git refs migrate` 用です:

`--ref-format=<format>`::
	参照ストアを移行する対象の参照形式。 以下のいずれかになります:
+
include::ref-storage-format.adoc[]

`--dry-run`::
	移行を実行しますが、 リポジトリーは変更しません。 移行された ref は、 別個に検査できるように別のディレクトリに書き込まれます。 ディレクトリの名前は stdout で報告されます。 これを使用して、 実際の移行を実行する前に、 移行が予想どおりに機能することを再確認できます。

`--reflog`::
`--no-reflog`::
	reflog データを新しいバックエンドへ移行するか、破棄するかを選択します。デフォルトは「移行する」(`--reflog`)です。

以下のオプション達は `git refs verify` 用です:

`--strict`::
	より厳格なエラー・チェックを有効にします。 これにより、 警告がエラーとして報告されます。 inkgit:git-fsck[1] 参照。

`--verbose`::
	参照データベースの一貫性を確認するときに、 おしゃべりにします。

以下のオプション達は `git refs list` 用です:

include::for-each-ref-options.adoc[]

以下のオプション達は `git refs optimize` 用です:

include::pack-refs-options.adoc[]

既知の制限
-----

参照形式の移行については、 現在の形式ではいくつかの既知の制限があります:

* ワークツリーを持つリポジトリーの移行はできません。

* 移行の進行中、 リポジトリーへの並列書き込みをブロックする方法はありません。 並列書き込みは一貫性のない移行状態につながる可能性があります。 ユーザーは、 より高いレベルで書き込みをブロックすることが期待されています。 あなたのリポジトリーがスケジュールされたメンテナンスのために登録されている場合、 git-maintenance(1) で最初に登録解除することをお勧めします。

これらの制限は将来的には解除される可能性があります。

GIT
---
Part of the linkgit:git[1] suite
