'\" t
.\"     Title: git-patch-id
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-PATCH\-ID" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-patch-id \- パッチの一意のIDを計算します
.SH "SYNOPSIS"
.sp
.nf
\fIgit patch\-id\fR [\-\-stable | \-\-unstable]
.fi
.sp
.SH "DESCRIPTION"
.sp
標準入力からパッチを読み取り、そのパッチIDを計算します。
.sp
「パッチID」は、パッチに関連付けられたファイル差分のSHA\-1の合計に過ぎず、空白と行番号は無視されます。そのため、「適度に安定」していますが、同時に適度に一意です。つまり、同じ「パッチID」を持つ2つのパッチは、ほぼ同じものであることが保証されています。
.sp
つまり、これを使用して、重複している可能性のあるコミットを探すことができます。
.sp
\fIgit diff\-tree\fR 出力を処理する場合、パッチの前にコミットのオブジェクト名が付いているという事実を利用して、2つの40バイトの16進文字列を出力します。最初の文字列はパッチIDで、2番目の文字列はコミットIDです。これを使用して、パッチIDからコミットIDへのマッピングを作成できます。
.SH "OPTIONS"
.PP
\fB\-\-stable\fR
.RS 4
パッチIDとして「安定した」ハッシュの合計を使用します。 このオプションを使用すると:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
パッチを構成するファイル差分を並べ替えても、IDには影響しません。特に、 "\-O<orderfile>" の異なる2つの設定で同じ2つのツリーを比較することによって生成された2つのパッチは、同じパッチIDになります。これにより、計算結果をキーとして使用して、 2本のツリー間の変更に関するメタ情報にインデックスを付ける事ができます。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
結果として、 "\-O<orderfile>" を使用せずに取得されたdiff出力で使用された場合でも、 git 1\&.9 以前で生成された値、または「unstable」ハッシュ(以下
\fB\-\-unstable\fR
を参照)が構成されたときに生成された値とは異なります。これにより、そのような「不安定な」または過去のパッチIDを格納している既存のデータベースが使用できなくなります。
.sp
.if n \{\
.RS 4
.\}
.nf
patchid\&.stable が true に設定されている場合は、こちらがデフォルトになります。
.fi
.if n \{\
.RE
.\}
.RE
.RE
.PP
\fB\-\-unstable\fR
.RS 4
パッチIDとして「不安定な」ハッシュを使用します。このオプションを使用すると、生成される結果は git1\&.9 以前で生成される patch\-id 値と互換性があります。git 1\&.9 以前で作成されたパッチIDを保存している既存のデータベースを使用しているユーザー(並べ替えられたパッチを処理しないユーザー)は、このオプションを使用することをお勧めします。
.sp
.if n \{\
.RS 4
.\}
.nf
*これがデフォルトです。
.fi
.if n \{\
.RE
.\}
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
