'\" t
.\"     Title: git-quiltimport
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-QUILTIMPORT" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-quiltimport \- quilt(キルト)パッチセットを現在のブランチに適用します
.SH "SYNOPSIS"
.sp
.nf
\fIgit quiltimport\fR [\-\-dry\-run | \-n] [\-\-author <author>] [\-\-patches <dir>]
                [\-\-series <file>] [\-\-keep\-non\-patch]
.fi
.sp
.SH "DESCRIPTION"
.sp
quiltパッチセットを現在のGitブランチに適用し、quiltパッチセットに存在するパッチ境界、パッチ順序、およびパッチの説明を保持します。
.sp
パッチごとに、コードはパッチの説明から作者を抽出しようとします。それが失敗した場合は、 \fB\-\-author\fR で指定された作者にフォールバックします。 \fB\-\-author\fR フラグが指定されていない場合、パッチの説明が表示され、ユーザーはパッチの作者をインタラクティブに入力するように求められます。
.sp
パッチの説明に件名が見つからない場合、パッチ名はGitの説明の1行の件名として保持されます。
.SH "OPTIONS"
.PP
\fB\-n\fR, \fB\-\-dry\-run\fR
.RS 4
一連(series)のパッチをウォークスルーし、パッチをコミットするために必要なすべての情報が見つからない場合は警告します。この記事の執筆時点では、欠落している作者情報のみを警告します。
.RE
.PP
\fB\-\-author Author Name <Author Email>\fR
.RS 4
パッチの説明に作者情報が見つからない場合に使用する作者名と電子メールアドレス。
.RE
.PP
\fB\-\-patches <dir>\fR
.RS 4
quiltパッチを見つけるためのディレクトリ。
.sp
パッチディレクトリのデフォルトは、 patches または
\fB$QUILT_PATCHES\fR
環境変数の値です。
.RE
.PP
\fB\-\-series <file>\fR
.RS 4
キルトシリーズファイル(quilt series file)。
.sp
シリーズファイルのデフォルトは、 <patches>/series または
\fB$QUILT_SERIES\fR
環境変数の値です。
.RE
.PP
\fB\-\-keep\-non\-patch\fR
.RS 4
\fB\-b\fR
フラグを
\fIgit mailinfo\fR
に渡します(\fBgit-mailinfo\fR(1)
参照)。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
