'\" t
.\"     Title: git-annotate
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-ANNOTATE" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-annotate \- 指定ファイルの各行のコミット情報を表示
.SH "SYNOPSIS"
.sp
.nf
\fIgit annotate\fR [<options>] <file> [<revision>]
.fi
.sp
.SH "DESCRIPTION"
.sp
指定されたファイルの各行に、その行を導入したコミットからの情報で注釈を付けます。オプションで、特定のリビジョンから注釈を付けます。
.sp
このコマンドと \fBgit-blame\fR(1) の唯一の違いは、わずかに異なる出力形式を使用することです。このコマンドは、既存のスクリプトをサポートするための下位互換性のためにのみ存在し、他のSCMシステムから来た人々により馴染みのあるコマンド名を提供します。
.SH "OPTIONS"
.PP
\fB\-b\fR
.RS 4
境界コミットでは空白のSHA\-1を表示します。これは、
\fBblame\&.blankBoundary\fR
構成オプションを介して制御することもできます。
.RE
.PP
\fB\-\-root\fR
.RS 4
ルートコミットを境界として扱わないでください。 これは、
\fBblame\&.showRoot\fR
構成オプションを介して制御することもできます。
.RE
.PP
\fB\-\-show\-stats\fR
.RS 4
blameの出力の最後に追加の統計を含めます。
.RE
.PP
\fB\-L <start>,<end>\fR, \fB\-L :<funcname>\fR
.RS 4
\fB<start>,<end>\fR
で指定の行範囲のみ、または正規表現関数名
\fB<funcname>\fR
で指定の行範囲のみに注釈を付けます。複数回指定できます。範囲が重複するのは許されます。
.sp
\fB<start>\fR
と
\fB<end>\fR
はオプションです。
\fB\-L <start>\fR
または
\fB\-L <start>,\fR
は
\fB<start>\fR
からファイルの終わりまでの範囲です。
\fB\-L ,<end>\fR
は、ファイルの先頭から
\fB<end>\fR
までの範囲です。
.sp
<start> と <end> は、以下のいずれかの形式です:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
数値
.sp
<start> または <end> が数値の場合、絶対行番号を指定します(行は1から数えます)。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB/regex/\fR
.sp
この形式は、指定されたPOSIX正規表現に一致する最初の行を使用します。 <start> が正規表現の場合、前の
\fB\-L\fR
範囲の末尾から検索します。それ以外の場合は、ファイルの先頭から検索します。 <start> が
\fB^/regex/\fR
の場合、ファイルの先頭から検索します。 <end> が正規表現の場合、 <start> で指定された行から検索開始します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
+offset or \-offset
.sp
これは <end> に対してのみ有効であり、 <start> で指定された行の前後の行数を指定します。
.RE
.sp
<start> と <end> の代わりに
\fB:<funcname>\fR
が指定されている場合、これは <funcname> に一致する最初の関数名行から次の関数名行までの範囲を示す正規表現です。
\fB:<funcname>\fR
は、前の
\fB\-L\fR
範囲の末尾から検索します。それ以外の場合は、ファイルの先頭から検索します。
\fB^:<funcname>\fR
はファイルの先頭から検索します。関数名は、
\fBgit diff\fR
がパッチハンクヘッダーを処理するのと同じ方法で決定されます(\fBgitattributes\fR(5)
の「Defining a custom hunk\-header」参照)。
.RE
.PP
\fB\-l\fR
.RS 4
長いレビジョンを表示します(デフォルト: off)。
.RE
.PP
\fB\-t\fR
.RS 4
生のタイムスタンプを表示します(デフフォルト: off)。
.RE
.PP
\fB\-S <revs\-file>\fR
.RS 4
\fBgit-rev-list\fR(1)
を呼び出す代わりに、revs\-fileのリビジョンを使用します。
.RE
.PP
\fB\-\-reverse <rev>\&.\&.<rev>\fR
.RS 4
履歴を後方へではなく前方へウォークします。行があらわれたされたリビジョンを表示する代わりに、行が存在した最後のリビジョンを表示します。これには、START\&.\&.END のように、STARTにblameのパスが存在するレビジョン範囲が必要です。 便宜上、
\fBgit blame \-\-reverse START\fR
は
\fBgit blame \-\-reverse START\&.\&.HEAD\fR
と見なされます。
.RE
.PP
\fB\-\-first\-parent\fR
.RS 4
マージコミットを確認したら、最初の親コミットのみを追跡します。 このオプションは、履歴全体にいつ導入されたかではなく、特定の統合ブランチにいつ導入されたかを判別するために使用できます。
.RE
.PP
\fB\-p\fR, \fB\-\-porcelain\fR
.RS 4
ソフトウェア等で使用するのに適した形式で表示します。
.RE
.PP
\fB\-\-line\-porcelain\fR
.RS 4
磁器形式で表示しますが、コミットが最初に参照されたときだけでなく、各行のコミット情報を出力します。 \-\-porcelain の機能を含んでいます。
.RE
.PP
\fB\-\-incremental\fR
.RS 4
ソフトウェア等で使用するのに適した形式で結果を段階的(incrementally)に表示します。
.RE
.PP
\fB\-\-encoding=<encoding>\fR
.RS 4
作者名(author names)の出力と要約のコミットに使用されるエンコーディングを指定します。 これを
\fBnone\fR
に設定すると、blame出力は変換されていないデータになります。詳細については、
\fBgit-log\fR(1)
のマニュアルページにある discussion の encoding に関する説明を参照してください。
.RE
.PP
\fB\-\-contents <file>\fR
.RS 4
<rev> が指定されていない場合、コマンドは作業ツリーのコピーから逆方向に開始して変更に注釈を付けます。このフラグにより、コマンドは、作業ツリーのコピーに、指定されたファイルの内容が含まれているように見せかけます(コマンドを標準入力から読み取るには、
\fB\-\fR
を指定します)。
.RE
.PP
\fB\-\-date <format>\fR
.RS 4
日付の出力に使用される形式を指定します。 \-\-date が指定されていない場合、blame\&.date 構成変数の値が使用されます。 blame\&.date 構成変数も設定されていない場合は、 iso形式が使用されます。サポートされている値については、
\fBgit-log\fR(1)
の \-\-date オプションの説明を参照してください。
.RE
.PP
\fB\-\-[no\-]progress\fR
.RS 4
進行状況は、端末に接続されている場合、デフォルトで標準エラーストリームに報告されます。このフラグは、端末に接続されていない場合でも進行状況のレポートを有効にします。
\fB\-\-progress\fR
を
\fB\-\-porcelain\fR
または
\fB\-\-incremental\fR
と一緒に使用することはできません。
.RE
.PP
\fB\-M[<num>]\fR
.RS 4
ファイル内の移動またはコピーされた行を検出します。コミットが行のブロックを移動またはコピーすると(たとえば、元のファイルにA、次にBがあり、コミットによってB、次にAに変更される)、従来の「blame」アルゴリズムは移動の半分だけに気づき、通常は行をblameします それは親に上に移動され(つまりB)、子のコミットに下に移動された(つまりA)行にblameを割り当てます。このオプションを使用すると、追加の検査パスを実行することにより、両方のグループの行が親のせいになります。
.sp
<num> はオプションですが、Gitがそれらの行を親コミットに関連付けるためにファイル内で移動/コピーとして検出する必要がある英数字の数(number of alphanumeric characters)の下限です。デフォルト値は20です。
.RE
.PP
\fB\-C[<num>]\fR
.RS 4
\fB\-M\fR
に加えて、同じコミットで変更された他のファイルから移動またはコピーされた行を検出します。これは、プログラムを再編成し、ファイル間でコードを移動するときに役立ちます。このオプションを2回指定すると、コマンドは、ファイルを作成するコミットで他のファイルからのコピーを追加で検索します。このオプションを3回指定すると、コマンドはコミットで他のファイルからのコピーを追加で検索します。
.sp
<num> はオプションですが、Gitがそれらの行を親コミットに関連付けるためにファイル間の移動/コピーとして検出する必要がある英数字の数(number of alphanumeric characters)の下限です。また、デフォルト値は40です。複数の
\fB\-C\fR
オプションが指定されている場合、最後の
\fB\-C\fR
の <num> 引数が有効になります。
.RE
.PP
\fB\-\-ignore\-rev <rev>\fR
.RS 4
変更が発生しなかったかのように、blameを割り当てるときにリビジョンによって行われた変更を無視します。無視されたコミットによって変更または追加された行は、その行または近くの行を変更した前のコミットのせいになります。このオプションは、複数のリビジョンを無視するために複数回指定できます。
\fBblame\&.markIgnoredLines\fR
構成オプションが設定されている場合、無視されたコミットによって変更され、別のコミットに起因する行は、blame出力で
\fB?\fR
でマークされます。
\fBblame\&.markUnblamableLines\fR
構成オプションが設定されている場合、別のリビジョンに帰することができなかった無視されたコミットによって触れられた行は、
\fB*\fR
でマークされます。
.RE
.PP
\fB\-\-ignore\-revs\-file <file>\fR
.RS 4
\fBfile\fR
にリストされているリビジョンを無視します。これは
\fBfsck\&.skipList\fR
と同じ形式である必要があります。このオプションは繰り返すことができ、これらのファイルは、
\fBblame\&.ignoreRevsFile\fR
構成オプションで指定されたファイルの後に処理されます。空のファイル名
\fB""\fR
は、以前に処理されたファイルからrevsのリストをクリアします。
.RE
.PP
\fB\-\-color\-lines\fR
.RS 4
前行と同一のコミットからの場合、デフォルト形式の行注釈に異なる色を付けます。 これにより、異なるコミットによって導入されたコード・ブロックを区別しやすくなります。 色のデフォルトはシアン(cyan)で、
\fBcolor\&.blame\&.repeatedLines\fR
設定オプションを使用して調整できます。
.RE
.PP
\fB\-\-color\-by\-age\fR
.RS 4
デフォルトの形式では、行の経過時間に応じて行の注釈に色を付けます。
\fBcolor\&.blame\&.highlightRecent\fR
構成オプションは、年齢の各範囲で使用される色を制御します。
.RE
.PP
\fB\-h\fR
.RS 4
ヘルプメッセージを表示する。
.RE
.SH "SEE ALSO"
.sp
\fBgit-blame\fR(1)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
