'\" t
.\"     Title: git-apply
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-APPLY" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-apply \- パッチをファイルやインデックスに適用します
.SH "SYNOPSIS"
.sp
.nf
\fIgit apply\fR [\-\-stat] [\-\-numstat] [\-\-summary] [\-\-check] [\-\-index | \-\-intent\-to\-add] [\-\-3way]
          [\-\-apply] [\-\-no\-add] [\-\-build\-fake\-ancestor=<file>] [\-R | \-\-reverse]
          [\-\-allow\-binary\-replacement | \-\-binary] [\-\-reject] [\-z]
          [\-p<n>] [\-C<n>] [\-\-inaccurate\-eof] [\-\-recount] [\-\-cached]
          [\-\-ignore\-space\-change | \-\-ignore\-whitespace]
          [\-\-whitespace=(nowarn|warn|fix|error|error\-all)]
          [\-\-exclude=<path>] [\-\-include=<path>] [\-\-directory=<root>]
          [\-\-verbose | \-\-quiet] [\-\-unsafe\-paths] [\-\-allow\-empty] [<patch>\&...]
.fi
.sp
.SH "DESCRIPTION"
.sp
提供されたdiff出力(つまり「パッチ」)を読み取り、ファイルに適用します。 リポジトリ内のサブディレクトリから実行する場合、ディレクトリ外のパスへのパッチは無視されます。 \fB\-\-index\fR オプションを使用すると、パッチはインデックスにも適用され、 \fB\-\-cached\fR オプションを使用すると、パッチはインデックスにのみ適用されます。 これらのオプションがない場合、コマンドはパッチをファイルにのみ適用し、Gitリポジトリにいる必要はありません。
.sp
このコマンドはパッチを適用しますが、コミットは作成しません。 \fBgit-format-patch\fR(1) によって生成されたパッチや、電子メールで受信されたパッチから、 \fBgit-am\fR(1) を使用してコミットを作成します。
.SH "OPTIONS"
.PP
<patch>\&...
.RS 4
パッチを読み取るファイル。
\fB\-\fR
は、標準入力から読み取るために使用できます。
.RE
.PP
\fB\-\-stat\fR
.RS 4
パッチを適用する代わりに、入力に対してdiffstatを出力します。 *applyはオフです(適用操作しません)。
.RE
.PP
\fB\-\-numstat\fR
.RS 4
\fB\-\-stat\fR
に似ていますが、機械読み取り用に、追加および削除された行数を10進表記で表示し、パス名を省略形で表示します。 バイナリファイルの場合、
\fB0 0\fR
と言う代わりに2つの
\fB\-\fR
を出力します。 *applyはオフです(適用操作しません)。
.RE
.PP
\fB\-\-summary\fR
.RS 4
パッチを適用する代わりに、ファイル作成、名前変更、モード変更など、git diff 拡張ヘッダーから取得した情報の要約を出力します。 *applyはオフです(適用操作しません)。
.RE
.PP
\fB\-\-check\fR
.RS 4
パッチを適用する代わりに、パッチが現在の作業ツリーやインデックスファイルに適用可能かどうかを確認し、エラーを検出します。 *applyはオフです(適用操作しません)。
.RE
.PP
\fB\-\-index\fR
.RS 4
パッチをインデックスと作業ツリーの両方に適用します(または、
\fB\-\-check\fR
が有効になっている場合は、両方に正しく適用されることをチェックします)。 注意:
\fB\-\-index\fR
はインデックスエントリと関連するパスの作業木のコピーが同じであることを期待し(それらの内容とファイルモードなどのメタデータは一致する必要があります)、そうでない場合には、たとえパッチがインデックスと作業ツリーのそれぞれに単独できれいに適用されるとしても、エラーを発生させることに注意してください。
.RE
.PP
\fB\-\-cached\fR
.RS 4
作業ツリーに触れることなく、インデックスのみにパッチを適用します。
\fB\-\-check\fR
が有効になっている場合は、インデックスエントリに正しく適用されることをチェックするだけです。
.RE
.PP
\fB\-\-intent\-to\-add\fR
.RS 4
パッチを作業ツリーだけに適用する場合は、新規ファイルをマークして後でインデックスに追加します(\fBgit-add\fR(1)
の
\fB\-\-intent\-to\-add\fR
オプションを参照してください)。このオプションは、Git リポジトリ内で実行していて
\fB\-\-index\fR
が指定されていない場合、無視されます。 なお、
\fB\-\-index\fR
は
\fB\-\-cached\fR
や
\fB\-\-3way\fR
などの他のオプションによって暗示される可能性があります。
.RE
.PP
\fB\-3\fR, \fB\-\-3way\fR
.RS 4
パッチが適用する予定のブロブのIDを記録していて、それらのブロブがローカルで利用可能である場合、3方向マージを試みます。作業ツリーのファイルに競合マーカーを残して、ユーザーが解決できるようにするかもしれません。 このオプションは、
\fB\-\-cached\fR
オプションが使用されていない限り、
\fB\-\-index\fR
オプションを意味し、
\fB\-\-reject\fR
オプションと互換性がありません。 また、
\fB\-\-reject\fR
オプションと互換性がありません。
\fB\-\-cached\fR
オプションと一緒に使用すると、競合があってもキャッシュの上位に残されます。
.RE
.PP
\fB\-\-build\-fake\-ancestor=<file>\fR
.RS 4
新しい
\fBgit diff\fR
出力には、パッチが適用される元のバージョンを識別するのに役立つ各ブロブの「インデックス情報」が埋め込まれています。 このオプションが指定され、元のバージョンのブロブがローカルで使用可能な場合は、それらのブロブを含む一時的なインデックスを作成します。
.sp
純粋なモード変更(インデックス情報を持たない)に遭遇した場合、代わりに現在のインデックスから情報が読み取られます。
.RE
.PP
\fB\-R\fR, \fB\-\-reverse\fR
.RS 4
パッチを逆に適用します。
.RE
.PP
\fB\-\-reject\fR
.RS 4
アトミックな場合、
\fBgit apply\fR
はデフォルトでパッチ全体に失敗し、一部のハンクが適用されない場合は作業ツリーにアクセスしません。 このオプションを使用すると、パッチの該当する部分が適用され、拒否されたハンクが対応する
\fB*\&.rej\fR
ファイルに残されます。
.RE
.PP
\fB\-z\fR
.RS 4
\fB\-\-numstat\fR
が指定されている場合、パス名を変更せずに、NULで終了する機械可読形式を使用します。
.sp
このオプションがないと、構成変数
\fBcore\&.quotePath\fR
で説明されているように、「異常な」文字を含むパス名がクォートされます(\fBgit-config\fR(1)
参照)。
.RE
.PP
\fB\-p<n>\fR
.RS 4
<n>個の先頭のパスコンポーネント(スラッシュで区切られている)を従来のdiffパスから削除します。 たとえば、
\fB\-p2\fR
を使用すると、
\fBa/dir/file\fR
に対するパッチが
\fBfile\fR
に直接適用されます。 デフォルトは1です。
.RE
.PP
\fB\-C<n>\fR
.RS 4
各変更の前後で、周囲のコンテキストの少なくとも<n>行が一致することを確認してください。 周囲のコンテキストの行が少ない場合、それらはすべて一致する必要があります。 デフォルトでは、コンテキストが無視されることはありません。
.RE
.PP
\fB\-\-unidiff\-zero\fR
.RS 4
デフォルトでは、
\fBgit apply\fR
は、適用されるパッチが少なくとも1行のコンテキストを持つ統一された差分(unified diff)であることを想定しています。 これは優れた安全索を提供しますが、
\fB\-\-unified=0\fR
で生成されたdiffを適用すると機能しなくなります。 これらのチェックをバイパスするには、
\fB\-\-unidiff\-zero\fR
を使用します。
.sp
注意: 上記の理由により、文脈自由パッチ(context\-free patches)の使用は推奨されないことに注意してください。
.RE
.PP
\fB\-\-apply\fR
.RS 4
上記の「*applyはオフです(適用操作しません)」と記されたされたオプションのいずれかを使用すると、
\fBgit apply\fR
は、実際にパッチを適用せずに、要求された情報を読み取って出力します。 これらのフラグの後にこのフラグを付けると、パッチも適用します。
.RE
.PP
\fB\-\-no\-add\fR
.RS 4
パッチを適用するときは、パッチによる追加を無視してください。 これを使用して、最初に
\fBdiff\fR
を実行し、このオプションを使用して結果を適用することにより、2つのファイル間の共通部分を抽出できます。これにより、削除部分は適用されますが、追加部分は適用されません。
.RE
.PP
\fB\-\-allow\-binary\-replacement\fR, \fB\-\-binary\fR
.RS 4
Gitの歴史上、ユーザーからの明示的な許可なしにバイナリパッチを適用することは許可されていませんでした。このフラグは、そのための方法でした。 現在、バイナリパッチの適用は常に許可されているため、これは何の操作も行いません(no\-op)。
.RE
.PP
\fB\-\-exclude=<path\-pattern>\fR
.RS 4
与えられたパスパターンに一致するファイルに変更を適用しないでください。 これは、特定のファイルまたはディレクトリを除外するパッチセットをインポートするときに役立ちます。
.RE
.PP
\fB\-\-include=<path\-pattern>\fR
.RS 4
与えられたパスパターンに一致するファイルに変更を適用します。 これは、特定のファイルまたはディレクトリを含めるパッチセットをインポートするときに役立ちます。
.sp
\fB\-\-exclude\fR
および
\fB\-\-include\fR
パターンが使用される場合、それらはコマンドラインに表示される順序で検査され、最初の一致によって各パスへのパッチが使用されるかどうかが決定されます。 どの include/exclude パターンにも一致しないパスへのパッチは、コマンドラインに include パターンがない場合は既定で使用され、includeパターンがある場合は無視されます。
.RE
.PP
\fB\-\-ignore\-space\-change\fR, \fB\-\-ignore\-whitespace\fR
.RS 4
パッチを適用するときは、必要に応じてコンテキスト行の空白(whitespace)の変更を無視してください。 コンテキスト行は空白を保持し、\fB\-\-whitespace\fR
オプションの値に関係なく空白が修正されることはありません。 ただし、追加行はこのオプションに関わらず引き続き修正されます。
.RE
.PP
\fB\-\-whitespace=<action>\fR
.RS 4
パッチを適用するときは、空白エラー(whitespace errors)のある新しい行または変更された行を検出してください。 何を空白エラーと見なすのかは、
\fBcore\&.whitespace\fR
構成で制御します。 デフォルトでは、末尾の空白(空白のみで構成される行を含む)と、行の最初のインデント内で直後にタブ文字が続くスペース文字は、空白エラーと見なされます。
.sp
デフォルトでは、コマンドは警告メッセージを出力しますが、パッチを適用します。
\fBgit\-apply\fR
が統計に使用され、パッチを適用しない場合、デフォルトで
\fBnowarn\fR
になります。
.sp
さまざまな
\fB<action>\fR
値を使用して、この振る舞いを制御できます:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBnowarn\fR
は、末尾の空白の警告をオフにします。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBwarn\fR
は、そのようないくつかのエラーに対する警告を出力しますが、パッチはそのまま適用します(デフォルト)。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBfix\fR
は、そのようないくつかのエラーに対する警告を出力し、それらを修正した後にパッチを適用します(\fBstrip\fR
は同義語です \-\-\- 末尾の空白文字のみをエラーと見なすために使用されるツールであり、fixにはstripが含まれますが、現在のGitはもっと多くのことをします)。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBerror\fR
は、そのようないくつかのエラーに対する警告を出力し、パッチの適用を拒否します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBerror\-all\fR
は
\fBerror\fR
に似ていますが、すべてのエラーを表示します。
.RE
.RE
.PP
\fB\-\-inaccurate\-eof\fR
.RS 4
特定の状況下では、
\fBdiff\fR
の一部のバージョンは、ファイルの最後で欠落している改行を正しく検出しません。 その結果、そのような
\fBdiff\fR
プログラムによって作成されたパッチは、不完全な行を正しく記録しません。 このオプションは、このバグを回避することにより、そのようなパッチを適用するためのサポートを追加します。
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
進捗状況をstderrに報告します。 デフォルトでは、現在適用されているパッチに関するメッセージのみが出力されます。 このオプションを使用すると、追加情報が報告されます。
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
stderr 出力を抑制します。 パッチのステータスや進行状況に関するメッセージは出力されません。
.RE
.PP
\fB\-\-recount\fR
.RS 4
ハンクヘッダーの行数を信頼せず、パッチを調べて推測してください。 (たとえば、ハンクヘッダーを適切に調整せずにパッチを編集した後。)
.RE
.PP
\fB\-\-directory=<root>\fR
.RS 4
すべてのファイル名の前に <root> を付けます。
\fB\-p\fR
引数も渡された場合、 新しい <root> を前に付ける前に適用されます。
.sp
たとえば、
\fBa/git\-gui\&.sh\fR
を
\fBb/git\-gui\&.sh\fR
に更新することについて説明しているパッチを作業ツリー
\fBmodules/git\-gui/git\-gui\&.sh のファイルに適用できます。 `git apply \-\-directory=modules/git\-gui\fR
を実行します。
.RE
.PP
\fB\-\-unsafe\-paths\fR
.RS 4
デフォルトでは、作業領域(Git制御の作業ツリー、または
\fBgit apply\fR
がGNUパッチの代わりに使用される場合の現在の作業ディレクトリ)の外側に影響を与えるパッチは、間違い(またはいたずら)として拒否されます。
.sp
\fBgit apply\fR
が「より良いGNUパッチ」として使用される場合、ユーザーは
\fB\-\-unsafe\-paths\fR
オプションを渡してこの安全性チェックをオーバーライドできます。
\fB\-\-index\fR
または
\fB\-\-cached\fR
が使用されている場合、このオプションは効果がありません。
.RE
.PP
\fB\-\-allow\-empty\fR
.RS 4
diff を含まないパッチに対してエラーを返さないでください。 空のパッチやコミット・テキストのみのパッチもこの対象になります。
.RE
.SH "CONFIGURATION"
.sp
このセクションの以下のすべては、 \fBgit-config\fR(1) ドキュメントの抜粋です。 内容は \fBgit-config\fR(1) ドキュメント にあるものと同一です:
.PP
apply\&.ignoreWhitespace
.RS 4
\fBchange\fR
に設定すると、
\fB\-\-ignore\-space\-change\fR
オプションと同じように、空白の変更を無視するように
\fBgit apply\fR
に指示します。
\fBno\fR,
\fBnone\fR,
\fBnever\fR,
\fBfalse\fR
のいずれかに設定すると、すべての空白の違いを尊重するように
\fBgit apply\fR
に指示されます。
\fBgit-apply\fR(1)
を参照してください。
.RE
.PP
apply\&.whitespace
.RS 4
\fB\-\-whitespace\fR
オプションと同じ方法で、
\fBgit apply\fR
に空白の処理方法を指示します。
\fBgit-apply\fR(1)
を参照してください。
.RE
.SH "SUBMODULES"
.sp
パッチにサブモジュールへの変更が含まれている場合、 \fBgit apply\fR はこれらの変更を以下のように扱います。
.sp
\fB\-\-index\fR が(明示的または暗黙的に)指定されている場合、パッチを適用するには、サブモジュールのコミットがインデックスと正確に一致する必要があります。 サブモジュールのいずれかがチェックアウトされている場合、これらのチェックアウトは完全に無視されます。つまり、サブモジュールは最新またはクリーンである必要はなく、更新されません。
.sp
\fB\-\-index\fR が指定されていない場合、パッチ内のサブモジュールのコミットは無視され、対応するサブディレクトリの有無のみがチェックされ、(可能であれば)更新されます。
.SH "SEE ALSO"
.sp
\fBgit-am\fR(1)\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
