'\" t
.\"     Title: git-hash-object
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-HASH\-OBJECT" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-hash-object \- オブジェクトIDを計算し、オプションでファイルからブロブを作成する
.SH "SYNOPSIS"
.sp
.nf
\fIgit hash\-object\fR [\-t <type>] [\-w] [\-\-path=<file>|\-\-no\-filters] [\-\-stdin [\-\-literally]] [\-\-] <file>\&...
\fIgit hash\-object\fR [\-t <type>] [\-w] \-\-stdin\-paths [\-\-no\-filters]
.fi
.sp
.SH "DESCRIPTION"
.sp
指定のファイル(作業ツリーの外部にある可能性あり)の内容を使用して、指定されたタイプのオブジェクトのオブジェクトID値を計算し、オブジェクトIDを標準出力に報告します。オプションで結果のオブジェクトをオブジェクトデータベースに書き込みます。 <type> が指定されていない場合、デフォルトで「blob」になります。
.SH "OPTIONS"
.PP
\fB\-t <type>\fR
.RS 4
タイプの指定(デフォルト: "blob")。
.RE
.PP
\fB\-w\fR
.RS 4
実際にオブジェクトをオブジェクトデータベースに書き込みます。
.RE
.PP
\fB\-\-stdin\fR
.RS 4
ファイルからではなく、標準入力からオブジェクトを読み取ります。
.RE
.PP
\fB\-\-stdin\-paths\fR
.RS 4
コマンドラインからではなく、標準入力から1行に1つずつファイル名を読み取ります。
.RE
.PP
\fB\-\-path\fR
.RS 4
指定されたパスにあるオブジェクトをハッシュします。ファイルの場所はハッシュ値に直接影響しませんが、パスを使用して、オブジェクトデータベースに配置する前にオブジェクトに適用するGitフィルターを決定し、フィルターを適用した結果、実際のブロブを配置します。オブジェクトデータベースへの入力は、指定されたファイルとは異なる場合があります。このオプションは主に、作業ディレクトリの外部にある一時ファイルまたは標準入力から読み取られたファイルをハッシュする場合に役立ちます。
.RE
.PP
\fB\-\-no\-filters\fR
.RS 4
行末変換など、属性メカニズムによって選択された入力フィルターを無視して、コンテンツをそのままハッシュします。 ファイルが標準入力から読み取られる場合、
\fB\-\-path\fR
オプションが指定されていない限り、これは常に暗黙に指定されたものとみなします。
.RE
.PP
\fB\-\-literally\fR
.RS 4
\fB\-\-stdin\fR
が、標準のオブジェクトパースやgit\-fsckチェックに合格しない可能性のあるガベージをハッシュして緩いオブジェクトにできるようにします。Git自体のストレステストや、野生で遭遇した破損または偽のオブジェクトの特性の再現に役立ちます。
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
