'\" t
.\"     Title: git-repack
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/10/2022
.\"    Manual: Git Manual
.\"    Source: Git 2.38.0.rc1.238.g4f4d434dc6.dirty
.\"  Language: English
.\"
.TH "GIT\-REPACK" "1" "12/10/2022" "Git 2\&.38\&.0\&.rc1\&.238\&.g" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-repack \- リポジトリ内のアンパックオブジェクトをパックする
.SH "SYNOPSIS"
.sp
.nf
\fIgit repack\fR [\-a] [\-A] [\-d] [\-f] [\-F] [\-l] [\-n] [\-q] [\-b] [\-m] [\-\-window=<n>] [\-\-depth=<n>] [\-\-threads=<n>] [\-\-keep\-pack=<pack\-name>] [\-\-write\-midx]
.fi
.sp
.SH "DESCRIPTION"
.sp
このコマンドは、現在パック内に存在しないすべてのオブジェクトを1つのパックに結合するために使用されます。また、既存のパックを単一のより効率的なパックに再編成するために使用することもできます。
.sp
パックは、個別に圧縮され、デルタ圧縮が適用され、関連付けられたインデックスファイルとともに単一のファイルに格納されたオブジェクトのコレクションです。
.sp
パックは、ミラーシステム、バックアップエンジン、ディスクストレージなどの負荷を軽減するために使用されます。
.SH "OPTIONS"
.PP
\fB\-a\fR
.RS 4
パックされていないオブジェクトを段階的にパックする代わりに、参照されるすべてのものを1つのパックにパックします。プライベート開発に使用されるリポジトリをパックする場合に特に便利です。
\fB\-d\fR
と一緒に使用します。 これにより、
\fBgit prune\fR
が残したオブジェクトがクリーンアップされますが、
\fBgit fsck \-\-full \-\-dangling\fR
ではぶら下がりを表示します。
.sp
馬鹿プロトコル(dumb protocol)を介してフェッチするユーザーは、含まれているオブジェクトを取得するために、そのパック内にすでにローカルにある他のオブジェクトの数に関係なく、まったく新しいパックをフェッチする必要があることに注意してください。
.sp
promisorパックファイルは個別に再パックされます。
\fB\&.promisor\fR
ファイルに関連付けられているパックファイルがある場合、これらのパックファイルは別の個別パックに再パックされ、新しい個別パックに対応する、空の
\fB\&.promisor\fR
ファイルが書き込まれます。
.RE
.PP
\fB\-A\fR
.RS 4
\fB\-d\fR
を使用しない限り
\fB\-a\fR
と同じです。 それから、前のパックの到達不能なオブジェクトは、古いパックに残されるのではなく、looseになって、パックされていないオブジェクトになります。再パックする場合でも、到達不能なオブジェクトが意図的にパックに追加されることはありません。このオプションは、到達不能なオブジェクトが古いパックに残されて、古いパックごと削除されることによって、すぐに削除されてしまうのを防ぎます。代わりに、loose到達不能オブジェクトは、以下の 「git gc」呼び出しで通常の有効期限ルールに従って剪定されます。
\fBgit-gc\fR(1)
を参照してください。
.RE
.PP
\fB\-d\fR
.RS 4
パック後、新しく作成されたパックによって既存のパックの一部が冗長になる場合は、冗長パックを削除してください。 また、「git prune\-packed」を実行して、冗長なルーズオブジェクトファイルを削除します。
.RE
.PP
\fB\-\-cruft\fR
.RS 4
\fB\-d\fR
が使用されない限り、
\fB\-a\fR
と同一です。 そして、到達不能なオブジェクトは別のクラフト・パックにパックされます。 到達不能なオブジェクトは、次回の
\fBgit gc\fR
の呼び出しで通常の有効期限ルールを使用して刈り込み(prune)できます(\fBgit-gc\fR(1)
参照)。
\fB\-k\fR
とは互換性がありません。
.RE
.PP
\fB\-\-cruft\-expiration=<approxidate>\fR
.RS 4
次回の
\fBgit gc\fR
の呼び出しを待つ代わりに、
\fB<approxidate>\fR
よりも古い到達不能オブジェクトをすぐに期限切れにします。
\fB\-\-cruft \-d\fR
でのみ有用です。
.RE
.PP
\fB\-l\fR
.RS 4
\fB\-\-local\fR
オプションを
\fBgit pack\-objects\fR
に渡します。
\fBgit-pack-objects\fR(1)
を参照してください。
.RE
.PP
\fB\-f\fR
.RS 4
\fB\-\-no\-reuse\-delta\fR
オプションを
\fBgit\-pack\-objects\fR
に渡します。
\fBgit-pack-objects\fR(1)
を参照してください。
.RE
.PP
\fB\-F\fR
.RS 4
\fB\-\-no\-reuse\-object\fR
オプションを
\fBgit\-pack\-objects\fR
に渡します。
\fBgit-pack-objects\fR(1)
を参照してください。
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
標準エラー・ストリームの進行状況を表示せず、かつ、
\fB\-q\fR
オプションを
\fBgit pack\-objects\fR
に渡します。
\fBgit-pack-objects\fR(1)
を参照してください。
.RE
.PP
\fB\-n\fR
.RS 4
\fBgit update\-server\-info\fR
でサーバー情報を更新しないでください。このオプションは、HTTPまたはFTPを介してこのリポジトリ(またはその直接のコピー)を公開するために必要なローカルカタログファイルの更新をスキップします。
\fBgit-update-server-info\fR(1)
を参照してください。
.RE
.PP
\fB\-\-window=<n>\fR, \fB\-\-depth=<n>\fR
.RS 4
これらの2つのオプションは、パックに含まれるオブジェクトがデルタ圧縮を使用して格納される方法に影響します。オブジェクトは最初にタイプ、サイズ、およびオプションで名前で内部的にソートされ、
\fB\-\-window\fR
内の他のオブジェクトと比較されて、デルタ圧縮を使用することでスペースが節約されるかどうかが確認されます。
\fB\-\-depth\fR
は最大デルタ深度を制限します。深くしすぎると、必要なオブジェクトに到達するためにデルタデータを何度も適用する必要があるため、アンパッカー側(unpacker side)のパフォーマンスに影響します。
.sp
\fB\-\-window\fR
のデフォルト値は10で、
\fB\-\-depth\fR
は50です。最大深度(maximum depth)は4095です。
.RE
.PP
\fB\-\-threads=<n>\fR
.RS 4
このオプションは
\fBgit pack\-objects\fR
に渡されます。
.RE
.PP
\fB\-\-window\-memory=<n>\fR
.RS 4
このオプションは、
\fB\-\-window\fR
に加えて追加の制限を提供します。ウィンドウサイズは、メモリ内で
\fB<n>\fR
バイトを超えないように動的に縮小されます。これは、大きなウィンドウと小さなオブジェクトが混在するリポジトリで、大きなウィンドウでメモリが不足しないようにするのに役立ちますが、小さなオブジェクトは大きなウィンドウを利用できます。 サイズには、「k」または「m」または「g」の接尾辞を付けることができます。
\fB\-\-window\-memory=0\fR
は、メモリ使用量を無制限にします。 デフォルトは、
\fBpack\&.windowMemory\fR
構成変数から取得されます。 実際のメモリ使用量は、制限に
\fBgit-pack-objects\fR(1)
で使用されるスレッド数を掛けたものになることに注意してください。
.RE
.PP
\fB\-\-max\-pack\-size=<n>\fR
.RS 4
各出力パックファイルの最大サイズ。 サイズには、「k」または「m」または「g」の接尾辞を付けることができます。許可される最小サイズは1MiBに制限されています。 指定した場合、複数のパックファイルが作成される可能性があります。これにより、ビットマップインデックスの作成も妨げられます。構成変数
\fBpack\&.packSizeLimit\fR
が設定されていない限り、デフォルトは無制限です。このオプションを使用すると、リポジトリが大きくなり、速度が低下する可能性があることに注意してください。
\fBpack\&.packSizeLimit\fR
の説明を参照してください。
.RE
.PP
\fB\-b\fR, \fB\-\-write\-bitmap\-index\fR
.RS 4
再パックの一部として到達可能性ビットマップインデックスを書き込みます。ビットマップは到達可能なすべてのオブジェクトを参照できる必要があるため、これは
\fB\-a\fR
または
\fB\-A\fR
または
\fB\-m\fR
とともに使用する場合にのみ意味があります。このオプションは、
\fBrepack\&.writeBitmaps\fR
の設定を上書きします。 このオプションは、複数のパックファイルが作成された場合、 MIDX を書き込まない限り効果がありません(この場合、マルチパック・ビットマップが作成されます)。
.RE
.PP
\fB\-\-pack\-kept\-objects\fR
.RS 4
再パックするときは
\fB\&.keep\fR
ファイルにオブジェクトを含めます。
\fBpack\-objects\fR
が終了した後も
\fB\&.keep\fR
パックを削除しないことに注意してください。これは、オブジェクトを複製する可能性があることを意味しますが、これにより、プッシュまたはフェッチが同時に発生する場合にオプションを安全に使用できます。このオプションを指定すると、ビットマップ化されたパックファイルに必要なオブジェクトが確実に含まれるため、通常、
\fB\-b\fR
または
\fBrepack\&.writeBitmaps\fR
を使用してビットマップを書き込む場合にのみ役立ちます。
.RE
.PP
\fB\-\-keep\-pack=<pack\-name>\fR
.RS 4
指定されたパックを再パックから除外します。 これは、パックに
\fB\&.keep\fR
ファイルがあるのと同じです。
\fB<pack\-name>\fR
は、先頭にディレクトリがないパックファイル名です(例:
\fBpack\-123\&.pack\fR)。このオプションは、複数のパックを保持するために複数回指定できます。
.RE
.PP
\fB\-\-unpack\-unreachable=<when>\fR
.RS 4
到達不能なオブジェクトのパックをほどく(loose)ときは、
\fB<when>\fR
より古いオブジェクトをわざわざほどきません。これは、フォローアップで行う
\fBgit prune\fR
によってすぐに剪定されるオブジェクトの書き込みを最適化するために使用できます。
.RE
.PP
\fB\-k\fR, \fB\-\-keep\-unreachable\fR
.RS 4
\fB\-ad\fR
と一緒に使用すると、既存のパックから到達できないオブジェクトは、削除されるのではなく、パックファイルの最後に追加されます。さらに、到達不能なlooseオブジェクトはパックされます(そしてそれらのlooseオブジェクトは削除されます)。
.RE
.PP
\fB\-i\fR, \fB\-\-delta\-islands\fR
.RS 4
\fB\-\-delta\-islands\fR
オプションを
\fBgit\-pack\-objects\fR
に渡します。
\fBgit-pack-objects\fR(1)
を参照してください。
.RE
.PP
\fB\-g=<factor>\fR, \fB\-\-geometric=<factor>\fR
.RS 4
結果のパック構造を、連続する各パックに、次に大きいパックのオブジェクト数の少なくとも
\fB<factor>\fR
倍が含まれるように配置します。
.sp
\fBgit repack\fR
が、等比数列を確実にするために1つに再パックする必要があるパックファイルの「切り分け」を決断することによってこれを保証します。 大きいパックファイルの多く(そのパックに含まれるオブジェクトの数による)がそのまま残るように、パックファイルの最小セットを選択します。
.sp
他の再パックモードとは異なり、梱包するオブジェクトのセットは、「ロールアップ」(rolled\-up)されるパックのセットによって一意に決定されます。言い換えれば、等比数列を復元するために組み合わせる必要があると判断されたパックです。
.sp
\fB\-\-unpacked\fR
が指定されている場合、ルーズオブジェクトは、到達可能性に関係なく、この「ロールアップ」に暗黙的に含まれます。 これは将来変更される可能性があります。このオプション(大幅に異なる再パックモードを意味する)は、
\fBgit repack\fR
の他のすべてのオプションの組み合わせで機能することが保証されていません。
.sp
マルチパック・ビットマップを書き込む場合、
\fBgit repack\fR
は結果として最大のパックを MIDX によるオブジェクト選択の優先パックとして選択します(\fBgit-multi-pack-index\fR(1)
参照)。
.RE
.PP
\fB\-m\fR, \fB\-\-write\-midx\fR
.RS 4
非冗長(non\-redundant)パックを含むマルチパック・インデックス (\fBgit-multi-pack-index\fR(1)
参照) を作成します。
.RE
.SH "CONFIGURATION"
.sp
さまざまな構成変数がパッキングに影響します。 \fBgit-config\fR(1) を参照してください(「pack」と「delta」を検索してください)。
.sp
デフォルトでは、コマンドは \fB\-\-delta\-base\-offset\fR オプションを \fBgit pack\-objects\fR に渡します。これにより、通常、パックはわずかに小さくなりますが、生成されたパックは、バージョン1\&.4\&.4より古いバージョンのGitと互換性がありません。直接またはダムhttpプロトコルを介して、このような古いバージョンのGitとリポジトリを共有する必要がある場合は、構成変数 \fBrepack\&.UseDeltaBaseOffset\fR を \fBfalse\fR に設定して再パックする必要があります。この場合、必要に応じて変換がオンザフライで実行されるため、ネイティブプロトコルを介した古いGitバージョンからのアクセスではこのオプションの影響を受けません。
.sp
デルタ圧縮は、 \fBcore\&.bigFileThreshold\fR 構成変数より大きいオブジェクト、および属性 \fBdelta\fR がfalseに設定されているファイルでは使用されません。
.SH "SEE ALSO"
.sp
\fBgit-pack-objects\fR(1) \fBgit-prune-packed\fR(1)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
