git-format-patch(1)
===================

NAME
----
git-format-patch - 電子メール送信用のパッチを準備します


SYNOPSIS
--------
[synopsis]
	'git format-patch' [-k] [(-o|--output-directory) <dir> | --stdout]
			   [--no-thread | --thread[=<style>]]
			   [(--attach|--inline)[=<boundary>] | --no-attach]
			   [-s | --signoff]
			   [--signature=<signature> | --no-signature]
			   [--signature-file=<file>]
			   [-n | --numbered | -N | --no-numbered]
			   [--start-number <n>] [--numbered-files]
			   [--in-reply-to=<message-id>] [--suffix=.<sfx>]
			   [--ignore-if-in-upstream] [--always]
			   [--cover-from-description=<mode>]
			   [--rfc[=<rfc>]] [--subject-prefix=<subject-prefix>]
			   [(--reroll-count|-v) <n>]
			   [--to=<email>] [--cc=<email>]
			   [--[no-]cover-letter] [--quiet]
			   [--[no-]encode-email-headers]
			   [--no-notes | --notes[=<ref>]]
			   [--interdiff=<previous>]
			   [--range-diff=<previous> [--creation-factor=<percent>]]
			   [--filename-max-length=<n>]
			   [--progress]
			   [<common-diff-options>]
			   [ <since> | <revision-range> ]

DESCRIPTION
-----------

UNIXメールボックスに似た形式で、コミットごとに1つの「メッセージ」に「パッチ」を含む各非マージコミットを準備します。このコマンドの出力は、電子メールの送信や「git am」での使用に便利です。

コマンドによって生成される「メッセージ」は、以下の3つの部分で構成されます:

* 短いメタデータヘッダー。「file(1)」などのプログラムが、ファイルがこのコマンドからの出力であることを認識できるように「From <commit>」と、固定の日付スタンプ「Mon Sep 17 00:00:00 2001」で始まり、 作者ID(author identity)や作者の日付(author date)や変更のタイトル(title of the change)(コミットログメッセージの最初の段落から取得)が記入されたフィールドがあります。

* コミットログメッセージの2番目以降の段落。

* コミットとその親の間の `diff -p --stat` 出力(linkgit:git-diff[1] 参照)である「パッチ」。

ログメッセージとパッチは、3本のダッシュ(`---`)で区切られています。

操作するコミットを指定する方法は2つあります。

1. 単一のコミット<since>は、現在のブランチの先端につながるコミットで、<since>が出力される履歴にないことを指定します。

2. 一般的な <revision-range> 評価式(linkgit:gitrevisions[7] の「SPECIFYING REVISIONS」セクション参照)は、 指定された範囲でのコミットを意味します。

単一の <commit> の場合、最初のルールが優先されます。2番目のルールを適用する、つまり、履歴の開始から <commit> までのすべてをフォーマットするには、 `--root` オプションを使用します: `git format-patch --root <commit>` とします。あなたが <commit> 自体のみをフォーマットしたい場合は、 `git format-patch -1 <commit>` を使用して行うことができます。

デフォルトでは、各出力ファイルには1から順番に番号が付けられ、ファイル名としてコミットメッセージの最初の行(パス名の安全のためにもみもみ(massage)れます)が使用されます。 `--numbered-files` オプションを使用すると、出力ファイル名は数字のみになり、コミットの最初の行は追加されません。 `--stdout`オプションが指定されていない限り、出力ファイル名が標準出力に出力されます。

`-o` を指定すると、出力ファイルは <dir> に作成されます。それ以外の場合は、現在の作業ディレクトリに作成されます。デフォルトのパスは、`format.outputDirectory` 構成オプションで設定できます。 `-o` オプションは `format.outputDirectory` よりも優先されます。 `format.outputDirectory` が他の場所を指している場合でも、パッチを現在の作業ディレクトリに保存したいときは、`-o.` を使用します。すべてのディレクトリコンポーネントが作成されます。

デフォルトでは、単一のパッチの件名は "[PATCH] " で、その後に、コミットメッセージから最初の空白行までの行が連結されます (linkgit:git-commit[1]の DISCUSSION セクション参照)。

複数のパッチが出力される場合、件名のプレフィックスは "[PATCH n/m] " になります。 1つのパッチに 1/1 を強制的に追加するには `-n` を使用します。件名からパッチ番号を省略するには `-N` を使用します。

`--thread` を指定すると、 `git-format-patch` は `In-Reply-To` ヘッダーと `References` ヘッダーを生成し、2番目以降のパッチメールを最初のメールへの返信として表示します。 これにより、参照する `Message-ID` ヘッダーも生成されます。

OPTIONS
-------
:git-format-patch: 1
include::diff-options.adoc[]

`-<n>`::
	最上位から見て <n> 個目のコミットからパッチを準備します。

`-o <dir>`::
`--output-directory <dir>`::
	現在の作業ディレクトリの代わりに、 <dir> を使用して結果のファイルを保存します。

`-n`::
`--numbered`::
	単一のパッチでも、 `[PATCH n/m]` 形式で名前を出力します。

`-N`::
`--no-numbered`::
	`[PATCH]` 形式 で名前を出力します。

`--start-number <n>`::
	パッチの番号付けを1ではなく<n>から開始します。

`--numbered-files`::
	出力ファイル名群は、コミットのデフォルトの最初の行が追加されていない単純な一連番号になります。

`-k`::
`--keep-subject`::
	コミットログメッセージの最初の行から `[PATCH]` を削除/追加 しないでください。

`-s`::
`--signoff`::
	あなた自身ののコミッターIDを使用して、コミットメッセージに `Signed-off-by` トレーラーを追加します。詳細については、 linkgit:git-commit[1]の signoff オフオプションを参照してください。

`--stdout`::
	コミットごとにファイルを作成するのではなく、すべてのコミットをmbox形式で標準出力に出力します。

`--attach[=<boundary>]`::
	マルチパート/混合の添付(multipart/mixed attachment)を作成します。最初の部分はコミットメッセージで、2番目の部分はパッチ自体です。 `Content-Disposition: attachment` を使用します。

`--no-attach`::
	添付ファイルの作成を無効にして、構成設定を上書きします。

`--inline[=<boundary>]`::
	マルチパート/混合の添付(multipart/mixed attachment)を作成します。最初の部分はコミットメッセージで、2番目の部分はパッチ自体です。 `Content-Disposition: inline` を使用します。

`--thread[=<style>]`::
`--no-thread`::
	`In-Reply-To` ヘッダーと `References` ヘッダーの追加を制御して、 2番目以降のメールを最初のメールへの返信として表示します。 また、参照する `Message-ID` ヘッダーの生成を制御します。
+
オプションの <style> 引数は、 `shallow` または `deep` のいずれかです。 「shallow」スレッドは、すべてのメールをシリーズの先頭に返信します。先頭は、送付状と `--in-reply-to` と最初のパッチメールからこの順序で選択されます。「deep」スレッドは、すべてのメールを前のメールへの返信にします。
+
`format.thread` 構成が設定されていない限り、 デフォルトは `--no-thread` です。 引数のない `--thread` は `--thread=shallow` と同等です。
+
`git send-email` のデフォルトが、電子メール自体をスレッド化することであることに注意してください。 `git format-patch` でスレッド化を処理する場合は、 `git send-email` でスレッド化が無効になっていることを確認する必要があります。

`--in-reply-to=<message-id>`::
	最初のメール(または `--no-thread` を含むすべてのメール)を、 指定の <message-id> への応答として表示します。 これにより、 スレッドが壊れて新しいパッチ・シリーズが提供されるのを防ぎます。

`--ignore-if-in-upstream`::
	`<until>..<since>` のコミットに一致するパッチを含めないでください。 これにより、<since>から到達可能で、<until>からは到達できないすべてのパッチが調べられ、生成されているパッチと比較されます。一致するパッチはすべて無視されます。

`--always`::
	デフォルトでは省略されている、変更を導入しないコミットのパッチを含めます。

`--cover-from-description=<mode>`::
	ブランチの説明を使用して、送付状のどの部分に自動的に入力されるかを制御します。
+
`<mode>` が `message` または `default` の場合、送付状の件名にプレースホルダーテキストが入力されます。送付状の本文には、ブランチの説明が入力されます。 これは、構成またはコマンドラインオプションが指定されていない場合のデフォルトモードです。
+
`<mode>` が `subject` の場合、ブランチの説明の最初の段落を送付状の件名に入力します。ブランチの説明の残りの部分は、送付状の本文に入力されます。
+
`<mode>` が `auto` の場合、 ブランチの説明の最初の段落 > 100バイト なら、モードは `message` になり、そうでない場合は `subject` が使用されます。
+
`<mode>` が `none` の場合、送付状の件名と本文の両方にプレースホルダーテキストが入力されます。

`--description-file=<file>`::
	カバーレターを生成するために、 ブランチの説明の代わりに <file> の内容を使用します。

`--subject-prefix=<subject-prefix>`::
	件名の標準の `[PATCH]` プレフィックスの代わりに、 `[<subject-prefix>]` を使用してください。 これは、 パッチ・シリーズの名前を付けるために使用でき、 `--numbered` オプションと組み合わせることができます。
+
設定変数 `format.subjectPrefix` を使用して、 全てのパッチに対して、 特定のリポジトリに適用する件名プレフィックスを設定できます。 これは、 複数のリポジトリからのパッチを受信するメーリングリストで役立つことが多く、 パッチを識別するために使用できます(例:「PATCH my-project」の値)。

`--filename-max-length=<n>`::
	標準の64バイトの代わりに、生成された出力ファイル名を約 `<n>` バイトに切り捨て(短すぎると、値が適切な長さに黙って引き上げられます)。 デフォルトは `format.filenameMaxLength` 構成変数の値、または構成されていない場合は64です。

`--rfc[=<rfc>]`::
	文字列 <rfc> (デフォルトは `RFC` )を処理します。 件名のプレフィックスのデフォルトが `PATCH` であるため、 デフォルトで `RFC PATCH` を取得します。
+
RFC とは「Request For Comments」(コメント募集)を意味します。 これは、 適用のためではなく、 議論のための実験的なパッチを送信する際に使用します。 `--rfc=WIP` もパッチがまだ完成していないことを示す有用な方法です(`WIP` は「Work In Progress」(作業中)の略です)。
+
受信側のコミュニティにおける特定の追加文字列の慣例が件名プレフィックスの「後」に配置するものであれば、 文字列 <rfc> にダッシュ(`-`) を先頭に付けることで、 <rfc> 文字列の残りの部分が件名プレフィックスの後ろに追加されることを指示することができます。例えば、`--rfc='-(WIP)'` を使用すると、 `PATCH (WIP)` になります。

`-v <n>`::
`--reroll-count=<n>`::
	そのシリーズをトピックの <n> 番目の反復としてマークします。出力ファイル名には `v<n>` が付加され、件名接頭辞(デフォルトでは `PATCH` ですが、 `--subject-prefix` オプションで構成可能)には `v<n>` が付加されます。例えば、 `--reroll-count=4` は、 `Subject: [PATCH v4 1/20] Add makefile` を含む `v4-0001-add-makefile.patch` ファイルを生成します。`<n>` は整数である必要はありませんが（たとえば、 `--reroll-count=4.4` とか `--reroll-count= 4rev2` とかでもOK)、このようなreroll-countを使用することの欠点は、以前のバージョンとの range-diff/interdiff で、新しい相互作用(new interation)がどのバージョンと比較されるかを正確に表示できなくなります。

`--to=<email>`::
	メールヘッダーに `To:` ヘッダーを追加します。 これは、任意の構成済みのヘッダー群に追加されるものであり、複数回使用される場合があります。 否定形式の `--no-to` は、これまでに追加されたすべての `To:` ヘッダーを(構成またはコマンドラインから)破棄します。

`--cc=<email>`::
	メールヘッダーに `Cc:` ヘッダーを追加します。 これは、任意の構成済みのヘッダー群に追加されるものであり、複数回使用される場合があります。 否定形式の `--no-cc` は、これまでに追加されたすべての `Cc:` ヘッダーを(構成またはコマンドラインから)破棄します。

`--from`::
`--from=<ident>`::
	各コミットメールの `From:` ヘッダーで <ident> を使用します。 コミットの作成者IDが、提供された <ident> とテキストで同一でない場合は、元の作成者とのメッセージの本文に `From:` ヘッダーを配置します。 <ident> が指定されていない場合は、コミッターIDを使用します。
+
注意: このオプションは、実際にメールを送信していて、自分を送信者として識別したいが、元の作成者を保持したい場合にのみ役立ちます(そして、 `git am` は本文のヘッダーを正しく取得します)。 また、 `git send-email` はすでにこの変換を処理するようになっているため、結果を `git send-email` にフィードする場合は、このオプションを使用しないでください。

`--force-in-body-from`::
`--no-force-in-body-from`::
	`--from` オプションで電子メールの送信者を指定すると、デフォルトでは、作者と送信者が異なる場合、コミットの実際の作者を識別するための本文内の `From:` がコミット・ログ・メッセージの先頭に追加されます。 このオプションを使用すると、送信者と作者が同じ名前とアドレスを持っている場合でも、本文内の `From:` が追加されます。これは、メーリング・リスト・ソフトウェアが送信者の身元を解読する場合に役立ちます。 デフォルトは `format.forceInBodyFrom` 構成変数の値です。

`--add-header=<header>`::
	電子メールヘッダーに任意のヘッダーを追加します。これは、構成済みのヘッダーに追加されるものであり、複数回使用される場合があります。 たとえば、 `--add-header="Organization: git-foo"` です。 否定形式の `--no-add-header` は、構成またはコマンドラインからこれまでに追加された「すべての」(`To:` と `Cc:` と カスタム)ヘッダーを破棄します。

`--cover-letter`::
`--no-cover-letter`::
	パッチに加えて、ブランチの説明、ショートログ、および全体的なdiffstatを含むカバーレターファイルを生成します。あなたは、送信する前に、ファイルに説明を入力できます。

`--encode-email-headers`::
`--no-encode-email-headers`::
	ヘッダーをそのまま(verbatim)出力する代わりに、非ASCII文字を含む電子メールヘッダーを `Q-encoding` (RFC 2047で説明)でエンコードします。 デフォルトは、 `format.encodeEmailHeaders` 構成変数の値です。

`--interdiff=<previous>`::
	レビュアーの補助として、カバーレターに、あるいは1パッチシリーズの単独パッチの解説として、パッチシリーズの前のバージョンと現在フォーマットされているシリーズとの違いを示す interdiff を挿入してください。 `previous` は、フォーマット中のシリーズと共通のベースを持つ、前のシリーズの先端を示す単一のリビジョンです(例えば、 `git format-patch --cover-letter --interdiff=feature/v1 -3 feature/v2` )。

`--range-diff=<previous>`::
	レビューの補助として、カバーレターに range-diff (linkgit:git-range-diff[1] 参照) を挿入するか、1パッチシリーズの単独パッチの解説として、そのパッチシリーズの前のバージョンと現在フォーマットされているシリーズとの相違を示します。 前バージョンは、フォーマットされるシリーズと共通のベースがある場合、前のシリーズの先端を示す単一のリビジョン(例えば `git format-patch --cover-letter --range-diff=feature/v1 -3 feature/v2` )、またはシリーズの二つのバージョンが分離している場合、リビジョンレンジ(例えば `git format-patch --cover-letter --range-diff=feature/v1~3..feature/v1 -3 feature/v2` )が使用されます。
+
注意: コマンドに渡される diff オプションは、 `format-patch` の基本製造物の生成方法に影響し、カバーレターの実体を生成するために使用される基礎となる `range-diff` 機構には渡されないことに注意してください(これは将来変更される可能性があります)。

`--creation-factor=<percent>`::
	`--range-diff` とともに使用すると、 作成/削除 のコストファッジ係数(cost fudge factor)を調整することにより、以前の一連のパッチと現在の一連のパッチの間でコミットを一致させるヒューリスティックを微調整します。 詳細については、 linkgit:git-range-diff[1] を参照してください。
+
デフォルトは 999 です(linkgit:git-range-diff[1] では 60)。 このユースケースは、 同一トピックの以前の反復との比較を表示するためにあり、 ツールは2つのパッチ・セット間でより多くの対応を見つけるべきです。

`--notes[=<ref>]`::
`--no-notes`::
	3つの破線(`---`)行の後に、コミットのnotes (linkgit:git-notes[1] を参照)を追加します。
+
この場合、コミットログメッセージに属さないコミットの説明を書いて、パッチを送信する際に添付することが期待されます。これらの説明は、単に `format-patch` を実行した後で送信する前に書くこともできますが、Git notes として残しておくと、パッチシリーズのバージョン間でそれらを維持することができます(ただし、この作業フローを使用するには linkgit:git-notes[1] の `notes.rewrite` 設定オプションに関するdiscussionを参照してください)。
+
`format.notes` 構成が設定されていない限り、デフォルトは `--no-notes` です。

`--signature=<signature>`::
`--no-signature`::
	生成された各メッセージに署名を追加します。 RFC 3676に従い、署名は `-- ` が付いた行で本文から区切られています。署名オプションを省略した場合、署名はデフォルトでGitバージョン番号になります。

`--signature-file=<file>`::
	署名がファイルから読み取られることを除いて、 `--signature` と同じように機能します。

`--suffix=.<sfx>`::
	生成されたファイル名のサフィックスとして `.patch` を使用する代わりに、指定されたサフィックスを使用します。 一般的な代替手段は `--suffix=.txt` です。 これを空のままにすると、 `.patch` サフィックスが削除されます。
+
注意: 先行する文字はドット(`.`)である必要はないことに注意してください。 たとえば、 `--suffix=-patch` を使用して `0001-description-of-my-change-patch` とかすることができます。

`-q`::
`--quiet`::
	生成されたファイルの名前を標準出力に出力しないでください。

`--no-binary`::
	バイナリファイルの変更内容を出力せず、代わりにそれらのファイルが変更されたという通知を表示します。このオプションを使用して生成されたパッチは適切に適用できませんが、コードレビューには役立ちます。

`--zero-commit`::
  コミットのハッシュの代わりに、各パッチのFromヘッダーにすべてゼロのハッシュを出力します。

`--no-base`::
`--base[=<commit>]`::
	ベースツリー情報を記録して、パッチシリーズが適用される状態を特定します。 詳細については、下記「BASE TREE INFORMATION」セクションを参照してください。 <commit> が `auto` の場合、ベースコミットが自動的に選択されます。 `--no-base` オプションは、 `format.useAutoBase` 構成をオーバーライドします。

`--root`::
	単一のコミットであっても、 リビジョン引数を <revision-range> として扱います(通常は <since> として扱われます)。 指定された範囲に含まれるルート・コミットは、 このフラグとは関係なく、 常に作成パッチとしてフォーマットされることに注意してください。

`--progress`::
	パッチが生成されるときに、stderrへ進捗レポートを表示します。

CONFIGURATION
-------------
あなたは、各メッセージに追加するメールヘッダー行の指定、件名のプレフィックスとファイルのサフィックスのデフォルト、複数のパッチを出力する場合のパッチ番号の指定、 `To:` または `Cc:` ヘッダーの追加、添付ファイルの設定、パッチ出力ディレクトリの変更、設定変数によるパッチのサインオフ、が可能です。

------------
[format]
	headers = "Organization: git-foo\n"
	subjectPrefix = CHANGE
	suffix = .txt
	numbered = auto
	to = <email>
	cc = <email>
	attach [ = mime-boundary-string ]
	signOff = true
	outputDirectory = <directory>
	coverLetter = auto
	coverFromDescription = auto
------------


DISCUSSION
----------

`git format-patch` によって生成されたパッチはUNIXメールボックス形式であり、ファイルが実際のメールボックスではなくformat-patchから出力されることを示す固定の「魔法の」タイムスタンプ(fixed "magic" time stamp)が付いています。

------------
From 8f72bad1baf19a53459661343e21d6491c3908d3 Mon Sep 17 00:00:00 2001
From: Tony Luck <tony.luck@intel.com>
Date: Tue, 13 Jul 2010 11:42:54 -0700
Subject: [PATCH] =?UTF-8?q?[IA64]=20Put=20ia64=20config=20files=20on=20the=20?=
 =?UTF-8?q?Uwe=20Kleine-K=C3=B6nig=20diet?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

arch/arm config files were slimmed down using a python script
(See commit c2330e286f68f1c408b4aa6515ba49d57f05beae comment)

Do the same for ia64 so we can have sleek & trim looking
...
------------

通常、MUAの下書きフォルダに配置され、タイムリーなコメントを追加するように編集されます。このコメントは、3つのダッシュ(`---`)の後に変更ログに記録されないように編集され、メッセージとして送信されます。この例では、本文は `arch/arm config files were...` です。受信側では、読者は興味あるパッチをUNIXメールボックスに保存し、 linkgit:git-am[1] を使用してそれらを適用できます。

パッチが進行中の議論の一部である場合、 `git format-patch` によって生成されたパッチは、`git am --scissors` 機能を利用するように調整できます。議論への応答の後に、`-- >8 --` （訳注: `>8` は、ハサミを横にしたアスキーアート(?))のみで構成される行があり、その後に不要なヘッダーフィールドが削除されたパッチが続きます:

------------
...
> So we should do such-and-such.

Makes sense to me.  How about this patch?

-- >8 --
Subject: [IA64] Put ia64 config files on the Uwe Kleine-König diet

arch/arm config files were slimmed down using a python script
...
------------

この方法でパッチを送信する場合、ほとんどの場合、独自のパッチを送信するため、 `From $SHA1 $magic_timestamp` マーカーに加えて、パッチファイルから `From:` と `Date:` 行を省略する必要があります。パッチのタイトルは、パッチが、応答するディスカッションの主題とは異なる可能性が高いため、上記の例のように、 `Subject:` 行を保持する必要がある可能性があります。

パッチの破損のチェック
~~~~~~~~~~~
多くのメーラーは、適切に設定されていないと空白(whitespace)を破損します。破損の一般的な2つのタイプは以下のとおりです:

* どの空白(whitespace)もない空のコンテキスト行。

* 先頭に1つの余分な空白(whitespace)がある空でないコンテキスト行。

あなたのMUAが正しく設定されているかどうかをテストする方法のひとつは以下のとおりです:

* リストとメンテナのアドレスを含まない To: 行 と Cc: 行 を除き、全く同じ方法で、パッチを自分自身に送信します。

* そのパッチをUNIXメールボックス形式のファイルに保存します。それを a.patch と呼ぶことにしましょう。

* それをapplyします:

    $ git fetch <project> master:test-apply
    $ git switch test-apply
    $ git restore --source=HEAD --staged --worktree :/
    $ git am a.patch

これが正しく適用されない場合、さまざまな理由が考えられます。

* パッチ自体はきれいに適用されません。それは悪いことですが、しかしあなたのMUAとはあまり関係がありません。この場合、パッチを再生成する前に、 linkgit:git-rebase[1] を使用してパッチをリベースすることをお勧めします。

* MUAがあなたのパッチ破損させました。 `am` は、パッチが適用されないと文句を言います。 .git/rebase-apply/ サブディレクトリを調べて、 `patch` ファイルに含まれているものを確認し、上記の一般的な破損パターンを確認します。

* そのとき、 `info` ファイルと `final-commit` ファイルも確認してください。 `final-commit` にあるものが、コミットログメッセージに表示したいものと正確に一致しない場合、パッチを適用するときに受信者がログメッセージを手作業で編集してしまう可能性が非常に高くなります。 パッチの電子メールの "Hi, this is my first patch.\n" のようなものは、コミットメッセージの終わりを示す3本の破線(`---`)の後に来るはずです。

MUA-SPECIFIC HINTS
------------------
さまざまなメーラーを使用してパッチをインラインで正常に送信する方法に関するヒントをいくつか。

GMail
~~~~~
Gmailには、Webインターフェイスでの行の折り返しをオフにする方法がないため、送信するすべての電子メールが破損します。 ただし、 `git send-email` を使用して、GMail SMTPサーバーを介してパッチを送信するか、任意のIMAPメールクライアントを使用してgoogle IMAPサーバーに接続し、それを介してメールを転送することができます。

`git send-email` を使用して GMail SMTP サーバーを介してパッチを送信するためのヒントについては、 linkgit:git-send-email[1] のEXAMPLEセクションを参照してください。

IMAPインターフェースを使用した送信のヒントについては、 linkgit:git-imap-send[1] の EXAMPLE セクションを参照してください。

Thunderbird
~~~~~~~~~~~
デフォルトでは、Thunderbirdはメールの行を折り返す(wrap)だけでなく、 `format=flowed` としてフラグを立てます。このため、結果のメールはGitで使用できなくなります。

3つの異なるアプローチがあります: アドオンを使用して行の折り返し(line wraps)をオフにする、またはパッチを切り刻まないようにThunderbirdを構成する、または外部エディターを使用してThunderbirdがパッチを切り刻まないようにします。

Approach #1 (add-on)
^^^^^^^^^^^^^^^^^^^^

https://addons.thunderbird.net/thunderbird/addon/toggle-line-wrap から入手できる Toggle Line Wrap アドオンをインストールします。これは、 Thunderbirdのメッセージ作成画面(composer)のツールバーに「Line Wrap」ボタンを追加し、 チェックを外せるようにします。これで、他の方法と同じようにメッセージを作成できます(カット＆ペースト、 `git format-patch` | `git imap-send` など)が、 しかし、 自分で入力したテキストには手動で改行を挿入する必要があります。

おまけの機能として、このアドオンはメッセージ作成画面内のパッチテキストを検出し、行の折り返しがまだオフになっていない場合に警告します。

このアドオンを使うには、高度な設定(about:config)をいくつか調整する必要があります。これらはダウンロードページに記載されています。

Approach #2 (configuration)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
3ステップ:

1. メールサーバーの構成をプレーンテキストとして構成します。 [Edit...Account Settings...Composition & Addressing] で、 [Compose Messages in HTML] のチェックを外します(訳注:手元のThunderBird 91.7.0(64ビット)では、メールごとの[アカウント設定...編集とアドレス入力...編集][HTML形式でメッセージを編集する(C)])

2. 行の折返しをしないように、あなたの一般作文ウィンドウ(general composition window)を設定します。
+
Thunderbird 2: [Edit..Preferences..Composition] で、 [wrap plain text messages] を 0 にセットする。
+
Thunderbird 3 : [Edit..Preferences..Advanced..ConfigEditor] で "mail.wrap_long_lines" を検索します。 それをトグルして `false` に設定されていることを確認します。 また、 `mailnews.wraplength` を検索し、値を0に設定します(訳注: ThunderBird 91.7.0(64ビット) 全体の設定...一般...の一番下にある[設定エディター...(C)]ボタン押下して「高度な設定」タブを開く。後は上記と一緒です)

3. format=flowed の使用を無効にします: [Edit..Preferences..Advanced..Config Editor](訳注:上記[設定エディター...(C)]参照) "mailnews.send_plaintext_flowed" を検索します。トグルして `false` に設定されていることを確認します。

これで今後は、あなたは他の方法(カット＆ペーストや `git format-patch | git imap-send` など)で電子メールを作成できるようになり、パッチが破損することはありません。

Approach #3 (external editor)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Thunderbird拡張機能が必要です: AboutConfig( https://mjg.github.io/AboutConfig/ ) と External Editor( https://globs.org/articles.php?lng=en&pg=8 )です。

1. あなたが選択した方法を使用して、パッチをテキストファイルとして準備します。

2. 作文ウィンドウ(compose window)を開く前に、 [Edit...Account] を使用して、パッチの送信に使用するアカウントの[Composition & Addressing]パネルの[Compose messages in HTML format]設定のチェックを外します(訳注:手元のThunderBird 91.7.0(64ビット)では、メールごとの[アカウント設定...編集とアドレス入力...編集][HTML形式でメッセージを編集する(C)])。

3. Thunderbirdのメインウィンドウで、パッチの作成ウィンドウを開く前に、 [Tools]-> [about:config] を使用して、以下を指定された値に設定します(訳注: ThunderBird 91.7.0(64ビット) 設定...一般...の一番下にある[設定エディター...(C)]ボタン押下して「高度な設定」タブを開く):
+
----------
	mailnews.send_plaintext_flowed  => false
	mailnews.wraplength             => 0
----------

4. 作文ウィンドウを開き、外部エディターアイコンをクリックします。

5. 外部エディタウィンドウで、パッチファイルを読み込み、通常どおりエディタを終了します。

補足: aboutconfig と以下の設定を使用して 手順2 を実行できる場合がありますが、まだ誰も試していません。

----------
	mail.html_compose                       => false
	mail.identity.default.compose_html      => false
	mail.identity.id?.compose_html          => false
----------

contrib/thunderbird-patch-inline には、あなたがThunderbirdにパッチを簡単にインクルードするのに役立つスクリプトがあります。これを使用するには、上記の手順を実行してから、スクリプトを外部エディターとして使用します。

KMail
~~~~~
これは、KMailを使用してパッチをインラインで送信するのに役立ちます。

1. パッチをテキストファイルとして準備します。

2. 「New Mail」をクリックします。

3. Composer ウィンドウの [Options] の下に移動し、[Word wrap] が設定されていないことを確認します。

4. Use Message -> Insert file して、パッチを挿入します。

5. 作文ウィンドウに戻ります。メッセージに他のテキストを追加し、アドレス指定フィールドと件名フィールドに入力して、送信を押します。

BASE TREE INFORMATION
---------------------

ベースツリー情報ブロックは、メンテナやサードパーティテスタが、パッチシリーズが適用される正確な状態を知るために使用されます。ベースツリー情報ブロックは、「ベースコミット」（プロジェクトの安定した歴史の一部であり、他のすべての人がそれを元に作業する）と、ゼロ個以上の「前提条件パッチ」(ベースコミットにまだ含まれない、よく知られたパッチで、パッチを適用する前にベースコミットにトポロジカルに追加する必要があります)で構成されています。

「ベースコミット」は、 `base-commit: ` の後にコミットオブジェクト名の40進数が続くものとして表示されます。 `prerequisite patch` は `prerequisite-patch-id: ` の後に40-hexの `patch id` として表示されます。これは、パッチを `git patch-id --stable` コマンドに渡すことで取得できます。

パブリックコミットPに加えて、他の誰かからのよく知られたパッチ X、Y、Z を適用し、3つのパッチシリーズ A、B、C を作成したと想像してください。その履歴は以下のようになります:

................................................
---P---X---Y---Z---A---B---C
................................................

`git format-patch --base=P -3 C` (またはその変形、たとえば `--cover-letter` または `-3C` の代わりに `Z..C` を使用して範囲を指定する)、 ベースツリー情報ブロックは、コマンドが出力する最初のメッセージ(最初のパッチまたはカバーレターのいずれか)の最後に、以下のように表示されます:

------------
base-commit: P
prerequisite-patch-id: X
prerequisite-patch-id: Y
prerequisite-patch-id: Z
------------

以下のようなのような非線形トポロジーの場合

................................................
---P---X---A---M---C
    \         /
     Y---Z---B
................................................

`git format-patch --base=P -3 C` を使用して A、B、C のパッチを生成することもできます。そして P、X、Y、Z の識別子が最初のメッセージの最後に追加されます。

cmdline で `--base=auto` を設定すると、cmdline で指定されたリモート追跡ブランチとリビジョン範囲の先端コミットのマージ・ベースとしてベース・コミットが自動的に計算されます。 ローカルブランチの場合、このオプションを使用する前に、 `gitbranch --set-upstream-to` でリモートブランチを追跡する必要があります。

EXAMPLES
--------

* リビジョンR1とR2の間のコミットを抽出します。そして、 それらをチェリーピックするために `git am` を使用して現在のブランチの先頭にそれらを適用します:
+
------------
$ git format-patch -k --stdout R1..R2 | git am -3 -k
------------

* 現在のブランチにはあるが、元のブランチにはないすべてのコミットを抽出します:
+
------------
$ git format-patch origin
------------
+
コミットごとに、現在のディレクトリに個別のファイルが作成されます。

* プロジェクトの開始以降で `origin` につながるすべてのコミットを抽出します。
+
------------
$ git format-patch --root origin
------------

* 以下は上記と同一です:
+
------------
$ git format-patch -M -B origin
------------
+
さらに、名前変更を検出して処理し、名前変更パッチを生成するためにインテリジェントに書き換えを完了します。 名前の変更パッチは、テキスト出力の量を減らし、一般的にレビューを容易にします。 Git以外の「パッチ」プログラムはパッチの名前変更を理解しないため、受信者がGitを使用してパッチを適用していることがわかっている場合にのみ使用してください。

* 現在のブランチの先頭から3つのコミットを抽出し、それらを電子メールで送信可能なパッチとしてフォーマットします:
+
------------
$ git format-patch -3
------------

CAVEATS
-------

注意: `format-patch`は、要求された範囲の一部であっても、出力からマージコミットを省略します。単純な「パッチ」には、受信側が同じマージコミットを再現するための十分な情報が含まれていません。

SEE ALSO
--------
linkgit:git-am[1], linkgit:git-send-email[1]

GIT
---
Part of the linkgit:git[1] suite
