Gitは、ある程度までは文字エンコードに依存しません。

 - ブロブオブジェクトの内容は、解釈されていないバイトのシーケンスです。コアレベルでのエンコーディング変換はありません。

 - パス名は UTF-8 正規化形式C(UTF-8 normalization form C)でエンコードされます。 これは、 ツリー・オブジェクトと、 インデックス・ファイルと、 参照名と、 コマンドライン引数と、環境変数と、 構成ファイル( `.git/config` (linkgit:git-config[1] 参照)と、 linkgit:gitignore[5] と、 linkgit:gitattributes[5] と、 linkgit:gitmodules[5]) のパス名に、 適用されます。
+
コアレベルのGitは、パス名を単に非NULバイトのシーケンスとして扱い、パス名をエンコードする変換はありません(MacとWindowsを除く)。したがって、非ASCIIパス名の使用は、レガシー拡張ASCIIエンコーディングを使用するプラットフォームやファイルシステムでもほとんど機能します。ただし、そのようなシステムで作成されたリポジトリは、UTF-8ベースのシステム(Linux、Mac、Windowsなど)では正しく機能しません。その逆も同様です。さらに、多くのGitベースのツールは、パス名がUTF-8であると単純に想定しており、他のエンコーディングを正しく表示できません。

 - コミット・ログ・メッセージは通常UTF-8でエンコードされますが、他の拡張ASCIIエンコードもサポートされています。これには、ISO-8859-xやCP125xなどが含まれます。 しかし、 UTF-16/32 や EBCDIC や CJK マルチバイトエンコーディング(GBK、Shift-JIS、Big5、EUC-x、CP9xxなど)は含まれません。

我々はコミットログメッセージをUTF-8でエンコードすることをお勧めしますが、コアとGit Porcelainはどちらも、プロジェクトでUTF-8を強制しないように設計されています。特定のプロジェクトのすべての参加者がレガシーエンコーディングを使用する方が便利だと感じた場合、Gitはそれを禁止しません。 ただし、覚えておくべきことがいくつかあります。

. `git commit` と `git commit-tree` は、 渡されたコミット・ログ・メッセージが正しい UTF-8 文字列に見えない場合に警告を表示します。 ただし、 プロジェクトがレガシーなエンコーディングを使用していることを明示的に宣言している場合は、 この警告を出しません。 その方法とは、 `.git/config` ファイルに `i18n.commitEncoding` を設定することです。 たとえば以下のようにします:
+
------------
[i18n]
	commitEncoding = ISO-8859-1
------------
+
上記の設定で作成されたコミットオブジェクトは、 `encoding` ヘッダーに `i18n.commitEncoding` の値を記録します。 これは、後でそれらを見る他の人々を助けるためです。このヘッダーがないということは、コミットログメッセージがUTF-8でエンコードされていることを意味します。

. `git log` や `git show` や `git blame` とその仲間たちは、 コミット・オブジェクトの `encoding` ヘッダーを見て、 特に指定がない限り、 ログ・メッセージを UTF-8 に再エンコーディングしようとします。 あなたは以下のように、 `.git/config` ファイルの `i18n.logOutputEncoding` を使用して目的の出力エンコーディングを指定できます:
+
------------
[i18n]
	logOutputEncoding = ISO-8859-1
------------
+
この構成変数がない場合は、代わりに `i18n.commitEncoding` の値が使用されます。

注意: UTF-8への再コーディングは必ずしも可逆的な操作ではないため、我々はコミットが行われたときにコミットログメッセージを再コーディングしないことを意図的に選択したことに注意してください。
