PRETTY FORMATS
--------------

マージ・コミットの場合で、 かつ、 pretty-format が `oneline` でも `email` でも `raw` でも無い場合、 `Author:` 行の前に追加で1行が挿入されます。 その行は "Merge: " で始まり、 親コミットのハッシュ値がスペースで区切られて出力されます。 注意: 履歴の表示を制限している場合、 たとえば、 特定のディレクトリまたはファイルに関連する変更のみに関心がある場合、 リストされたコミットは必ずしも「直接」の親のコミットのリストではない可能性があることに注意してください。

いくつかの組み込みフォーマットがあります。そして以下で説明するように、 pretty.<name> 構成オプション(config option)を別のフォーマット名または `format:` 文字列に設定することで、追加のフォーマットを定義できます(linkgit:git-config[1] 参照)。組み込みフォーマットの詳細は以下のとおりです:

* `oneline`

	  <hash> <title-line>
+
これは、可能な限りコンパクトになるように設計されています。

* `short`

	  commit <hash>
	  Author: <author>

	      <title-line>

* `medium`

	  commit <hash>
	  Author: <author>
	  Date:   <author-date>

	      <title-line>

	      <full-commit-message>

* `full`

	  commit <hash>
	  Author: <author>
	  Commit: <committer>

	      <title-line>

	      <full-commit-message>

* `fuller`

	  commit <hash>
	  Author:     <author>
	  AuthorDate: <author-date>
	  Commit:     <committer>
	  CommitDate: <committer-date>

	       <title-line>

	       <full-commit-message>

* `reference`

	  <abbrev-hash> (<title-line>, <short-author-date>)
+
この形式は、 コミット・メッセージ内の別のコミットを参照するために使用され、 ++--pretty=\'format:%C(auto)%h (%s, %ad)'++ と同一です。 デフォルトでは、 別の `--date` オプションが明示的に指定されていない限り、 日付は `--date=short` でフォーマットされます 。format プレースホルダーを使用する他の `format:` と同様に、 その出力は、 `--decorate` や `--walk-reflogs` などの他のオプションの影響を受けません。

* `email`

	  From <hash> <date>
	  From: <author>
	  Date: <author-date>
	  Subject: [PATCH] <title-line>

	  <full-commit-message>

* `mboxrd`
+
`email` と同様ですが、コミットメッセージの "From " で始まる行(前に0個以上の `>` が付いている)は `>` でクォートされているため、新しいコミットの開始と混同されることはありません。

* `raw`
+
`raw` 形式は、 コミット・オブジェクトに格納されているとおりにコミット全体を正確に表示します。 とりわけ `--abbrev` または `--no-abbrev` のどちらが使用されているかに関係なく、 ハッシュは完全に表示され、「親」(parents)情報は、 grafts や履歴の単純化を考慮せずに、 真の親のコミットを示します。 この形式は、 コミットの表示方法に影響しますが、 いわゆる `git log --raw` の diff の表示方法ではありません。 生の diff 形式で完全なオブジェクト名を取得するには、 `--no-abbrev` を使用します。

* `format:<format-string>`
+
`format:<format-string>` 形式を使用すると、表示する情報を指定できます。注意: これはprintf書式に少し似ていますが、 `\n` の代わりに `%n` を使用して改行を取得するという例外に注意してください。
+
例: `format:"The author of %h was %an, %ar%nThe title was >>%s<<%n"` は以下のように表示されます:
+
-------
The author of fe6e0ee was Junio C Hamano, 23 hours ago
The title was >>t4119: test autocomputing -p<n> for traditional diff input.<<

-------
+
さて、以下がプレースホルダー達です:

- 単一のリテラル文字に展開されるプレースホルダー:
++%n++:: 改行(newline)
++%%++:: ++%++ そのもの
++%x00++:: ++%x++ に続く2桁の16進数は、 その値を持つバイト値に置き換えられます(このドキュメントでは、 これを「リテラル書式設定コード」(literal formatting code)と呼びます)。

- 後続のプレースホルダーの書式設定に影響を与えるプレースホルダー達:
++%Cred++:: 赤色に切り替える
++%Cgreen++:: 緑色に切り替える
++%Cblue++:: 青色に切り替える。
++%Creset++:: 色をリセットする
++%C(++_<spec>_++)++:: linkgit:git-config[1] の「CONFIGURATION FILE」の Values で説明されている色の指定。 デフォルトでは、色はログ出力が有効になっている場合にのみ表示されます(`color.diff` または `color.ui` または `--color` によって、ターミナルに出す場合は前者の `auto` 設定を尊重します)。 ++%C(auto,++_<spec>_++)++ は、 `default` の歴史的同義語として受け入れられます(例: ++%C(auto,red)++)。 ++%C(always,++_<spec>_++)++ を指定すると、 色が有効になってい無い場合でも色が表示されます(この形式やgitが色付けする可能性のある他のすべてのものを含め、出力全体の色を有効にするために `--color=always` の使用を検討してください)。 `auto` のみ(つまり、 ++%C(auto)++)は、色が再び切り替えられるまで、これに続くプレースホルダーで自動色付けをオンにします。
++%m++:: 左(`<`) または 右(`>`) または 境界 (`-`) の印
++%w(++`[<w>[,<i1>[,<i2>]]]`++)++:: linkgit:git-shortlog[1] の -w オプションのように、行の折返しを切り替えます。
++%<(++`<n>[,(trunc|ltrunc|mtrunc)]`++)++:: これは次のプレースホルダーに対して、 少なくとも N 桁幅を確保します。 必要に応じて右側に空白でパディングします。 オプションで、 出力が _<n>_
桁を超える場合には切り捨て(truncate)を行えます(ここで、 切り捨ての印は `..`)。 左側を切り捨て(ltrunc) は ++..ft++
、 中央切り捨て(mtrunc) は ++mi..le++ 、 末尾切り捨て(trunc) は ++rig..++ です。 注意1: 切り捨ては
_<n>_ >= 2 の場合にのみ正しく機能します。 注意2: _<n>_ 値と _<m>_ 値(下記参照)の前後の空白はオプションです。 注意3:
絵文字やその他のワイド・キャラクタは表示桁を2つ必要とするため、 桁の境界を超える可能性があります。 注意4: 複合文字マーク(character
combining marks)が詰物境界で誤って分割配置される可能性があります。
++%<|(++_<m>_ ++)++:: これの次のプレースホルダーが少なくとも _<m>_ 桁目の表示桁までを占めるようにし、必要に応じて右側に空白を詰めます。 端末ウィンドウの右端から測定した桁位置には、負の _<m>_ 値を使用して下さい。
++%>(++_<n>_++)++::
++%>|(++_<m>_++)++:: それぞれ ++%<(++_<n>_++)++ や ++%<|(++_<m>_++)++ に似ていますが、左側に空白が埋め込まれます
++%>>(++_<n>_++)++::
++%>>|(++_<m>_++)++:: それぞれ ++%>(++_<n>_++)++ や ++%>|(++_<m>_++)++ に似ていますが、 これに続くプレースホルダーが指定よりも多くの空白を使用し、その左側に空白がある場合は、それらの空白を使用します
++%><(++_<n>_++)++::
++%><|(++_<m>_++)++:: それぞれ ++%<(++_<n>_++)++ や ++%<|(++_<m>_++)++ に似ていますが、 両側にパディングがあります(つまり、 テキストが中央に配置されます)

- コミットから抽出された情報に展開するプレースホルダー:
+%H+:: コミットハッシュ
+%h+:: 省略されたコミットハッシュ
+%T+:: ツリーハッシュ
+%t+:: 省略されたツリーハッシュ
+%P+:: 親のハッシュ達
+%p+:: 省略された親のハッシュ達
+%an+:: 作者名
+%aN+:: 作者名( .mailmap に関しては、 linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%ae+:: 作者電子メールアドレス
+%aE+:: 作者電子メールアドレス( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%al+:: 作者の電子メール・アカウント名(local-part)(`@` の前の部分)
+%aL+:: 作者の電子メール・アカウント名(+%al+ 参照)( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%ad+:: 作成日(フォーマットに関しては `--date=` オプション参照)
+%aD+:: 作成日 RFC2822形式
+%ar+:: 作成日 相対(relative)形式
+%at+:: 作成日 UNIXタイムスタンプ形式
+%ai+:: 作成日 ISO 8601風形式
+%aI+:: 作成日 厳密なISO 8601形式
+%as+:: 作成日 短い形式(`YYYY-MM-DD`)
+%ah+:: 作者作成日(author date)の人間が読める形式(human style)(linkgit:git-rev-list[1] の `--date=human` に似ている)
+%cn+:: コミッター名
+%cN+:: コミッター名( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%ce+:: コミッター電子メールアドレス
+%cE+:: コミッター電子メールアドレス( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%cl+:: コミッター電子メール・アカウント名(local-part)( `@` の前の部分)
+%cL+:: コミッターの電子メール・アカウント名(local-part)(+%cl+ 参照)。 `.mailmap` を考慮します。 詳細は linkgit:git-shortlog[1] または linkgit:git-blame[1] を参照。
+%cd+:: コミッター日付(フォーマットに関しては `--date=` オプション参照)
+%cD+:: コミッター日付 RFC2822形式
+%cr+:: コミッター日付 相対(relative)形式
+%ct+:: コミッター日付 UNIXタイムスタンプ形式
+%ci+:: コミッター日付 ISO 8601風形式
+%cI+:: コミッター日付 厳密なISO 8601形式
+%cs+:: コミッター日付 短い形式(`YYYY-MM-DD`)
+%ch+:: コミッター日付 人間が読める形式(linkgit:git-rev-list[1] の `--date=human` に似ている)
+%d+:: 参照名。 linkgit:git-log[1] の `--decorate` オプションみたいなの
+%D+:: " (", ")" で囲ってない参照名
++%(decorate++`[:<option>,...]`++)++::
カスタム装飾が施された参照名。 `decorate` 文字列の後には、 コロン(":")と 0 個以上のカンマ(",")区切りのオプション達が続く場合があります。 オプション値にカンマ(",")や閉じ丸括弧(")")自体を含める場合は、 それぞれリテラル書式設定コードの `%x2C` (コンマ)や `%x29` (閉じ丸括弧) を使用する必要があります。

** `prefix=<value>`: 参照名のリストの前に表示されます。 デフォルトは "{nbsp}++(++" です。
** `suffix=<value>`: 参照名のリストの後に表示されます。 デフォルトは "+)+" です。
** `separator=<value>`: 参照名と参照名の間に表示されます。 デフォルトは "+,+{nbsp}" です。
** `pointer=<value>`: (存在する場合、) HEAD とそれが指すブランチの間に表示されます。
		      デフォルトは "{nbsp}&#45;&#62;{nbsp}" です。
** `tag=<value>`: タグ名の前に表示されます。 デフォルトは "`tag:`{nbsp}" です。

+
--
たとえば、 行ラッピングやタグ注釈を使用せず、 区切り文字としてスペースを使用して装飾を作成するには、 以下のようにします:

++%(decorate:prefix=,suffix=,tag=,separator= )++
--

++%(describe++`[:<option>,...]`++)++::
linkgit:git-describe[1] のような人間が読める名前。説明できないコミットの場合は空の文字列。 `describe` 文字列の後には、コロンと、0個以上のカンマで区切られたオプションを続けることができます。タグの追加や削除を同時に行うと、説明に一貫性がなくなる可能性があります。
+
** `tags[=<bool-value>]`: 注釈付きタグ(annotated tags)だけを考慮するのではなく、 軽量タグ(lightweight tags)も考慮してください。
** `abbrev=<number>`: 短縮ブジェクト名のデフォルトの16進数の桁数(デフォルトは 7 で、リポジトリ内のオブジェクトの数によって異なります)を使用する代わりに、 <number> 桁数を指定するか、または一意のオブジェクト名を形成するために必要な桁数。
** `match=<pattern>`: `refs/tags/` プレフィックスを除いて、 指定の `glob(7)` パターン(_<pattern>_)にマッチするタグのみを考慮します。
** `exclude=<pattern>`: `refs/tags/` プレフィックスを除いて、 指定の `glob(7)` パターン(_<pattern>_)にマッチするタグを対象外にします。

+%S+:: (`git log --source` のような、)コマンドラインで指定した、コミットに到達した参照名で、 `git log` でのみ機能します。
+%e+:: エンコーディング
+%s+:: 件名(subject)
+%f+:: ファイル名に適した、サニタイズされた件名
+%b+:: 本文(body)
+%B+:: 生本文(raw body)(行折り曲げされてない件名と本文)
ifndef::git-rev-list[]
+%N+:: コミットノート(commit notes)
endif::git-rev-list[]
+%GG+:: 署名されたコミットの為のGPGからの生の検証メッセージ
+%G?+:: 有効な署名には「G」、不正な署名には「B」、有効だが信頼性が不明な署名には「U」、有効だが期限切れの署名には「X」、期限切れの鍵で作られた有効な署名には「Y」、失効した鍵で作られた有効な署名には「R」、署名を確認できない場合（例：鍵がない）には「E」、署名がない場合には「N」を表示します。
+%GS+:: 署名されたコミットの署名者の名前を表示する
+%GK+:: 署名されたコミットに署名するために使用されるキーを表示する
+%GF+:: 署名されたコミットに署名するために使用されるキーのフィンガープリントを表示する
+%GP+:: 署名付きコミットの署名に使用されたサブキー(subkey)の主キー(primary key)のフィンガープリントを表示します
+%GT+:: 署名されたコミットに署名するために使用されるキーの信頼レベル(trust level)を表示します
+%gD+:: reflog セレクター(例えば `refs/stash@{1}` とか `refs/stash@{2 minutes ago}`)。 この形式は、 `-g` オプションで説明されている規則に従います。 `@` の前の部分は、コマンドラインで指定された参照名です(したがって、 `git log -g refs/heads/master` は `refs/heads/master@{0}` を生成します)。
+%gd+:: 短縮 reflog セレクター。 `%gD` と同一ですが、人間が読みやすい形式でrefname部分が短縮されています(したがって、 `refs/heads/master` は単に `master` になります)。
+%gn+:: reflog ID名
+%gN+:: reflog ID名( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%ge+:: reflog ID 電子メールアドレス
+%gE+:: reflog ID 電子メールアドレス( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%gs+:: reflog 件名
++%(trailers++`[:<option>,...]`++)++::
linkgit:git-interpret-trailers[1] によって解釈されるように本文(body)のトレーラーを表示します。 `trailers` 文字列の後には、コロンと、0個以上のカンマで区切られたオプションを続けることができます。いずれかのオプションが複数回提供された場合、それぞれ最後のものが優先されます。
+
** `key=<key>`: 指定の <key> を持つトレーラーのみを表示します。 マッチングは大文字と小文字を区別せずに行われ、 末尾のコロンはオプションです。 オプションが複数回指定されている場合、 それらのいずれかのキーに一致するトレーラー行が表示されます。 このオプションは自動的に `only` オプションを有効にして、 トレーラー・ブロック内の非トレーラー行が非表示になるようにします。 それが望ましくない場合は、 `only=false` で無効にすることができます。 たとえば、 +%(trailers:key=Reviewed-by)+ は、キーが `Reviewed-by` のトレーラー行を表示します。
** `only[=<bool>]`: トレーラー・ブロックに非トレーラー行を含めるかどうかを選択します。
** `separator=<sep>`: トレーラー行の間に挿入される区切り文字を指定します。 デフォルトはLFです。 文字列 <sep> には、上記のリテラル書式設定コードが含まれる場合があります。区切り文字としてコンマ(",")を使用するには、次のオプションとして解析されないよう `%x2C` を使用する必要があります。 たとえば、 +%(trailers:key=Ticket,separator=%x2C )+ は、キーが `Ticket` であるすべてのトレーラー行をカンマと「スペース」で区切って表示します。
** `unfold[=<bool>]`: interpret-trailer の `--unfold`
   オプションが指定されたかのように動作させます。たとえば、 +%(trailers:only,unfold=true)+
   が展開され、すべてのトレーラー行が表示されます。
** `keyonly[=<bool>]`: トレーラーのキー部分のみを表示。
** `valueonly[=<bool>]`: トレーラーの値部分のみ表示。
** `key_value_separator=<sep>`: 各トレーラーの、 キーと値の間に挿入される区切り文字を指定します。 デフォルトは ": " です。 それ以外の場合は、上記の `separator=<sep>` と同じセマンティクスを共有します。

NOTE: 一部のプレースホルダーは、 リビジョン・トラバーサル・エンジンに指定された他のオプションに依存する場合があります。 たとえば、 +%g*+
reflogオプションは、 reflogエントリをトラバースしない限り(たとえば、 `git log -g`
によって)空の文字列を挿入します。コマンドラインで `--decorate` がまだ指定されていない場合、 +%d+ と +%D+
プレースホルダーは「短い」(short)装飾形式を使用します。

ブール値のオプションは、 オプションで `[=<bool-value>]` という形で値を受け取ることができます。 `--type=bool` で受け入れられる値(linkgit:git-config[1] 参照)は、 `yes` や `off` など全てが受け入れられます。 ブール値オプションに `=<value>` を付けずに指定した場合、 それは `=true` を指定したのと同等です。

プレースホルダーの +%+ の後に `+` (プラス記号)を追加すると、プレースホルダーが空でない文字列に展開される場合に限り、展開の直前に改行が挿入されます。

プレースホルダーの +%+ の後に `-` (マイナス記号)を追加すると、プレースホルダーが空の文字列に展開された場合にのみ、展開の直前の連続するすべての改行が削除されます。

プレースホルダーの +%+ の後に `' '` (空白1つ)を追加すると、プレースホルダーが空でない文字列に展開される場合に限り、展開の直前にスペースが挿入されます。

* `tformat:`
+
`tformat:` 形式は、 "separator" セマンティクスの代わりに "terminator" セマンティクスを提供することを除いて、 `format:` とまったく同じように機能します。 つまり、各コミットには、エントリ間に区切り文字を配置するのではなく、メッセージターミネータ文字(通常は改行)が追加されます。 これは、「1行」形式と同様に、1行形式の最終エントリが新しい行で適切に終了することを意味します。 例えば以下のようになります:
+
---------------------
$ git log -2 --pretty=format:%h 4da45bef \
  | perl -pe '$_ .= " -- NO NEWLINE\n" unless /\n/'
4da45be
7134973 -- NO NEWLINE

$ git log -2 --pretty=tformat:%h 4da45bef \
  | perl -pe '$_ .= " -- NO NEWLINE\n" unless /\n/'
4da45be
7134973
---------------------
+
さらに、 +%+ を含む認識されない文字列は、 その前に `tformat:` があるかのように解釈(interpret)されます。 たとえば、以下の2つは同等です:
+
---------------------
$ git log -2 --pretty=tformat:%h 4da45bef
$ git log -2 --pretty=%h 4da45bef
---------------------
