PRETTY FORMATS
--------------

If the commit is a merge, and if the pretty-format is not `oneline`, `email` or `raw`, an additional line is inserted before the `Author:` line. This line begins with "Merge: " and the hashes of ancestral commits are printed, separated by spaces. Note that the listed commits may not necessarily be the list of the 'direct' parent commits if you have limited your view of history: for example, if you are only interested in changes related to a certain directory or file.

There are several built-in formats, and you can define additional formats by setting a pretty.<name> config option to either another format name, or a `format:` string, as described below (see linkgit:git-config[1]). Here are the details of the built-in formats:

* `oneline`

	  <hash> <title-line>
+
これは、可能な限りコンパクトになるように設計されています。

* `short`

	  commit <hash>
	  Author: <author>

	      <title-line>

* `medium`

	  commit <hash>
	  Author: <author>
	  Date:   <author-date>

	      <title-line>

	      <full-commit-message>

* `full`

	  commit <hash>
	  Author: <author>
	  Commit: <committer>

	      <title-line>

	      <full-commit-message>

* `fuller`

	  commit <hash>
	  Author:     <author>
	  AuthorDate: <author-date>
	  Commit:     <committer>
	  CommitDate: <committer-date>

	       <title-line>

	       <full-commit-message>

* `reference`

	  <abbrev-hash> (<title-line>, <short-author-date>)
+
This format is used to refer to another commit in a commit message and is the same as ++--pretty=\'format:%C(auto)%h (%s, %ad)'++. By default, the date is formatted with `--date=short` unless another `--date` option is explicitly specified. As with any `format:` with format placeholders, its output is not affected by other options like `--decorate` and `--walk-reflogs`.

* `email`

	  From <hash> <date>
	  From: <author>
	  Date: <author-date>
	  Subject: [PATCH] <title-line>

	  <full-commit-message>

* `mboxrd`
+
Like `email`, but lines in the commit message starting with "From " (preceded by zero or more ">") are quoted with ">" so they aren't confused as starting a new commit.

* `raw`
+
The `raw` format shows the entire commit exactly as stored in the commit object. Notably, the hashes are displayed in full, regardless of whether `--abbrev` or `--no-abbrev` are used, and 'parents' information show the true parent commits, without taking grafts or history simplification into account. Note that this format affects the way commits are displayed, but not the way the diff is shown e.g. with `git log --raw`. To get full object names in a raw diff format, use `--no-abbrev`.

* `format:<format-string>`
+
The `format:<format-string>` format allows you to specify which information you want to show. It works a little bit like printf format, with the notable exception that you get a newline with `%n` instead of `\n`.
+
例: `format:"The author of %h was %an, %ar%nThe title was >>%s<<%n"` は以下のように表示されます:
+
-------
The author of fe6e0ee was Junio C Hamano, 23 hours ago
The title was >>t4119: test autocomputing -p<n> for traditional diff input.<<

-------
+
さて、以下がプレースホルダー達です:

- 単一のリテラル文字に展開されるプレースホルダー:
++%n++:: 改行(newline)
++%%++:: a raw ++%++
++%x00++:: ++%x++ followed by two hexadecimal digits is replaced with a byte with the hexadecimal digits' value (we will call this "literal formatting code" in the rest of this document).

- 後続のプレースホルダーの書式設定に影響を与えるプレースホルダー達:
++%Cred++:: 赤色に切り替える
++%Cgreen++:: 緑色に切り替える
++%Cblue++:: 青色に切り替える。
++%Creset++:: 色をリセットする
++%C(++_<spec>_++)++:: color specification, as described under Values in the "CONFIGURATION FILE"
section of linkgit:git-config[1].  By default, colors are shown only when
enabled for log output (by `color.diff`, `color.ui`, or `--color`, and
respecting the `auto` settings of the former if we are going to a
terminal). ++%C(auto,++_<spec>_++)++ is accepted as a historical synonym for
the default (e.g., ++%C(auto,red)++). Specifying ++%C(always,++_<spec>_++)++
will show the colors even when color is not otherwise enabled (though
consider just using `--color=always` to enable color for the whole output,
including this format and anything else git might color).  `auto` alone
(i.e. ++%C(auto)++) will turn on auto coloring on the next placeholders
until the color is switched again.
++%m++:: 左(`<`) または 右(`>`) または 境界 (`-`) の印
++%w(++`[<w>[,<i1>[,<i2>]]]`++)++:: switch line wrapping, like the `-w` option of linkgit:git-shortlog[1].
++%<(++`<n>[,(trunc|ltrunc|mtrunc)]`++)++:: make the next placeholder take at least N column widths, padding spaces on the right if necessary. Optionally truncate (with ellipsis `..`) at the left (ltrunc) `..ft`, the middle (mtrunc) `mi..le`, or the end (trunc) `rig..`, if the output is longer than _<n>_ columns. Note 1: that truncating only works correctly with _<n>_ >= 2. Note 2: spaces around the _<n>_ and _<m>_ (see below) values are optional. Note 3: Emojis and other wide characters will take two display columns, which may over-run column boundaries. Note 4: decomposed character combining marks may be misplaced at padding boundaries.
++%<|(++_<m>_ ++)++:: make the next placeholder take at least until _<m>_ th display column, padding spaces on the right if necessary. Use negative _<m>_ values for column positions measured from the right hand edge of the terminal window.
++%>(++_<n>_++)++::
++%>|(++_<m>_++)++:: similar to ++%<(++_<n>_++)++, ++%<|(++_<m>_++)++ respectively, but padding spaces on the left
++%>>(++_<n>_++)++::
++%>>|(++_<m>_++)++:: similar to ++%>(++_<n>_++)++, ++%>|(++_<m>_++)++ respectively, except that if the next placeholder takes more spaces than given and there are spaces on its left, use those spaces
++%><(++_<n>_++)++::
++%><|(++_<m>_++)++:: similar to ++%<(++_<n>_++)++, ++%<|(++_<m>_++)++ respectively, but padding both sides (i.e. the text is centered)

- コミットから抽出された情報に展開するプレースホルダー:
+%H+:: コミットハッシュ
+%h+:: 省略されたコミットハッシュ
+%T+:: ツリーハッシュ
+%t+:: 省略されたツリーハッシュ
+%P+:: 親のハッシュ達
+%p+:: 省略された親のハッシュ達
+%an+:: 作者名
+%aN+:: 作者名( .mailmap に関しては、 linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%ae+:: 作者電子メールアドレス
+%aE+:: 作者電子メールアドレス( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%al+:: author email local-part (the part before the `@` sign)
+%aL+:: author local-part (see +%al+) respecting .mailmap, see linkgit:git-shortlog[1] or linkgit:git-blame[1])
+%ad+:: 作成日(フォーマットに関しては `--date=` オプション参照)
+%aD+:: 作成日 RFC2822形式
+%ar+:: 作成日 相対(relative)形式
+%at+:: 作成日 UNIXタイムスタンプ形式
+%ai+:: 作成日 ISO 8601風形式
+%aI+:: 作成日 厳密なISO 8601形式
+%as+:: 作成日 短い形式(`YYYY-MM-DD`)
+%ah+:: 作者作成日(author date)の人間が読める形式(human style)(linkgit:git-rev-list[1] の `--date=human` に似ている)
+%cn+:: コミッター名
+%cN+:: コミッター名( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%ce+:: コミッター電子メールアドレス
+%cE+:: コミッター電子メールアドレス( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%cl+:: committer email local-part (the part before the `@` sign)
+%cL+:: committer local-part (see +%cl+) respecting .mailmap, see linkgit:git-shortlog[1] or linkgit:git-blame[1])
+%cd+:: コミッター日付(フォーマットに関しては `--date=` オプション参照)
+%cD+:: コミッター日付 RFC2822形式
+%cr+:: コミッター日付 相対(relative)形式
+%ct+:: コミッター日付 UNIXタイムスタンプ形式
+%ci+:: コミッター日付 ISO 8601風形式
+%cI+:: コミッター日付 厳密なISO 8601形式
+%cs+:: コミッター日付 短い形式(`YYYY-MM-DD`)
+%ch+:: コミッター日付 人間が読める形式(linkgit:git-rev-list[1] の `--date=human` に似ている)
+%d+:: ref名 linkgit:git-log[1] の `--decorate` オプションみたいなの
+%D+:: " (", ")" で囲ってないref名
++%(decorate++`[:<option>,...]`++)++::
カスタム装飾が施された ref 名。 `decorate` 文字列の後には、 コロン(":")と 0 個以上のカンマ(",")区切りのオプション達が続く場合があります。 オプション値にカンマ(",")や閉じ丸括弧(")")自体を含める場合は、 それぞれリテラル書式設定コードの `%x2C` (コンマ)や `%x29` (閉じ丸括弧) を使用する必要があります。

** `prefix=<value>`: Shown before the list of ref names. Defaults to "{nbsp}++(++".
** `suffix=<value>`: Shown after the list of ref names. Defaults to "+)+".
** `separator=<value>`: Shown between ref names. Defaults to "+,+{nbsp}".
** `pointer=<value>`: Shown between HEAD and the branch it points to, if any.
		      Defaults to "{nbsp}++->++{nbsp}".
** `tag=<value>`: Shown before tag names. Defaults to "`tag:`{nbsp}".

+
--
たとえば、 行ラッピングやタグ注釈を使用せず、 区切り文字としてスペースを使用して装飾を作成するには、 以下のようにします:

++%(decorate:prefix=,suffix=,tag=,separator= )++
--

++%(describe++`[:<option>,...]`++)++::
linkgit:git-describe[1] のような人間が読める名前。説明できないコミットの場合は空の文字列。 `describe` 文字列の後には、コロンと、0個以上のカンマで区切られたオプションを続けることができます。タグの追加や削除を同時に行うと、説明に一貫性がなくなる可能性があります。
+
** `tags[=<bool-value>]`: Instead of only considering annotated tags, consider lightweight tags as well.
** `abbrev=<number>`: Instead of using the default number of hexadecimal digits (which will vary according to the number of objects in the repository with a default of 7) of the abbreviated object name, use <number> digits, or as many digits as needed to form a unique object name.
** `match=<pattern>`: Only consider tags matching the given `glob(7)` _<pattern>_, excluding the `refs/tags/` prefix.
** `exclude=<pattern>`: Do not consider tags matching the given `glob(7)` _<pattern>_, excluding the `refs/tags/` prefix.

+%S+:: (`git log --source` のような、)コマンドラインで指定した、コミットに到達したref名で、 `git log` でのみ機能します。
+%e+:: エンコーディング
+%s+:: 件名(subject)
+%f+:: ファイル名に適した、サニタイズされた件名
+%b+:: 本文(body)
+%B+:: 生本文(raw body)(行折り曲げされてない件名と本文)
ifndef::git-rev-list[]
+%N+:: コミットノート(commit notes)
endif::git-rev-list[]
+%GG+:: 署名されたコミットの為のGPGからの生の検証メッセージ
+%G?+:: show "G" for a good (valid) signature, "B" for a bad signature, "U" for a good signature with unknown validity, "X" for a good signature that has expired, "Y" for a good signature made by an expired key, "R" for a good signature made by a revoked key, "E" if the signature cannot be checked (e.g. missing key) and "N" for no signature
+%GS+:: 署名されたコミットの署名者の名前を表示する
+%GK+:: 署名されたコミットに署名するために使用されるキーを表示する
+%GF+:: 署名されたコミットに署名するために使用されるキーのフィンガープリントを表示する
+%GP+:: 署名付きコミットの署名に使用されたサブキー(subkey)の主キー(primary key)のフィンガープリントを表示します
+%GT+:: 署名されたコミットに署名するために使用されるキーの信頼レベル(trust level)を表示します
+%gD+:: reflog セレクター(例えば `refs/stash@{1}` とか `refs/stash@{2 minutes ago}`)。 この形式は、 `-g` オプションで説明されている規則に従います。 `@` の前の部分は、コマンドラインで指定されたrefnameです(したがって、 `git log -g refs/heads/master` は `refs/heads/master@{0}` を生成します)。
+%gd+:: 短縮 reflog セレクター。 `%gD` と同一ですが、人間が読みやすい形式でrefname部分が短縮されています(したがって、 `refs/heads/master` は単に `master` になります)。
+%gn+:: reflog ID名
+%gN+:: reflog ID名( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%ge+:: reflog ID 電子メールアドレス
+%gE+:: reflog ID 電子メールアドレス( .mailmap に関しては、linkgit:git-shortlog[1] または linkgit:git-blame[1] 参照)
+%gs+:: reflog 件名
++%(trailers++`[:<option>,...]`++)++::
linkgit:git-interpret-trailers[1] によって解釈されるように本文(body)のトレーラーを表示します。 `trailers` 文字列の後には、コロンと、0個以上のカンマで区切られたオプションを続けることができます。いずれかのオプションが複数回提供された場合、それぞれ最後のものが優先されます。
+
** `key=<key>`: only show trailers with specified <key>. Matching is done case-insensitively and trailing colon is optional. If option is given multiple times trailer lines matching any of the keys are shown. This option automatically enables the `only` option so that non-trailer lines in the trailer block are hidden. If that is not desired it can be disabled with `only=false`. E.g., +%(trailers:key=Reviewed-by)+ shows trailer lines with key `Reviewed-by`.
** `only[=<bool>]`: select whether non-trailer lines from the trailer block should be included.
** `separator=<sep>`: specify the separator inserted between trailer lines. Defaults to a line feed character. The string <sep> may contain the literal formatting codes described above. To use comma as separator one must use `%x2C` as it would otherwise be parsed as next option. E.g., +%(trailers:key=Ticket,separator=%x2C )+ shows all trailer lines whose key is "Ticket" separated by a comma and a space.
** `unfold[=<bool>]`: make it behave as if interpret-trailer's `--unfold` option was given. E.g., +%(trailers:only,unfold=true)+ unfolds and shows all trailer lines.
** `keyonly[=<bool>]`: only show the key part of the trailer.
** `valueonly[=<bool>]`: only show the value part of the trailer.
** `key_value_separator=<sep>`: specify the separator inserted between the key and value of each trailer. Defaults to ": ". Otherwise it shares the same semantics as `separator=<sep>` above.

NOTE: Some placeholders may depend on other options given to the revision traversal engine. For example, the +%g*+ reflog options will insert an empty string unless we are traversing reflog entries (e.g., by `git log -g`). The +%d+ and +%D+ placeholders will use the "short" decoration format if `--decorate` was not already provided on the command line.

The boolean options accept an optional value `[=<bool-value>]`. The values taken by `--type=bool` linkgit:git-config[1], like `yes` and `off`, are all accepted. Giving a boolean option without `=<value>` is equivalent to giving it with `=true`.

If you add a `+` (plus sign) after +%+ of a placeholder, a line-feed is inserted immediately before the expansion if and only if the placeholder expands to a non-empty string.

If you add a `-` (minus sign) after +%+ of a placeholder, all consecutive line-feeds immediately preceding the expansion are deleted if and only if the placeholder expands to an empty string.

If you add a `' '` (space) after +%+ of a placeholder, a space is inserted immediately before the expansion if and only if the placeholder expands to a non-empty string.

* `tformat:`
+
The `tformat:` format works exactly like `format:`, except that it provides "terminator" semantics instead of "separator" semantics. In other words, each commit has the message terminator character (usually a newline) appended, rather than a separator placed between entries. This means that the final entry of a single-line format will be properly terminated with a new line, just as the "oneline" format does. For example:
+
---------------------
$ git log -2 --pretty=format:%h 4da45bef \
  | perl -pe '$_ .= " -- NO NEWLINE\n" unless /\n/'
4da45be
7134973 -- NO NEWLINE

$ git log -2 --pretty=tformat:%h 4da45bef \
  | perl -pe '$_ .= " -- NO NEWLINE\n" unless /\n/'
4da45be
7134973
---------------------
+
In addition, any unrecognized string that has a +%+ in it is interpreted as if it has `tformat:` in front of it. For example, these two are equivalent:
+
---------------------
$ git log -2 --pretty=tformat:%h 4da45bef
$ git log -2 --pretty=%h 4da45bef
---------------------
