Commit Limiting
~~~~~~~~~~~~~~~

ここで説明されている特別な表記法を使用してリストする必要があるコミットの範囲を指定することに加えて、追加のコミット制限が適用される場合があります。

Using more options generally further limits the output (e.g. `--since=<date1>` limits to commits newer than _<date1>_, and using it with `--grep=<pattern>` further limits to commits whose log message has a line that matches _<pattern>_), unless otherwise noted.

注意: これらは、 `--reverse` などのコミット順序およびフォーマットオプションの前に適用されることに注意してください。

+-<number>+::
+-n <number>+::
+--max-count=<number>+::
	Limit the output to _<number>_ commits.

+--skip=<number>+::
	Skip _<number>_ commits before starting to show the commit output.

--since=<date>::
+--after=<date>+::
	Show commits more recent than _<date>_.

+--since-as-filter=<date>+::
	Show all commits more recent than _<date>_. This visits all commits in the range, rather than stopping at the first commit which is older than _<date>_.

+--until=<date>+::
+--before=<date>+::
	Show commits older than _<date>_.

ifdef::git-rev-list[]
+--max-age=<timestamp>+::
+--min-age=<timestamp>+::
	コミット出力を指定された時間範囲に制限します。
endif::git-rev-list[]

+--author=<pattern>+::
+--committer=<pattern>+::
	Limit the commits output to ones with author/committer header lines that match the _<pattern>_ regular expression. With more than one `--author=<pattern>`, commits whose author matches any of the _<pattern>_ are chosen (similarly for multiple `--committer=<pattern>`).

+--grep-reflog=<pattern>+::
	Limit the commits output to ones with reflog entries that match the _<pattern>_ regular expression. With more than one `--grep-reflog`, commits whose reflog message matches any of the given patterns are chosen. It is an error to use this option unless `--walk-reflogs` is in use.

+--grep=<pattern>+::
	Limit the commits output to ones with a log message that matches the _<pattern>_ regular expression. With more than one `--grep=<pattern>`, commits whose message matches any of the _<pattern>_ are chosen (but see `--all-match`).
ifndef::git-rev-list[]
+
`--notes` が有効な場合、ノートからのメッセージは、ログメッセージの一部であるかのようにマッチングされます。
endif::git-rev-list[]

`--all-match`::
	コミット出力を、少なくとも1つに一致するものではなく、指定されたすべての `--grep` に一致するものに制限します。

`--invert-grep`::
	Limit the commits output to ones with a log message that do not match the _<pattern>_ specified with `--grep=<pattern>`.

`-i`::
`--regexp-ignore-case`::
	大文字小文字に関係なく、正規表現の制限パターンに一致します。

`--basic-regexp`::
	制限パターンを基本正規表現として扱います。これがデフォルトです。

`-E`::
`--extended-regexp`::
	制限パターンを、デフォルトの基本正規表現の代わりに拡張正規表現として扱います。

`-F`::
`--fixed-strings`::
	制限パターンを固定文字列として扱います(パターンを正規表現として解釈しないでください)。

`-P`::
`--perl-regexp`::
	制限パターンをPerl互換の正規表現として扱います。
+
これらのタイプの正規表現のサポートは、コンパイル時オプションに依存します。Gitが当該のサポート付きでコンパイルされていない場合、このオプションを使うと、Gitが終了(die)します。

`--remove-empty`::
	指定されたパスがツリーから見えなくなったら停止(stop)します。

`--merges`::
	マージコミットのみを出力します。これは `--min-parents=2` とまったく同じです。

`--no-merges`::
	複数の親を持つコミットを出力しない。これは `--max-parents=1` とまったく同じです。

+--min-parents=<number>+::
+--max-parents=<number>+::
`--no-min-parents`::
`--no-max-parents`::
	量の多少に関わらず、 とにかく複数の親コミットがあるコミットのみを表示します。特に、 `--max-parents=1` は `--no-merges` と同じであり、 `--min-parents=2` は `--merges` と同じです。 `--max-parents=0` はすべてのルートコミットを提供し、 `--min-parents=3` はすべてのタコ足マージ(octopus merges)を示します。
+
`--no-min-parents` と `--no-max-parents` は、これらの制限を(制限なしに)再度リセットします。同等の形式は、 `--min-parents=0` (すべてのコミットに0個以上の親があります)および `--max-parents=-1` (マイナスの数は上限がないことを示します)です。

`--first-parent`::
	インクルードするコミットを探すとき、マージ・コミットの最初の親コミットのみをたどります。 このオプションは、特定のトピックブランチの進化を表示するときに、より良い概要を提供できます。トピックブランチへのマージは、時々更新されるアップストリームに調整することだけである傾向があり、このオプションを使用すると、そのようなマージによって履歴に取り込まれた個々のコミットを無視できます。
ifdef::git-log[]
+
このオプションは、マージコミットのデフォルトのdiff形式も `first-parent` に変更します。詳細については、 `--diff-merges=first-parent` を参照してください。
endif::git-log[]

`--exclude-first-parent-only`::
	( `^` を使用して)除外するコミットを見つけるときは、 判明したマージ・コミットの最初の親コミットのみに従います。 任意のマージが有効なトピック・ブランチの変更になる可能性がある場合、 これを使用して、 リモート・ブランチから分岐したポイントからトピック・ブランチ内の一連の変更を見つけることができます。

`--not`::
	次の `--not` までの後続のすべてのリビジョン指定子について、 {caret} プレフィックス(またはその欠落)の意味を反転します。 コマンドラインで `--stdin` より前で使用すると、 stdin を介して渡されたリビジョンは影響を受けません。 逆に、 標準入力経由で渡された場合、 コマンドラインで渡されたリビジョンは影響を受けません。

`--all`::
	Pretend as if all the refs in `refs/`, along with `HEAD`, are listed on the command line as _<commit>_.

+--branches[=<pattern>]+::
	Pretend as if all the refs in `refs/heads` are listed on the command line as _<commit>_. If _<pattern>_ is given, limit branches to ones matching given shell glob. If _<pattern>_ lacks '?', '{asterisk}', or '[', '/{asterisk}' at the end is implied.

+--tags[=<pattern>]+::
	Pretend as if all the refs in `refs/tags` are listed on the command line as _<commit>_. If _<pattern>_ is given, limit tags to ones matching given shell glob. If pattern lacks '?', '{asterisk}', or '[', '/{asterisk}' at the end is implied.

+--remotes[=<pattern>]+::
	Pretend as if all the refs in `refs/remotes` are listed on the command line as _<commit>_. If _<pattern>_ is given, limit remote-tracking branches to ones matching given shell glob. If pattern lacks '?', '{asterisk}', or '[', '/{asterisk}' at the end is implied.

+--glob=<glob-pattern>+::
	Pretend as if all the refs matching shell glob _<glob-pattern>_ are listed on the command line as _<commit>_. Leading 'refs/', is automatically prepended if missing. If pattern lacks '?', '{asterisk}', or '[', '/{asterisk}' at the end is implied.

+--exclude=<glob-pattern>+::

	Do not include refs matching _<glob-pattern>_ that the next `--all`, `--branches`, `--tags`, `--remotes`, or `--glob` would otherwise consider. Repetitions of this option accumulate exclusion patterns up to the next `--all`, `--branches`, `--tags`, `--remotes`, or `--glob` option (other options or arguments do not clear accumulated patterns).
+
与えられたパターンは、それぞれ `--branches` または `--tags` または `--remotes` に適用される場合、 `refs/heads` または `refs/tags` または `refs/remotes` で始まるべきではありません。 `--glob` または `--all` に適用する場合は、 `refs/` で始める必要があります。末尾の "/{asterisk}" を意図している場合は、明示的に指定する必要があります。

`--exclude-hidden=(fetch|receive|uploadpack)`::
	`transfer.hideRefs` とともに適切な `fetch.hideRefs` 設定または `receive.hideRefs` 設定または `uploadpack.hideRefs` 設定を参照して、 `git-fetch` または `git-receive-pack` または `git-upload-pack` によって非表示になるrefを含めないでください(linkgit:git-config[1] 参照)。 このオプションはそれ以降疑似参照オプション `--all` または `--glob` に影響し、 それらの処理後にクリアされます。

`--reflog`::
	Pretend as if all objects mentioned by reflogs are listed on the command line as _<commit>_.

`--alternate-refs`::
	代替リポジトリのref先端として言及されているすべてのオブジェクトがコマンドラインにリストされているかのように見せかけます。 代替リポジトリは、 オブジェクトディレクトリが `objects/info/alternates` で指定されているリポジトリです。 インクルードされたオブジェクトのセットは、 `core.alternateRefsCommand` などによって変更できます。 linkgit:git-config[1]を参照してください。

`--single-worktree`::
	デフォルトでは、 作業ツリーが複数ある場合、 `--all` と `--reflog` と `--indexed-objects` では、 すべての作業ツリーが検査されます(linkgit:git-worktree[1]を参照)。 このオプションは、 現在の作業ツリーのみを調べるように強制します。

`--ignore-missing`::
	入力に無効なオブジェクト名が含まれている場合、そもそもその不正な入力が行われていないかのように見せかけます。

ifndef::git-rev-list[]
`--bisect`::
	コマンドラインで、bad bisection ref `refs/bisect/bad` がリストされ、その後に `--not` と good bisection ref `refs/bisect/good-*` が続くかのように見せかけます。
endif::git-rev-list[]

`--stdin`::
	コマンドラインから引数を取得するだけでなく、 標準入力からも引数を読み込みます。 これはコミットや、`--all` や `--glob=` のような疑似オプションを受け付けます。 `--` 区切り文字が現れた場合、 それに以降の入力はパス(paths)として扱われ、 出力結果を制限するために使用されます。 標準入力経由で読み取られる `--not` のようなフラグは、 同一のやり方である標準入力経由で読み取られて渡された引数に対してのみ考慮され、 `--stdin` の後ろに置いたコマンド・ライン引数には影響しません。

ifdef::git-rev-list[]
`--quiet`::
	標準出力には何も出力しないでください。この形式は主に、呼び出し元が終了ステータスをテストして、オブジェクトの範囲が完全に接続されているかどうかを確認できるようにすることを目的としています。出力をフォーマットする必要がないため、stdoutを`/dev/null`にリダイレクトするよりも高速です。

`--disk-usage`::
`--disk-usage=human`::
	通常の出力を抑制します。代わりに、選択したコミットまたはオブジェクトによってディスク上のストレージに使用されたバイトの合計を出力します。これは、出力が(特に `--use-bitmap-index` を伴った場合)はるかに高速に実行されることを除いて、出力を +git cat-file --batch-check='%(objectsize:disk)'+ にパイプすることと同じです。 "on-disk storage" の意味する制限については、 linkgit:git-cat-file[1] の「CAVEATS」を参照してください。 オプションの値 `human` を使用すると、ディスク上のストレージ・サイズが人間が読み取れる文字列で表示されます(例: 12.24 Kib、3.50 Mib など)。
endif::git-rev-list[]

`--cherry-mark`::
	`--cherry-pick`（以下を参照）と同様ですが、同等のコミットを省略せずに `=` と印し、同等でないコミットを `+` と印します。

`--cherry-pick`::
	コミットの組を対称差(symmetric difference)に制限する場合、「反対側」の別のコミットと同じ変更を導入するコミットを省略します。
+
たとえば、`A` と `B` の2つのブランチがある場合、それらの片側だけですべてのコミットを一覧表示する通常の方法は、 `--left-right` を使用することです(`--left-right` オプションの説明の以下の例を参照してください)。ただし、他のブランチからは(ブランチAと重複しない)厳選されたコミットが表示されます(たとえば、「3rd onb」はブランチAからチェリーピックされる可能性があります)。このオプションを使用すると、そのようなコミットのペアは出力から除外されます。

`--left-only`::
`--right-only`::
	リストは、 対称差のそれぞれの側でのみコミットします。 つまり、 `--left-right` で `<` と印されるのだけか、あるいは `--left-right` で `>` と印されるものだけです。
+
たとえば、 +--cherry-pick --right-only A...B+ は、 `A` にある、 または `A` のコミットとパッチと同等のコミットを `B` から省略します。 つまり、 これは `git cherry A B` からの `+` コミットをリストします。 より正確に書くと、 `--cherry-pick --right-only --no-merges` により正確なリストを提供します。

`--cherry`::
	+--right-only --cherry-mark --no-merges+ の同義語です。 出力を私たちの側のコミットに制限し、 フォークされた履歴の反対の側に適用されたものを、 `git cherry upstream mybranch` と同様に +git log --cherry upstream...mybranch+ でマークするのに役立ちます。

`-g`::
`--walk-reflogs`::
	Instead of walking the commit ancestry chain, walk reflog entries from the most recent one to older ones. When this option is used you cannot specify commits to exclude (that is, `^<commit>`, `<commit1>..<commit2>`, and `<commit1>...<commit2>` notations cannot be used).
+
(明らかな理由で、) `oneline` と `reference` 以外の `--pretty` 形式では、 これにより、
出力にreflogから取得された2行の追加情報が含まれます。 出力のreflog指定子は、 +ref@{<Nth>}+ ( <Nth>
はreflogの逆時系列インデックス(reverse-chronological index)) または +ref@{<timestamp>}+
(そのエントリを <timestamp> 付で)として表示されます。 表示は下記のいくつかのルールに依存します:
+
--
1. 開始点が +ref@{<Nth>}+ として指定されている場合は、 インデックス形式を表示します。
+
2. 開始点が `ref@{now}` として指定されている場合は、タイムスタンプ形式を表示します。
+
3. 上記のどちらも使用されていないが、コマンドラインで `--date` が指定されている場合は、 `--date` で要求された形式でタイムスタンプを表示します。
+
4. それ以外の場合は、インデックス形式を表示します。
--
+
`--pretty = oneline` では、コミットメッセージの前にこの情報が同じ行に付けられます。このオプションを `--reverse` と組み合わせることはできません。 linkgit:git-reflog[1]も参照してください。
+
`--pretty=reference` では、この情報はまったく表示されません。

`--merge`::
	範囲 +HEAD...<other>+ 内の競合したパスに触れる(touch)コミットを表示します。 ここで、`<other>` は `MERGE_HEAD` または `CHERRY_PICK_HEAD` または `REVERT_HEAD` または `REBASE_HEAD` のいずれかの最初の既存の擬似ref(pseudoref)です。 インデックスにマージされていないエントリがある場合にのみ機能します。 このオプションを使用すると、 三者間マージからの競合を解決するときに関連するコミットを表示できます。

`--boundary`::
	除外された境界コミットを出力します。 境界コミットの前には `-` が付いています。

ifdef::git-rev-list[]
`--use-bitmap-index`::

	(使用可能な場合は、)パックビットマップインデックスを使用して、トラバーサルを高速化しようと試みます。 `--objects` でトラバースする場合、ツリーとブロブには関連するパスが出力されないことに注意してください。

+--progress=<header>+::
	オブジェクトが対象になるたびに、 stderrに進捗レポートを出力します。 進行状況が更新されるたびに `<header>` テキストが出力されます。

`-z`::
	Instead of being newline-delimited, each outputted object and its accompanying metadata is delimited using NUL bytes. Output is printed in the following form:
+
-----------------------------------------------------------------------
<OID> NUL [<token>=<value> NUL]...
-----------------------------------------------------------------------
+
Additional object metadata, such as object paths or boundary objects, is printed using the `<token>=<value>` form. Token values are printed as-is without any encoding/truncation. An OID entry never contains a '=' character and thus is used to signal the start of a new object record. Examples:
+
-----------------------------------------------------------------------
<OID> NUL
<OID> NUL path=<path> NUL
<OID> NUL boundary=yes NUL
<OID> NUL missing=yes NUL [<token>=<value> NUL]...
-----------------------------------------------------------------------
+
This mode is only compatible with the `--objects`, `--boundary`, and `--missing` output options.
endif::git-rev-list[]

History Simplification
~~~~~~~~~~~~~~~~~~~~~~

特定の<path>を変更するコミットなど、履歴の一部のみに関心がある場合があります。ただし、「履歴の簡略化」(History Simplification)は2つの部分から成ります。履歴を簡略化するためにはさまざまな戦略があるためです。その1つはコミットの選択であり、もう1つはそれを行う方法です。

以下のオプションは、表示するコミットを選択します:

`<paths>`::
	<paths> で指定したパスを変更するコミットが選択されます。

`--simplify-by-decoration`::
	いくつかのブランチまたはタグによって参照されるコミットが選択されます。

注意: 意味のある重要な履歴のために、追加のコミットを表示できることに注意してください。

以下のオプションは、簡略化の実行方法に影響します。

`Default mode`::
	(以下を指定しない時のデフォルトのモード)履歴を、ツリーの最終状態を説明する最も単純な履歴に単純化します。最終結果が同じである場合(つまり、同じコンテンツのブランチをマージする場合)、いくつかの傍流ブランチ(side branches)を削除するため、最も単純です。

`--show-pulls`::
	デフォルト・モードからのすべてのコミットを含めますが、最初の親へのTREESAMEではなく、後の親へのTREESAMEであるマージ・コミットも含めます。このモードは、ブランチに変更を「最初に導入した」マージ・コミットを表示するのに役立ちます。(訳注:TREESAME=pathspecが全く同一であるツリー)

`--full-history`::
	デフォルト・モードと同じですが、一部の履歴を削除しません。

`--dense`::
	選択したコミットのみが表示され、重大で意味のある履歴を持つコミットもいくつか表示されます。

`--sparse`::
	簡略化された履歴内のすべてのコミットが表示されます。

`--simplify-merges`::
	このマージに寄与する選択されたコミットがないため、結果の履歴からいくつかの不要なマージを削除するための `--full-history` への追加オプション。

+--ancestry-path[=<commit>]+::
	When given a range of commits to display (e.g. `<commit1>..<commit2>` or `<commit2> ^<commit1>`), and a commit _<commit>_ in that range, only display commits in that range that are ancestors of _<commit>_, descendants of _<commit>_, or _<commit>_ itself. If no commit is specified, use _<commit1>_ (the excluded part of the range) as _<commit>_. Can be passed multiple times; if so, a commit is included if it is any of the commits given or if it is an ancestor or descendant of one of them.

より詳細な説明は以下のとおりです。

Suppose you specified `foo` as the _<paths>_. We shall call commits that modify `foo` !TREESAME, and the rest TREESAME. (In a diff filtered for `foo`, they look different and equal, respectively.)

以下、簡略化設定の違いを説明するために、同じ履歴例を使います。このコミットグラフでは、ファイル `foo` をフィルタリングしていると想定しています:

-----------------------------------------------------------------------
	  .-A---M---N---O---P---Q
	 /     /   /   /   /   /
	I     B   C   D   E   Y
	 \   /   /   /   /   /
	  `-------------'   X
-----------------------------------------------------------------------

履歴 A---Q の水平線は、各マージの最初の親と見なされます。その各コミットは以下のとおりです:

* `I` is the initial commit, in which `foo` exists with contents `asdf`, and a file `quux` exists with contents `quux`. Initial commits are compared to an empty tree, so `I` is !TREESAME.

* In `A`, `foo` contains just `foo`.

* `B` には `A` と同じ変更が含まれています。 よって、 そのマージ `M` は些細(trivial)なことであり、 したがって、 その全ての親に対して TREESAME です。

* `C` does not change `foo`, but its merge `N` changes it to `foobar`, so it is not TREESAME to any parent.

* `D` sets `foo` to `baz`. Its merge `O` combines the strings from `N` and `D` to `foobarbaz`; i.e., it is not TREESAME to any parent.

* `E` changes `quux` to `xyzzy`, and its merge `P` combines the strings to `quux xyzzy`. `P` is TREESAME to `O`, but not to `E`.

* `X` は、新ファイル `side` を追加し、 `Y` がそれを変更した独立したルートコミットです。 `Y` は `X` へのTREESAMEです。そのマージ `Q` は `P` に `side` を追加し、 `Q` は `P` にはTREESAMEですが、`Y` に対してはそうではありません。

`rev-list` は、 `--full-history` および/または、( `--parents` または `--children` を介して)親の書き換えが使用されているかどうかに基づいて、コミットを含めたり除外したりして、履歴を逆方向にウォークスルーします。以下の設定が可能です。

デフォルト・モード::
	(以下を指定しない場合のデフォルトのモード)コミットは、どの親に対してもTREESAMEでない場合に含まれます(これは変更できますが、以下の `--sparse` を参照してください)。コミットがマージであり、一方の親に対するTREESAMEであった場合は、その親のみをフォローします。(TREESAMEの親が複数ある場合でも、そのうちの1つだけをフォローします)。それ以外の場合は、すべての親をフォローします。
+
これにより、以下のようになります:
+
-----------------------------------------------------------------------
	  .-A---N---O
	 /     /   /
	I---------D
-----------------------------------------------------------------------
+
TREESAMEの親のみに従うルールが利用可能な場合は、 `B` を検討対象から完全に削除したことに注意してください。 `C` は `N` を介して考慮されましたが、しかしそれはTREESAMEです。ルートコミットは空のツリーと比較されるため、 `I` は !TREESAME です。
+
親子関係は `--parents` でのみ表示されますが、デフォルト・モードで選択されたコミットには影響しないため、親の行を示しました。

`--full-history` without parent rewriting::
	このモードはデフォルト・モードとはある一点で異なります：マージのすべての親を常に追跡する点です。 たとえそれが親の1つに対して TREESAME であってもです。 マージの複数の側に含まれるコミットがあったとしても、 それはマージ自体が含まれていることを意味するわけではありません。 この例では以下のようになります
+
-----------------------------------------------------------------------
	I  A  B  N  D  O  P  Q
-----------------------------------------------------------------------
+
`M` は、両方の親にとってTREESAMEであるため、除外されました。 `E` と `C` と `B` をすべて巡りましたが、 そのうちの `B` だけが !TREESAME だったので、 それ以外の `E` と `C` は表示されません。
+
注意: 親の書き換え(rewrite)がないと、コミット間の親子関係について話す(talk)ことは実際には不可能であるため、それらが切断されている(disconnected)ことを示していることに注意してください。

`--full-history` with parent rewriting::
	通常のコミットは !TREESAME の場合にのみ含まれます(これは変更できますが、以下の `--sparse` を参照してください)。
+
マージは常に含まれます。ただし、親リストは書き直されます。各親に沿って、自身が含まれていないコミットを削除します。 これにより以下のようになります
+
-----------------------------------------------------------------------
	  .-A---M---N---O---P---Q
	 /     /   /   /   /
	I     B   /   D   /
	 \   /   /   /   /
	  `-------------'
-----------------------------------------------------------------------
+
これを書き直し無しの `--full-history` と比較してください。 `E` は TREESAME であるため削除されましたが、 Pの親リストは `E` の親 `I` を含むように書き直されていることに注意してください。 `C` と `N` および `X` と `Y` と `Q` についても同じことが起こりました。

上記の設定に加えて、あなたはTREESAMEが包含に影響を与えるかどうかを変更できます:

`--dense`::
	巡ったコミットは、親にとってTREESAMEでない場合に含まれます。

`--sparse`::
	巡ったすべてのコミットが含まれます。
+
`--full-history` がなくても、これによりマージが単純化されることに注意してください。親の1つがTREESAMEの場合、その1つだけに従うため、マージの反対側を巡ることはありません。

`--simplify-merges`::
	最初に、親を書き換えた `--full-history` と同じ方法で履歴グラフを作成します(上記を参照)。
+
それから、以下のルールに従って、各コミット `C` を最終履歴内の置換 `C'` に単純化します:
+
--
* `C'` を `C` にセットします。
+
* `C'` の各親 `P` をその簡略化された `P'` に置き換えます。その過程で、他の親の祖先であるか、ルートである親を削除すると、TREESAMEが空のツリーにコミットされ、重複が削除されますが、TREESAMEであるすべての親を削除しないように注意してください。
+
* この親の書き換え後、 `C'` がルートまたはマージコミット(0または >1 の親を持つ)、境界コミット、または !TREESAMEである場合、それは残ります。それ以外の場合は、唯一の親に置き換えられます。
--
+
この効果は、親の書き換えを使用した `--full-history` と比較することで最もよく示されます。例は以下のようになります:
+
-----------------------------------------------------------------------
	  .-A---M---N---O
	 /     /       /
	I     B       D
	 \   /       /
	  `---------'
-----------------------------------------------------------------------
+
注意: `--full-history` に対する `N` と `P` と `Q` の主な違いに注意してください:
+
--
* `N` の親リストは、他の親 `M` の祖先であるため、 `I` が削除されました。それでも、 !TREESAME なので `N` が残りました。
+
* `P` の親リストも同様に `I` が削除されました。 `P` は、親が1つで TREESAMEであるため、完全に削除されました。
+
* `Q` の親リストでは、 `Y` が `X` に簡略化されていました。その後、 `X` はTREESAMEルートであったため、削除されました。 `Q` は、親が1つで TREESAMEであるため、完全に削除されました。
--

利用可能な別の簡略化モードがあります:

+--ancestry-path[=<commit>]+::
	Limit the displayed commits to those which are an ancestor of _<commit>_, or which are a descendant of _<commit>_, or are _<commit>_ itself.
+
ユースケースの例として、以下のコミット履歴について考えます:
+
-----------------------------------------------------------------------
	    D---E-------F
	   /     \       \
	  B---C---G---H---I---J
	 /                     \
	A-------K---------------L--M
-----------------------------------------------------------------------
+
A regular 'D..M' computes the set of commits that are ancestors of `M`, but excludes the ones that are ancestors of `D`. This is useful to see what happened to the history leading to `M` since `D`, in the sense that "what does `M` have that did not exist in `D`". The result in this example would be all the commits, except `A` and `B` (and `D` itself, of course).
+
When we want to find out what commits in `M` are contaminated with the bug introduced by `D` and need fixing, however, we might want to view only the subset of `D..M` that are actually descendants of `D`, i.e. excluding `C` and `K`. This is exactly what the `--ancestry-path` option does. Applied to the `D..M` range, it results in:
+
-----------------------------------------------------------------------
		E-------F
		 \       \
		  G---H---I---J
			       \
				L--M
-----------------------------------------------------------------------
+
We can also use `--ancestry-path=D` instead of `--ancestry-path` which means the same thing when applied to the `D..M` range but is just more explicit.
+
代わりに、この範囲内の特定のトピックに関心があり、そのトピックによって影響を受けるすべてのコミットに関心がある場合、祖先パスにそのトピックを含む `D..M` のサブセットのみを表示したい場合があります。 たとえば、`--ancestry-path=H D..M` を使用すると、以下のようになります:
+
-----------------------------------------------------------------------
		E
		 \
	      C---G---H---I---J
			       \
				L--M
-----------------------------------------------------------------------
+
一方、+--ancestry-path=K D..M+ は以下のようになります
+
-----------------------------------------------------------------------
		K---------------L--M
-----------------------------------------------------------------------

別のオプション `--show-pulls` について説明する前に、新しいサンプル履歴を作成する必要があります。

簡略化された履歴を見るときにユーザーが直面する一般的な問題は、ファイルを変更したことがわかっているコミットが、ファイルの簡略化された履歴に表示されないことです。そこで、新しい例を示し、その場合に `--full-history` や `--simplify-merges` などのオプションがどのように機能するかを示しましょう。

-----------------------------------------------------------------------
	  .-A---M-----C--N---O---P
	 /     / \  \  \/   /   /
	I     B   \  R-'`-Z'   /
	 \   /     \/         /
	  \ /      /\        /
	   `---X--'  `---Y--'
-----------------------------------------------------------------------

この例では、 `I` が `file.txt` を作成し、それが `A` と`B` と `X` にてさまざまな方法で変更されたとします。ひとり親のコミット `C` と `Z` と `Y` は `file.txt` を変更していません。マージコミット `M` は、マージの競合を解決して、 `A` と `B` の両方の変更を含めることによって作成されたため、どちらにもTREESAMEではありません。ただし、マージコミット `R` は、 `M` の `file.txt` の内容を無視し、 `X` の `file.txt` の内容のみを取得することによって作成されました。 したがって、 `R` は `X` へのTREESAMEですが、 `M` はそうではありません。最後に、 `N` を作成するための自然なマージ解決は、 `R` で `file.txt` の内容を取得することです。したがって、 `N` は `C` ではなく `R` へのTREESAMEです。マージコミット `O` と `P` は、最初の親にはTREESAMEですが、2番目の親である `Z` と `Y` にはついてはそうではありません。

デフォルト・モードを使用する場合、 `N` と `R` は両方ともTREESAMEの親を持っているため、 TREESAMEの親へ向かう経路(edges)はウォークされ、 それ以外のTREESAMEでない経路は無視されます。 結果の履歴グラフは以下のとおりです:

-----------------------------------------------------------------------
	I---X
-----------------------------------------------------------------------

`--full-history` を使用する場合、Gitはすべての経路(edge)を巡ります。これにより、コミット `A` と `B` と マージ `M` が検出されますが、マージコミット `O` と `P` も明らかになります。 親を書き換えると、結果のグラフは以下のようになります:

-----------------------------------------------------------------------
	  .-A---M--------N---O---P
	 /     / \  \  \/   /   /
	I     B   \  R-'`--'   /
	 \   /     \/         /
	  \ /      /\        /
	   `---X--'  `------'
-----------------------------------------------------------------------

ここで、マージコミット `O` と `P` は、実際には `file.txt` への変更を提供しなかったため、余分なノイズを提供します。古いバージョンの `file.txt` に基づいたトピックのみをマージしました。これは、多くの寄稿者が並行して作業し、トピックブランチを単一のトランクに沿ってマージするワークフローを使用するリポジトリの一般的な問題です。 `--full-history` の結果には、関連のない多くのマージが表示されます。

`--simplify-merges` オプションを使用すると、コミット `O` と `P` が結果から消えます。 これは、 `O` と `P` の書き直された2番目の親が、最初の親から到達可能であるためです。これらの経路(edges)が削除されると、コミットは、親にとってTREESAMEである単一の親のコミットのように見えます。これはコミット `N` にも発生し、以下のような履歴ビューが表示されます:

-----------------------------------------------------------------------
	  .-A---M--.
	 /     /    \
	I     B      R
	 \   /      /
	  \ /      /
	   `---X--'
-----------------------------------------------------------------------

このビューでは、 `A` と `B` と `X` からの重要なひとり親の変更がすべて表示されます。また、慎重に解決されたマージ `M` とそれほど慎重に解決されていないマージ `R` も表示されます。これは通常、コミット `A` と `B` がデフォルトのビューの履歴から「消えた」理由を判断するのに十分な情報です。ただし、このアプローチにはいくつかの問題があります。

最初の問題はパフォーマンスです。以前のオプションとは異なり、 `--simplify-merges` オプションでは、単一の結果を返す前にコミット履歴全体をウォークする必要があります。これにより、非常に大規模なリポジトリでこのオプションを使用するのが難しくなる可能性があります。

2番目の問題は監査に関するものです。 多くの寄稿者が同じリポジトリで作業している場合、 どのマージ・コミットが重要なブランチに変更を導入したかが重要です。 上記の問題のあるマージ `R` は、 重要なブランチにマージするために使用されたマージ・コミットではない可能性が高いです。 代わりに、 `R` と `X` を重要なブランチにマージするためにマージ `N` が使われました。 このコミットのコミット・メッセージには、 なぜ変更 `X` が `A` と `B` からの変更を上書きするようになった理由に関する情報が含まれている可能性があります。

`--show-pulls`::
	デフォルトの履歴に表示されるコミットに加えて、最初の親にはTREESAMEではなく、後の親にはTREESAMEである各マージコミットを表示します。
+
マージコミットが `--show-pulls` に含まれている場合、マージは別のブランチから変更を「プル」したかのように扱われます。この例で `--show-pulls` を使用すると(他のオプションは使用しない場合、)結果のグラフは以下のようになります:
+
-----------------------------------------------------------------------
	I---X---R---N
-----------------------------------------------------------------------
+
ここで、コミット `X` と `R` をそれぞれベースブランチにプルしたため、マージコミット `R` と `N` が含まれています。これらのマージは、コミット `A` と `B` がデフォルトの履歴に表示されない理由です。
+
`--show-pulls` が `--simplify-merges` とペアになっている場合、グラフには必要なすべての情報が含まれます:
+
-----------------------------------------------------------------------
	  .-A---M--.   N
	 /     /    \ /
	I     B      R
	 \   /      /
	  \ /      /
	   `---X--'
-----------------------------------------------------------------------
+
`M` は `R` から到達可能であるため、 `N` から `M` への経路(edge)が単純化されていることに注意してください。ただし、 `N` は、変更 `R` をメインブランチに「プル」したため、重要なコミットとして履歴に表示されます。

`--simplify-by-decoration` オプションを使用すると、タグで参照されていないコミットを省略して、履歴のトポロジの全体像のみを表示できます。コミットは、(1)タグによって参照されている場合、または (2)コマンドラインで指定されたパスの内容を変更した場合に、!TREESAMEとしてマークされます(つまり、上記の履歴簡略化ルールの後に保持されます)。他のすべてのコミットはTREESAMEとしてマークされます(簡略化される可能性があります)。

ifndef::git-shortlog[]
ifdef::git-rev-list[]
Bisection Helpers
~~~~~~~~~~~~~~~~~

`--bisect`::
	含まれるコミットと除外されるコミットのほぼ中間にある1つのコミットオブジェクトに出力を制限します。(存在する場合)bad bisection ref `refs/bisect/bad` が含まれるコミットに追加され、（存在する場合)good bisection ref `refs/bisect/good-*` が除外されるコミットに追加されることに注意してください。したがって、 `refs/bisect/` にrefsがないと仮定すると、
+
-----------------------------------------------------------------------
	$ git rev-list --bisect foo ^bar ^baz
-----------------------------------------------------------------------
+
は、2つのコマンドの出力である中間点(midpoint)を出力します
+
-----------------------------------------------------------------------
	$ git rev-list foo ^midpoint
	$ git rev-list midpoint ^bar ^baz
-----------------------------------------------------------------------
+
上記は、ほぼ同じ長さになります。 したがって、回帰を導入する変更を見つけることは、バイナリ検索(binary search)に還元されます。コミットチェーンの長さが1になるまで、新しい中間点(midpoint)を繰り返し生成してテストします。

`--bisect-vars`::
	これは、 `refs/bisect/` 内のrefが使用されないこと、およびシェルによって評価される準備ができているテキストを出力することを除いて、 `--bisect` と同じように計算されます。これらの行は、中間点リビジョンの名前を変数 `bisect_rev` に割り当て、 `bisect_rev` が `bisect_nr` にテストされた後にテストされるコミットの予想数、 `bisect_rev` が `bisect_good`に適していることが判明した場合にテストされるコミットの予想数、 `bisect_rev` が `bisect_bad` に不適切であることが判明した場合にテストされるコミットの予想数、および現在 `bisect_all` に二等分しているコミットの数です。

`--bisect-all`::
	これにより、含まれるコミットと除外されるコミットの間のすべてのコミットオブジェクトが、含まれるコミットと除外されるコミットまでの距離順に出力されます。 `refs/bisect/` のrefは使用されません。それらから最も遠いものが最初に表示されます。(これは `--bisect` によって表示される唯一のものです。)
+
これは、何らかの理由(たとえば、コンパイルできない場合など)でそれらの一部をテストすることを避けたい場合に、テストするための適切なコミットを簡単に選択できるため便利です。
+
このオプションは `--bisect-vars` と一緒に使用できます。この場合、ソートされたすべてのコミットオブジェクトの後に、 `--bisect-vars` が単独で使用された場合と同じテキストが表示されます。
endif::git-rev-list[]
endif::git-shortlog[]

ifndef::git-shortlog[]
Commit Ordering
~~~~~~~~~~~~~~~

デフォルトでは、コミットは新しい順に表示されます。

`--date-order`::
	すべての子が表示されるまで親を表示しませんが、それ以外の場合はコミットタイムスタンプの順序でコミットを表示します。

`--author-date-order`::
	すべての子が表示されるまで親を表示しませんが、それ以外の場合は、作者(author)のタイムスタンプ順にコミットを表示します。

`--topo-order`::
	すべての子が表示されるまで親を表示せず、複数の履歴行が混在するコミットを表示しないようにします。
+
たとえば、以下のようなコミット履歴があります:
+
----------------------------------------------------------------

    ---1----2----4----7
	\	       \
	 3----5----6----8---

----------------------------------------------------------------
+
ここで、数字はコミットタイムスタンプの順序を示し、 `gitrev-list` と `--date-order` のある友達は、タイムスタンプの順序でコミットを示します。つまり、8 7 6 5 4 3 2 1
+
`--topo-order` を使用すると、8 6 5 3 7 4 2 1（または8 7 4 2 6 5 3 1）が表示されます。2つの並列開発トラックからのコミットが混在して表示されないようにするために、いくつかの古いコミットが新しいコミットの前に表示されます。

`--reverse`::
	Output the commits chosen to be shown (see 'Commit Limiting' section above) in reverse order. Cannot be combined with `--walk-reflogs`.
endif::git-shortlog[]

ifndef::git-shortlog[]
Object Traversal
~~~~~~~~~~~~~~~~

これらのオプションは、主にGitリポジトリのパッキングを対象としています。

ifdef::git-rev-list[]
`--objects`::
	Print the object IDs of any object referenced by the listed commits. `--objects foo ^bar` thus means "send me all object IDs which I need to download if I have the commit object `bar` but not `foo`". See also `--object-names` below.

`--in-commit-order`::
	ツリーIDとブロブのIDをコミット順に出力します。 ツリーIDとブロブのIDは、コミットによって最初に参照された後に出力されます。

`--objects-edge`::
	Similar to `--objects`, but also print the IDs of excluded commits prefixed with a "`-`" character. This is used by linkgit:git-pack-objects[1] to build a ``thin'' pack, which records objects in deltified form based on objects contained in these excluded commits to reduce network traffic.

`--objects-edge-aggressive`::
	`--objects-edge` に似ていますが、時間がかかるという犠牲を払って、除外されたコミットを見つけためにもっともっと頑張ります。これは、`--objects-edge` の代わりに使用されて浅いリポジトリ(shallow repositories)用の「薄い」パック(thin pack)を構築します。

`--indexed-objects`::
	インデックスで使用されるすべてのツリーとブロブがコマンドラインにリストされているかのように見せかけます。 注意: たぶんあなたは一緒に `--objects` も使用したいと思うでしょう。

`--unpacked`::
	`--objects` と一緒の時のみ役立ちます。パックに含まれていないオブジェクトIDを出力します。

`--object-names`::
	`--objects` でのみ有用です。 見つかった オブジェクトID の名前を出力します。 これはデフォルトの振る舞いです。 各オブジェクトの「名前」は曖昧であり、 主にオブジェクトをパッキングするためのヒントとして意図されていることに注意してください。 特に、タグとツリーとブロブの名前は区別されません。 パス名を変更して改行を削除することもできます。 また、 オブジェクトが異なる名前で複数回あらわれる場合は、1 つの名前のみが表示されます。

`--no-object-names`::
	`--objects` と一緒の時のみ役立ちます。見つかったオブジェクトIDの名前は出力されません。これにより、 `--object-names` が反転します。 このフラグを使用すると、 linkgit:git-cat-file[1] などのコマンドで出力をより簡単に解析できます。

+--filter=<filter-spec>+::
	Only useful with one of the `--objects*`; omits objects (usually blobs) from the list of printed objects. The _<filter-spec>_ may be one of the following:
+
The form `--filter=blob:none` omits all blobs.
+
The form `--filter=blob:limit=<n>[kmg]` omits blobs of size at least _<n>_ bytes or units. _<n>_ may be zero. The suffixes `k`, `m`, and `g` can be used to name units in KiB, MiB, or GiB. For example, `blob:limit=1k` is the same as 'blob:limit=1024'.
+
The form `--filter=object:type=(tag|commit|tree|blob)` omits all objects which are not of the requested type.
+
The form `--filter=sparse:oid=<blob-ish>` uses a sparse-checkout specification contained in the blob (or blob-expression) _<blob-ish>_ to omit blobs that would not be required for a sparse checkout on the requested refs.
+
The form `--filter=tree:<depth>` omits all blobs and trees whose depth from the root tree is >= _<depth>_ (minimum depth if an object is located at multiple depths in the commits traversed). _<depth>_=0 will not include any trees or blobs unless included explicitly in the command-line (or standard input when `--stdin` is used). _<depth>_=1 will include only the tree and blobs which are referenced directly by a commit reachable from _<commit>_ or an explicitly-given object. _<depth>_=2 is like <depth>=1 while also including trees and blobs one more level removed from an explicitly-given commit or tree.
+
Note that the form `--filter=sparse:path=<path>` that wants to read from an arbitrary path on the filesystem has been dropped for security reasons.
+
Multiple `--filter=` flags can be specified to combine filters. Only objects which are accepted by every filter are included.
+
The form `--filter=combine:<filter1>+<filter2>+...<filterN>` can also be used to combined several filters, but this is harder than just repeating the `--filter` flag and is usually not necessary. Filters are joined by '{plus}' and individual filters are %-encoded (i.e. URL-encoded). Besides the '{plus}' and '%' characters, the following characters are reserved and also must be encoded: `~!@#$^&*()[]{}\;",<>?`+&#39;&#96;+ as well as all characters with ASCII code &lt;= `0x20`, which includes space and newline.
+
Other arbitrary characters can also be encoded. For instance, `combine:tree:3+blob:none` and `combine:tree%3A3+blob%3Anone` are equivalent.

`--no-filter`::
	以前の `--filter=` 引数をすべてオフにします。

`--filter-provided-objects`::
	明示的に提供されたオブジェクトのリストをフィルタリングします。そうしないと、どのフィルターとも一致しなくても常に出力されます。 `--filter=` と一緒に使った時のみ役に立ちます。

`--filter-print-omitted`::
	`--filter=` と一緒の時のみ役立ちます。フィルタによって省略されたオブジェクトのリストを出力します。オブジェクトIDの前には ``~'' 文字が付いています。

+--missing=<missing-action>+::
	将来の「部分クローン」(partial clone)開発に役立つデバッグオプション。このオプションは、欠落しているオブジェクトの処理方法を指定します。
+
The form `--missing=error` requests that rev-list stop with an error if a missing object is encountered. This is the default action.
+
The form `--missing=allow-any` will allow object traversal to continue if a missing object is encountered. Missing objects will silently be omitted from the results.
+
The form `--missing=allow-promisor` is like `allow-any`, but will only allow object traversal to continue for EXPECTED promisor missing objects. Unexpected missing objects will raise an error.
+
The form `--missing=print` is like `allow-any`, but will also print a list of the missing objects. Object IDs are prefixed with a ``?'' character.
+
The form `--missing=print-info` is like `print`, but will also print additional information about the missing object inferred from its containing object. The information is all printed on the same line with the missing object ID in the form: `?<oid> [<token>=<value>]...`. The `<token>=<value>` pairs containing additional information are separated from each other by a _SP_. The value is encoded in a token specific fashion, but _SP_ or _LF_ contained in value are always expected to be represented in such a way that the resulting encoded value does not have either of these two problematic bytes. Each `<token>=<value>` may be one of the following:
+
--
* The `path=<path>` shows the path of the missing object inferred from a containing object. A path containing _SP_ or special characters is enclosed in double-quotes in the C style as needed.
+
* The `type=<type>` shows the type of the missing object inferred from a containing object.
--
+
トラバーサルへ渡された先端(tip)が見つからない場合、 それらも欠落しているとみなされ、 トラバーサルはそれらを無視します。 ただし、 それらのオブジェクト ID を取得できない場合は、 エラーが発生します。

`--exclude-promisor-objects`::
	(内部使用のみ。) promisor境界でのオブジェクトトラバーサルをプレフィルターします。これは部分クローン(partial clone)で使用されます。これは、欠落しているオブジェクトに関するエラーを単に黙らせるのではなく、トラバーサルを制限するため、 `--missing=allow-promisor` よりも強力です。
endif::git-rev-list[]

+--no-walk[=(sorted|unsorted)]+::
	指定されたコミットのみを表示し、祖先をトラバースしない。範囲が指定されている場合、これは効果がありません。引数 `unsorted` が指定されている場合、コミットはコマンドラインで指定された順序で表示されます。それ以外の場合( `sorted` または引数が指定されていない場合)、コミットはコミット時間の逆順に表示されます。 `--graph` と組み合わせることはできません。

`--do-walk`::
	以前の `--no-walk` を上書きします。
endif::git-shortlog[]

ifndef::git-shortlog[]
Commit Formatting
~~~~~~~~~~~~~~~~~

ifdef::git-rev-list[]
Using these options, linkgit:git-rev-list[1] will act similar to the more specialized family of commit log tools:
ifndef::with-breaking-changes[]
linkgit:git-log[1], linkgit:git-show[1], and linkgit:git-whatchanged[1].
endif::with-breaking-changes[]
ifdef::with-breaking-changes[]
linkgit:git-log[1] and linkgit:git-show[1].
endif::with-breaking-changes[]
endif::git-rev-list[]

include::pretty-options.adoc[]

`--relative-date`::
	`--date=relative` と同じ。

`--date=<format>`::
	`--pretty` を使用する場合など、人間が読める形式で表示される日付に対してのみ有効になります。 `log.date` 構成変数(config variable)は、logコマンドの `--date` オプションのデフォルト値を設定します。デフォルトでは、日付は元のタイムゾーン(コミッターの、または作者のいずれか)で表示されます。 書式に `-local` が追加されている場合(例: `iso-local` )、代わりにユーザーのローカルタイムゾーンが使用されます。
+
--
`--date=relative` は、現在の時刻を基準にした日付を示します。例: ``2 hours ago'' 。 `-local` オプションは `--date=relative` には効果がありません。

`--date=local` は `--date=default-local` のエイリアスです。

`--date=iso` (または `--date=iso8601` )は、タイムスタンプをISO 8601のような形式で表示します。厳密なISO 8601形式との違いは以下のとおりです:

	- `T` 日付/時刻区切り文字の代わりにスペース
	- 時間とタイムゾーンの間のスペース
	- タイムゾーンの時間と分の間にコロンがありません

`--date=iso-strict` (または `--date=iso8601-strict` )は、タイムスタンプを厳密なISO 8601形式で表示します。

`--date=rfc` (または `--date=rfc2822` )は、RFC 2822形式のタイムスタンプを示します。これは、電子メールメッセージでよく見られます。

`--date=short` は、日付のみを表示し、時刻は表示せず、 `YYYY-MM-DD` 形式で表示します。

`--date=raw` は、エポック(1970-01-01 00:00:00 UTC)からの秒数、スペース、UTCからのオフセット(`+` または
`-` の付いた4桁数字で、最初の2つは時間、次の2つは分です)。つまり、タイムスタンプが +strftime("%s %z")+
でフォーマットされているかのようになります。 `-local`
オプションは、seconds-since-epoch値(常にUTCで測定されます)には影響しませんが、付随するタイムゾーン値を切り替えることに注意してください。

`--date=human` は、タイムゾーンが現在のタイムゾーンと一致しない場合はタイムゾーンを表示し、一致する場合は日付全体を出力しません(つまり、「今年」の日付の場合は年の出力をスキップしますが、何があったか覚えてるような過去数日については日付自体もスキップします)。 古い日付の場合、時と分も省略されます。

`--date=unix` は、日付をUnixエポックタイムスタンプ(1970年からの秒数)として表示します。 `--raw` と同様に、これは常にUTCであるため、 `-local` は効果がありません。

`--date=format:<format>` feeds the _<format>_ to your system `strftime`, except for `%s`, `%z`, and `%Z`, which are handled internally. Use `--date=format:%c` to show the date in your system locale's preferred format. See the `strftime`(3) manual for a complete list of format placeholders. When using `-local`, the correct syntax is `--date=format-local:<format>`.

`--date=default` はデフォルトの形式であり、 ctime(3) の出力に基づいています。これは 3文字の曜日と、3文字の月と、日付と、「HH:MM:SS」形式の時分秒が 1 ​​行に表示され、 その後に 4 桁の年と、ローカルタイムゾーンが使用されている場合を除きタイムゾーン情報が続きます。例: +Thu Jan 1 00:00:00 1970 +0000+
--

ifdef::git-rev-list[]
`--header`::
	コミットの内容をraw形式で出力します。各レコードはNUL文字で区切られます。

`--no-commit-header`::
	"commit" を含むヘッダー行と、指定された形式の前に出力されたオブジェクトIDを抑制します。これは組み込みフォーマットには影響しません。 カスタムフォーマットのみが影響を受けます。

`--commit-header`::
	以前の `--no-commit-header` を上書きします。
endif::git-rev-list[]

`--parents`::
	コミットの親も出力します( "commit parent..." の形式で)。親の書き換えも可能にします。上記「History Simplification」を参照してください。

`--children`::
	コミットの子も出力します( "commit child..." の形式で)。親の書き換えも可能にします。上記「History Simplification」を参照してください。

ifdef::git-rev-list[]
`--timestamp`::
	生のコミットタイムスタンプを出力します。
endif::git-rev-list[]

`--left-right`::
	対称差のどちら側からコミットに到達できるかをマークします。左側からのコミットには `<` が付けられ、右側からのコミットには `>` が付けられます。 `--boundary` と組み合わせると、それらのコミットの前に `-` が付きます。
+
たとえば、以下のトポロジーの場合:
+
-----------------------------------------------------------------------
	     y---b---b  branch B
	    / \ /
	   /   .
	  /   / \
	 o---x---a---a  branch A
-----------------------------------------------------------------------
+
以下のような出力が得られます:
+
-----------------------------------------------------------------------
	$ git rev-list --left-right --boundary --pretty=oneline A...B

	>bbbbbbb... 3rd on b
	>bbbbbbb... 2nd on b
	<aaaaaaa... 3rd on a
	<aaaaaaa... 2nd on a
	-yyyyyyy... 1st on b
	-xxxxxxx... 1st on a
-----------------------------------------------------------------------

`--graph`::
	出力の左側に、コミット履歴のテキストベースのグラフィック表現を描画します。グラフ履歴を適切に描画するために、コミットの間に余分な行が出力される可能性があります。 `--no-walk` と組み合わせることはできません。
+
これにより、親の書き換えが可能になります。上記「History Simplification」を参照してください。
+
これは、デフォルトで `--topo-order` オプションを意味しますが、 `--date-order` オプションも指定できます。

+--show-linear-break[=<barrier>]+::
	When `--graph` is not used, all history branches are flattened which can make it hard to see that the two consecutive commits do not belong to a linear branch. This option puts a barrier in between them in that case. If _<barrier>_ is specified, it is the string that will be shown instead of the default one.

ifdef::git-rev-list[]
`--count`::
	リストされたコミットの数を示す数値を出力し、他のすべての出力を抑制します。 `--left-right` と一緒に使用する場合は、代わりに、タブで区切って、左右のコミットのカウントを出力します。 `--cherry-mark` と一緒に使用する場合は、これらのカウントからパッチの同等のコミットを省略し、タブで区切られた同等のコミットのカウントを出力します。
endif::git-rev-list[]
endif::git-shortlog[]
