Commit Limiting
~~~~~~~~~~~~~~~

ここで説明されている特別な表記法を使用してリストする必要があるコミットの範囲を指定することに加えて、追加のコミット制限が適用される場合があります。

より多くのオプションを使用すると、 通常、 出力がさらに制限されます(たとえば、 `--since=<date1>` は _<date1>_ より新しいコミットに制限され、 `--grep=<pattern>` と一緒に使用すると、ログメッセージに _<pattern>_ と一致する行があるコミットにさらに制限されます)。

注意: これらは、 `--reverse` などのコミット順序およびフォーマットオプションの前に適用されることに注意してください。

`-<number>`::
`-n <number>`::
`--max-count=<number>`::
	出力を _<number>_ 個のコミットに制限します。

`--skip=<number>`::
	コミット出力の表示を開始する前に、 _<number>_ 個のコミットをスキップします。

`--since=<date>`::
`--after=<date>`::
	指定の日付(_<date>_)よりも新しいコミットを表示します。

`--since-as-filter=<date>`::
	指定の日付(_<date>_)より新しいすべてのコミットを表示します。 これは、 指定の日付(_<date>_)より古い最初のコミットで停止するのではなく、 範囲内のすべてのコミットを訪問します。

`--until=<date>`::
`--before=<date>`::
	指定の日付(_<date>_)より古いコミットを表示します。

ifdef::git-rev-list[]
`--max-age=<timestamp>`::
`--min-age=<timestamp>`::
	コミット出力を指定された時間範囲に制限します。
endif::git-rev-list[]

`--author=<pattern>`::
`--committer=<pattern>`::
	コミット出力を、 指定のパターン(_<pattern>_)(正規表現)に一致する 作者(author)/コミッター(committer) ヘッダー行を持つものに制限します。 複数の `--author=<pattern>` がある場合、 作者が指定されたパターン(_<pattern>_)のいずれかに一致するコミットが選択されます(複数の `--committer=<pattern>` の場合も同様)。

`--grep-reflog=<pattern>`::
	コミット出力を、 指定の正規表現パターン(_<pattern>_)に一致する reflog エントリを持つものに制限します。 複数の `--grep-reflog` を使用すると、 指定されたパターンのいずれかに一致する reflog メッセージを持つコミットが選択されます。 `--walk-reflogs` 無しでこのオプションを使用するとエラーになります。

`--grep=<pattern>`::
	コミット出力を、 指定の正規表現パターン(_<pattern>_)にマッチする単一のログ・メッセージを持つモノに制限します。 複数の `--grep=<pattern>` を使用すると、 指定のパターン(_<pattern>_)のいずれかにメッセージがマッチするコミットが選択されます(全てにマッチするコミットだけを選択したい場合は、`--all-match` を参照してください)。
ifndef::git-rev-list[]
+
`--notes` が有効な場合、ノートからのメッセージは、ログメッセージの一部であるかのようにマッチングされます。
endif::git-rev-list[]

`--all-match`::
	コミット出力を、少なくとも1つに一致するものではなく、指定されたすべての `--grep` に一致するものに制限します。

`--invert-grep`::
	コミット出力を、 `--grep=<pattern>` で指定したパターン(_<pattern>_)とマッチしない単一のログ・メッセージを持つモノに制限します。

`-i`::
`--regexp-ignore-case`::
	大文字小文字に関係なく、正規表現の制限パターンに一致します。

`--basic-regexp`::
	制限パターンを基本正規表現として扱います。これがデフォルトです。

`-E`::
`--extended-regexp`::
	制限パターンを、デフォルトの基本正規表現の代わりに拡張正規表現として扱います。

`-F`::
`--fixed-strings`::
	制限パターンを固定文字列として扱います(パターンを正規表現として解釈しないでください)。

`-P`::
`--perl-regexp`::
	制限パターンをPerl互換の正規表現として扱います。
+
これらのタイプの正規表現のサポートは、 コンパイル時オプションに依存します。 Gitが当該のサポート付きでコンパイルされてい無い場合、 これらオプションを使うと、 Gitが終了(die)します。

`--remove-empty`::
	指定されたパスがツリーから見えなくなったら停止(stop)します。

`--merges`::
	マージコミットのみを出力します。これは `--min-parents=2` とまったく同じです。

`--no-merges`::
	複数の親を持つコミットを出力しない。これは `--max-parents=1` とまったく同じです。

`--min-parents=<number>`::
`--max-parents=<number>`::
`--no-min-parents`::
`--no-max-parents`::
	量の多寡に関わらず、 とにかく複数の親コミットがあるコミットのみを表示します。 特に、 `--max-parents=1` は `--no-merges` と同じであり、 `--min-parents=2` は `--merges` と同じです。 `--max-parents=0` はすべてのルート・コミットを提供し、 `--min-parents=3` はすべてのタコ足マージ(octopus merges)を表示します。
+
`--no-min-parents` と `--no-max-parents` は、これらの制限を(制限なしに)再度リセットします。同等の形式は、 `--min-parents=0` (すべてのコミットに0個以上の親があります)および `--max-parents=-1` (マイナスの数は上限がないことを示します)です。

`--first-parent`::
	インクルードするコミットを探すとき、マージ・コミットの最初の親コミットのみをたどります。 このオプションは、特定のトピックブランチの進化を表示するときに、より良い概要を提供できます。トピックブランチへのマージは、 時々更新されるアップストリームにアジャストすることだけである傾向があり、 このオプションを使用すると、そのようなマージによって履歴に取り込まれた個々のコミットを無視できます。
ifdef::git-log[]
+
このオプションは、マージコミットのデフォルトのdiff形式も `first-parent` に変更します。詳細については、 `--diff-merges=first-parent` を参照してください。
endif::git-log[]

`--exclude-first-parent-only`::
	( `^` を使用して)除外するコミットを見つけるときは、 判明したマージ・コミットの最初の親コミットのみに従います。 任意のマージが有効なトピック・ブランチの変更になる可能性がある場合、 これを使用して、 リモート・ブランチから分岐したポイントからトピック・ブランチ内の一連の変更を見つけることができます。

`--not`::
	次の `--not` までの後続のすべてのリビジョン指定子について、 {caret} プレフィックス(またはその欠落)の意味を反転します。 コマンドラインで `--stdin` より前で使用すると、 標準入力を介して渡されたリビジョンは影響を受けません。 逆に、 標準入力経由で渡された場合、 コマンドラインで渡されたリビジョンは影響を受けません。

`--all`::
	`refs/` 内のすべての参照が HEAD と共に、 コマンドラインに _<commit>_ としてリストされているかのように見せかけます。

`--branches[=<pattern>]`::
	`refs/heads` 内のすべての参照がコマンドラインに _<commit>_ としてリストされているかのように見せかけます。 _<pattern>_ が指定されている場合、 ブランチを指定されたシェルグロブ(shell glob)に一致するものに制限します。 パターン(_<pattern>_)に "?" または "{asterisk}" または "[" がない場合、最後に "/{asterisk}" が含まれます。

`--tags[=<pattern>]`::
	`refs/tags` 内のすべての参照がコマンドラインに _<commit>_ としてリストされているかのように見せかけます。 _<pattern>_ が指定されている場合は、 指定されたシェルグロブ(shell glob)に一致するタグにタグを制限します。 パターンに "?" または "{asterisk}" または "[" がない場合、最後に "/{asterisk}" が含まれます。

`--remotes[=<pattern>]`::
	`refs/remotes` 内のすべての参照がコマンドラインに _<commit>_ としてリストされているかのように見せかけます。 _<pattern>_ が指定されている場合、 リモート追跡ブランチを指定されたシェルグロブ(shell glob)に一致するものに制限します。 パターンに "?" または "{asterisk}" または "[" がない場合、最後に "/{asterisk}" が含まれます。

`--glob=<glob-pattern>`::
	シェルグロブ _<glob-pattern>_ に一致するすべての参照がコマンドラインに _<commit>_ としてリストされているかのように見せかけます。 先頭の `refs/` は、 欠落している場合は自動的に先頭に追加されます。 パターンに "?" または "{asterisk}" または "[" がない場合、最後に "/{asterisk}" が含まれます。

`--exclude=<glob-pattern>`::

	次に指定する `--all` または `--branches` または `--tags` または `--remotes` または `--glob` が通常は対象として認識する参照のうち、_<glob-pattern>_ に一致するものは除外します。 このオプションは繰り返し指定可能で、 除外パターンは次の `--all` または `--branches` または `--tags` または `--remotes` または `--glob` オプションが現れるまで累積される(これら以外のオプションや引数は、 累積された除外パターンをクリアしません)。
+
与えられたパターンは、それぞれ `--branches` または `--tags` または `--remotes` に適用される場合、 `refs/heads` または `refs/tags` または `refs/remotes` で始まるべきではありません。 `--glob` または `--all` に適用する場合は、 `refs/` で始める必要があります。末尾の "/{asterisk}" を意図している場合は、明示的に指定する必要があります。

`--exclude-hidden=(fetch|receive|uploadpack)`::
	`transfer.hideRefs` 構成とともに適切な `fetch.hideRefs` または `receive.hideRefs` または `uploadpack.hideRefs` を参照して、 `git-fetch` または `git-receive-pack` または `git-upload-pack` によって非表示になる参照を含めないでください(linkgit:git-config[1] 参照)。 このオプションはそれ以降の疑似参照(pseudo-ref)オプション `--all` または `--glob` に影響し、 それらの処理後にクリアされます。

`--reflog`::
	reflogs で言及されているすべてのオブジェクトがコマンドラインに _<commit>_ としてリストされているかのように見せかけます。

`--alternate-refs`::
	代替リポジトリー(alternate repositories)の参照先端として言及されているすべてのオブジェクトがコマンドラインにリストされているかのように見せかけます。 代替リポジトリーは、 オブジェクト・ディレクトリが `objects/info/alternates` と指定されているリポジトリーです。 インクルードされたオブジェクトの組は、 `core.alternateRefsCommand` などによって変更できます。 linkgit:git-config[1]を参照してください。

`--single-worktree`::
	デフォルトでは、 作業ツリー(working tree)が複数ある場合、 `--all` と `--reflog` と `--indexed-objects` では、 すべての作業ツリーが検査されます(linkgit:git-worktree[1]を参照)。 このオプションは、 現在の作業ツリーのみを調べるように強制します。

`--ignore-missing`::
	入力に無効なオブジェクト名が含まれている場合、そもそもその不正な入力が行われていないかのように見せかけます。

ifndef::git-rev-list[]
`--bisect`::
	コマンドラインで、 bad bisection 参照 `refs/bisect/bad` がリストされ、 その後に `--not` と good bisection 参照 `refs/bisect/good-*` が続くかのように見せかけます。
endif::git-rev-list[]

`--stdin`::
	コマンドラインから引数を取得するだけでなく、 標準入力からも引数を読み込みます。 これはコミットや、`--all` や `--glob=` のような疑似オプションを受け付けます。 `--` 区切り文字が現れた場合、 それに以降の入力はパス(paths)として扱われ、 出力結果を制限するために使用されます。 標準入力経由で読み取られる `--not` のようなフラグは、 同一のやり方である標準入力経由で読み取られて渡された引数に対してのみ考慮され、 `--stdin` の後ろに置いたコマンド・ライン引数には影響しません。

ifdef::git-rev-list[]
`--quiet`::
	標準出力には何も出力しない。 この形式は、 主に呼び出し元が終了ステータス(exit status)を確認することで、 指定したオブジェクトの範囲が完全に繋がっているか(または繋がっていないか)を判定できるようにするためのものです。 出力をフォーマットする必要がないため、 標準出力を `/dev/null` にリダイレクトするよりも高速です。

`--disk-usage`::
`--disk-usage=human`::
	通常の出力を抑制します。代わりに、選択したコミットまたはオブジェクトによってディスク上のストレージに使用されたバイトの合計を出力します。これは、出力が(特に `--use-bitmap-index` を伴った場合)はるかに高速に実行されることを除いて、出力を `git cat-file --batch-check='%(objectsize:disk)'` にパイプすることと同じです。 "on-disk storage" の意味する制限については、 linkgit:git-cat-file[1] の「CAVEATS」を参照してください。 オプションの値 `human` を使用すると、ディスク上のストレージ・サイズが人間が読み取れる文字列で表示されます(例: 12.24 Kib、3.50 Mib など)。
endif::git-rev-list[]

`--cherry-mark`::
	`--cherry-pick`（以下を参照）と同様ですが、同等のコミットを省略せずに `=` と印し、同等でないコミットを `+` と印します。

`--cherry-pick`::
	コミットの組を対称差(symmetric difference)に制限する場合、「反対側」(other side)の別のコミットと同じ変更を導入するコミットを省略します。
+
たとえば、`A` と `B` の2つのブランチがある場合、それらの片側だけですべてのコミットを一覧表示する通常の方法は、 `--left-right` を使用することです(`--left-right` オプションの説明の以下の例を参照してください)。ただし、他のブランチからは(ブランチAと重複しない)厳選されたコミットが表示されます(たとえば、 ``3rd on b'' はブランチAからチェリーピックされる可能性があります)。このオプションを使用すると、そのようなコミットのペアは出力から除外されます。

`--left-only`::
`--right-only`::
	リストは、 対称差のそれぞれの側でのみコミットします。 つまり、 `--left-right` で `<` と印されるのだけか、あるいは `--left-right` で `>` と印されるものだけです。
+
たとえば、 `--cherry-pick --right-only A...B` は、 `A` にある、 または `A` のコミットとパッチと同等のコミットを `B` から省略します。 つまり、 これは `git cherry A B` からの `+` コミットをリストします。 より正確に書くと、 `--cherry-pick --right-only --no-merges` により正確なリストを提供します。

`--cherry`::
	`--right-only --cherry-mark --no-merges` の同義語です。 出力を私たちの側(our side)のコミットに制限し、 フォークされた履歴の反対の側(other side)に適用されたものを、 `git cherry upstream mybranch` と同様に `git log --cherry upstream...mybranch` でマークするのに役立ちます。

`-g`::
`--walk-reflogs`::
	コミットの祖先チェーンをたどる代わりに、 reflogエントリを最新のものから古いものに移動します。 このオプションを使用する場合、 除外するコミットを指定することはできません(つまり、 `^<commit>` や `<commit1>..<commit2>` や `<commit1>...<commit2>` 表記は使用できません)。
+
(明らかな理由で、) `oneline` と `reference` 以外の `--pretty` 形式では、 これにより、 出力にreflogから取得された2行の追加情報が含まれます。 出力のreflog指定子は、 `ref@{<Nth>}` ( _<Nth>_ はreflogの逆時系列インデックス(reverse-chronological index)) または `ref@{<timestamp>}` (そのエントリを _<timestamp>_ 付で)として表示されます。 表示は下記のいくつかのルールに依存します:
+
--
1. 開始点が `ref@{<Nth>}` として指定されている場合は、 インデックス形式を表示します。
+
2. 開始点が `ref@{now}` として指定されている場合は、タイムスタンプ形式を表示します。
+
3. 上記のどちらも使用されていないが、コマンドラインで `--date` が指定されている場合は、 `--date` で要求された形式でタイムスタンプを表示します。
+
4. それ以外の場合は、インデックス形式を表示します。
--
+
`--pretty=oneline` では、コミット・メッセージの前にこの情報が同じ行に付けられます。 このオプションを `--reverse` と組み合わせることはできません。 linkgit:git-reflog[1]も参照してください。
+
`--pretty=reference` では、この情報はまったく表示されません。

`--merge`::
	範囲 `HEAD...<other>` 内の競合したパスに触れる(touch)コミットを表示します。 ここで、 `<other>` は `MERGE_HEAD` または `CHERRY_PICK_HEAD` または `REVERT_HEAD` または `REBASE_HEAD` のいずれかの最初の既存の擬似参照(pseudoref)です。 インデックスにマージされていないエントリがある場合にのみ機能します。 このオプションを使用すると、 三者間マージからの競合を解決するときに関連するコミットを表示できます。

`--boundary`::
	除外された境界コミットを出力します。 境界コミットの前には `-` が付いています。

ifdef::git-rev-list[]
`--use-bitmap-index`::

	(使用可能な場合は、)パック・ビットマップ・インデックスを使用して、 トラバーサルを高速化しようと試みます。 `--objects` でトラバースする場合、 ツリーとブロブには関連するパスが出力されないことに注意してください。

`--progress=<header>`::
	オブジェクトが対象になるたびに、 stderrに進捗レポートを出力します。 進行状況が更新されるたびに `<header>` テキストが出力されます。

`-z`::
	改行区切りではなく、 出力される各オブジェクトとそれに付随するメタデータは、 NULバイトで区切られます。 出力は以下の形式で表示されます:
+
-----------------------------------------------------------------------
<OID> NUL [<token>=<value> NUL]...
-----------------------------------------------------------------------
+
オブジェクトのパスや境界オブジェクトなどのオブジェクト追加メタデータは、 `<token>=<value>` の形式で出力されます。 トークンの値は、 エンコードや切り詰め(truncation)処理を一切行わず、 そのまま出力されます。 OID のエントリには決して `=` 文字が含まれないため、 `=` の出現は「新しいオブジェク・トレコードの開始」を示す合図として利用されます。 以下、例:
+
-----------------------------------------------------------------------
<OID> NUL
<OID> NUL path=<path> NUL
<OID> NUL boundary=yes NUL
<OID> NUL missing=yes NUL [<token>=<value> NUL]...
-----------------------------------------------------------------------
+
このモードは、 `--objects` と `--boundary` と `--missing` の出力オプションとのみ互換性があります。
endif::git-rev-list[]

History Simplification
~~~~~~~~~~~~~~~~~~~~~~

特定の <path> を変更するコミットなど、 履歴の一部のみに関心がある場合があります。 しかし「履歴の簡略化」(History Simplification)はふたつの側面があります。 履歴を簡略化するためにはさまざまな戦略があるためです。 そのひとつはコミットの選択であり、 もうひとつはそれを行う方法です。

以下のオプションは、表示するコミットを選択します:

`<paths>`::
	<paths> で指定したパスを変更するコミットが選択されます。

`--simplify-by-decoration`::
	いくつかのブランチまたはタグによって参照されるコミットが選択されます。

注意: 意味のある重要な履歴のために、追加のコミットを表示できることに注意してください。

以下のオプションは、簡略化の実行方法に影響します。

デフォルト・モード::
	(以下を指定しない時のデフォルトのモード)履歴を、ツリーの最終状態を説明する最も単純な履歴に単純化します。最終結果が同じである場合(つまり、同じコンテンツのブランチをマージする場合)、いくつかの傍流ブランチ(side branches)を削除するため、最も単純です。

`--show-pulls`::
	デフォルト・モードで表示されるすべてのコミットに加えて、 1つ目の親に対しては TREESAME でない(!TREESAME)、 かつ、 2つ目以降の親のいずれかが TREESAME であるマージ・コミットも含めます。 このモードは、 とある変更をそのブランチに「最初に導入した」マージ・コミットを表示するのに役立ちます。

`--full-history`::
	デフォルト・モードと同じですが、一部の履歴を削除しません。

`--dense`::
	選択したコミットのみが表示され、重大で意味のある履歴を持つコミットもいくつか表示されます。

`--sparse`::
	簡略化された履歴内のすべてのコミットが表示されます。

`--simplify-merges`::
	このマージに寄与する選択されたコミットがないため、結果の履歴からいくつかの不要なマージを削除するための `--full-history` への追加オプション。

`--ancestry-path[=<commit>]`::
	コミットの範囲を指定して表示する場合(たとえば `<commit1>..<commit2>` とか `<commit2> ^<commit1>` のように指定したとき)、 その範囲内にあるコミットとして _<commit>_ が与えられたら、 _<commit>_ の祖先または、 _<commit>_ の子孫または、 _<commit>_ 自身のみを表示します。 コミット(_<commit>_)が明示的に指定されていない場合は、 _<commit1>_ (範囲の除外部分)を _<commit>_ として使用します。 このオプションは複数回指定可能で、 その場合、 指定されたいずれかのコミット自体であるか、またはそれらのいずれかの祖先・子孫であるコミットが含まれます。

より詳細な説明は以下のとおりです。

_<paths>_ として `foo` を指定したとします。 `foo` を変更するコミットを !TREESAME と呼び、 それ以外のコミットを TREESAME と呼びます。 ( `foo` でフィルタリングされた diff では、 それぞれ異なって見えたりたり同じに見えたりします。）

以降の説明では、 簡略化設定の違いを分かりやすく示すために、 常に同一のコミット履歴の例を用います。 ここでは、 以下のコミット・グラフにおいてファイル `foo` を対象にフィルタリングしているものとします:

-----------------------------------------------------------------------
	  .-A---M---N---O---P---Q
	 /     /   /   /   /   /
	I     B   C   D   E   Y
	 \   /   /   /   /   /
	  `-------------'   X
-----------------------------------------------------------------------

履歴 A---Q の水平線は、 各マージの1つ目の親(first parent)と見なします。 その各コミットは以下のとおりです:

* `I` は最初のコミットであり、 ファイル `foo` が内容 `asdf` で存在し、 ファイル `quux` は内容 `quux` で存在します。 最初のコミットは空のツリーと比較されるため、 `I` は !TREESAME です。

* コミット `A` では、 ファイル `foo` には `foo` だけが含まれています。

* コミット `B` には コミット `A` と同じ変更が含まれています。 よって、 そのマージ `M` は些細(trivial)なことであり、 したがって、 その全ての親に対して TREESAME です。

* コミット `C` は `foo` を変更しませんが、そのマージ `N` は ファイル `foo` を `foobar` に変更するので、 どの親に対しても TREESAME ではありません。

* コミット `D` は ファイル `foo` の内容を `baz` に変更する。 そのマージ・コミット `O` は、 `N` と `D` の文字列を合わせて `foobarbaz` という内容にする。 つまり、どの親に対しても TREESAME ではありません。

* コミット `E` は ファイル `quux` を `xyzzy` に変更し、 そのマージ・コミット `P` は文字列を結合して `quux xyzzy` にします。 マージ・コミット `P` は マージ・コミット `O` に対して TREESAME ですが、 コミット `E` に対してはそうではありません。

* `X` は、新ファイル `side` を追加し、 `Y` がそれを変更した独立したルートコミットです。 `Y` は `X` へのTREESAMEです。そのマージ `Q` は `P` に `side` を追加し、 `Q` は `P` にはTREESAMEですが、`Y` に対してはそうではありません。

`rev-list` は、 `--full-history` および/または、( `--parents` または `--children` を介して)親の書き換えが使用されているかどうかに基づいて、コミットを含めたり除外したりして、履歴を逆方向にウォークスルーします。以下の設定が可能です。

デフォルト・モード::
	このモードでは、 全ての親が !TREESAME の場合に当該コミットを対象に含める(ただし、 後述の `--sparse` を付けると挙動が変わります)。 また、 もしそのコミットがマージ・コミットで、 いずれか1つの親に対して TREESAME だった場合、 その親だけを追跡し(TREESAME な親が複数あったとしても、 そのうちの1つだけを追跡します)、 それ以外の場合(訳注: 全ての親が !TREESAME の場合)は、 すべての親を追跡します。
+
これにより、以下のようになります:
+
-----------------------------------------------------------------------
	  .-A---N---O
	 /     /   /
	I---------D
-----------------------------------------------------------------------
+
注意: 利用可能な場合は TREESAME な親だけを追跡する、 というルールによって、 コミット `B` は完全に除外されてしまいました。 コミット `C` は コミット `N` を介して候補に挙がったものの、 TREESAME だったため除外されています。 一方、 ルート・コミットは空のツリーと比較されるため、 コミット `I` は !TREESAME です。
+
親子関係は `--parents` オプションを付けないと表示されないものの、 デフォルト・モードでの「どのコミットが選ばれるか」には影響しないため、 ここでは分かりやすさのために親子関係の線を描いて示しています(訳注: 上図 `N` に 線が2つ入っているのは、 親が2つあるマージ・コミットである事を示している(が、しかし、 2つ目の親の `C` は TREESAME であるため表示されない))

親の書き換えなし(`--graph` 無し)の `--full-history`::
	このモードはデフォルト・モードとはある一点で異なります：マージのすべての親を常に追跡する点です。 たとえそれが親の1つに対して TREESAME であってもです。 マージの複数の側に含まれるコミットがあったとしても、 それはマージ自体が含まれていることを意味するわけではありません。 この例では以下のようになります
+
-----------------------------------------------------------------------
	I  A  B  N  D  O  P  Q
-----------------------------------------------------------------------
+
`M` は、両方の親にとってTREESAMEであるため、除外されました。 `E` と `C` と `B` をすべて巡りましたが、 そのうちの `B` だけが !TREESAME だったので、 それ以外の `E` と `C` は表示されません。
+
注意: 親情報を書き換えていない場合、 どのコミットがどのコミットの親・子なのかを正しく表現することができないため、 上記グラフ上ではそれらのコミットを「繋がっていない」（親子関係の線が引かれていない）形で表示しています。

親を書き換える(`--graph` あり) `--full-history`::
	通常のコミットは !TREESAME の場合にのみ含まれます(これは変更できますが、以下の `--sparse` を参照してください)。
+
マージは常に含まれます。ただし、親リストは書き直されます。各親に沿って、自身が含まれていないコミットを削除します。 これにより以下のようになります
+
-----------------------------------------------------------------------
	  .-A---M---N---O---P---Q
	 /     /   /   /   /
	I     B   /   D   /
	 \   /   /   /   /
	  `-------------'
-----------------------------------------------------------------------
+
これを書き直し無しの `--full-history` と比較してください。 `E` は TREESAME であるため削除されましたが、 Pの親リストは `E` の親 `I` を含むように書き直されていることに注意してください。 `C` と `N` および `X` と `Y` と `Q` についても同じことが起こりました。

上記の設定に加えて、あなたはTREESAMEが包含に影響を与えるかどうかを変更できます:

`--dense`::
	巡ったコミットは、親にとってTREESAMEでない場合に含まれます。

`--sparse`::
	巡ったすべてのコミットが含まれます。
+
`--full-history` がなくても、これによりマージが単純化されることに注意してください。親の1つがTREESAMEの場合、その1つだけに従うため、マージの反対側を巡ることはありません。

`--simplify-merges`::
	最初に、親を書き換えた `--full-history` と同じ方法で履歴グラフを作成します(上記を参照)。
+
それから、以下のルールに従って、各コミット `C` を最終履歴内の置換 `C'` に単純化します:
+
--
* `C'` を `C` にセットします。
+
* `C'` の各親 `P` をその簡略化された `P'` に置き換えます。その過程で、他の親の祖先であるか、ルートである親を削除すると、TREESAMEが空のツリーにコミットされ、重複が削除されますが、TREESAMEであるすべての親を削除しないように注意してください。
+
* この親の書き換え後、 `C'` がルートまたはマージコミット(0または >1 の親を持つ)、境界コミット、または !TREESAMEである場合、それは残ります。それ以外の場合は、唯一の親に置き換えられます。
--
+
この効果は、親の書き換えを使用した `--full-history` と比較することで最もよく示されます。例は以下のようになります:
+
-----------------------------------------------------------------------
	  .-A---M---N---O
	 /     /       /
	I     B       D
	 \   /       /
	  `---------'
-----------------------------------------------------------------------
+
注意: `--full-history` に対する `N` と `P` と `Q` の主な違いに注意してください:
+
--
* `N` の親リストは、他の親 `M` の祖先であるため、 `I` が削除されました。それでも、 !TREESAME なので `N` が残りました。
+
* `P` の親リストも同様に `I` が削除されました。 `P` は、親が1つで TREESAMEであるため、完全に削除されました。
+
* `Q` の親リストでは、 `Y` が `X` に簡略化されていました。その後、 `X` はTREESAMEルートであったため、削除されました。 `Q` は、親が1つで TREESAMEであるため、完全に削除されました。
--

利用可能な別の簡略化モードがあります:

`--ancestry-path[=<commit>]`::
	表示されるコミットを _<commit>_ の祖先、または _<commit>_ の子孫、または _<commit>_ 自身に制限します。
+
ユースケースの例として、以下のコミット履歴について考えます:
+
-----------------------------------------------------------------------
	    D---E-------F
	   /     \       \
	  B---C---G---H---I---J
	 /                     \
	A-------K---------------L--M
-----------------------------------------------------------------------
+
通常の `D..M` は、 `M` の祖先であるコミットのセットを計算しますが、 `D` の祖先であるコミットは除外します。 これは、「 `M` には `D` には存在しなかったものがある」という意味で、 `D` 以降の `M` に至るまでの歴史に何が起こったのかを知るのに役立ちます。この例の結果は、 `A` と `B` (そしてもちろん `D` 自体)を除くすべてのコミットになります。
+
ただし、 `M` のコミットが `D` で入ったバグで汚染されており、修正が必要な場合は、実際には `D` の子孫である `D..M` のサブセットのみを表示する必要があります。つまり、 `C` と `K` を除外します。これはまさに `--ancestry-path` オプションが行うことです。これを `D..M` 範囲に適用すると、以下のようになります:
+
-----------------------------------------------------------------------
		E-------F
		 \       \
		  G---H---I---J
			       \
				L--M
-----------------------------------------------------------------------
+
`--ancestry-path` の代わりに `--ancestry-path=D` を使用することもできます。これは、`D..M` 範囲に適用された場合と同じことを意味しますが、より明示的です。
+
代わりに、この範囲内の特定のトピックに関心があり、そのトピックによって影響を受けるすべてのコミットに関心がある場合、祖先パスにそのトピックを含む `D..M` のサブセットのみを表示したい場合があります。 たとえば、`--ancestry-path=H D..M` を使用すると、以下のようになります:
+
-----------------------------------------------------------------------
		E
		 \
	      C---G---H---I---J
			       \
				L--M
-----------------------------------------------------------------------
+
一方、 `--ancestry-path=K D..M` は以下のようになります
+
-----------------------------------------------------------------------
		K---------------L--M
-----------------------------------------------------------------------

別のオプション `--show-pulls` について説明する前に、新しいサンプル履歴を作成する必要があります。

簡略化された履歴を見るときにユーザーが直面する一般的な問題は、ファイルを変更したことがわかっているコミットが、ファイルの簡略化された履歴に表示されないことです。そこで、新しい例を示し、その場合に `--full-history` や `--simplify-merges` などのオプションがどのように機能するかを示しましょう。

-----------------------------------------------------------------------
	  .-A---M-----C--N---O---P
	 /     / \  \  \/   /   /
	I     B   \  R-'`-Z'   /
	 \   /     \/         /
	  \ /      /\        /
	   `---X--'  `---Y--'
-----------------------------------------------------------------------

この例では、 `I` が `file.txt` を作成し、それが `A` と`B` と `X` にてさまざまな方法で変更されたとします。ひとり親のコミット `C` と `Z` と `Y` は `file.txt` を変更していません。マージコミット `M` は、マージの競合を解決して、 `A` と `B` の両方の変更を含めることによって作成されたため、どちらにもTREESAMEではありません。ただし、マージコミット `R` は、 `M` の `file.txt` の内容を無視し、 `X` の `file.txt` の内容のみを取得することによって作成されました。 したがって、 `R` は `X` へのTREESAMEですが、 `M` はそうではありません。最後に、 `N` を作成するための自然なマージ解決は、 `R` で `file.txt` の内容を取得することです。したがって、 `N` は `C` ではなく `R` へのTREESAMEです。マージコミット `O` と `P` は、最初の親にはTREESAMEですが、2番目の親である `Z` と `Y` にはついてはそうではありません。

デフォルト・モードを使用する場合、 `N` と `R` は両方ともTREESAMEの親を持っているため、 TREESAMEの親へ向かう経路(edges)はウォークされ、 それ以外のTREESAMEでない経路は無視されます。 結果の履歴グラフは以下のとおりです:

-----------------------------------------------------------------------
	I---X
-----------------------------------------------------------------------

`--full-history` を使用する場合、Gitはすべての経路(edge)を巡ります。これにより、コミット `A` と `B` と マージ `M` が検出されますが、マージコミット `O` と `P` も明らかになります。 親を書き換えると、結果のグラフは以下のようになります:

-----------------------------------------------------------------------
	  .-A---M--------N---O---P
	 /     / \  \  \/   /   /
	I     B   \  R-'`--'   /
	 \   /     \/         /
	  \ /      /\        /
	   `---X--'  `------'
-----------------------------------------------------------------------

ここで、マージコミット `O` と `P` は、実際には `file.txt` への変更を提供しなかったため、余分なノイズを提供します。古いバージョンの `file.txt` に基づいたトピックのみをマージしました。これは、多くの寄稿者が並行して作業し、トピックブランチを単一のトランクに沿ってマージするワークフローを使用するリポジトリの一般的な問題です。 `--full-history` の結果には、関連のない多くのマージが表示されます。

`--simplify-merges` オプションを使用すると、コミット `O` と `P` が結果から消えます。 これは、 `O` と `P` の書き直された2番目の親が、最初の親から到達可能であるためです。これらの経路(edges)が削除されると、コミットは、親にとってTREESAMEである単一の親のコミットのように見えます。これはコミット `N` にも発生し、以下のような履歴ビューが表示されます:

-----------------------------------------------------------------------
	  .-A---M--.
	 /     /    \
	I     B      R
	 \   /      /
	  \ /      /
	   `---X--'
-----------------------------------------------------------------------

このビューでは、 `A` と `B` と `X` からの重要なひとり親の変更がすべて表示されます。また、慎重に解決されたマージ `M` とそれほど慎重に解決されていないマージ `R` も表示されます。これは通常、コミット `A` と `B` がデフォルトのビューの履歴から「消えた」理由を判断するのに十分な情報です。ただし、このアプローチにはいくつかの問題があります。

最初の問題はパフォーマンスです。以前のオプションとは異なり、 `--simplify-merges` オプションでは、単一の結果を返す前にコミット履歴全体をウォークする必要があります。これにより、非常に大規模なリポジトリでこのオプションを使用するのが難しくなる可能性があります。

2番目の問題は監査に関するものです。 多くの寄稿者が同じリポジトリで作業している場合、 どのマージ・コミットが重要なブランチに変更を導入したかが重要です。 上記の問題のあるマージ `R` は、 重要なブランチにマージするために使用されたマージ・コミットではない可能性が高いです。 代わりに、 `R` と `X` を重要なブランチにマージするためにマージ `N` が使われました。 このコミットのコミット・メッセージには、 なぜ変更 `X` が `A` と `B` からの変更を上書きするようになった理由に関する情報が含まれている可能性があります。

`--show-pulls`::
	デフォルトの履歴に表示されるコミットに加えて、最初の親にはTREESAMEではなく、後の親にはTREESAMEである各マージコミットを表示します。
+
マージコミットが `--show-pulls` に含まれている場合、マージは別のブランチから変更を「プル」したかのように扱われます。この例で `--show-pulls` を使用すると(他のオプションは使用しない場合、)結果のグラフは以下のようになります:
+
-----------------------------------------------------------------------
	I---X---R---N
-----------------------------------------------------------------------
+
ここで、コミット `X` と `R` をそれぞれベースブランチにプルしたため、マージコミット `R` と `N` が含まれています。これらのマージは、コミット `A` と `B` がデフォルトの履歴に表示されない理由です。
+
`--show-pulls` が `--simplify-merges` とペアになっている場合、グラフには必要なすべての情報が含まれます:
+
-----------------------------------------------------------------------
	  .-A---M--.   N
	 /     /    \ /
	I     B      R
	 \   /      /
	  \ /      /
	   `---X--'
-----------------------------------------------------------------------
+
`M` は `R` から到達可能であるため、 `N` から `M` への経路(edge)が単純化されていることに注意してください。ただし、 `N` は、変更 `R` をメインブランチに「プル」したため、重要なコミットとして履歴に表示されます。

`--simplify-by-decoration` オプションを使用すると、タグで参照されていないコミットを省略して、履歴のトポロジの全体像のみを表示できます。コミットは、(1)タグによって参照されている場合、または (2)コマンドラインで指定されたパスの内容を変更した場合に、!TREESAMEとしてマークされます(つまり、上記の履歴簡略化ルールの後に保持されます)。他のすべてのコミットはTREESAMEとしてマークされます(簡略化される可能性があります)。

ifndef::git-shortlog[]
ifdef::git-rev-list[]
Bisection Helpers
~~~~~~~~~~~~~~~~~

`--bisect`::
	含まれるコミットと除外されるコミットのほぼ中間にある1つのコミットオブジェクトに出力を制限します。(存在する場合)bad bisection ref `refs/bisect/bad` が含まれるコミットに追加され、（存在する場合)good bisection ref `refs/bisect/good-*` が除外されるコミットに追加されることに注意してください。したがって、 `refs/bisect/` にrefsがないと仮定すると、
+
-----------------------------------------------------------------------
	$ git rev-list --bisect foo ^bar ^baz
-----------------------------------------------------------------------
+
は、2つのコマンドの出力である中間点(midpoint)を出力します
+
-----------------------------------------------------------------------
	$ git rev-list foo ^midpoint
	$ git rev-list midpoint ^bar ^baz
-----------------------------------------------------------------------
+
上記は、ほぼ同じ長さになります。 したがって、回帰を導入する変更を見つけることは、バイナリ検索(binary search)に還元されます。コミットチェーンの長さが1になるまで、新しい中間点(midpoint)を繰り返し生成してテストします。

`--bisect-vars`::
	これは、 `refs/bisect/` 内のrefが使用されないこと、およびシェルによって評価される準備ができているテキストを出力することを除いて、 `--bisect` と同じように計算されます。これらの行は、中間点リビジョンの名前を変数 `bisect_rev` に割り当て、 `bisect_rev` が `bisect_nr` にテストされた後にテストされるコミットの予想数、 `bisect_rev` が `bisect_good`に適していることが判明した場合にテストされるコミットの予想数、 `bisect_rev` が `bisect_bad` に不適切であることが判明した場合にテストされるコミットの予想数、および現在 `bisect_all` に二等分しているコミットの数です。

`--bisect-all`::
	これにより、含まれるコミットと除外されるコミットの間のすべてのコミットオブジェクトが、含まれるコミットと除外されるコミットまでの距離順に出力されます。 `refs/bisect/` のrefは使用されません。それらから最も遠いものが最初に表示されます。(これは `--bisect` によって表示される唯一のものです。)
+
これは、何らかの理由(たとえば、コンパイルできない場合など)でそれらの一部をテストすることを避けたい場合に、テストするための適切なコミットを簡単に選択できるため便利です。
+
このオプションは `--bisect-vars` と一緒に使用できます。この場合、ソートされたすべてのコミットオブジェクトの後に、 `--bisect-vars` が単独で使用された場合と同じテキストが表示されます。
endif::git-rev-list[]
endif::git-shortlog[]

ifndef::git-shortlog[]
Commit Ordering
~~~~~~~~~~~~~~~

デフォルトでは、コミットは新しい順に表示されます。

`--date-order`::
	すべての子が表示されるまで親を表示しませんが、それ以外の場合はコミットタイムスタンプの順序でコミットを表示します。

`--author-date-order`::
	すべての子が表示されるまで親を表示しませんが、それ以外の場合は、作者(author)のタイムスタンプ順にコミットを表示します。

`--topo-order`::
	すべての子が表示されるまで親を表示せず、複数の履歴行が混在するコミットを表示しないようにします。
+
たとえば、以下のようなコミット履歴があります:
+
----------------------------------------------------------------

    ---1----2----4----7
	\	       \
	 3----5----6----8---

----------------------------------------------------------------
+
ここで、数字はコミットタイムスタンプの順序を示し、 `gitrev-list` と `--date-order` のある友達は、タイムスタンプの順序でコミットを示します。つまり、8 7 6 5 4 3 2 1
+
`--topo-order` を使用すると、8 6 5 3 7 4 2 1（または8 7 4 2 6 5 3 1）が表示されます。2つの並列開発トラックからのコミットが混在して表示されないようにするために、いくつかの古いコミットが新しいコミットの前に表示されます。

`--reverse`::
	表示するように選択したコミットを逆の順序で出力します(上記「Commit Limiting」セクション参照)。 `--walk-reflogs` と組み合わせることはできません。
endif::git-shortlog[]

ifndef::git-shortlog[]
Object Traversal
~~~~~~~~~~~~~~~~

これらのオプションは、主にGitリポジトリのパッキングを対象としています。

ifdef::git-rev-list[]
`--objects`::
	リストされたコミットによって参照されるオブジェクトのオブジェクトIDを出力します。 したがって `--objects foo ^bar` は「コミット・オブジェクト `bar` は持っているが `foo` は持っていない場合に、 ダウンロードする必要があるすべてのオブジェクトIDを送ってくれ」という意味です。 下記 `--object-names` も参照してください。

`--in-commit-order`::
	ツリーIDとブロブのIDをコミット順に出力します。 ツリーIDとブロブのIDは、コミットによって最初に参照された後に出力されます。

`--objects-edge`::
	`--objects` に似ていますが、接頭辞 "`-`" 文字が付いた除外されたコミットのIDも出力します。これは linkgit:git-pack-objects[1] によって使用され、ネットワークトラフィックを削減するために、これらの除外されたコミットに含まれるオブジェクトに基づいてオブジェクトを削除された形式で記録する「薄い」パック(thin pack)を構築します。

`--objects-edge-aggressive`::
	`--objects-edge` に似ていますが、時間がかかるという犠牲を払って、除外されたコミットを見つけためにもっともっと頑張ります。これは、`--objects-edge` の代わりに使用されて浅いリポジトリ(shallow repositories)用の「薄い」パック(thin pack)を構築します。

`--indexed-objects`::
	インデックスで使用されるすべてのツリーとブロブがコマンドラインにリストされているかのように見せかけます。 注意: たぶんあなたは一緒に `--objects` も使用したいと思うでしょう。

`--unpacked`::
	`--objects` と一緒の時のみ役立ちます。パックに含まれていないオブジェクトIDを出力します。

`--object-names`::
	`--objects` でのみ有用です。 見つかった オブジェクトID の名前を出力します。 これはデフォルトの振る舞いです。 各オブジェクトの「名前」は曖昧であり、 主にオブジェクトをパッキングするためのヒントとして意図されていることに注意してください。 特に、タグとツリーとブロブの名前は区別されません。 パス名を変更して改行を削除することもできます。 また、 オブジェクトが異なる名前で複数回あらわれる場合は、1 つの名前のみが表示されます。

`--no-object-names`::
	`--objects` と一緒の時のみ役立ちます。見つかったオブジェクトIDの名前は出力されません。これにより、 `--object-names` が反転します。 このフラグを使用すると、 linkgit:git-cat-file[1] などのコマンドで出力をより簡単に解析できます。

`--filter=<filter-spec>`::
	これは `--objectsほげほげ` のどれかと一緒に指定した時のみ役立ちます。 出力するオブジェクトのリストからオブジェクト(通常はブロブ)を省略します。 _<filter-spec>_ は、以下のいずれかになります:
+
`--filter=blob:none` の形式では、すべてのブロブが省略されます。
+
`--filter=blob:limit=<n>[kmg]` の形式では、 少なくとも _<n>_ バイト(bytes)または単位(units)の、 サイズのブロブが省略されます。 _<n>_ はゼロの場合があります。 接尾辞 `k` と `m` と `g` を使用して、 KiBまたはMiBまたはGiB単位にすることができます。 たとえば、 `blob:limit=1k` は `blob:limit=1024` と同じです。
+
`--filter=object:type=(tag|commit|tree|blob)` の形式では、要求されたタイプではないすべてのオブジェクトが省略されます。
+
`--filter=sparse:oid=<blob-ish>` の形式は、ブロブ(またはブロブ式)(<blob-ish> ; ブロブっぽい何か)に格納されている sparse-checkout 定義を利用して、 要求された参照で sparse checkout に必要のないブロブを除外します。
+
`--filter=tree:<depth>` 形式は、 ルート・ツリーからの深さ(depth)が _<depth>_ 以上であるすべてのブロブとツリーを除外します(複数の深さに存在するオブジェクトがある場合は、 最小の深さが基準となります)。 _<depth>_=0 の場合、 コマンドライン(または `--stdin` 使用時は標準入力)で明示的に指定されたもの以外、 一切のブロブやツリーを含めません。 _<depth>_=1 の場合、 _<commit>_ から到達可能なコミットが直接参照しているブロブとツリーのみを含みます(または明示的に指定されたオブジェクトが直接参照しているもの)。 _<depth>_=2 の場合は _<depth>_=1 と同様ですが、 明示的に指定されたコミットやツリーからさらに1段階離れたブロブとツリーも含めます。
+
注意: ファイルシステム上の任意のパスから読み取れる形式である `--filter=sparse:path=<path>` は、セキュリティ上の理由から削除されたことに注意してください。
+
複数の `--filter=` フラグを指定して、フィルターを組み合わせることができます。指定の全てのフィルターで受け入れられるオブジェクトのみが含まれます。
+
`--filter=combine:<filter1>+<filter2>+...<filterN>` の形式を使用して、複数のフィルターを組み合わせることができますが、これは `--filter` フラグを繰り返すよりもずっとずっと難しく、 通常は必要はありません。 フィルタは `+` で結合され、 個々のフィルタは `%` エンコードされます(つまり、URLエンコードされます)。 `+` と `%` 文字に加えて、 次の文字は予約されており、エンコードする必要があります: `~!@#$^&*()[]{}\;",<>?`+&#39;&#96;+ および、 ASCIIコード `0x20` 以下の全ての文字(空白(space)と改行(newline)を含む)。
+
他の任意の文字もエンコードできます。 たとえば、 `combine:tree:3+blob:none` と `combine:tree%3A3+blob%3Anone` は同等です。

`--no-filter`::
	以前の `--filter=` 引数をすべてオフにします。

`--filter-provided-objects`::
	明示的に提供されたオブジェクトのリストをフィルタリングします。そうしないと、どのフィルターとも一致しなくても常に出力されます。 `--filter=` と一緒に使った時のみ役に立ちます。

`--filter-print-omitted`::
	`--filter=` と一緒の時のみ役立ちます。フィルタによって省略されたオブジェクトのリストを出力します。オブジェクトIDの前には ``~'' 文字が付いています。

`--missing=<missing-action>`::
	将来の「部分クローン」(partial clone)開発に役立つデバッグオプション。このオプションは、欠落しているオブジェクトの処理方法を指定します。
+
`--missing=error` の形式は、欠落しているオブジェクトが検出された場合に、 rev-list がエラーで停止(stop)することを要求します。これがデフォルトのアクションです。
+
`--missing=allow-any` の形式を使用すると、欠落しているオブジェクトが検出された場合でも、オブジェクトの走査を続行できます。欠落しているオブジェクトは、結果から黙って省略されます。
+
`--missing=allow-promisor` の形式は `allow-any` に似ていますが、 オブジェクトのトラバーサルは、 EXPECTED promisor が欠落しているオブジェクトに対してのみ続行できます。 予期しない欠落したオブジェクトはエラーを発生させます。
+
`--missing=print` の形式は `allow-any` に似ていますが、欠落しているオブジェクトのリストも出力します。オブジェクトIDの前には ``?'' 文字が付いています。
+
The form `--missing=print-info` is like `print`, but will also print additional information about the missing object inferred from its containing object.`--missing=print-info` という形式は `print` に似ていますが、 欠落オブジェクトについて、 そのオブジェクトを含んでいるオブジェクトから推測される追加情報も出力します。 この情報は欠落オブジェクトのIDと同じ行に `?<oid> [<token>=<value>]...` という形式で出力され、 各 `<token>=<value>` ペアは _SP_ で区切られます。 値はトークンごとに専用の方法でエンコードされますが、 値に含まれる _SP_ や _LF_ は、 必ずエンコード後にこれら二つの問題のあるバイトが現れない形で表現されます。 各 `<token>=<value>` は以下のいずれかです:
+
--
* `path=<path>` は、欠落オブジェクトを含んでいるオブジェクトから推測された、 その欠落オブジェクトのパスを表示します。 パスに _SP_ や特殊文字が含まれる場合は、 必要に応じて C 言語スタイルでエスケープ表現され、 ダブルクォートで囲まれます。
+
* `type=<type>` は、含まれているオブジェクトから推測された、 欠落しているオブジェクトのタイプを示します。
--
+
トラバーサルへ渡された先端(tip)が見つからない場合、 それらも欠落しているとみなされ、 トラバーサルはそれらを無視します。 ただし、 それらのオブジェクト ID を取得できない場合は、 エラーが発生します。

`--exclude-promisor-objects`::
	(内部使用のみ。) promisor境界でのオブジェクトトラバーサルをプレフィルターします。これは部分クローン(partial clone)で使用されます。これは、欠落しているオブジェクトに関するエラーを単に黙らせるのではなく、トラバーサルを制限するため、 `--missing=allow-promisor` よりも強力です。
endif::git-rev-list[]

`--no-walk[=(sorted|unsorted)]`::
	指定されたコミットのみを表示し、祖先をトラバースしない。範囲が指定されている場合、これは効果がありません。引数 `unsorted` が指定されている場合、コミットはコマンドラインで指定された順序で表示されます。それ以外の場合( `sorted` または引数が指定されていない場合)、コミットはコミット時間の逆順に表示されます。 `--graph` と組み合わせることはできません。

`--do-walk`::
	以前の `--no-walk` を上書きします。
endif::git-shortlog[]

ifndef::git-shortlog[]
Commit Formatting
~~~~~~~~~~~~~~~~~

ifdef::git-rev-list[]
これらのオプションを使用すると、 linkgit:git-rev-list[1] は、 右記の特殊なコミット・ログ・ツール・ファミリと同様に動作します:
ifndef::with-breaking-changes[]
linkgit:git-log[1] と linkgit:git-show[1] と linkgit:git-whatchanged[1]
endif::with-breaking-changes[]
ifdef::with-breaking-changes[]
linkgit:git-log[1] と linkgit:git-show[1]
endif::with-breaking-changes[]
endif::git-rev-list[]

include::pretty-options.adoc[]

`--relative-date`::
	`--date=relative` と同じ。

`--date=<format>`::
	`--pretty` を使用する場合など、人間が読める形式で表示される日付に対してのみ有効になります。 `log.date` 構成変数(config variable)は、logコマンドの `--date` オプションのデフォルト値を設定します。デフォルトでは、日付は元のタイムゾーン(コミッターの、または作者のいずれか)で表示されます。 書式に `-local` が追加されている場合(例: `iso-local` )、代わりにユーザーのローカルタイムゾーンが使用されます。
+
--
`--date=relative` は、現在の時刻を基準にした日付を示します。例: ``2 hours ago'' 。 `-local` オプションは `--date=relative` には効果がありません。

`--date=local` は `--date=default-local` のエイリアスです。

`--date=iso` (または `--date=iso8601` )は、タイムスタンプをISO 8601のような形式で表示します。厳密なISO 8601形式との違いは以下のとおりです:

	- `T` 日付/時刻区切り文字の代わりにスペース
	- 時間とタイムゾーンの間のスペース
	- タイムゾーンの時間と分の間にコロンがありません

`--date=iso-strict` (または `--date=iso8601-strict` )は、タイムスタンプを厳密なISO 8601形式で表示します。

`--date=rfc` (または `--date=rfc2822` )は、RFC 2822形式のタイムスタンプを示します。これは、電子メールメッセージでよく見られます。

`--date=short` は、日付のみを表示し、時刻は表示せず、 `YYYY-MM-DD` 形式で表示します。

`--date=raw` は、エポック(1970-01-01 00:00:00 UTC)からの秒数、スペース、UTCからのオフセット(`+` または
`-` の付いた4桁数字で、最初の2つは時間、次の2つは分です)。つまり、タイムスタンプが +strftime("%s %z")+
でフォーマットされているかのようになります。 `-local`
オプションは、seconds-since-epoch値(常にUTCで測定されます)には影響しませんが、付随するタイムゾーン値を切り替えることに注意してください。

`--date=human` は、タイムゾーンが現在のタイムゾーンと一致しない場合はタイムゾーンを表示し、一致する場合は日付全体を出力しません(つまり、「今年」の日付の場合は年の出力をスキップしますが、何があったか覚えてるような過去数日については日付自体もスキップします)。 古い日付の場合、時と分も省略されます。

`--date=unix` は、日付をUnixエポックタイムスタンプ(1970年からの秒数)として表示します。 `--raw` と同様に、これは常にUTCであるため、 `-local` は効果がありません。

`--date=format:<format>` は、内部で処理される `%s` と `%z` と `%Z` を除いて、 フォーマット _<format>_ をあなたのシステムの `strftime` に送ります。 `--date=format:%c` を使用して、 システム・ロケールの推奨形式で日付を表示します。 フォーマット・プレースホルダーの完全なリストについては、 `strftime`(3) マニュアルを参照してください。 `-local` を使用する場合、 正しい構文は `--date=format-local:<format>` です。

`--date=default` はデフォルトの形式であり、 ctime(3) の出力に基づいています。これは 3文字の曜日と、3文字の月と、日付と、「HH:MM:SS」形式の時分秒が 1 ​​行に表示され、 その後に 4 桁の年と、ローカルタイムゾーンが使用されている場合を除きタイムゾーン情報が続きます。例: +Thu Jan 1 00:00:00 1970 +0000+
--

ifdef::git-rev-list[]
`--header`::
	コミットの内容をraw形式で出力します。各レコードはNUL文字で区切られます。

`--no-commit-header`::
	"commit" を含むヘッダー行と、指定された形式の前に出力されたオブジェクトIDを抑制します。これは組み込みフォーマットには影響しません。 カスタムフォーマットのみが影響を受けます。

`--commit-header`::
	以前の `--no-commit-header` を上書きします。
endif::git-rev-list[]

`--parents`::
	コミットの親も出力します( "commit parent..." の形式で)。親の書き換えも可能にします。上記「History Simplification」を参照してください。

`--children`::
	コミットの子も出力します( "commit child..." の形式で)。親の書き換えも可能にします。上記「History Simplification」を参照してください。

ifdef::git-rev-list[]
`--timestamp`::
	生のコミットタイムスタンプを出力します。
endif::git-rev-list[]

`--left-right`::
	対称差のどちら側からコミットに到達できるかをマークします。左側からのコミットには `<` が付けられ、右側からのコミットには `>` が付けられます。 `--boundary` と組み合わせると、それらのコミットの前に `-` が付きます。
+
たとえば、以下のトポロジーの場合:
+
-----------------------------------------------------------------------
	     y---b---b  branch B
	    / \ /
	   /   .
	  /   / \
	 o---x---a---a  branch A
-----------------------------------------------------------------------
+
以下のような出力が得られます:
+
-----------------------------------------------------------------------
	$ git rev-list --left-right --boundary --pretty=oneline A...B

	>bbbbbbb... 3rd on b
	>bbbbbbb... 2nd on b
	<aaaaaaa... 3rd on a
	<aaaaaaa... 2nd on a
	-yyyyyyy... 1st on b
	-xxxxxxx... 1st on a
-----------------------------------------------------------------------

`--graph`::
	出力の左側に、コミット履歴のテキストベースのグラフィック表現を描画します。グラフ履歴を適切に描画するために、コミットの間に余分な行が出力される可能性があります。 `--no-walk` と組み合わせることはできません。
+
これにより、親の書き換えが可能になります。上記「History Simplification」を参照してください。
+
これは、デフォルトで `--topo-order` オプションを意味しますが、 `--date-order` オプションも指定できます。

`--show-linear-break[=<barrier>]`::
	`--graph` を使用しない場合、 すべての履歴ブランチがフラット化されるため、 2つの連続するコミットが線形ブランチに属していないことがわかりにくくなる可能性があります。 このオプションは、 その場合にそれらの間に障壁(barrier)を置きます。 _<barrier>_ が指定されている場合、 デフォルトの障壁文字列の代わりに _<barrier>_ が表示されます。

ifdef::git-rev-list[]
`--count`::
	リストされたコミットの数を示す数値を出力し、他のすべての出力を抑制します。 `--left-right` と一緒に使用する場合は、代わりに、タブで区切って、左右のコミットのカウントを出力します。 `--cherry-mark` と一緒に使用する場合は、これらのカウントからパッチの同等のコミットを省略し、タブで区切られた同等のコミットのカウントを出力します。
endif::git-rev-list[]
endif::git-shortlog[]
