include::urls.adoc[]

REMOTES[[REMOTES]]
------------------

`<repository>` 引数として、URLの代わりに以下のいずれかの名前を使用できます:

* Git構成ファイル(configuration file)内のリモート(remote)として、 `$GIT_DIR/config` または
* `$GIT_DIR/remotes` ディレクトリ内のファイル または
* `$GIT_DIR/branches` ディレクトリ内のファイル

これらはすべて、gitがデフォルトで使用するrefspecをそれぞれ含んでいるため、コマンドラインからrefspecを省略できます。

Named remote in configuration file
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

あなたは、 linkgit:git-remote[1] を使うか、または linkgit:git-config[1] を使うか、または `$GIT_DIR/config` ファイルを手動で編集して、これ以前に構成したリモートの名前から選択できます。このリモートのURLは、リポジトリーへのアクセスに使用されます。コマンドラインでrefspecを指定しない場合、このリモートのrefspecがデフォルトで使用されます。構成ファイルのエントリは以下のようになります:

------------
	[remote "<name>"]
		url = <URL>
		pushurl = <pushurl>
		push = <refspec>
		fetch = <refspec>
------------

`<pushurl>` は push でのみ使用されます。 これはオプションであり、 デフォルトは `<URL>` です。 リモートへの push は、 定義済の全ての pushurls に影響し、 pushurls が定義されていない場合は全ての定義済の URL に影響します。ただし、 複数の url が定義されている場合、 fetch 用は最初に定義された url のみです。

Named file in `$GIT_DIR/remotes`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

あなたは、 `$GIT_DIR/remotes` でファイル名を指定できます。このファイルのURLは、リポジトリーへのアクセスに使用されます。コマンドラインでrefspecを指定しない場合、このファイルのrefspecがデフォルトとして使用されます。このファイルの形式は以下のとおりです:

------------
	URL: one of the above URL formats
	Push: <refspec>
	Pull: <refspec>

------------

`Push:` 行は `git push` で使用され、 `Pull:` 行は `git pull` と `git fetch` で使用されます。追加のブランチマッピングのために、複数の `Push:` および `Pull:` 行を指定できます。

Named file in `$GIT_DIR/branches`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`$GIT_DIR/branches` でファイル名を指定できます。このファイルのURLは、リポジトリーへのアクセスに使用されます。 このファイルの形式は以下のとおりです:


------------
	<URL>#<head>
------------

`<URL>` は必須です。 `#<head>` はオプションです。

コマンドラインで指定しない場合、操作に応じて、gitは以下のrefspecのいずれかを使用します。 `<branch>` は `$GIT_DIR/branchs` 内のこのファイルの名前であり、 `<head>` はデフォルトで `master` になります。

git fetch は以下を使用します:

------------
	refs/heads/<head>:refs/heads/<branch>
------------

git push は以下を使用します:

------------
	HEAD:refs/heads/<head>
------------


[[UPSTREAM-BRANCHES]]
UPSTREAM BRANCHES
-----------------

Branches in Git can optionally have an upstream remote branch. Git defaults to using the upstream branch for remote operations, for example:

* It's the default for `git pull` or `git fetch` with no arguments.
* It's the default for `git push` with no arguments, with some exceptions. For example, you can use the `branch.<name>.pushRemote` option to push to a different remote than you pull from, and by default with `push.default=simple` the upstream branch you configure must have the same name.
* Various commands, including `git checkout` and `git status`, will show you how many commits have been added to your current branch and the upstream since you forked from it, for example "Your branch and 'origin/main' have diverged, and have 2 and 3 different commits each respectively".

The upstream is stored in `.git/config`, in the "remote" and "merge" fields. For example, if `main`'s upstream is `origin/main`:

------------
[branch "main"]
   remote = origin
   merge = refs/heads/main
------------

You can set an upstream branch explicitly with `git push --set-upstream <remote> <branch>` but Git will often automatically set the upstream for you, for example:

* When you clone a repository, Git will automatically set the upstream for the default branch.
* If you have the `push.autoSetupRemote` configuration option set, `git push` will automatically set the upstream the first time you push a branch.
* Checking out a remote-tracking branch with `git checkout <branch>` will automatically create a local branch with that name and set the upstream to the remote branch.

[NOTE]
Upstream branches are sometimes referred to as "tracking information", as in "set the branch's tracking information".
