include::urls.adoc[]

REMOTES[[REMOTES]]
------------------

`<repository>` 引数として、URLの代わりに以下のいずれかの名前を使用できます:

* Git構成ファイル(configuration file)内のリモート(remote)として、 `$GIT_DIR/config` または
* `$GIT_DIR/remotes` ディレクトリ内のファイル または
* `$GIT_DIR/branches` ディレクトリ内のファイル

これらはすべて、gitがデフォルトで使用するrefspecをそれぞれ含んでいるため、コマンドラインからrefspecを省略できます。

Named remote in configuration file
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

あなたは、 linkgit:git-remote[1] を使うか、または linkgit:git-config[1] を使うか、または `$GIT_DIR/config` ファイルを手動で編集して、これ以前に構成したリモートの名前から選択できます。このリモートのURLは、リポジトリーへのアクセスに使用されます。コマンドラインでrefspecを指定しない場合、このリモートのrefspecがデフォルトで使用されます。構成ファイルのエントリは以下のようになります:

------------
	[remote "<name>"]
		url = <URL>
		pushurl = <pushurl>
		push = <refspec>
		fetch = <refspec>
------------

`<pushurl>` は push でのみ使用されます。 これはオプションであり、 デフォルトは `<URL>` です。 リモートへの push は、 定義済の全ての pushurls に影響し、 pushurls が定義されていない場合は全ての定義済の URL に影響します。ただし、 複数の url が定義されている場合、 fetch 用は最初に定義された url のみです。

Named file in `$GIT_DIR/remotes`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

あなたは、 `$GIT_DIR/remotes` でファイル名を指定できます。このファイルのURLは、リポジトリーへのアクセスに使用されます。コマンドラインでrefspecを指定しない場合、このファイルのrefspecがデフォルトとして使用されます。このファイルの形式は以下のとおりです:

------------
	URL: one of the above URL formats
	Push: <refspec>
	Pull: <refspec>

------------

`Push:` 行は `git push` で使用され、 `Pull:` 行は `git pull` と `git fetch` で使用されます。追加のブランチマッピングのために、複数の `Push:` および `Pull:` 行を指定できます。

Named file in `$GIT_DIR/branches`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`$GIT_DIR/branches` でファイル名を指定できます。このファイルのURLは、リポジトリーへのアクセスに使用されます。 このファイルの形式は以下のとおりです:


------------
	<URL>#<head>
------------

`<URL>` は必須です。 `#<head>` はオプションです。

コマンドラインで指定しない場合、操作に応じて、gitは以下のrefspecのいずれかを使用します。 `<branch>` は `$GIT_DIR/branchs` 内のこのファイルの名前であり、 `<head>` はデフォルトで `master` になります。

git fetch は以下を使用します:

------------
	refs/heads/<head>:refs/heads/<branch>
------------

git push は以下を使用します:

------------
	HEAD:refs/heads/<head>
------------


[[UPSTREAM-BRANCHES]]
UPSTREAM BRANCHES
-----------------

Git のブランチには、 オプションで上流(upstream)のリモート・ブランチを含めることができます。 Git はデフォルトでは、 リモート操作に上流ブランチを使用します。 以下に例を示します:

* これは、 引数なしの `git pull` や `git fetch` のデフォルトです。
* これは、引数なしの `git push` のデフォルトです。 たとえば、 `branch.<name>.pushRemote` 設定を使うことで、 pull 元とは異なるリモートに push することができ、 また、 デフォルトの `push.default=simple` の場合には、 設定する上流ブランチの名前は必ずローカル・ブランチのいずれかと同一の名前でなければなりません。
* `git checkout` や `git status` など、 さまざまなコマンドは、 あなたがそのブランチをフォークして以降、 現在いるブランチと上流でそれぞれ何コミット追加されたかを教えてくれます。 たとえば、「あなたのブランチと `origin/main` は分岐しており、 それぞれ 2 個と 3 個の異なるコミットがあります。」("Your branch and 'origin/main' have diverged, and have 2 and 3 different commits each respectively"). と表示されます。

上流(upstream)は `.git/config` の「remote」フィールドと「merge」フィールドに保存されます。 たとえば、 `main` の上流が `origin/main` の場合以下のようになります:

------------
[branch "main"]
   remote = origin
   merge = refs/heads/main
------------

あなたは `git Push --set-upstream <remote> <branch>` を使用して上流ブランチを明示的に設定できますが、 多くの場合、 Git は自動的に上流を設定します。 以下に例を示します:

* あなたがリポジトリーのクローンを作成すると、 Git はデフォルト・ブランチの上流を自動的に設定します。
* あなたが `push.autoSetupRemote` 設定オプションを設定している場合、 初めてブランチをプッシュするときに、 `git Push` が自動的に上流を設定します。
* `git checkout <branch>` を使用してリモート追跡ブランチをチェックアウトすると、 その名前でローカル・ブランチが自動的に作成され、 上流が上流ブランチに設定されます。

[NOTE]
上流ブランチは、「ブランチの追跡情報を設定する」(set the branch's tracking information)と言うように、 「追跡情報」(tracking information)と呼ばれることもあります。
