core.fileMode::
	作業ツリー内のファイルの実行可能ビットを尊重するかどうかをGitに通知します。
+
一部のファイルシステムでは、実行可能としてマークされたファイルがチェックアウトされるか、実行可能ビットがオンになっている実行不可能なファイルをチェックアウトすると、実行可能ビットを失います。 linkgit:git-clone[1] または linkgit:git-init[1] は、ファイルシステムを調査して、実行可能ビットを正しく処理し、この変数が必要に応じて自動的に設定されるかどうかを確認します。
+
リポジトリはファイルモードを正しく処理するファイルシステム上にある可能性があり、この変数は作成時に「true」に設定されますが、後でファイルモードを失う別の環境からアクセスできるようになる可能性があります(たとえば、CIFSマウントを介したext4のエクスポート。CygwinがGit for WindowsまたはEclipseでリポジトリを作成た時など)。このような場合、この変数を「false」に設定する必要がある場合があります。 linkgit:git-update-index[1] を参照してください。
+
(設定ファイルでcore.filemodeが指定されていない場合、)デフォルトはtrueです。

core.hideDotFiles::
	(Windowsのみ)trueの場合、名前がドットで始まる、新しく作成されたディレクトリと新しく作成されたファイルを非表示としてマークします。 `dotGitOnly` の場合、 `.git/` ディレクトリのみが非表示になり、ドットで始まる他のファイルは非表示になりません。デフォルトのモードは `dotGitOnly` です。

core.ignoreCase::
	APFS、HFS+、FAT、NTFSなどの大文字と小文字を区別しないファイルシステムでGitをより適切に機能させるためのさまざまな回避策を可能にする内部変数。たとえば、Gitが「Makefile」を予期しているときにディレクトリリストで「makefile」が見つかった場合、Git それは実際には同じファイルであると想定し、「Makefile」として記憶し続けます。
+
デフォルトはfalseですが、 linkgit:git-clone[1] または linkgit:git-init[1] は、リポジトリの作成時に必要に応じてcore.ignoreCaseを調査してtrueに設定します。
+
あなたのオペレーティングシステムとファイルシステムに関して、Gitは、この変数の適切な構成に依存しています。この値を変更すると、予期しない動作が発生する可能性があります。

core.precomposeUnicode::
	このオプションは、GitのMacOS実装でのみ使用されます。 core.precomposeUnicode=true の場合、GitはMacOSによって行われたファイル名のUnicode分解(unicode decomposition)を元に戻します。これは、MacOSとLinuxまたはWindowsの間でリポジトリを共有する場合に便利です。 (Git for Windows 1.7.10以降、または Git under cygwin 1.7 が必要です)。 falseの場合、ファイル名はGitによって完全に透過的に処理されます。これは、古いバージョンのGitとの下位互換性があります。

core.protectHFS::
	trueに設定されている場合、 HFS+ ファイルシステムで `.git` と同等と見なされるパスのチェックアウトを許可しないでください。デフォルトはMacOSでは `true` 、それ以外の場合は `false` です。

core.protectNTFS::
	trueに設定されている場合、NTFSファイルシステムで問題を引き起こす可能性のあるパスのチェックアウトを許可しないでください。 例えば、 8.3 の「短い」名前と競合します。デフォルトは、Windowsでは「true」、それ以外の場合は「false」です。

core.fsmonitor::
	true に設定すると、この作業ディレクトリのための組み込みファイル・システム・モニター・デーモンが有効になります(linkgit:git-fsmonitor{litdd}daemon[1])。
+
フック・ベースのファイル・システム・モニター(hook-based file system monitors)と同様に、組み込みのファイル・システム・モニターは、多数のファイルを含む作業ディレクトリで Git インデックスを更新する必要がある Git コマンド (例: `git status`) を高速化できます。 組み込みのモニターにより、外部のサードパーティ ツールをインストールして維持する必要がなくなります。
+
組み込みのファイル・システム・モニターは、現在のところ、サポートされているプラットフォームの限られたセットでのみ使用できます。 現在、これには Windows と MacOS が含まれます。
+
それ以外の場合、この変数には fsmonitor フック・コマンドのパス名が含まれます。
+
このフック・コマンドは、要求された日時以降に変更された可能性のあるすべてのファイルを識別するために使用されます。 この情報は、変更されていないファイルの不要なスキャンを回避することで git を高速化するために使用されます。
+
linkgit:githooks[5] の「fsmonitor-watchman」セクションを参照してください。
+
注意: コマンド・ラインでとあるバージョンを使用し、 IDEツールで別のバージョンを使用するなど、Gitの複数のバージョンを同時に使用する場合、 `core.fsmonitor` の定義が拡張され、フック・パス名に加えてブール値が許可されることに注意してください。 Git バージョン 2.35.1 以前はブール値を認識せず、 `true` または `false` の値を呼び出されるフック・パス名と見なします。 Git バージョン 2.26 〜 2.35.1 までは、デフォルトでプロトコルV2 をフックし、 fsmonitor 無し (フル スキャン) にフォールバックします。 2.26 より前のバージョンの Git は、デフォルトでプロトコルV1 をフックし、報告する変更がない(スキャンなし)と暗黙のうちに想定するため、ステータス・コマンドは不完全な結果を報告する場合があります。 このため、組み込みのファイル・システム・モニターを使用する前に、すべての Git バージョンをアップグレードすることをお勧めします。

core.fsmonitorHookVersion::
	「fsmonitor」フックを呼び出すときに使用するプロトコル・バージョンを設定します。
+
現在、バージョン1と2があります。これが設定されていない場合、バージョン2が最初に試行され、失敗した場合はバージョン1が試行されます。 バージョン1は、入力としてtimpstampを使用して、それ以降に変更があったファイルを判別しますが、watchmanなどの一部のモニターでは、timestampを使用すると競合状態になります。バージョン2はopaque stringを使用しているため、モニターは競合状態なしで変更されたファイルを判別するために使用できるものを返すことができます。

core.trustctime::
	falseの場合、インデックスと作業ツリー間のctimeの違いは無視されます。iノードの変更時刻がGitの外部の何か(ファイルシステムクローラーおよび一部のバックアップシステム)によって定期的に変更される場合に役立ちます。 linkgit:git-update-index[1] を参照してください。デフォルトではtrueです。

core.splitIndex::
	trueの場合、インデックスの分割インデックス機能が使用されます。 linkgit:git-update-index[1] を参照してください。 デフォルトではfalseです。

core.untrackedCache::
	インデックスの追跡されていないモノのキャッシュ機能をどうするかを決定します。この変数が設定されていない(unset)か、 `keep` に設定されている場合、キャッシュが保持されます。 `true` に設定すると、自動的に追加されます。 また、 `false` に設定すると、自動的に削除されます。 `true` に設定する前に、mtimeがシステムで正しく機能していることを確認する必要があります。 linkgit:git-update-index[1] を参照してください。 この設定をデフォルトで `true` に設定する `feature.manyFiles` が有効になっていない限り、デフォルトは `keep` です。

core.checkStat::
	core.checkStat が設定されていないか `default` に設定されている場合、Gitがファイルを調べてからファイルが変更されたかどうかを検出するために、stat構造体の多くのフィールドがチェックされます。この構成変数が `minimal` に設定されている場合、mtimeとctimeの1秒未満の部分、ファイルの所有者のuidとgid、iノード番号(およびGitがそれを使用するようにコンパイルされている場合はデバイス番号も)はチェック対象から除外され、mtimeの2分の1の部分(および `core.trustCtime` が設定されている場合はctime)とファイルサイズチェックのみがチェック対象として残ります。
+
(JGitなど)一部のフィールドに使用可能な値を残さないGitの実装があります。これらのフィールドを比較から除外することにより、 `minimal` モードは、同じリポジトリがこれらの他のシステムによって同時に使用される場合の相互運用性に役立つ可能性があります。

core.quotePath::
	パスを出力するコマンド(例: `ls-files` 、 `diff`)は、パス名を二重引用符で囲み(`"..."`)、Cが制御文字をエスケープするのと同じ方法でそれらの文字をバックスラッシュ(`\`)でエスケープすることにより、パス名の「異常な」文字をクォートします(例: TABの場合は `\t` 、LFの場合は `\n` 、バックスラッシュの場合は `\\` )、または0x80より大きい値のバイト(たとえば、UTF-8の "micro" の場合は8進数 `\302\265`)。この変数がfalseに設定されている場合、0x80を超えるバイトは「異常」とは見なされなくなります。この変数の設定に関係なく、二重引用符(`"`)、バックスラッシュ(`\`)、および制御文字は常にエスケープされます。単純なスペース文字は「異常」とは見なされません。多くのコマンドは、 `-z` オプションを使用してパス名を完全にそのままで出力できます。デフォルト値はtrueです。

core.eol::
	作業ディレクトリ内で、( `text` 属性を設定するか、`text=auto` とGitがコンテンツをテキストとして自動検出することにより)テキストとしてマークされたファイルが使用する行末タイプを設定します。 代替手段は、 `lf` と `crlf` と プラットフォームの生来の行末を使用する `native` があります。デフォルト値は `native` です。行末変換の詳細については、 linkgit:gitattributes[5] を参照してください。注意: `core.autocrlf` が `true` または `input` に設定されている場合、この値は無視されることに注意してください。

core.safecrlf::
	trueの場合、行末変換がアクティブなときに `CRLF` の変換が可逆的かどうかをGitにチェックさせます。 Gitは、コマンドが作業ツリー内のファイルを直接または間接的に変更するかどうかを確認します。たとえば、あるファイルをコミットしてから同じファイルをチェックアウトすると、作業ツリーに元のファイルが生成されます。この操作が `core.autocrlf` の現在の設定に当てはまらない場合、Gitはそのファイルを拒否します。変数を `warn` に設定でき、その場合、Gitは不可逆的な変換についてのみ警告はしますが、操作を続行します。
+
CRLF変換には、データが破損する可能性がわずかにあります。有効にすると、Gitはコミット時にCRLFをLFに変換し、チェックアウト時にLFをCRLFに変換します。コミット前にLFとCRLFが混在しているファイルは、Gitでは復元できません。リポジトリにLF行末のみが含まれるように行末を修正するのは、テキストファイルの場合は正しい操作です。しかし、誤ってテキストとして分類されたバイナリファイルの場合、変換によってデータが破損する可能性があります。
+
あなたがこのような破損を早期に認識した場合は、 .gitattributes で変換タイプを明示的に設定することで簡単に修正できます。コミットした直後は、作業ツリーに元のファイルが残っており、このファイルはまだ破損していません。 このファイルはバイナリファイルなのだからと、Gitがファイルを適切に処理することをGitに明示的に伝えることができます。
+
残念ながら、行末が混在するテキストファイルをクリーンアップするという望ましい効果と、バイナリファイルを破損するという望ましくない効果を区別することはできません。どちらの場合も、CRLFは元に戻せない方法で削除されます。テキストファイルの場合、CRLFは行末であるため、これは正しいことですが、バイナリファイルの場合、CRLFを変換するとデータが破損します。
+
注意: この安全性チェックは、チェックアウトによって、 `core.eol` と `core.autocrlf` の異なる設定に対して元のファイルと同じファイルが生成されることを意味するのではなく、現在のファイルに対してのみ生成されることに注意してください。 たとえば、 `LF` を含むテキストファイルは `core.eol=lf` で受け入れられ、後で ` core.eol=crlf` でチェックアウトできます。この場合、結果のファイルには `CRLF` が含まれますが、 元のファイルには `LF`が含まれていました。 ただし、両方の作業ツリーで、行末は一貫しています。つまり、すべて `LF` または、 すべて `CRLF` のいずれかですが、混合されることはありません。行末が混在するファイルは、 `core.safecrlf` メカニズムによって報告されます。

core.autocrlf::
	この変数を「true」に設定することは、すべてのファイルで「text」属性を「auto」に設定し、core.eolを「crlf」に設定することと同じです。 作業ディレクトリに `CRLF` 行末があり、リポジトリにLF行末がある場合は、trueに設定します。 この変数は「input」に設定できます。この場合、出力変換は実行されません。

core.checkRoundtripEncoding::
	`working-tree-encoding` 属性で使用された場合に Git が UTF-8 のラウンドトリップチェックを行うエンコーディングの、カンマや空白で区切られたリスト(linkgit:gitattributes[5] を参照)。デフォルト値は `SHIFT-JIS` です。

core.symlinks::
	falseの場合、シンボリックリンクは、リンクテキストを含む小さなプレーンファイルとしてチェックアウトされます。 linkgit:git-update-index[1] と linkgit:git-add[1] は、記録されたタイプを通常のファイルに変更しません。シンボリックリンクをサポートしないFATのようなファイルシステムで役立ちます。
+
デフォルトは true ですが、linkgit:git-clone[1] や linkgit:git-init[1] はリポジトリの作成時に core.symlinks を調査して必要に応じて core.symlinks を false に設定します。

core.gitProxy::
	フェッチにGitプロトコルを使用する場合、リモートサーバーへの直接接続を確立する代わりに(「コマンドホストポート」として)実行する「プロキシコマンド」。変数値が「COMMAND for DOMAIN」形式の場合、コマンドは、指定されたドメイン文字列で終わるホスト名にのみ適用されます。この変数は複数回設定でき、指定された順序で照合されます。最初にマッチしたものが採用されます。
+
`GIT_PROXY_COMMAND` 環境変数(特別な「for」処理なしで常に普遍的に適用されます)によってオーバーライドできます。
+
特別な文字列 `none` をプロキシコマンドとして使用して、特定のドメインパターンにプロキシを使用しないように指定できます。これは、ファイアウォール内のサーバをプロキシの使用から除外する一方で、外部ドメインには共通のプロキシをデフォルトで使用する場合に便利です。

core.sshCommand::
	この変数が設定されている場合、 `git fetch` と `git push` は、リモートシステムに接続する必要があるときに、 `ssh` の代わりに指定したコマンドを使用します。このコマンドは `GIT_SSH_COMMAND` 環境変数と同じ形式であり、環境変数が設定されると上書きされます。

core.ignoreStat::
	trueの場合、Gitはインデックスと作業ツリーの両方で同じように更新された追跡ファイルの「assume-unchanged」(無変更と仮定する)ビットを設定することにより、ファイルが変更されたかどうかを検出するための lstat() 呼び出しを回避します。
+
ファイルがGitの外部で変更される場合、ユーザーは変更されたファイルを明示的にステージングする必要があります(たとえば、 linkgit:git-update-index[1] の「Examples」セクションを参照)。 Gitは通常、これらのファイルへの変更を検出しません。
+
これは、 CIFS/Microsoft Windows など、 lstat() 呼び出しが非常に遅いシステムで役立ちます。
+
false がデフォルトです。

core.preferSymlinkRefs::
	HEADおよびその他のシンボリック参照ファイルのデフォルトの「symref」形式の代わりに、シンボリックリンクを使用します。これは、HEADがシンボリックリンクであることを期待する古いスクリプトを操作するために必要になる場合があります。
+
この設定は非推奨であり、 Git 3.0 で削除される予定です。 将来的には、 シンボリック参照は常にテキスト形式の symref として書き込まれます。

core.alternateRefsCommand::
	alternateから利用可能な履歴のヒントをアドバタイズする場合は、 linkgit:git-for-each-ref[1] の代わりに、シェルを使用して指定されたコマンドを実行します。最初の引数は、alternateの絶対パスです。出力には、1行に1つの16進オブジェクトIDが含まれている必要があります(つまり、 `git for-each-ref --format='%(objectname)'` によって生成されたものと同じある必要があります)。
+
注意: 通常、 あなたは `git for-each-ref` をconfig値に直接入れることはできません。これは、リポジトリパスを引数として受け取らないためです(ただし、あなたは上記のコマンドをシェルスクリプトでラップすることはできます)。

core.alternateRefsPrefixes::
	alternateからの参照を一覧表示する場合は、指定のプレフィックスで始まる参照のみを一覧表示します。プレフィックスは linkgit:git-for-each-ref[1] への引数として指定されたかのようにマッチングします。複数のプレフィックスを一覧表示するには、それらを空白で区切ります。 `core.alternateRefsCommand` が設定されている場合、 `core.alternateRefsPrefixes` を設定しても効果ありません。

core.bare::
	trueの場合、このリポジトリは「ベア」(bare;ベアリポジトリ)であると見なされ、作業ディレクトリは関連付けられていません。この場合、 linkgit:git-add[1] や linkgit:git-merge[1] など、作業ディレクトリを必要とする多くのコマンドが無効になります。
+
この設定は、リポジトリの作成時に linkgit:git-clone[1] または linkgit:git-init[1] によって自動的に推測されます。 デフォルトでは、 `/.git` で終わるリポジトリはベアではないと見なされ(bare = false)、他のすべてのリポジトリはベアであると見なされます(bare 
= true)。

core.worktree::
	作業ツリーのルートへのパスを設定します。 `GIT_COMMON_DIR` 環境変数が設定されている場合、 core.worktree は無視され、作業ツリーのルートを決定するために使用されません。core.worktree は `GIT_WORK_TREE` 環境変数と `--work-tree` コマンドラインオプションで上書きできます。値は、絶対パスまたは `.git` ディレクトリへの相対パスにすることができます。これは、 `--git-dir` または GIT_DIR 環境変数で指定されるか、`--git-dir` や GIT_DIR 環境変数の指定が無い場合は自動的に検出されます。`--work-tree` と GIT_WORK_TREE と core.worktree のいずれも指定されていない場合、現在の作業ディレクトリが作業ツリーの最上位と見なされます。
+
注意: この変数は、ディレクトリの `.git｀ サブディレクトリ内の構成ファイルに設定されている場合でも適用され、その値は前者のディレクトリとは異なることに注意してください(たとえば、 `/path/to/` ディレクトリの `.git` サブディレクトリ内の構成ファイル `/path/to/.git/config` 内の core.worktree が `/different/path` に設定されていたとする)、これはおそらく設定ミスです。あなたが `/path/to` ディレクトリでGitコマンドを実行すると、引き続き `/different/path` が作業ツリーのルートとして使用され、あなたが何をしているのか分かっている(たとえば、リポジトリの通常の作業ツリーとは異なる場所に同じインデックスの読み取り専用スナップショットを作成している)のでない限り混乱を招く可能性があります。

core.logAllRefUpdates::
	reflog を有効にします。 参照 <ref> への更新は、 ファイル `$GIT_DIR/logs/<ref>` が存在する場合にのみ、 新しい SHA-1 と古い SHA-1や、日時や、 更新理由を追記することで記録されます。 この構成変数を `true` にすると、 ブランチ・ヘッド(refs/heads/ 以下)や、 リモート参照(refs/remotes/ 以下)や、 ノート参照(refs/notes/ 以下)や、 シンボリック参照 HEAD に、 ついて、 対応する `$GIT_DIR/logs/<ref>` ファイルが存在しない場合に自動的に作成されます。 `always` に設定すると、 `refs/` 以下の任意の参照に対して、 reflog ファイルが存在しない場合に自動的に作成されます。
+
この情報を使用して、「2日前」(2 days ago)にブランチの先端であったコミットを判別できます。
+
この値は、作業ディレクトリが関連付けられているリポジトリではデフォルトでtrueになり、ベアリポジトリではデフォルトでfalseになります。

core.repositoryFormatVersion::
	リポジトリの形式とレイアウトのバージョンを識別する内部変数。 linkgit:gitrepository-layout[5] 参照。

core.sharedRepository::
	`group` (または `true` )の場合、リポジトリはグループ内の複数のユーザー間で共有可能になります(すべてのファイルとオブジェクトがグループ書き込み可能であることを確認してください)。 `all` (または `world` または `everybody`)の場合、リポジトリはグループ共有可能であることに加えて、すべてのユーザーが読み取り可能になります。 `umask` (または `false` )の場合、Gitは umask(2) によって報告された権限を使用します。 `0xxx` (`0xxx` は8進数)の場合、リポジトリ内のファイルはこのモード値になります。「0xxx」はユーザーのumask値をオーバーライドします(他のオプションはユーザーのumask値の要求された部分のみをオーバーライドします)。例: `0660` は、所有者とグループがリポジトリを 読み取り/書き込み 可能にしますが、他のユーザーはアクセスできません(umaskが `0022` などでない限り、 `group` と同等です)。 `0640` は、グループで読み取り可能ですが、グループで書き込み可能ではないリポジトリです。 linkgit:git-init[1] を参照してください。 デフォルトでは False です。

core.warnAmbiguousRefs::
	true の場合、 渡した参照名があいまいでリポジトリー内の複数の参照と一致する可能性がある場合に、 Git は警告を表示します。 デフォルトでは true

core.compression::
	デフォルトの圧縮レベルを示す整数 -1〜9。 -1はzlibのデフォルトです。0は圧縮がないことを意味し、1〜9はさまざまな速度とサイズのトレードオフであり、9が最も低速です。設定されている場合、これは `core.looseCompression` や `pack.compression` などの他の圧縮変数のデフォルトを提供します。

core.looseCompression::
	整数 -1〜9は、パックファイルにないオブジェクトの圧縮レベルを示します。-1はzlibのデフォルトです。0は圧縮がないことを意味し、1〜9はさまざまな速度とサイズのトレードオフであり、9が最も低速です。設定されていない場合、デフォルトは core.compression です。 これが設定されていない場合、デフォルトは1(最高速度)になります。

core.packedGitWindowSize::
	1回のマッピング操作でメモリにマップするパックファイルのバイト数。ウィンドウサイズを大きくすると、システムが少数の大きなパックファイルをより迅速に処理できるようになる場合があります。ウィンドウサイズを小さくすると、オペレーティングシステムのメモリマネージャへの呼び出しが増えるため、パフォーマンスに悪影響を及ぼしますが、多数の大きなパックファイルにアクセスする場合のパフォーマンスが向上する可能性があります。
+
コンパイル時にNO_MMAPが設定されている場合、デフォルトは1Mバイトです。それ以外の場合、32ビットプラットフォームでは32Mバイト、64ビットプラットフォームでは1Gバイトです。これは、すべてのユーザー/オペレーティングシステムにとって妥当なはずです。おそらくあなたはこの値を調整する必要はありません。
+
`k` または `m` または `g` の一般的な単位接尾辞がサポートされています。

core.packedGitLimit::
	パックファイルからメモリに同時にマップする最大バイト数。Gitが操作を完了するために一度にこれ以上のバイトにアクセスする必要がある場合、Gitは既存の領域のマップを解除して、プロセス内の仮想アドレス空間を再利用します。
+
デフォルトは、32ビットプラットフォームでは256Mバイト、64ビットプラットフォームでは32Tバイト(事実上無制限)です。これは、超巨大プロジェクトを除いて、すべてのユーザー/オペレーティングシステムにとって妥当なはずです。あなたは、おそらくこの値を調整する必要はありません。
+
`k` または `m` または `g` の一般的な単位接尾辞がサポートされています。

core.deltaBaseCacheLimit::
	複数の削除されたオブジェクトによって参照される可能性のあるベースオブジェクトをキャッシュするために予約するスレッドあたりの最大バイト数。解凍(decompress)されたベースオブジェクト全体をキャッシュに保存することで、Gitは頻繁に使用されるベースオブジェクトを何度もアンパックおよび解凍することを回避できます。
+
デフォルトは、すべてのプラットフォームで96Mバイトです。これは、超巨大プロジェクトを除いて、すべてのユーザー/オペレーティングシステムにとって妥当なはずです。あなたは、おそらくこの値を調整する必要はありません。
+
`k` または `m` または `g` の一般的な単位接尾辞がサポートされています。

core.bigFileThreshold::
	「大きい」(big)と見なされるファイルのサイズは、以下で説明するように、多数の git コマンドの動作と、そのようなファイルがリポジトリ内に格納される方法を変更します。 デフォルトは 512 MiB です。 `k` または `m` または `g` の一般的な単位サフィックスがサポートされています。
+
構成された制限を超えるファイルは以下のようになります:
+
* デルタ圧縮を試行せずに、圧縮された状態でパックファイルに保存されます。
+
デフォルトの制限は、主にこのユースケースを念頭に置いて設定されています。 これにより、ほとんどのプロジェクトのソース・コードとその他のテキスト・ファイルはデルタ圧縮されますが、より大きなバイナリ・メディア・ファイルは圧縮されません。
+
デルタ圧縮なしで大きなファイルを保存すると、ディスク使用量が増えるというわずかな犠牲を払って、過度のメモリ使用量を回避できます。
+
* 「binary」とラベル付けされているかのように扱われます(linkgit:gitattributes[5] 参照)。 例えば linkgit:git-log[1] と linkgit:git-diff[1] は、この制限を超えるファイルのdiffを計算しません。
+
* 通常、書き込み時にストリーミングされます。これにより、過度のメモリ使用が回避されますが、一定のオーバーヘッドが発生します。 これを利用するコマンドには、 linkgit:git-archive[1] や linkgit:git-fast-import[1] や linkgit:git-index-pack[1] や linkgit:git-unpack-objects[1] や linkgit:git-fsck[1] などがあります。

core.excludesFile::
	`.gitignore` (ディレクトリごと)と `.git/info/exclude` に加えて、追跡されることを意図されていないパスを記述するパターンを含むファイルへのパス名を指定します。 デフォルトは `$XDG_CONFIG_HOME/git/ignore` です。 `$XDG_CONFIG_HOME` が設定されていないか空の場合、代わりに `$HOME/.config/git/ignore` が使用されます。 linkgit:gitignore[5] を参照してください。

core.askPass::
	パスワードを対話的に要求する一部のコマンド(svnやhttpインターフェイスなど)は、この変数の値を介して指定された外部プログラムを使用するように指示できます。 `GIT_ASKPASS` 環境変数でオーバーライドできます。設定されていない場合は、 `SSH_ASKPASS` 環境変数の値にフォールバックするか、それが失敗した場合は、単純なパスワードプロンプトにフォールバックします。外部プログラムには、コマンドライン引数として適切なプロンプトが与えられ、その標準出力にパスワードを書き出す事になっています。

core.attributesFile::
	`.gitattributes` (ディレクトリごと) と `.git/info/attributes` に加えて、Gitはこのファイルで属性を調べます(linkgit:gitattributes[5] を参照)。パスの拡張は、 `core.excludesFile` の場合と同じ方法で行われます。デフォルト値は `$XDG_CONFIG_HOME/git/attributes` です。 `$XDG_CONFIG_HOME` が設定されていないか空の場合、代わりに `$HOME/.config/git/attributes` が使用されます。

core.hooksPath::
	デフォルトでは、Gitは `$GIT_DIR/hooks` ディレクトリでフックを探します。これを別のパスに設定します。例えば `/etc/git/hooks` です。そしてGitはそのディレクトリであなたのフックを見つけようとします。例えば `$GIT_DIR/hooks/pre-receive` の代わりに `/etc/git/hooks/pre-receive` です。
+
パスは絶対パスでも相対パスでもかまいません。相対パスは、フックが実行されているディレクトリを基準にしたものと見なされます(linkgit:githooks[5] の「DESCRIPTION」セクションを参照)。
+
この設定変数は、あなたのGitフックをリポジトリごとに設定するのではなく一元的に設定したい場合や、デフォルトのフックを変更した `init.templateDir` に代わるより柔軟で一元的な設定として有用です。
+
すべてのフックを完全に無効化したい場合は、 `core.hooksPath` を `/dev/null` に設定できます。 これは通常、 熟練したユーザーのみが使用すべきであり、 通常はコマンド単位で `git -c core.hooksPath=/dev/null ...` のような構成パラメータを使って行うのが適切です。

core.editor::
	エディタを起動してメッセージを編集できる `commit` や `tag` などのコマンドは、この変数が設定されているときにこの変数の値を使用し、環境変数 `GIT_EDITOR` は設定されていません。 linkgit:git-var[1] を参照してください。

core.commentChar::
core.commentString::
	メッセージを編集できる `commit` や `tag` などのコマンドは、 この文字で始まるコメント行とみなし、 エディターから戻った後にそれらを削除します(デフォルトは `#`)。
+
ifndef::with-breaking-changes[]
`auto` に設定した場合、 `git-commit` は既存のコミット・メッセージ内のどの行の先頭文字とも重複しない文字を自動的に選択します。 `auto` のサポートは非推奨であり、 以下の制限があるため Git 3.0 で削除される予定です:
+
--
* これは、 コミット・メッセージ・テンプレートにコメントを追加する場合と互換性がありません。 これには、 `cherry-pick` や `merge` や `rebase` や `revert` がコミット・メッセージに追加する競合コメントも含まれます。
* これは、 prepare-commit-msg フックでコミット・メッセージにコメントを追加する場合と互換性がありません。
* これは、 リベース時の `fixup` や `squash` コマンドと互換性がありません。
* これは `git notes` では尊重されません。
--
+
endif::with-breaking-changes[]
注意: これら 2 つの変数は相互にエイリアスとして機能し、 Git の最新バージョンでは文字列(たとえば `//` や `⁑⁕⁑`) を `commentChar` とともに自由に使用できることに注意してください。 v2.45.0 より前のバージョンの Git では、`commentString` は無視されます。 しかし、 複数の ASCII バイトで構成される `commentChar` の値は拒否されます。 Git の古いバージョンと新しいバージョンで構成を使用する予定がある場合は、 以下のように両方を指定することをお勧めします:
+
    [core]
    # 古目のバージョン用の「1文字」
    commentChar = "#"
    # 新しいバージョン用の「文字列」(ファイル内で commentChar より
    # 後で現れるため、 commentChar をオーバーライドします)
    commentString = "//"

core.filesRefLockTimeout::
	個々の参照をロックしようとしたときに再試行する時間の長さ(ミリ秒単位)。値0は、まったく再試行しないことを意味します。 -1 は無期限に試すことを意味します。 デフォルトは100です(つまり、100ミリ秒再試行します)。

core.packedRefsTimeout::
	`packed-refs` ファイルをロックしようとしたときに再試行する時間の長さ(ミリ秒単位)。値0は、まったく再試行しないことを意味します。-1は無期限に試すことを意味します。デフォルトは1000です(つまり、1秒間再試行します)。

core.pager::
	Gitコマンドで使用するテキストビューア( `less` など)。値はシェルによって解釈されることを意図しています。 優先順位は、 `$GIT_PAGER` 環境変数、 `core.pager` 構成、 `$PAGER` 、そしてコンパイル時に選択されたデフォルト(通常は `less`)です。
+
`LESS` 環境変数が設定されていない(unset)場合、Gitはそれを `FRX` に設定(set)します(`LESS` 環境変数が設定されている場合は、Gitはそれをまったく変更しません)。Gitのデフォルト設定である `LESS` を選択的にオーバーライドする場合は、 `core.pager` を、例えば `less -S` と設定できます。これはGitによってシェルに渡され、Gitは最後のコマンドを `LESS=FRX less -S` に変換します。環境変数では `S` オプションを設定しませんが、コマンドラインでは設定し、長い行を切り捨てるように指示します。同様に、 `core.pager` を `less -+F` に設定すると、環境変数によって指定された `F`オプションがコマンドラインによって非アクティブになり、 `less` の「1画面の場合は終了」動作が非アクティブになります。特定のGitコマンドに対していくつかのフラグを特に指定してアクティブにすることができます。たとえば、 `pager.blame` を `less -S` に設定すると、 `git blame` でのみページャーで行の切り捨てが有効になります。
+
同様に、 `LV` 環境変数が設定されていない場合、Gitはそれを `-c` に設定します。この設定を上書きするには、 `LV` を別の値でエクスポートするか、 `core.pager` を `lv +c` に設定します。

core.whitespace::
	注意すべき一般的な空白(whitespace)の問題のコンマ(`,`)区切りのリスト。 `gitdiff` は `color.diff.whitespace` を使用してそれらを強調表示し、 `git apply --whitespace = error` はそれらをエラーと見なします。 接頭辞 `-` を付けて、それらのいずれかを無効にすることができます(例: `-trailing-space`):
+
* `blank-at-eol` は、行末の末尾の空白をエラーとして扱います(デフォルトで有効になっています)。
* `space-before-tab` は、行の最初のインデント部分のタブ文字の直前に表示されるスペース文字をエラーとして扱います(デフォルトで有効になっています)。
* `indent-with-non-tab` は、同等のタブではなくスペース文字でインデントされた行をエラーとして扱います(デフォルトでは有効になっていません)。
* `tab-in-indent` は、行の最初のインデント部分にあるタブ文字をエラーとして扱います(デフォルトでは有効になっていません)。
* `blank-at-eof` は、ファイルの最後に追加された空白行をエラーとして扱います(デフォルトで有効になっています)。
* `trailing-space` は、` blank-at-eol` と `blank-at-eof` の両方をカバーする省略形です。
* `cr-at-eol` は、行末のキャリッジリターンをラインターミネータの一部として扱います。つまり、そのようなキャリッジリターンの前の文字が空白(a whitespace)でない場合、 `trailing-space` はトリガーされません(デフォルトでは有効になっていません)。
* `tabwidth=<n>` は、タブが占める文字数を示します。 これは、 `indent-with-non-tab` と、 Gitが `tab-in-indent` エラーを修正する場合に関連します。デフォルトのタブ幅は8です。許可される値は1〜63です。

core.fsync::
	作成または変更時に core.fsyncMethod を介して強化する必要があるリポジトリのコンポーネントのコンマ区切りリスト。 コンポーネントの前に `-` を付けることで、コンポーネントの堅牢化を無効にすることができます。 堅牢化されていないアイテムは、不正なシステム・シャットダウンが発生した場合に失われる可能性があります。 特別な要件がない限り、このオプションを空のままにするか、 `committed` または `added` または `all` のいずれかを選択することをお勧めします。
+
この構成が検出されると、一連のコンポーネントがプラットフォームのデフォルト値で開始され、無効なコンポーネントが削除され、追加のコンポーネントが追加されます。 `none` は、プラットフォームのデフォルトが無視されるように状態をリセットします。
+
空の文字列は、 fsync 構成をプラットフォームのデフォルトにリセットします。 ほとんどのプラットフォームのデフォルトは `core.fsync=committed,-loose-object` と同等で、パフォーマンスは良好ですが、システムが正常にシャットダウンされなかった場合に最近の作業が失われるリスクがあります。
+
* `none` は、fsync されたコンポーネントのセットをクリアします。
* `loose-object` は、リポジトリに追加されたオブジェクトを緩いオブジェクト形式に堅牢化します。
* `pack` は、リポジトリに追加されたオブジェクトをパックファイル形式に堅牢化します。
* `pack-metadata` は、パックファイルのビットマップとインデックスに堅牢化します。
* `commit-graph` は、コミット・グラフ・ファイルを堅牢化します。
* `index` は、変更時にインデックスに堅牢化します。
* `objects` は、 `loose-object,pack` と同等の集約オプションです。
* reference` は、リポジトリで変更された参照に堅牢化します。
* `derived-metadata` は、 `pack-metadata,commit-graph` と同等の集約オプションです。
* `committed` は、現在のところ `objects` と同等の集約オプションです。 このモードでは、 `git commit` または同様のコマンドでリポジトリにコミットされた作業が確実に堅牢化されるようにして、パフォーマンスがいくらか犠牲になります。
* `added` は、現在のところ `committed,index` と同等の集約オプションです。 このモードでは、 `git add` などのコマンドや同様の操作の結果が確実に堅牢化されるようにして、パフォーマンスが犠牲が追加されます。
* `all` は、上記のすべての個々のコンポーネントをsyncする集約オプションです。

core.fsyncMethod::
	fsync および関連するプリミティブを使用してリポジトリ・データを堅牢化するために Git が使用する戦略を示す値。
+
* `fsync` は、 fsync() システム・コール、または、当該プラットフォームで fsync() システム・コールと同等のものを使用します。
* `writeout-only` はページ・キャッシュの書き戻し(writeback)要求を発行しますが、ファイル・システムとストレージ・ハードウェアによっては、システム・クラッシュが発生した場合にリポジトリに追加されたデータが保持されない場合があります。 これは macOS のデフォルト・モードです。
* `batch` は、書き込み専用(writeout-only)フラッシュを使用してディスク・ライトバック・キャッシュに複数の更新をステージングするモードを有効にし、その後、操作の最後にディスク・キャッシュ・フラッシュをトリガーするためにダミー・ファイル 1 つによっての完全な fsync を実行します。
+
現在、 `batch` モードは緩いオブジェクト・ファイルにのみ適用されます。 他のリポジトリ・データは、 `fsync` が指定されたかのように永続化されます。 このモードは、 macOS では HFS+ または APFS ファイルシステムに格納されたリポジトリに対して、 Windows では NTFS または ReFS ファイルシステムに格納されたリポジトリに対しては `fsync` と同じくらい安全であると予想されます。

core.fsyncObjectFiles::
	このブール値は、オブジェクトファイルを書き込むときに `fsync()` を有効にします。 この設定は非推奨です。 代わりに core.fsync を使用してください。
+
この設定は、 緩いオブジェクト形式で Git リポジトリに追加されたデータに影響します。 true に設定すると、Git は fsync または同様のシステム・コールを発行してキャッシュをフラッシュし、不正なシステム・シャットダウンに直面しても緩いオブジェクトの一貫性が維持されるようにします。

core.preloadIndex::
	`git diff` などの操作のために並列インデックスプリロードを有効にする
+
これにより、特にキャッシュセマンティクスが弱く、IOレイテンシが比較的高いNFSなどのファイルシステムで、「git diff」や「git status」などの操作を高速化できます。有効にすると、Gitはファイルシステムデータとのインデックス比較を並行して実行し、重複する入出力を許可します。デフォルトはtrueです。

core.unsetenvvars::
	Windowsのみ: 他のプロセスを生成する前に設定を解除する必要がある環境変数の名前のコンマ(`,`)区切りのリスト。Git for Windowsが独自のPerlインタープリターの使用を主張しているという事実を説明するために、デフォルトは `PERL5LIB` です。

core.createObject::
	これを `link` に設定できます。この場合、ハードリンク後のソース削除を、オブジェクトの作成が既存のオブジェクトが上書しないことをチェックするために使用します。
+
一部のファイルシステム/オペレーティングシステムの組み合わせでは、これは信頼できませんので、この構成設定を `rename` に設定します。ただし、これにより、既存のオブジェクトファイルが上書きされないようにするチェックが削除されます。

core.notesRef::
	コミット・メッセージを表示するときは、 指定の参照に保存されているノートも表示します。 参照は完全に修飾されている必要があります。 指定の参照が存在しない場合、 それはエラーではありませんが、 そのノートを出力してはいけないないことを意味します。
+
この設定のデフォルトは「refs/notes/commits」であり、 `GIT_NOTES_REF` 環境変数でオーバーライドできます。 linkgit:git-notes[1] を参照してください。

core.commitGraph::
	trueの場合、gitはcommit-graphファイル(存在する場合)を読み取り、コミットのグラフ構造をパースします。デフォルトはtrueです。詳細については、 linkgit:git-commit-graph[1] を参照してください。

core.useReplaceRefs::
	`false` に設定すると、コマンドラインで `--no-replace-objects` オプションが指定されたかのように振る舞います。詳細については linkgit:git[1] と linkgit:git-replace[1] を参照してください。

core.multiPackIndex::
	multi-pack-index ファイルを使用して、単一のインデックスを使用して複数のパックファイルを追跡します。詳細については linkgit:git-multi-pack-index[1] を参照してください。デフォルトはtrueです。

core.sparseCheckout::
	「スパースチェックアウト」(sparse checkout)機能を有効にします。 詳細については、 linkgit:git-sparse-checkout[1] を参照してください。

core.sparseCheckoutCone::
	スパースチェックアウト機能の「コーンモード」(cone mode)を有効にします。スパースチェックアウトファイルに含まれるパターンのセットが限られている場合、このモードはパフォーマンスに大きな利点をもたらします。 この変数を `false` に設定することで、より柔軟なパターンを指定できるように「非コーンモード」(non-cone mode)を要求できます。 詳細については linkgit:git-sparse-checkout[1] を参照してください。

core.abbrev::
	オブジェクト名の省略形の長さを設定します。指定されていないか「auto」に設定されている場合、リポジトリ内のパックされたオブジェクトのおおよその数に基づいて適切な値が計算されます。それは、省略されたオブジェクト名がしばらくの間(some time)一意であるのに十分な長さです。「no」に設定すると、省略形は作成されず、オブジェクト名は完全な長さで表示されます。 最小の長さは4です。

core.maxTreeDepth::
	Git がツリーのトラバース中に再帰的に使用できる最大の深さ(たとえば "a/b/cde/f" の深さは 4)。 これは、 Git を正常に中止で(abort cleanly)きるようにするためのフェイルセーフであり、 通常は調整する必要はありません。 Git が MSVC でコンパイルされる場合、 デフォルトは 512 です。 それ以外の場合、 デフォルトは 2048 です。
