format.attach::
	`format-patch` のデフォルトとして マルチパート(multipart)/混合(mixed) の添付(attachments)を有効にします。 値は二重引用符(`"..."`)で囲まれた文字列にすることもでき、その場合、 添付ファイルがデフォルトとして有効になり、 この二重引用符で囲まれた文字列が境界として設定されます。 linkgit:git-format-patch[1] の `--attach` オプションを参照してください。 以前に設定した値を無効にするには、値を空の文字列に設定します。

format.from::
	`--from` オプションのデフォルト値をformat-patchに提供します。ブール値、または名前と電子メールアドレスを受け入れます。 falseの場合、format-patchはデフォルトで `--no-from` になり、パッチメールの `From:` フィールドに直接コミット作成者を使用します。 trueの場合、format-patchはデフォルトで `--from` になり、パッチメールの `From:` フィールドにあなたのコミッターIDを使い、異なる場合にはパッチメールの本文に `From:` フィールドを含めます。 ブール値でない値を設定した場合、format-patch はあなたのコミッターIDの代わりにその値を使用します。 デフォルトは false です。

format.forceInBodyFrom::
	`--[no-]force-in-body-from` オプションのデフォルト値を format-patch に提供します。 デフォルトは false です。

format.numbered::
	パッチ件名のシーケンス番号を有効または無効にできるブール値。 デフォルトは「auto」で、複数のパッチがある場合にのみ有効になります。 「true」または「false」に設定することで、すべてのメッセージに対して有効または無効にできます。 linkgit:git-format-patch[1]の `--numbered` オプションを参照してください。

format.headers::
	メールで送信するパッチに含める追加の電子メールヘッダー。 linkgit:git-format-patch[1] を参照してください。

format.to::
format.cc::
	メールで送信するパッチに含める追加の受信者。 linkgit:git-format-patch[1]の `--to` および` --cc` オプションを参照してください。

format.subjectPrefix::
	format-patchのデフォルトは、 `[PATCH]` という接頭辞の件名のファイルを出力することです。 この変数を使用して、その接頭辞を変更します。

format.coverFromDescription::
	ブランチの説明を使用してカバーレターのどの部分にデータを入力するかを決定するためのformat-patchのデフォルトモード。 linkgit:git-format-patch[1]の `--cover-from-description` オプションを参照してください。

format.signature::
	format-patchのデフォルトは、Gitバージョン番号を含む署名を出力することです。 この変数を使用して、そのデフォルトを変更します。 この変数を空の文字列("")に設定すると、署名の生成を抑制します。

format.signatureFile::
	この変数で指定されたファイルの内容が署名として使用されることを除いて、 format.signature と同じように機能します。

format.suffix::
	format-patchのデフォルトは、接尾辞が `.patch` のファイルを出力することです。 この変数を使用して、その接尾辞を変更します(必要に応じて、必ずドット(`.`)を含めてください)。

format.encodeEmailHeaders::
	電子メール送信用に、非ASCII文字を含む電子メールヘッダーを「Q-encoding」(RFC 2047で説明)でエンコードします。 デフォルトはtrueです。

format.pretty::
ifndef::with-breaking-changes[]
	The default pretty format for log/show/whatchanged command.
	See linkgit:git-log[1], linkgit:git-show[1],
	linkgit:git-whatchanged[1].
endif::with-breaking-changes[]
ifdef::with-breaking-changes[]
	The default pretty format for log/show command.
	See linkgit:git-log[1], linkgit:git-show[1].
endif::with-breaking-changes[]

format.thread::
	`git format-patch` のデフォルトのスレッドスタイル。 ブール値 または `shallow` または `deep` にすることができます。 `shallow` スレッドは、すべてのメールをシリーズの先頭にに対して返信します。先頭は、カバーレター、 `--in-reply-to` 、最初のパッチメールの順に選択されます。 `deep` スレッドは、すべてのメールを前のメールに返信します。 true のブール値は `shallow` と同じであり、 false値はスレッド化を無効にします。

format.signOff::
	デフォルトでformat-patchの `-s/--signoff` オプションを有効にできるブール値。 *注意* パッチに「Signed-off-by」トレーラーを追加することは意識的な行為である必要があり、同じオープンソースライセンスの下でこの作品を提出する権利があることを証明することを意味します。 詳細については、「SubmittingPatches」ドキュメントを参照してください。

format.coverLetter::
	format-patchが呼び出されたときにカバーレターを生成するかどうかを制御するブール値ですが、さらに「auto」に設定して、複数のパッチがある場合にのみカバーレターを生成することができます。 デフォルトはfalseです。

format.outputDirectory::
	現在の作業ディレクトリの代わりに、結果のファイルを保存するカスタムディレクトリを設定します。 すべてのディレクトリコンポーネントが作成されます。

format.filenameMaxLength::
	`format-patch` コマンドによって生成される出力ファイル名の最大長。 デフォルトは64です。`--filename-max-length=<n>` コマンドラインオプションで上書きできます。

format.useAutoBase::
	format-patch のオプションである `--base=auto` をデフォルトで有効にするためのブール値です。 `whenAble` に設定すると、適切なベースがある場合に `--base=auto` を有効にし、それ以外の場合はフォーマット終了せずにベース情報の追加をスキップすることもできます。

format.notes::
	format-patchの `--notes` オプションのデフォルト値を提供します。 ブール値、またはnotesを取得する場所を指定するrefを受け入れます。 falseの場合、format-patchのデフォルトは `--no-notes` です。 trueの場合、format-patchのデフォルトは `--notes` です。 非ブール値に設定されている場合、format-patchのデフォルトは `--notes=<ref>` です。ここで、 `ref` は指定した非ブール値です。 デフォルトはfalseです。
+
ref `refs/notes/true` を使用したい場合は、 代わりにそのリテラルを使用してください。
+
この構成は、複数のnotes refを含めるために複数回指定できます。その場合、渡された複数の `--[no-]notes[=]` オプションと同様に動作します。つまり、値 `true` はデフォルトのnotesを表示し、値 `<ref>` はそのnotes ref からのnotesも表示し、値 `false` はそれ以前の設定を無効にし、notesを表示しません。
+
例えば以下の場合、
+
------------
[format]
	notes = true
	notes = foo
	notes = false
	notes = bar
------------
+
`refs/notes/bar` からのnotesのみが表示されます。

format.mboxrd::
	"^>+From " 行をエスケープするために `--stdout` が使用されている場合に、 堅牢な "mboxrd" 形式を有効にするブール値。

format.noprefix::
	設定すると、 パッチに送信元または宛先のプレフィックスが表示されなくなります。 これは、 `git diff` で使用される `diff.noprefix` オプションと同等です(ただし、 `format-patch` では無視されます)。 これを設定すると、 あなたが生成したパッチを受信した人は `-p0` オプションを使用してパッチを適用する必要があることに注意してください。
